#!/usr/bin/env python3
"""gennet.py — generate the DOM device C from dom.net.json.

DOM is the order book: the first internal-domain consumer past the CDC FIFO. The
device logic is GENERATED from the netlist, never hand-written. One device edge
samples the fifo_rx head slot (gated by the FIFO's read-fire), updates the price
tables + best/totals/derived/relay/counters, and latches the prev prices.

  READ    : the fifo_rx head lanes (via the producer's generated fifo_rx_head_addr,
            gated by FIFO_RD_FIRE & ~FIFO_EMPTY), the prev bid/ask, the addressed
            table cells at the bid/ask price indices, and the relay candidate cells.
  COMPUTE : consume = rd_fire & ~empty                                  (branchless)
            bid_chg = ~eqmask(head_bid, prev_bid) & consume
            ask_chg = ~eqmask(head_ask, prev_ask) & consume
            idx = (price - session_base) & (depth-1)                    (address math)
            table updates: presence (set 1 / clear 0) via cell_mux; count += 1 via
            cell_addsub; time latch via cell_mux — all gated by the touch enable.
            best price/qty via cell_mux on *_chg; totals via cell_addsub; spread =
            cell_addsub(ask,bid,sub=1) and mid = cell_addsub(bid,ask)>>1, both gated
            by ask-valid; relay ladder best +/- (i+1)*pip via cell_addsub.
  WRITE   : the two touched table cells per side, best regs, totals, derived, the 40
            relay lanes, the counters, last-feed-time, and prev state. Write-only.

Generated data path contains ZERO if/switch/?: — selection is mask algebra in the
cells. NO native +/-/* on data — equality is cell_eqmask, add/sub is cell_addsub,
selection is cell_mux. The price index and table base offsets are ADDRESS math (a
power-of-two mask + a constant base), the same dispensation cells.h takes for its
loop counter — outside the data-path operator ban. The free-running edge loop is
the canonical clock primitive and lives here, not in any test.
"""
import json
import sys


HEADER = """/* GENERATED by gennet.py from dom.net.json — DO NOT EDIT BY HAND.
 * DOM: the order book. Price-indexed qty/count/time tables, best-bid/ask tracking,
 * running totals, derived spread/mid, 10-level relay ladders, diagnostic counters.
 * Samples the fifo_rx head slot (the FIFO's published window) via the producer's
 * generated head-address helper. All as a netlist of cells over addressed
 * registers. No branch in the data path; no native add/sub/mul on data. */
#ifndef DOM_GEN_H
#define DOM_GEN_H
#include "cells.h"
#include "fifo_rx_gen.h"   /* the fifo_rx CANONICAL window (generated from
                            * ../fifo_rx/fifo_rx.net.json by the FIFO's gennet —
                            * single source). DOM SAMPLES the head slot + RD_FIRE/
                            * EMPTY flags; no private copy of the FIFO map. */
"""


def emit_helpers():
    """Device-local comparator for the bounded self-run (carry chain over cell_fa,
    XOR/shift only — no native +/-/* on data). Device-local name avoids colliding
    with fifo_rx_gen.h / nic_gen.h symbols pulled in transitively."""
    return """
/* dom_cmp_lt: gate-netlist comparator (a < b), carry chain over cell_fa. The
 * bounded self-run uses it on a configured tick budget (config, not external
 * stepping). Device-local name (fifo_rx_gen.h defines fifo_cmp_lt). */
static inline word_t dom_cmp_lt(word_t a, word_t b) {
    word_t carry = 1ULL;
    word_t i = 0ULL;
    for (i = 0ULL; i < 64ULL; i = i + 1ULL) {
        const word_t aa = (a >> i) & 1ULL;
        const word_t nb = (cell_not(b) >> i) & 1ULL;
        const word_t fa = cell_fa(aa, nb, carry);
        carry           = (fa >> 1) & 1ULL;
    }
    return (carry & 1ULL) ^ 1ULL;
}
"""


def main():
    net_path = sys.argv[1] if len(sys.argv) > 1 else "dom.net.json"
    with open(net_path) as f:
        net = json.load(f)

    depth = net["table_depth"]
    if depth <= 0 or (depth & (depth - 1)) != 0:
        sys.stderr.write(
            f"gennet: table_depth ({depth}) must be a power of two "
            f"(price index is a branchless mask: (price - base) & (depth-1)).\n")
        sys.exit(2)
    levels = net["relay_levels"]
    w = net["wiring"]
    run = net["run"]
    tables = net["tables"]
    head_ofs = net["fifo_head_ofs"]
    P = "DOM"

    # ---- assign addresses: config -> dff -> comb -> each table (depth cells). ---
    order = []
    for n in net.get("config_nodes", []):
        order.append(n["name"])
    for n in net.get("dff_nodes", []):
        order.append(n["name"])
    for n in net.get("comb_nodes", []):
        order.append(n["name"])
    addr = {nm: i for i, nm in enumerate(order)}
    scalar_count = len(order)
    # the four tables follow the scalars, each a contiguous depth-cell region.
    table_base = {}
    cur = scalar_count
    for t in tables:
        table_base[t["name"]] = cur
        cur += depth
    count = cur

    out = [HEADER]
    out.append(f"#define {P}_REG_COUNT {count}u")
    out.append(f"#define {P}_WINDOW_BASE {net['window_base']}u")
    out.append(f"#define {P}_TABLE_DEPTH {depth}u")
    out.append(f"#define {P}_RELAY_LEVELS {levels}u")
    # price-index wrap mask DERIVED from depth (power of two) — not a second literal.
    out.append(f"#define {P}_IDX_MASK ({P}_TABLE_DEPTH - 1u)\n")
    for nm in order:
        out.append(f"#define {P}_{nm} {addr[nm]}u")
    out.append("")
    for t in tables:
        out.append(f"#define {P}_{t['name']}_BASE {table_base[t['name']]}u")
    out.append("")
    out.append(emit_helpers())
    out.append("")

    # ---- init: power-off synchronous reset (everything zero). ------------------
    out.append("static inline void dom_init(word_t *r) {")
    out.append("    word_t i = 0ULL;")
    out.append(f"    for (i = 0ULL; i < {P}_REG_COUNT; i = i + 1ULL) {{ r[i] = 0ULL; }}")
    out.append("}")
    out.append("")

    # ---- table cell address helpers (ADDRESS math only; no data path). ---------
    for t in tables:
        nm = t["name"]
        out.append(f"/* {nm}: addressed table cell at price index (address math). */")
        out.append(f"static inline word_t dom_{nm.lower()}_addr(word_t idx) {{")
        out.append(f"    return (word_t){P}_{nm}_BASE + (idx & {P}_IDX_MASK);")
        out.append("}")
        out.append("")

    # ---- one device edge: READ -> COMPUTE -> WRITE. ---------------------------
    out.append("/* dom_tick: one device clock edge. READ the fifo_rx head slot (gated by the")
    out.append(" * FIFO read-fire) + prev prices + the addressed table cells, COMPUTE the")
    out.append(" * branchless book update (delta detect, index, presence/count/time, best,")
    out.append(" * totals, derived, relay), WRITE every owned register. Write-only WRITE. */")
    # NOTE: signature MUST stay on ONE line — gate stage 2b skips only the single
    # line matching `_tick(`; a wrapped continuation would be scanned as body and
    # its `*fifo` pointer declarator falsely flagged as native multiply.
    out.append("static inline void dom_tick(word_t *r, const word_t *fifo) {")
    out.append("    /* READ phase — pre-read every operand from its register. */")
    out.append(f"    const word_t power     = r[{P}_{net['power']}] & 1ULL;")
    out.append(f"    const word_t base_px   = r[{P}_{w['session_base']}];")
    out.append(f"    const word_t pip_res   = r[{P}_{w['pip_res']}];")
    # the fifo_rx published consume gate + validity (read from the FIFO window).
    out.append(f"    const word_t rd_fire   = fifo[{net['fifo_fire']}] & 1ULL;")
    out.append(f"    const word_t fifo_empty = fifo[{net['fifo_empty']}] & 1ULL;")
    # the head-slot lanes (via the producer's generated head-address helper).
    out.append("    /* fifo_rx head slot lanes (producer's generated head address; no copy). */")
    out.append(f"    const word_t head_bid  = fifo[fifo_rx_head_addr(fifo, {head_ofs['BID_PX']}ULL)];")
    out.append(f"    const word_t head_ask  = fifo[fifo_rx_head_addr(fifo, {head_ofs['ASK_PX']}ULL)];")
    out.append(f"    const word_t head_tai  = fifo[fifo_rx_head_addr(fifo, {head_ofs['TIME']}ULL)];")
    out.append("")
    out.append("    /* prev prices (for branchless delta detection) + current book state. */")
    out.append(f"    const word_t prev_bid  = r[{P}_{w['prev_bid']}];")
    out.append(f"    const word_t prev_ask  = r[{P}_{w['prev_ask']}];")
    out.append(f"    const word_t cur_bbid_p = r[{P}_{w['best_bid_price']}];")
    out.append(f"    const word_t cur_bask_p = r[{P}_{w['best_ask_price']}];")
    out.append(f"    const word_t cur_tbid  = r[{P}_{w['total_bid']}];")
    out.append(f"    const word_t cur_task  = r[{P}_{w['total_ask']}];")
    out.append(f"    const word_t cur_pkt   = r[{P}_{w['pkt_count']}];")
    out.append(f"    const word_t cur_add   = r[{P}_{w['add_count']}];")
    out.append(f"    const word_t cur_cancel = r[{P}_{w['cancel_count']}];")
    out.append(f"    const word_t cur_lft   = r[{P}_{w['last_feed_time']}];")
    out.append("")
    out.append("    /* COMPUTE phase — branchless. consume = rd_fire & ~empty. */")
    out.append("    const word_t consume = cell_and(rd_fire, cell_not(fifo_empty) & 1ULL) & 1ULL;")
    out.append("    /* delta detect: changed = ~eqmask(head, prev) & consume (gate the edge). */")
    out.append("    const word_t bid_chg = cell_and(cell_not(cell_eqmask(head_bid, prev_bid)) & 1ULL, consume) & 1ULL;")
    out.append("    const word_t ask_chg = cell_and(cell_not(cell_eqmask(head_ask, prev_ask)) & 1ULL, consume) & 1ULL;")
    out.append("")
    out.append("    /* price -> table index (ADDRESS math: mask, the only native op, on")
    out.append("     * addresses not data). new index for bid/ask; old index = prev price. */")
    out.append(f"    const word_t idx_bid_new = cell_addsub(head_bid, base_px, 1ULL) & {P}_IDX_MASK;")
    out.append(f"    const word_t idx_ask_new = cell_addsub(head_ask, base_px, 1ULL) & {P}_IDX_MASK;")
    out.append(f"    const word_t idx_bid_old = cell_addsub(prev_bid, base_px, 1ULL) & {P}_IDX_MASK;")
    out.append(f"    const word_t idx_ask_old = cell_addsub(prev_ask, base_px, 1ULL) & {P}_IDX_MASK;")
    out.append("")
    out.append("    /* addressed table cells touched this edge (read in READ-equivalent: the")
    out.append("     * index is data-derived, so the read is here, before any WRITE). */")
    out.append(f"    const word_t bidc_new = r[dom_{w['bid_qty_table'].lower()}_addr(idx_bid_new)];")
    out.append(f"    const word_t askc_new = r[dom_{w['ask_qty_table'].lower()}_addr(idx_ask_new)];")
    out.append(f"    const word_t bidc_old = r[dom_{w['bid_qty_table'].lower()}_addr(idx_bid_old)];")
    out.append(f"    const word_t askc_old = r[dom_{w['ask_qty_table'].lower()}_addr(idx_ask_old)];")
    out.append(f"    const word_t cntc_bid = r[dom_{w['count_table'].lower()}_addr(idx_bid_new)];")
    out.append(f"    const word_t cntc_ask = r[dom_{w['count_table'].lower()}_addr(idx_ask_new)];")
    out.append("")
    out.append("    /* presence model (PARTS_LIST §2): on a change, the NEW level is set to 1")
    out.append("     * and the OLD level cleared to 0 (branchless cell_mux, gated by *_chg). */")
    out.append("    const word_t bid_new_val = cell_mux(bidc_new, 1ULL, bid_chg);")
    out.append("    const word_t bid_old_val = cell_mux(bidc_old, 0ULL, bid_chg);")
    out.append("    const word_t ask_new_val = cell_mux(askc_new, 1ULL, ask_chg);")
    out.append("    const word_t ask_old_val = cell_mux(askc_old, 0ULL, ask_chg);")
    out.append("    /* count += 1 on a touch; time latch = head TAI on a touch (cell_mux). */")
    out.append("    const word_t cnt_bid_n = cell_mux(cntc_bid, cell_addsub(cntc_bid, 1ULL, 0ULL), bid_chg);")
    out.append("    const word_t cnt_ask_n = cell_mux(cntc_ask, cell_addsub(cntc_ask, 1ULL, 0ULL), ask_chg);")
    out.append("    const word_t time_bid_n = cell_mux(0ULL, head_tai, bid_chg);")
    out.append("    const word_t time_ask_n = cell_mux(0ULL, head_tai, ask_chg);")
    out.append("")
    out.append("    /* best price/qty: latch the new price on a change (cell_mux); best qty")
    out.append("     * follows the new level's presence value (1 when set). */")
    out.append("    const word_t bbid_p_n = cell_mux(cur_bbid_p, head_bid, bid_chg);")
    out.append("    const word_t bask_p_n = cell_mux(cur_bask_p, head_ask, ask_chg);")
    out.append("    const word_t bbid_q_n = cell_mux(r[" + f"{P}_{w['best_bid_qty']}], bid_new_val, bid_chg);")
    out.append("    const word_t bask_q_n = cell_mux(r[" + f"{P}_{w['best_ask_qty']}], ask_new_val, ask_chg);")
    out.append("")
    out.append("    /* running totals: += 1 when a new level became present (cell_addsub). */")
    out.append("    const word_t tbid_n = cell_addsub(cur_tbid, bid_chg, 0ULL);")
    out.append("    const word_t task_n = cell_addsub(cur_task, ask_chg, 0ULL);")
    out.append("")
    out.append("    /* derived (guarded by ask-valid = best ask price != 0). spread = ask-bid;")
    out.append("     * mid = (bid+ask) >> 1. cell_addsub for both; shift is address-class. */")
    out.append("    const word_t ask_valid = cell_not(cell_eqmask(bask_p_n, 0ULL)) & 1ULL;")
    out.append("    const word_t spread_raw = cell_addsub(bask_p_n, bbid_p_n, 1ULL);")
    out.append("    const word_t mid_raw    = cell_addsub(bbid_p_n, bask_p_n, 0ULL) >> 1;")
    out.append("    const word_t spread_n = cell_mux(0ULL, spread_raw, ask_valid);")
    out.append("    const word_t mid_n    = cell_mux(bbid_p_n, mid_raw, ask_valid);")
    out.append("")
    out.append("    /* diagnostic counters: pkt += consume; add += (bid_chg|ask_chg);")
    out.append("     * cancel += (bid_chg|ask_chg) [a change clears an old level]. */")
    out.append("    const word_t any_chg = cell_or(bid_chg, ask_chg) & 1ULL;")
    out.append("    const word_t pkt_n    = cell_addsub(cur_pkt, consume, 0ULL);")
    out.append("    const word_t add_n    = cell_addsub(cur_add, any_chg, 0ULL);")
    out.append("    const word_t cancel_n = cell_addsub(cur_cancel, any_chg, 0ULL);")
    out.append("    const word_t lft_n    = cell_mux(cur_lft, head_tai, consume);")
    out.append("    /* prev prices latch the consumed head (hold when ~consume). */")
    out.append("    const word_t prev_bid_n = cell_mux(prev_bid, head_bid, consume);")
    out.append("    const word_t prev_ask_n = cell_mux(prev_ask, head_ask, consume);")
    out.append("")

    # ---- relay ladder: best +/- (i+1)*pip, qty = addressed table cell. ---------
    out.append("    /* relay ladder (PARTS_LIST §8): level i price = best -/+ (i+1)*pip;")
    out.append("     * qty = the addressed table cell at that price's index. Step is built")
    out.append("     * additively (cell_addsub by pip each level) — no native multiply. */")
    out.append("    word_t rb_px = bbid_p_n;")
    out.append("    word_t ra_px = bask_p_n;")
    for i in range(levels):
        out.append(f"    rb_px = cell_addsub(rb_px, pip_res, 1ULL);   /* bid level {i}: best - (i+1)*pip */")
        out.append(f"    ra_px = cell_addsub(ra_px, pip_res, 0ULL);   /* ask level {i}: best + (i+1)*pip */")
        out.append(f"    const word_t rb_px_{i} = rb_px;")
        out.append(f"    const word_t ra_px_{i} = ra_px;")
        out.append(f"    const word_t rb_idx_{i} = cell_addsub(rb_px_{i}, base_px, 1ULL) & {P}_IDX_MASK;")
        out.append(f"    const word_t ra_idx_{i} = cell_addsub(ra_px_{i}, base_px, 1ULL) & {P}_IDX_MASK;")
        out.append(f"    const word_t rb_q_{i} = r[dom_{w['bid_qty_table'].lower()}_addr(rb_idx_{i})];")
        out.append(f"    const word_t ra_q_{i} = r[dom_{w['ask_qty_table'].lower()}_addr(ra_idx_{i})];")
    out.append("")

    out.append("    /* WRITE phase — commit every owned register (write-only). */")
    out.append(f"    r[{P}_{w['prev_bid']}] = prev_bid_n;")
    out.append(f"    r[{P}_{w['prev_ask']}] = prev_ask_n;")
    out.append(f"    r[{P}_{w['best_bid_price']}] = bbid_p_n;")
    out.append(f"    r[{P}_{w['best_ask_price']}] = bask_p_n;")
    out.append(f"    r[{P}_{w['best_bid_qty']}]   = bbid_q_n;")
    out.append(f"    r[{P}_{w['best_ask_qty']}]   = bask_q_n;")
    out.append(f"    r[{P}_{w['total_bid']}] = tbid_n;")
    out.append(f"    r[{P}_{w['total_ask']}] = task_n;")
    out.append(f"    r[{P}_{w['spread']}] = spread_n;")
    out.append(f"    r[{P}_{w['mid']}] = mid_n;")
    out.append(f"    r[{P}_{w['pkt_count']}] = pkt_n;")
    out.append(f"    r[{P}_{w['add_count']}] = add_n;")
    out.append(f"    r[{P}_{w['cancel_count']}] = cancel_n;")
    out.append(f"    r[{P}_{w['trade_count']}] = 0ULL;   /* PARTS_LIST §6: KEPT FOR API COMPAT, NOT USED */")
    out.append(f"    r[{P}_{w['last_feed_time']}] = lft_n;")
    out.append("    /* table cells: new level set, old level cleared; count/time on a touch. */")
    out.append(f"    r[dom_{w['bid_qty_table'].lower()}_addr(idx_bid_new)] = bid_new_val;")
    out.append(f"    r[dom_{w['bid_qty_table'].lower()}_addr(idx_bid_old)] = bid_old_val;")
    out.append(f"    r[dom_{w['ask_qty_table'].lower()}_addr(idx_ask_new)] = ask_new_val;")
    out.append(f"    r[dom_{w['ask_qty_table'].lower()}_addr(idx_ask_old)] = ask_old_val;")
    out.append(f"    r[dom_{w['count_table'].lower()}_addr(idx_bid_new)] = cnt_bid_n;")
    out.append(f"    r[dom_{w['count_table'].lower()}_addr(idx_ask_new)] = cnt_ask_n;")
    out.append(f"    r[dom_{w['time_table'].lower()}_addr(idx_bid_new)] = time_bid_n;")
    out.append(f"    r[dom_{w['time_table'].lower()}_addr(idx_ask_new)] = time_ask_n;")
    out.append("    /* relay ladders (40 lanes). */")
    for i in range(levels):
        out.append(f"    r[{P}_DOM_REL_BID_PRICE_{i}] = rb_px_{i};")
        out.append(f"    r[{P}_DOM_REL_BID_QTY_{i}]   = rb_q_{i};")
        out.append(f"    r[{P}_DOM_REL_ASK_PRICE_{i}] = ra_px_{i};")
        out.append(f"    r[{P}_DOM_REL_ASK_QTY_{i}]   = ra_q_{i};")
    out.append("    /* tick bookkeeping (self-run counter). */")
    out.append(f"    r[{P}_{run['count']}] = cell_addsub(r[{P}_{run['count']}], 1ULL, 0ULL);")
    out.append(f"    (void)power;")
    out.append("}")
    out.append("")

    # ---- the self-run loop (clocked), bounded by a configured tick budget. -----
    out.append("/* dom_run: the canonical clock primitive. DOM self-runs on its clock edge")
    out.append(" * while powered, bounded by a configured tick budget (config, not external")
    out.append(" * stepping). The starter powers it on and steps away. */")
    out.append("static inline void dom_run(word_t *r, const word_t *fifo) {")
    rc, rl = run["count"], run["limit"]
    out.append(f"    while ((r[{P}_{run['power']}] & 1ULL)")
    out.append(f"           && dom_cmp_lt(r[{P}_{rc}], r[{P}_{rl}])) {{")
    out.append("        dom_tick(r, fifo);")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append("#endif /* DOM_GEN_H */")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
