#!/usr/bin/env python3
"""gennet.py — generate the NIC device C from nic.net.json.

The NIC is the wire->fifo gateway. The device logic is GENERATED from the netlist,
never hand-written. On the MAC edge:

  READ    : the wire bus (WIRE_* from wire_gen.h), TAI_MAC (from tai_cdc_gen.h),
            and the dedup ring slot at idx = WIRE_SEQ & RING_MASK.
  COMPUTE : dup  = WIRE_VALID & slot_valid & eqmask(slot_seq, WIRE_SEQ)  (branchless)
            pass = WIRE_VALID & ~dup
            re-stamp: SEAM_TIME = TAI_MAC ; SEAM_SRC_TIME = WIRE_TIME ; rest passthrough
            seam flops latch on en=pass ; ring slot at idx latches seq + valid on en=pass
            (per-slot select = eqmask(idx, i) & pass — branchless, no if)
  WRITE   : commit ticks, ring (seq+valid), seam lanes, SEAM_VALID/STROBE/DEDUP_MARK.

Generated data path contains ZERO if/switch/?: — selection is mask algebra in the
cells. NO native +/-/* on data — equality is cell_eqmask, the bounded self-run
uses cmp_lt (carry chain), the tick counter steps via cell_addsub. The ring index
is a power-of-two MASK cell (no %). The free-running mac-edge loop is the canonical
clock primitive and lives here in the device, not in any test.
"""
import json
import sys


HEADER = """/* GENERATED by gennet.py from nic.net.json — DO NOT EDIT BY HAND.
 * The NIC device: samples the wire bus, dedups by seq (history ring), re-stamps
 * with the MAC-domain TAI value (TAI_MAC), and deposits the structured packet
 * into the nic->fifo seam on a 1-cycle write strobe. All as a netlist of cells
 * over addressed registers. No branch in the data path; no native add/sub/mul. */
#ifndef NIC_GEN_H
#define NIC_GEN_H
#include "cells.h"
#include "wire_gen.h"      /* the wire's CANONICAL bus lane map (generated from
                            * ../wire/wire.net.json by the wire's gennet — single
                            * source). The NIC SAMPLES these lanes; no private copy. */
#include "tai_cdc_gen.h"   /* tai_cdc's CANONICAL window (generated from
                            * ../tai_cdc/tai_cdc.net.json). The NIC reads TAI_MAC
                            * (MAC-domain TAI value) in-domain to stamp packets. */
"""


def emit_cmp_lt():
    """nic_cmp_lt(a, b) -> 1 iff a < b, gate-netlist carry chain (no C relational op).

    Named nic_cmp_lt (device-local) to avoid colliding with the cmp_lt that
    tai_cdc_gen.h (included for TAI_MAC) already defines.
    """
    return """
/* nic_cmp_lt: gate-netlist comparator (a < b), carry chain over cell_fa. The
 * bounded self-run uses it on a configured tick budget (config, not external
 * stepping). Device-local name (tai_cdc_gen.h also defines a cmp_lt). */
static inline word_t nic_cmp_lt(word_t a, word_t b) {
    word_t carry = 1ULL;
    word_t i = 0ULL;
    for (i = 0ULL; i < 64ULL; i = i + 1ULL) {
        const word_t aa = (a >> i) & 1ULL;
        const word_t nb = (cell_not(b) >> i) & 1ULL;
        const word_t fa = cell_fa(aa, nb, carry);
        carry           = (fa >> 1) & 1ULL;
    }
    return (carry & 1ULL) ^ 1ULL;
}
"""


def main():
    net_path = sys.argv[1] if len(sys.argv) > 1 else "nic.net.json"
    with open(net_path) as f:
        net = json.load(f)

    ring = net["ring"]
    depth = ring["depth"]
    if depth <= 0 or (depth & (depth - 1)) != 0:
        sys.stderr.write(
            f"gennet: ring depth ({depth}) must be a power of two "
            f"(index is a branchless mask: WIRE_SEQ & (depth-1)).\n")
        sys.exit(2)

    seam = net["seam_nodes"]
    status = net["seam_status"]
    comp = net["compute"]
    run = net["run"]

    # ---- assign addresses: one register slot per NIC-owned node, in order. ----
    # config -> dff(NIC_TICKS) -> ring(seq_i, valid_i for i in depth) ->
    # seam lanes -> seam status.
    order = []
    for n in net.get("config_nodes", []):
        order.append(n["name"])
    for n in net.get("dff_nodes", []):
        order.append(n["name"])
    ring_seq = [f"{ring['seq_prefix']}_{i}" for i in range(depth)]
    ring_val = [f"{ring['valid_prefix']}_{i}" for i in range(depth)]
    for i in range(depth):
        order.append(ring_seq[i])
        order.append(ring_val[i])
    for n in seam:
        order.append(n["name"])
    for n in status:
        order.append(n["name"])

    addr = {nm: i for i, nm in enumerate(order)}
    count = len(order)
    P = "NIC"   # register prefix

    out = [HEADER]
    out.append(f"#define {P}_REG_COUNT {count}u")
    out.append(f"#define {P}_WINDOW_BASE {net['window_base']}u")
    out.append(f"#define {P}_RING_DEPTH {depth}u")
    # ring wrap mask DERIVED from depth (power of two) — not a second literal.
    out.append(f"#define {P}_RING_MASK ({P}_RING_DEPTH - 1u)\n")
    for nm in order:
        out.append(f"#define {P}_{nm} {addr[nm]}u")
    out.append("")
    out.append(emit_cmp_lt())
    out.append("")

    # ---- init: power-off synchronous reset (everything zero). -----------------
    out.append("static inline void nic_init(word_t *r) {")
    out.append("    word_t i = 0ULL;")
    out.append(f"    for (i = 0ULL; i < {P}_REG_COUNT; i = i + 1ULL) {{ r[i] = 0ULL; }}")
    out.append("}")
    out.append("")

    # ---- one MAC clock edge: READ -> COMPUTE -> WRITE. -----------------------
    out.append("/* nic_tick: one MAC clock edge. READ the wire bus + TAI_MAC + the dedup")
    out.append(" * ring slot, COMPUTE dedup/stamp/strobe (branchless), WRITE the ring, the")
    out.append(" * seam lanes, and the status flops. Write-only WRITE phase. */")
    # NOTE: the signature MUST stay on ONE line — gate stage 2b skips only the
    # single line that opens the tick body (the line matching `_tick(`); a wrapped
    # signature's continuation would be scanned as body and its `*tai` pointer
    # declarator falsely flagged as native multiply.
    out.append("static inline void nic_tick(word_t *r, const wire_word_t *wire, const word_t *tai) {")
    out.append("    /* READ phase — pre-read every operand from its register. */")
    out.append(f"    const word_t power = r[{P}_{net['power']}] & 1ULL;")
    out.append(f"    const word_t w_valid = wire[WIRE_{comp['valid']}] & 1ULL;")
    out.append(f"    const word_t w_seq   = wire[WIRE_{comp['seq']}];")
    out.append(f"    const word_t w_time  = wire[WIRE_{comp['src_time']}];")
    out.append(f"    const word_t tai_mac = tai[TAI_CDC_{comp['stamp']}];")
    # the wire passthrough operands the seam lanes copy from. WIRE_TIME (the
    # src_time) is read separately as w_time below, so exclude it here to avoid an
    # unused duplicate local.
    wire_srcs = sorted({n["from"] for n in seam
                        if n["from"].startswith("WIRE_")
                        and n["from"] != comp["src_time"]})
    for ws in wire_srcs:
        local = "rd_" + ws.lower()
        # wire_gen.h defines are WIRE_<nodename>; node names are themselves WIRE_*,
        # so the macro is WIRE_WIRE_BID_PX etc. Prefix accordingly.
        out.append(f"    const word_t {local} = wire[WIRE_{ws}];")
    out.append("")
    out.append("    /* ring index = WIRE_SEQ & (depth-1) — a branchless power-of-two mask")
    out.append("     * cell (depth is a power of two; no %, no if). */")
    out.append(f"    const word_t idx = cell_and(w_seq, {P}_RING_MASK);")
    # pre-read the addressed ring slot: select slot_seq/slot_valid by branchless
    # OR-of-masked-slots (eqmask(idx, i) gates exactly one slot).
    out.append("    /* read the addressed ring slot (branchless select: eqmask(idx,i)")
    out.append("     * gates exactly one slot; OR-reduce). */")
    out.append("    word_t slot_seq = 0ULL;")
    out.append("    word_t slot_val = 0ULL;")
    for i in range(depth):
        out.append(f"    slot_seq = cell_or(slot_seq, cell_gate(r[{P}_{ring_seq[i]}], cell_eqmask(idx, {i}ULL)));")
        out.append(f"    slot_val = cell_or(slot_val, cell_gate(r[{P}_{ring_val[i]}], cell_eqmask(idx, {i}ULL)));")
    out.append("")
    out.append("    /* COMPUTE phase — branchless dedup + stamp + strobe. */")
    out.append("    /* dup = valid & slot_valid & (slot_seq == WIRE_SEQ). */")
    out.append("    const word_t seq_match = cell_eqmask(slot_seq, w_seq);")
    out.append("    const word_t dup  = cell_and(cell_and(w_valid, slot_val & 1ULL), seq_match) & 1ULL;")
    out.append("    /* pass = valid & ~dup (a fresh, non-duplicate packet). */")
    out.append("    const word_t pass = cell_and(w_valid, cell_not(dup) & 1ULL) & 1ULL;")
    out.append("")
    out.append("    /* seam flops: latch the re-stamped packet on en=pass (gated dff).")
    out.append("     * SEAM_TIME = TAI_MAC (authoritative); SEAM_SRC_TIME = WIRE_TIME. */")
    seam_locals = {}
    for n in seam:
        nm = n["name"]
        frm = n["from"]
        if frm == comp["stamp"]:
            src = "tai_mac"
        elif frm == comp["src_time"]:
            src = "w_time"
        elif frm.startswith("WIRE_"):
            src = "rd_" + frm.lower()
        else:
            sys.stderr.write(f"gennet: seam lane {nm} has unknown source {frm}\n")
            sys.exit(2)
        local = "seam_" + nm.lower()
        seam_locals[nm] = local
        out.append(f"    const word_t {local} = cell_dff(r[{P}_{nm}], {src}, pass);")
    out.append("")
    out.append("    /* status flops (latched while powered): VALID/STROBE <= pass; DEDUP_MARK <= dup. */")
    status_locals = {}
    for n in status:
        nm = n["name"]
        src = n["from"]   # "pass" or "dup"
        local = "st_" + nm.lower()
        status_locals[nm] = local
        out.append(f"    const word_t {local} = cell_dff(r[{P}_{nm}], {src}, power);")
    out.append("")
    out.append("    /* ring update on pass: the slot at idx latches WIRE_SEQ and its valid")
    out.append("     * bit latches 1. Per-slot select = eqmask(idx,i) & pass (branchless). */")
    ring_seq_locals = []
    ring_val_locals = []
    for i in range(depth):
        sl_en = f"(cell_eqmask(idx, {i}ULL) & pass)"
        sseq = f"rs_{i}"
        sval = f"rv_{i}"
        ring_seq_locals.append(sseq)
        ring_val_locals.append(sval)
        out.append(f"    const word_t {sseq} = cell_dff(r[{P}_{ring_seq[i]}], w_seq, {sl_en});")
        out.append(f"    const word_t {sval} = cell_dff(r[{P}_{ring_val[i]}], 1ULL, {sl_en});")
    out.append("")
    out.append("    /* WRITE phase — commit every dff (registered hop). Write-only. */")
    for nm in seam_locals:
        out.append(f"    r[{P}_{nm}] = {seam_locals[nm]};")
    for nm in status_locals:
        out.append(f"    r[{P}_{nm}] = {status_locals[nm]};")
    for i in range(depth):
        out.append(f"    r[{P}_{ring_seq[i]}] = {ring_seq_locals[i]};")
        out.append(f"    r[{P}_{ring_val[i]}] = {ring_val_locals[i]};")
    out.append("}")
    out.append("")

    # ---- the self-run loop (mac-edge clocked), bounded by a configured tick. --
    out.append("/* nic_run: the canonical clock primitive. The NIC self-runs on the mac")
    out.append(" * edge while powered, bounded by a configured tick budget (config, not")
    out.append(" * external stepping). The starter powers it on and steps away. */")
    out.append("static inline void nic_run(word_t *r, const wire_word_t *wire,")
    out.append("                           const word_t *tai) {")
    rc, rl = run["count"], run["limit"]
    out.append(f"    while ((r[{P}_{run['power']}] & 1ULL)")
    out.append(f"           && nic_cmp_lt(r[{P}_{rc}], r[{P}_{rl}])) {{")
    out.append("        nic_tick(r, wire, tai);")
    out.append(f"        r[{P}_{rc}] = cell_addsub(r[{P}_{rc}], 1ULL, 0ULL);")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append("#endif /* NIC_GEN_H */")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
