#!/usr/bin/env python3
"""gennet.py — generate the fifo_rx device C from fifo_rx.net.json.

fifo_rx is the MAC->internal async CDC FIFO (Cummings). The device logic is
GENERATED from the netlist, never hand-written. One device edge models both FIFO
ports (each gated by its own enable + flow-control flag); the 2-FF sync chains
impose the cross-domain 2-cycle pointer latency that makes the crossing safe.

  READ    : the nic seam (SEAM_* from nic_gen.h), the read-enable, both pointers
            (binary + gray), the sync stages, and the RAM slot at the write index.
  COMPUTE : EMPTY  = eqmask(rd_gray, rq2_wgray)                        (read domain)
            FULL   = eqmask(wr_gray, invert_top2(wq2_rgray))          (write domain)
            wr_fire = SEAM_STROBE & ~FULL ; rd_fire = RD_EN & ~EMPTY   (branchless)
            wr_bin' = wr_bin + wr_fire ; rd_bin' = rd_bin + rd_fire   (cell_addsub)
            wr_gray' = bin2gray(wr_bin') ; rd_gray' = bin2gray(rd_bin')
            2-FF sync: each stage is a power-gated dff (no logic between stages)
            slot[wr_idx] <= seam lanes on (wr_fire) — per-slot select is
            eqmask(wr_idx,i) & wr_fire (branchless, one slot enabled).
  WRITE   : commit ticks, both pointers (bin+gray), the 4 sync stages, FULL/EMPTY,
            the fire flags, and every RAM slot lane. Write-only WRITE phase.

Generated data path contains ZERO if/switch/?: — selection is mask algebra in the
cells. NO native +/-/* on data — equality is cell_eqmask, pointer advance is
cell_addsub, gray encode/decode are XOR/shift, the bounded self-run uses
fifo_cmp_lt (carry chain). Slot index is a power-of-two MASK (no %). The free-
running edge loop is the canonical clock primitive and lives here, not in any test.
"""
import json
import sys


HEADER = """/* GENERATED by gennet.py from fifo_rx.net.json — DO NOT EDIT BY HAND.
 * fifo_rx: the MAC->internal async CDC FIFO (Cummings). Gray-coded (n+1)-bit
 * pointers crossing through dual 2-FF synchronizers; FULL/EMPTY derived from the
 * synced opposite-domain pointer; packet-wide slots (one slot = the 8 nic-seam
 * lanes). All as a netlist of cells over addressed registers. No branch in the
 * data path; no native add/sub/mul. */
#ifndef FIFO_RX_GEN_H
#define FIFO_RX_GEN_H
#include "cells.h"
#include "nic_gen.h"      /* the nic's CANONICAL seam lane map (generated from
                           * ../nic/nic.net.json by the nic's gennet — single
                           * source). fifo_rx SAMPLES the SEAM_* lanes; no copy. */
"""


def emit_helpers():
    """Device-local comparator + gray encode. fifo_cmp_lt for the bounded self-run;
    bin2gray for pointer gray encoding. Both XOR/shift/carry-chain only (no native
    +/-/* on data). Device-local names avoid colliding with nic_gen.h symbols."""
    return """
/* fifo_cmp_lt: gate-netlist comparator (a < b), carry chain over cell_fa. The
 * bounded self-run uses it on a configured tick budget (config, not external
 * stepping). Device-local name (nic_gen.h also defines nic_cmp_lt). */
static inline word_t fifo_cmp_lt(word_t a, word_t b) {
    word_t carry = 1ULL;
    word_t i = 0ULL;
    for (i = 0ULL; i < 64ULL; i = i + 1ULL) {
        const word_t aa = (a >> i) & 1ULL;
        const word_t nb = (cell_not(b) >> i) & 1ULL;
        const word_t fa = cell_fa(aa, nb, carry);
        carry           = (fa >> 1) & 1ULL;
    }
    return (carry & 1ULL) ^ 1ULL;
}

/* bin2gray: binary -> gray, g = b ^ (b >> 1). XOR/shift only (not arithmetic);
 * exactly 1 gray bit flips per binary increment — the metastability-safe form. */
static inline word_t bin2gray(word_t b) {
    return cell_xor(b, b >> 1);
}
"""


def main():
    net_path = sys.argv[1] if len(sys.argv) > 1 else "fifo_rx.net.json"
    with open(net_path) as f:
        net = json.load(f)

    depth = net["depth"]
    if depth <= 0 or (depth & (depth - 1)) != 0:
        sys.stderr.write(
            f"gennet: depth ({depth}) must be a power of two "
            f"(slot index is a branchless mask: ptr_bin & (depth-1)).\n")
        sys.exit(2)
    addr_bits = net["addr_bits"]
    ptr_bits = net["ptr_bits"]
    ram = net["ram"]
    lanes = ram["lanes"]
    ws = net["write_side"]
    rs = net["read_side"]
    fire = net["fire"]
    run = net["run"]
    P = "FIFO"   # register prefix

    # ---- assign addresses: one register slot per fifo_rx-owned node, in order. -
    # config -> dff -> comb -> RAM (slot_i_LANE for each slot, each lane).
    order = []
    for n in net.get("config_nodes", []):
        order.append(n["name"])
    for n in net.get("dff_nodes", []):
        order.append(n["name"])
    for n in net.get("comb_nodes", []):
        order.append(n["name"])
    slot_lane = {}   # (i, lane) -> node name
    for i in range(depth):
        for ln in lanes:
            nm = f"{ram['slot_prefix']}_{i}_{ln}"
            slot_lane[(i, ln)] = nm
            order.append(nm)

    addr = {nm: i for i, nm in enumerate(order)}
    count = len(order)

    out = [HEADER]
    out.append(f"#define {P}_REG_COUNT {count}u")
    out.append(f"#define {P}_DEPTH {depth}u")
    out.append(f"#define {P}_ADDR_BITS {addr_bits}u")
    out.append(f"#define {P}_PTR_BITS {ptr_bits}u")
    # slot-index wrap mask DERIVED from depth (power of two) — not a second literal.
    out.append(f"#define {P}_SLOT_MASK ({P}_DEPTH - 1u)")
    # the two MSBs of an (n+1)-bit pointer, used by the Cummings FULL test.
    out.append(f"#define {P}_TOP2_MASK (3ULL << ({P}_PTR_BITS - 2u))\n")
    for nm in order:
        out.append(f"#define {P}_{nm} {addr[nm]}u")
    out.append("")
    out.append(emit_helpers())
    out.append("")

    # ---- init: power-off synchronous reset (everything zero). -----------------
    out.append("static inline void fifo_rx_init(word_t *r) {")
    out.append("    word_t i = 0ULL;")
    out.append(f"    for (i = 0ULL; i < {P}_REG_COUNT; i = i + 1ULL) {{ r[i] = 0ULL; }}")
    out.append("}")
    out.append("")

    # ---- one device edge: READ -> COMPUTE -> WRITE. --------------------------
    out.append("/* fifo_rx_tick: one device clock edge modelling both FIFO ports. READ the")
    out.append(" * nic seam + read-enable + both pointers + sync stages + the addressed RAM")
    out.append(" * slot, COMPUTE empty/full/fire/advance/sync (branchless), WRITE the")
    out.append(" * pointers, sync stages, flags, fire flags, and RAM slot. Write-only WRITE. */")
    # NOTE: the signature MUST stay on ONE line — gate stage 2b skips only the
    # single line that opens the tick body (the line matching `_tick(`); a wrapped
    # signature's continuation would be scanned as body and its `*nic` pointer
    # declarator falsely flagged as native multiply.
    out.append("static inline void fifo_rx_tick(word_t *r, const word_t *nic) {")
    out.append("    /* READ phase — pre-read every operand from its register. */")
    out.append(f"    const word_t power   = r[{P}_{net['power']}] & 1ULL;")
    out.append(f"    const word_t rd_en   = r[{P}_{rs['fire_from']}] & 1ULL;")
    out.append(f"    const word_t strobe  = nic[NIC_{ws['fire_from']}] & 1ULL;")
    out.append(f"    const word_t wr_bin  = r[{P}_{ws['bin']}];")
    out.append(f"    const word_t rd_bin  = r[{P}_{rs['bin']}];")
    out.append(f"    const word_t wr_gray = r[{P}_{ws['gray']}];")
    out.append(f"    const word_t rd_gray = r[{P}_{rs['gray']}];")
    out.append(f"    const word_t wq1_cur = r[{P}_{ws['sync1']}];")
    out.append(f"    const word_t wq2_cur = r[{P}_{ws['sync2']}];")
    out.append(f"    const word_t rq1_cur = r[{P}_{rs['sync1']}];")
    out.append(f"    const word_t rq2_cur = r[{P}_{rs['sync2']}];")
    # the nic seam packet lanes this FIFO stores (read each once in READ phase).
    out.append("    /* the nic seam packet lanes carried into the slot (read once). */")
    for ln in lanes:
        out.append(f"    const word_t rd_{ln.lower()} = nic[NIC_{ram_seam_src(ln)}];")
    out.append("")
    out.append("    /* write-side slot index = wr_bin & (depth-1) — branchless mask. */")
    out.append(f"    const word_t wr_idx = cell_and(wr_bin, {P}_SLOT_MASK);")
    out.append("")
    out.append("    /* COMPUTE phase — branchless flow control + advance + sync. */")
    out.append("    /* EMPTY (read domain): rd_gray == synced write gray. */")
    out.append(f"    const word_t empty = cell_eqmask(rd_gray, rq2_cur) & 1ULL;")
    out.append("    /* FULL (write domain, Cummings): wr_gray == synced read gray with the")
    out.append("     * top TWO bits inverted. inv = wq2 ^ TOP2_MASK (flip both MSBs). */")
    out.append(f"    const word_t full_cmp = cell_xor(wq2_cur, {P}_TOP2_MASK);")
    out.append(f"    const word_t full = cell_eqmask(wr_gray, full_cmp) & 1ULL;")
    out.append("    /* fire = enable & ~flag (honoured this edge; no overflow/underflow). */")
    out.append("    const word_t wr_fire = cell_and(strobe, cell_not(full) & 1ULL) & 1ULL;")
    out.append("    const word_t rd_fire = cell_and(rd_en,  cell_not(empty) & 1ULL) & 1ULL;")
    out.append("")
    out.append("    /* pointer advance: bin' = bin + fire (cell_addsub; fire is 0/1).")
    out.append("     * gray' = bin2gray(bin') — only 1 gray bit flips per increment. */")
    out.append("    const word_t wr_bin_n  = cell_addsub(wr_bin, wr_fire, 0ULL);")
    out.append("    const word_t rd_bin_n  = cell_addsub(rd_bin, rd_fire, 0ULL);")
    out.append("    const word_t wr_gray_n = bin2gray(wr_bin_n);")
    out.append("    const word_t rd_gray_n = bin2gray(rd_bin_n);")
    out.append("")
    out.append("    /* 2-FF synchronizers (power-gated dffs; NO logic between stages).")
    out.append("     * write domain captures the READ gray; read domain captures the WRITE")
    out.append("     * gray. Stage 2 latches stage 1's CURRENT value (the registered hop). */")
    out.append(f"    const word_t wq1_n = cell_dff(wq1_cur, rd_gray, power);")
    out.append(f"    const word_t wq2_n = cell_dff(wq2_cur, wq1_cur, power);")
    out.append(f"    const word_t rq1_n = cell_dff(rq1_cur, wr_gray, power);")
    out.append(f"    const word_t rq2_n = cell_dff(rq2_cur, rq1_cur, power);")
    out.append("")
    out.append("    /* slot write: the slot at wr_idx latches the seam lanes on wr_fire.")
    out.append("     * Per-slot enable = eqmask(wr_idx,i) & wr_fire (branchless; one slot). */")
    # generate per-slot, per-lane next values.
    for i in range(depth):
        en = f"(cell_eqmask(wr_idx, {i}ULL) & wr_fire)"
        for ln in lanes:
            nm = slot_lane[(i, ln)]
            local = f"s{i}_{ln.lower()}"
            out.append(f"    const word_t {local} = cell_dff(r[{P}_{nm}], rd_{ln.lower()}, {en});")
    out.append("")
    out.append("    /* WRITE phase — commit every dff/comb (registered hops). Write-only. */")
    out.append(f"    r[{P}_{ws['bin']}]   = wr_bin_n;")
    out.append(f"    r[{P}_{rs['bin']}]   = rd_bin_n;")
    out.append(f"    r[{P}_{ws['gray']}]  = wr_gray_n;")
    out.append(f"    r[{P}_{rs['gray']}]  = rd_gray_n;")
    out.append(f"    r[{P}_{ws['sync1']}] = wq1_n;")
    out.append(f"    r[{P}_{ws['sync2']}] = wq2_n;")
    out.append(f"    r[{P}_{rs['sync1']}] = rq1_n;")
    out.append(f"    r[{P}_{rs['sync2']}] = rq2_n;")
    out.append(f"    r[{P}_{ws['full']}]  = full;")
    out.append(f"    r[{P}_{rs['empty']}] = empty;")
    out.append(f"    r[{P}_{fire['write']}] = wr_fire;")
    out.append(f"    r[{P}_{fire['read']}]  = rd_fire;")
    for i in range(depth):
        for ln in lanes:
            nm = slot_lane[(i, ln)]
            local = f"s{i}_{ln.lower()}"
            out.append(f"    r[{P}_{nm}] = {local};")
    out.append("}")
    out.append("")

    # ---- read port helper: the slot the consumer would sample (rd_bin & mask). -
    # A pure address helper (no cell logic, no tick) so the display/consumer can
    # name the current head slot lane without recomputing the mask by hand.
    out.append("/* fifo_rx_head_addr: the register address of lane `lane_ofs` in the slot")
    out.append(" * at the READ pointer (rd_bin & mask). Address math only (no data path). */")
    out.append("static inline word_t fifo_rx_head_addr(const word_t *r, word_t lane_ofs) {")
    out.append(f"    const word_t rd_idx = cell_and(r[{P}_{rs['bin']}], {P}_SLOT_MASK);")
    # slot base = first lane of slot 0 + rd_idx*lanes + lane_ofs. This is ADDRESS
    # math (index arithmetic), not a data-path operator — outside any *_tick body.
    out.append(f"    const word_t slot0 = (word_t){P}_{slot_lane[(0, lanes[0])]};")
    out.append(f"    return slot0 + rd_idx * {len(lanes)}ULL + lane_ofs;")
    out.append("}")
    out.append("")

    # ---- the self-run loop (clocked), bounded by a configured tick budget. -----
    out.append("/* fifo_rx_run: the canonical clock primitive. The FIFO self-runs on its")
    out.append(" * clock edge while powered, bounded by a configured tick budget (config,")
    out.append(" * not external stepping). The starter powers it on and steps away. */")
    out.append("static inline void fifo_rx_run(word_t *r, const word_t *nic) {")
    rc, rl = run["count"], run["limit"]
    out.append(f"    while ((r[{P}_{run['power']}] & 1ULL)")
    out.append(f"           && fifo_cmp_lt(r[{P}_{rc}], r[{P}_{rl}])) {{")
    out.append("        fifo_rx_tick(r, nic);")
    out.append(f"        r[{P}_{rc}] = cell_addsub(r[{P}_{rc}], 1ULL, 0ULL);")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append("#endif /* FIFO_RX_GEN_H */")

    sys.stdout.write("\n".join(out) + "\n")


def ram_seam_src(lane):
    """The nic seam lane that feeds packet lane `lane` (SEAM_<LANE>)."""
    return f"SEAM_{lane}"


if __name__ == "__main__":
    main()
