#!/usr/bin/env python3
"""gennet.py — generate the PIP_RESOLVER device C from pip_resolver.net.json.

The PIP_RESOLVER is the per-symbol pip-resolution lookup. The device logic is
GENERATED from the netlist, never hand-written. On the MAC edge:

  READ    : the NIC seam (SEAM_SYMBOL, SEAM_VALID from nic_gen.h) and the static
            pip-config table slot at idx = SEAM_SYMBOL & TABLE_MASK.
  COMPUTE : idx = symbol & (depth-1)                            (power-of-two mask)
            res = OR-reduce over i of (eqmask(idx,i) ? table[i] : 0)  (slot select)
            en  = SEAM_VALID
  WRITE   : PIP_RESOLUTION_REG <= res (en) ; PIP_SYMBOL <= symbol (en) ;
            PIP_VALID <= SEAM_VALID ; commit PIP_TICKS via the run loop.

Generated data path contains ZERO if/switch/?: — selection is mask algebra in the
cells. NO native +/-/* on data — equality is cell_eqmask, the slot select is
cell_gate, the bounded self-run uses cmp_lt (carry chain), the tick counter steps
via cell_addsub. The table index is a power-of-two MASK cell (no %). The
free-running mac-edge loop is the canonical clock primitive and lives here in the
device, not in any test. The pip-config table is CONFIG ONLY — the tick READS it,
never writes it.
"""
import json
import sys


HEADER = """/* GENERATED by gennet.py from pip_resolver.net.json — DO NOT EDIT BY HAND.
 * The PIP_RESOLVER device: samples the NIC seam's SEAM_SYMBOL, indexes a static
 * pip-config table by the symbol address (symbol*8 bytes = the symbol-th slot;
 * power-of-two mask, no %), and publishes the resolved pip value on
 * PIP_RESOLUTION_REG. A netlist of cells over addressed registers. No branch in
 * the data path; no native add/sub/mul; the config table is read-only in the tick. */
#ifndef PIP_RESOLVER_GEN_H
#define PIP_RESOLVER_GEN_H
#include "cells.h"
#include "nic_gen.h"       /* the NIC's CANONICAL output window (generated from
                            * ../nic/nic.net.json by the NIC's gennet — single
                            * source). The PIP_RESOLVER SAMPLES the SEAM_SYMBOL /
                            * SEAM_VALID lanes; no private copy. */
"""


def emit_cmp_lt():
    """pip_cmp_lt(a, b) -> 1 iff a < b, gate-netlist carry chain (no C relational op).

    Named pip_cmp_lt (device-local) to avoid colliding with any cmp_lt that an
    included sibling header might already define.
    """
    return """
/* pip_cmp_lt: gate-netlist comparator (a < b), carry chain over cell_fa. The
 * bounded self-run uses it on a configured tick budget (config, not external
 * stepping). Device-local name (avoid colliding with an included cmp_lt). */
static inline word_t pip_cmp_lt(word_t a, word_t b) {
    word_t carry = 1ULL;
    word_t i = 0ULL;
    for (i = 0ULL; i < 64ULL; i = i + 1ULL) {
        const word_t aa = (a >> i) & 1ULL;
        const word_t nb = (cell_not(b) >> i) & 1ULL;
        const word_t fa = cell_fa(aa, nb, carry);
        carry           = (fa >> 1) & 1ULL;
    }
    return (carry & 1ULL) ^ 1ULL;
}
"""


def main():
    net_path = sys.argv[1] if len(sys.argv) > 1 else "pip_resolver.net.json"
    with open(net_path) as f:
        net = json.load(f)

    table = net["table"]
    depth = table["depth"]
    if depth <= 0 or (depth & (depth - 1)) != 0:
        sys.stderr.write(
            f"gennet: table depth ({depth}) must be a power of two "
            f"(index is a branchless mask: SEAM_SYMBOL & (depth-1)).\n")
        sys.exit(2)

    comp = net["compute"]
    out_nodes = net["out_nodes"]
    out_status = net["out_status"]
    run = net["run"]

    # ---- assign addresses: one register slot per PIP-owned node, in order. ----
    # config -> table slots -> dff(PIP_TICKS) -> out nodes -> out status.
    order = []
    for n in net.get("config_nodes", []):
        order.append(n["name"])
    table_slots = [f"{table['prefix']}_{i}" for i in range(depth)]
    for slot in table_slots:
        order.append(slot)
    for n in net.get("dff_nodes", []):
        order.append(n["name"])
    for n in out_nodes:
        order.append(n["name"])
    for n in out_status:
        order.append(n["name"])

    addr = {nm: i for i, nm in enumerate(order)}
    count = len(order)
    P = "PIP"   # register prefix

    out = [HEADER]
    out.append(f"#define {P}_REG_COUNT {count}u")
    out.append(f"#define {P}_TABLE_DEPTH {depth}u")
    # table wrap mask DERIVED from depth (power of two) — not a second literal.
    out.append(f"#define {P}_TABLE_MASK ({P}_TABLE_DEPTH - 1u)\n")
    for nm in order:
        out.append(f"#define {P}_{nm} {addr[nm]}u")
    out.append("")
    out.append(emit_cmp_lt())
    out.append("")

    # ---- init: power-off synchronous reset (everything zero). -----------------
    out.append("static inline void pip_resolver_init(word_t *r) {")
    out.append("    word_t i = 0ULL;")
    out.append(f"    for (i = 0ULL; i < {P}_REG_COUNT; i = i + 1ULL) {{ r[i] = 0ULL; }}")
    out.append("}")
    out.append("")

    # ---- one MAC clock edge: READ -> COMPUTE -> WRITE. -----------------------
    out.append("/* pip_resolver_tick: one MAC clock edge. READ the NIC seam (SEAM_SYMBOL,")
    out.append(" * SEAM_VALID) + the static table slot at idx = symbol & MASK, COMPUTE the")
    out.append(" * resolved pip value (branchless eqmask-gate-OR slot select), WRITE the")
    out.append(" * output lanes + status. The config table is READ-only here. Write-only")
    out.append(" * WRITE phase. */")
    # NOTE: the signature MUST stay on ONE line — gate stage 2b skips only the
    # single line that opens the tick body (the line matching `_tick(`); a wrapped
    # signature's continuation would be scanned as body and its `*nic` pointer
    # declarator falsely flagged as native multiply.
    out.append("static inline void pip_resolver_tick(word_t *r, const word_t *nic) {")
    out.append("    /* READ phase — pre-read every operand from its register. */")
    out.append(f"    const word_t power  = r[{P}_{net['power']}] & 1ULL;")
    out.append(f"    const word_t symbol = nic[NIC_{comp['symbol']}];")
    out.append(f"    const word_t valid  = nic[NIC_{comp['valid']}] & 1ULL;")
    out.append("")
    out.append("    /* table index = SEAM_SYMBOL & (depth-1) — a branchless power-of-two")
    out.append("     * mask cell (depth is a power of two; the symbol*8 byte address maps")
    out.append("     * to word slot = symbol, reduced to the table range; no %, no if). */")
    out.append(f"    const word_t idx = cell_and(symbol, {P}_TABLE_MASK);")
    out.append("    /* read the addressed table slot (branchless select: eqmask(idx,i)")
    out.append("     * gates exactly one config slot through; OR-reduce the rest as 0). */")
    out.append("    word_t res = 0ULL;")
    for i in range(depth):
        out.append(f"    res = cell_or(res, cell_gate(r[{P}_{table_slots[i]}], cell_eqmask(idx, {i}ULL)));")
    out.append("")
    out.append("    /* COMPUTE phase — the latch enable: only a valid sampled symbol")
    out.append("     * updates the resolved output. */")
    out.append("    const word_t en = valid;")
    out.append("")
    out.append("    /* output flops: latch the resolved pip value + the symbol on en=valid")
    out.append("     * (gated dff); PIP_VALID latches SEAM_VALID while powered. */")
    out_locals = {}
    for n in out_nodes:
        nm = n["name"]
        frm = n["from"]
        if frm == "res":
            src = "res"
        elif frm == "symbol":
            src = "symbol"
        else:
            sys.stderr.write(f"gennet: out lane {nm} has unknown source {frm}\n")
            sys.exit(2)
        en = n.get("en", "valid")   # the latch enable selector ("valid")
        local = "out_" + nm.lower()
        out_locals[nm] = local
        out.append(f"    const word_t {local} = cell_dff(r[{P}_{nm}], {src}, en);")
    status_locals = {}
    for n in out_status:
        nm = n["name"]
        src = n["from"]   # "valid"
        local = "st_" + nm.lower()
        status_locals[nm] = local
        out.append(f"    const word_t {local} = cell_dff(r[{P}_{nm}], {src}, power);")
    out.append("")
    out.append("    /* WRITE phase — commit every dff (registered hop). Write-only. */")
    for nm in out_locals:
        out.append(f"    r[{P}_{nm}] = {out_locals[nm]};")
    for nm in status_locals:
        out.append(f"    r[{P}_{nm}] = {status_locals[nm]};")
    out.append("}")
    out.append("")

    # ---- the self-run loop (mac-edge clocked), bounded by a configured tick. --
    out.append("/* pip_resolver_run: the canonical clock primitive. The device self-runs")
    out.append(" * on the mac edge while powered, bounded by a configured tick budget")
    out.append(" * (config, not external stepping). The starter powers it on, configures")
    out.append(" * the static table, and steps away. */")
    out.append("static inline void pip_resolver_run(word_t *r, const word_t *nic) {")
    rc, rl = run["count"], run["limit"]
    out.append(f"    while ((r[{P}_{run['power']}] & 1ULL)")
    out.append(f"           && pip_cmp_lt(r[{P}_{rc}], r[{P}_{rl}])) {{")
    out.append("        pip_resolver_tick(r, nic);")
    out.append(f"        r[{P}_{rc}] = cell_addsub(r[{P}_{rc}], 1ULL, 0ULL);")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append("#endif /* PIP_RESOLVER_GEN_H */")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
