#!/usr/bin/env python3
"""gennet.py — generate the counter-clock device C from a <clock>.net.json.

The device logic is GENERATED from the netlist, never hand-written. Every node
becomes an addressed register slot; the tick is straight-line cell composition
(cell_gate + cell_addsub) with NO if/switch/?: in the data path. Selection is
mask algebra inside the cells; the increment is the structural ripple-carry
cell_addsub adder (no native +).

Drives the free-running counter family: taisoc / tai / mac / internal. A counter
advances by `step` each powered tick. `step` is either:
  - a power gate of 1 (a self-running oscillator: cell_gate(1, power)), or
  - an external edge strobe lane (e.g. tai counts taisoc's edge), declared via
    counter.increment.

An optional `edge` node emits a 1-per-powered-tick strobe (the oscillator edge).

The free-running loop self-oscillates from the power bit, bounded by a configured
stop count (run_bound) — exactly as the adapter self-runs bounded by its finite
buffer. The bound is configuration (set once by the starter), not external
stepping: nothing outside the device advances the clock. The comparison
(cycle < bound) is the structural carry-chain comparator cmp_lt, not a C compare.
"""
import json
import sys


def emit_cmp_lt():
    """Emit cmp_lt(a, b) -> 1 iff a < b, built ONLY from cells (carry chain).

    a < b  <=>  a - b borrows out of bit 63  <=>  the carry-out of (a + ~b + 1)
    is 0. Pure gate netlist over cell_fa — no C relational operator. This mirrors
    the adapter's cmp_le; it is generator-level unrolling, not a data-path branch.
    """
    return """
/* cmp_lt: gate-netlist comparator. Returns 1 (bit0) iff a < b (unsigned).
 * a - b = a + (~b) + 1 via 64 full-adder cells; the carry-out of the top bit is
 * (a >= b). So (a < b) = 1 - carry, expressed branchlessly as (carry ^ 1). */
static inline word_t cmp_lt(word_t a, word_t b) {
    word_t carry = 1ULL;                 /* +1 for two's-complement of b */
    word_t i = 0ULL;
    for (i = 0ULL; i < 64ULL; i = i + 1ULL) {
        const word_t aa = (a >> i) & 1ULL;
        const word_t nb = (cell_not(b) >> i) & 1ULL;     /* ~b bit */
        const word_t fa = cell_fa(aa, nb, carry);
        carry           = (fa >> 1) & 1ULL;              /* carry-out to next */
    }
    return (carry & 1ULL) ^ 1ULL;        /* carry==0 (borrow) == (a < b) */
}
"""


def main():
    net_path = sys.argv[1] if len(sys.argv) > 1 else "taisoc.net.json"
    with open(net_path) as f:
        net = json.load(f)

    dev = net["device"]
    DEV = dev.upper()
    pfx = DEV  # register prefix, e.g. TAISOC_

    # ---- one register slot per node, in declaration order. -------------------
    order = []
    for grp in ("config_nodes", "dff_nodes"):
        for n in net.get(grp, []):
            order.append(n["name"])
    addr = {nm: i for i, nm in enumerate(order)}
    count = len(order)

    config = [n["name"] for n in net.get("config_nodes", [])]
    counter = net["counter"]
    creg = counter["reg"]
    cpower = counter["power"]
    cinc = counter.get("increment")     # external strobe lane, or None -> gate(1,power)
    edge = net.get("edge")
    run_power = net["run_power"]
    run_bound = net.get("run_bound")    # {"count": <counter reg>, "limit": <config reg>} or None

    out = []
    out.append(f"/* GENERATED by gennet.py from {net_path} — DO NOT EDIT BY HAND.")
    out.append(f" * The {dev} clock: a free-running counter (+ optional edge strobe) as a")
    out.append(" * netlist of cells over addressed registers. No if/switch/?: in the data")
    out.append(" * path; the increment is the structural cell_addsub ripple-carry adder. */")
    out.append(f"#ifndef {DEV}_GEN_H")
    out.append(f"#define {DEV}_GEN_H")
    out.append('#include "cells.h"')
    out.append("")
    out.append(f"#define {pfx}_REG_COUNT {count}u")
    for nm in order:
        out.append(f"#define {pfx}_{nm} {addr[nm]}u")
    out.append("")
    if run_bound:
        out.append(emit_cmp_lt())
        out.append("")

    # ---- init: power-off synchronous reset value (everything zero). ----------
    out.append(f"static inline void {dev}_init(word_t *r) {{")
    out.append("    word_t i = 0ULL;")
    out.append(f"    for (i = 0ULL; i < {pfx}_REG_COUNT; i = i + 1ULL) {{ r[i] = 0ULL; }}")
    out.append("}")
    out.append("")

    # ---- one clock edge: READ -> COMPUTE -> WRITE. ---------------------------
    out.append(f"/* {dev}_tick: one clock edge. READ inputs as const locals, COMPUTE the")
    out.append(" * gated step + ripple-carry increment, WRITE the counter (and edge). The")
    out.append(" * WRITE phase is write-only; no read-after-write. */")
    out.append(f"static inline void {dev}_tick(word_t *r) {{")
    out.append("    /* READ phase — pre-read every operand from its register. */")
    out.append(f"    const word_t power = r[{pfx}_{cpower}] & 1ULL;")
    out.append(f"    const word_t cur   = r[{pfx}_{creg}];")
    if cinc:
        out.append(f"    const word_t inc   = r[{pfx}_{cinc}] & 1ULL;")
    out.append("")
    out.append("    /* COMPUTE phase — branchless. */")
    if cinc:
        # step = the external strobe, gated by power (only count when powered AND strobe high).
        out.append("    /* step: count one when the incoming strobe is high AND we are powered. */")
        out.append("    const word_t step = cell_gate(inc, power);")
    else:
        # self-running oscillator: step = power-gated 1.
        out.append("    /* step: advance by 1 while powered, 0 while off (power-gated). */")
        out.append("    const word_t step = cell_gate(1ULL, power);")
    out.append("    /* increment via the structural ripple-carry adder (no native +). */")
    out.append("    const word_t cnt_next = cell_addsub(cur, step, 0ULL);")
    if edge:
        out.append("    /* edge strobe: high every powered tick (the oscillator edge). */")
        out.append("    const word_t edge_next = cell_gate(1ULL, power) & 1ULL;")
    out.append("")
    out.append("    /* WRITE phase — commit the registered hop(s). */")
    out.append(f"    r[{pfx}_{creg}] = cnt_next;")
    if edge:
        out.append(f"    r[{pfx}_{edge['reg']}] = edge_next;")
    out.append("}")
    out.append("")

    # ---- canonical free-running clock loop (power-bit gated). -----------------
    out.append(f"/* {dev}_run: the canonical clock primitive. Power on once; the clock")
    out.append(" * self-oscillates from the power bit. Nothing external advances it.")
    if run_bound:
        out.append(" * Bounded by a CONFIGURED stop count (set once by the starter) — exactly")
        out.append(" * as the adapter self-runs bounded by its finite buffer. The bound is")
        out.append(" * configuration, not external stepping; the compare is the cmp_lt carry")
        out.append(" * chain (no C relational operator in the loop condition's intent). */")
    else:
        out.append(" */")
    out.append(f"static inline void {dev}_run(word_t *r) {{")
    if run_bound:
        bc = run_bound["count"]
        bl = run_bound["limit"]
        out.append(f"    while ((r[{pfx}_{run_power}] & 1ULL)")
        out.append(f"           && cmp_lt(r[{pfx}_{bc}], r[{pfx}_{bl}])) {{ {dev}_tick(r); }}")
    else:
        out.append(f"    while (r[{pfx}_{run_power}] & 1ULL) {{ {dev}_tick(r); }}")
    out.append("}")
    out.append("")
    out.append(f"#endif /* {DEV}_GEN_H */")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
