/* GENERATED by gennet.py from interconnect/switch_box.net.json — DO NOT EDIT BY HAND.
 * The switch_box device: register lanes + cell-based logic (READ->COMPUTE->WRITE).
 * Netlist-generated; every data operation is a structural cell call. */
#ifndef SWITCH_BOX_GEN_H
#define SWITCH_BOX_GEN_H
#include "cells.h"

#define SWITCH_BOX_REG_COUNT 69u

#define SWITCH_BOX_IN_0 0u
#define SWITCH_BOX_IN_1 1u
#define SWITCH_BOX_IN_2 2u
#define SWITCH_BOX_IN_3 3u
#define SWITCH_BOX_CFG_0_0_D 4u
#define SWITCH_BOX_CFG_0_1_D 5u
#define SWITCH_BOX_CFG_0_2_D 6u
#define SWITCH_BOX_CFG_0_3_D 7u
#define SWITCH_BOX_CFG_1_0_D 8u
#define SWITCH_BOX_CFG_1_1_D 9u
#define SWITCH_BOX_CFG_1_2_D 10u
#define SWITCH_BOX_CFG_1_3_D 11u
#define SWITCH_BOX_CFG_2_0_D 12u
#define SWITCH_BOX_CFG_2_1_D 13u
#define SWITCH_BOX_CFG_2_2_D 14u
#define SWITCH_BOX_CFG_2_3_D 15u
#define SWITCH_BOX_CFG_3_0_D 16u
#define SWITCH_BOX_CFG_3_1_D 17u
#define SWITCH_BOX_CFG_3_2_D 18u
#define SWITCH_BOX_CFG_3_3_D 19u
#define SWITCH_BOX_CFG_EN 20u
#define SWITCH_BOX_PIP_0_0 21u
#define SWITCH_BOX_PIP_0_1 22u
#define SWITCH_BOX_PIP_0_2 23u
#define SWITCH_BOX_PIP_0_3 24u
#define SWITCH_BOX_PIP_1_0 25u
#define SWITCH_BOX_PIP_1_1 26u
#define SWITCH_BOX_PIP_1_2 27u
#define SWITCH_BOX_PIP_1_3 28u
#define SWITCH_BOX_PIP_2_0 29u
#define SWITCH_BOX_PIP_2_1 30u
#define SWITCH_BOX_PIP_2_2 31u
#define SWITCH_BOX_PIP_2_3 32u
#define SWITCH_BOX_PIP_3_0 33u
#define SWITCH_BOX_PIP_3_1 34u
#define SWITCH_BOX_PIP_3_2 35u
#define SWITCH_BOX_PIP_3_3 36u
#define SWITCH_BOX_G_0_0 37u
#define SWITCH_BOX_G_0_1 38u
#define SWITCH_BOX_G_0_2 39u
#define SWITCH_BOX_G_0_3 40u
#define SWITCH_BOX_G_1_0 41u
#define SWITCH_BOX_G_1_1 42u
#define SWITCH_BOX_G_1_2 43u
#define SWITCH_BOX_G_1_3 44u
#define SWITCH_BOX_G_2_0 45u
#define SWITCH_BOX_G_2_1 46u
#define SWITCH_BOX_G_2_2 47u
#define SWITCH_BOX_G_2_3 48u
#define SWITCH_BOX_G_3_0 49u
#define SWITCH_BOX_G_3_1 50u
#define SWITCH_BOX_G_3_2 51u
#define SWITCH_BOX_G_3_3 52u
#define SWITCH_BOX_ACC_0_1 53u
#define SWITCH_BOX_ACC_0_2 54u
#define SWITCH_BOX_OUT_0_C 55u
#define SWITCH_BOX_ACC_1_1 56u
#define SWITCH_BOX_ACC_1_2 57u
#define SWITCH_BOX_OUT_1_C 58u
#define SWITCH_BOX_ACC_2_1 59u
#define SWITCH_BOX_ACC_2_2 60u
#define SWITCH_BOX_OUT_2_C 61u
#define SWITCH_BOX_ACC_3_1 62u
#define SWITCH_BOX_ACC_3_2 63u
#define SWITCH_BOX_OUT_3_C 64u
#define SWITCH_BOX_OUT_0 65u
#define SWITCH_BOX_OUT_1 66u
#define SWITCH_BOX_OUT_2 67u
#define SWITCH_BOX_OUT_3 68u

static inline void switch_box_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < SWITCH_BOX_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
}

/* switch_box_tick: one clock edge. READ inputs as const locals,
 * COMPUTE via cells (no native add/sub/mul on data), WRITE every register. */
static inline void switch_box_tick(word_t *r) {
    /* READ phase — pre-read every consumed register value. */
    const word_t in_0 = r[SWITCH_BOX_IN_0];
    const word_t in_1 = r[SWITCH_BOX_IN_1];
    const word_t in_2 = r[SWITCH_BOX_IN_2];
    const word_t in_3 = r[SWITCH_BOX_IN_3];
    const word_t cfg_0_0_d = r[SWITCH_BOX_CFG_0_0_D];
    const word_t cfg_0_1_d = r[SWITCH_BOX_CFG_0_1_D];
    const word_t cfg_0_2_d = r[SWITCH_BOX_CFG_0_2_D];
    const word_t cfg_0_3_d = r[SWITCH_BOX_CFG_0_3_D];
    const word_t cfg_1_0_d = r[SWITCH_BOX_CFG_1_0_D];
    const word_t cfg_1_1_d = r[SWITCH_BOX_CFG_1_1_D];
    const word_t cfg_1_2_d = r[SWITCH_BOX_CFG_1_2_D];
    const word_t cfg_1_3_d = r[SWITCH_BOX_CFG_1_3_D];
    const word_t cfg_2_0_d = r[SWITCH_BOX_CFG_2_0_D];
    const word_t cfg_2_1_d = r[SWITCH_BOX_CFG_2_1_D];
    const word_t cfg_2_2_d = r[SWITCH_BOX_CFG_2_2_D];
    const word_t cfg_2_3_d = r[SWITCH_BOX_CFG_2_3_D];
    const word_t cfg_3_0_d = r[SWITCH_BOX_CFG_3_0_D];
    const word_t cfg_3_1_d = r[SWITCH_BOX_CFG_3_1_D];
    const word_t cfg_3_2_d = r[SWITCH_BOX_CFG_3_2_D];
    const word_t cfg_3_3_d = r[SWITCH_BOX_CFG_3_3_D];
    const word_t cfg_en = r[SWITCH_BOX_CFG_EN];
    const word_t pip_0_0 = r[SWITCH_BOX_PIP_0_0];
    const word_t pip_0_1 = r[SWITCH_BOX_PIP_0_1];
    const word_t pip_0_2 = r[SWITCH_BOX_PIP_0_2];
    const word_t pip_0_3 = r[SWITCH_BOX_PIP_0_3];
    const word_t pip_1_0 = r[SWITCH_BOX_PIP_1_0];
    const word_t pip_1_1 = r[SWITCH_BOX_PIP_1_1];
    const word_t pip_1_2 = r[SWITCH_BOX_PIP_1_2];
    const word_t pip_1_3 = r[SWITCH_BOX_PIP_1_3];
    const word_t pip_2_0 = r[SWITCH_BOX_PIP_2_0];
    const word_t pip_2_1 = r[SWITCH_BOX_PIP_2_1];
    const word_t pip_2_2 = r[SWITCH_BOX_PIP_2_2];
    const word_t pip_2_3 = r[SWITCH_BOX_PIP_2_3];
    const word_t pip_3_0 = r[SWITCH_BOX_PIP_3_0];
    const word_t pip_3_1 = r[SWITCH_BOX_PIP_3_1];
    const word_t pip_3_2 = r[SWITCH_BOX_PIP_3_2];
    const word_t pip_3_3 = r[SWITCH_BOX_PIP_3_3];

    /* COMPUTE phase — combinational cell chain (declaration order). */
    const word_t g_0_0 = cell_gate(in_0, pip_0_0);
    const word_t g_0_1 = cell_gate(in_0, pip_0_1);
    const word_t g_0_2 = cell_gate(in_0, pip_0_2);
    const word_t g_0_3 = cell_gate(in_0, pip_0_3);
    const word_t g_1_0 = cell_gate(in_1, pip_1_0);
    const word_t g_1_1 = cell_gate(in_1, pip_1_1);
    const word_t g_1_2 = cell_gate(in_1, pip_1_2);
    const word_t g_1_3 = cell_gate(in_1, pip_1_3);
    const word_t g_2_0 = cell_gate(in_2, pip_2_0);
    const word_t g_2_1 = cell_gate(in_2, pip_2_1);
    const word_t g_2_2 = cell_gate(in_2, pip_2_2);
    const word_t g_2_3 = cell_gate(in_2, pip_2_3);
    const word_t g_3_0 = cell_gate(in_3, pip_3_0);
    const word_t g_3_1 = cell_gate(in_3, pip_3_1);
    const word_t g_3_2 = cell_gate(in_3, pip_3_2);
    const word_t g_3_3 = cell_gate(in_3, pip_3_3);
    const word_t acc_0_1 = cell_or(g_0_0, g_1_0);
    const word_t acc_0_2 = cell_or(acc_0_1, g_2_0);
    const word_t out_0_c = cell_or(acc_0_2, g_3_0);
    const word_t acc_1_1 = cell_or(g_0_1, g_1_1);
    const word_t acc_1_2 = cell_or(acc_1_1, g_2_1);
    const word_t out_1_c = cell_or(acc_1_2, g_3_1);
    const word_t acc_2_1 = cell_or(g_0_2, g_1_2);
    const word_t acc_2_2 = cell_or(acc_2_1, g_2_2);
    const word_t out_2_c = cell_or(acc_2_2, g_3_2);
    const word_t acc_3_1 = cell_or(g_0_3, g_1_3);
    const word_t acc_3_2 = cell_or(acc_3_1, g_2_3);
    const word_t out_3_c = cell_or(acc_3_2, g_3_3);

    /* WRITE phase — gated dff commit: r[X] = cell_dff(q, fed_by, enable). */
    r[SWITCH_BOX_PIP_0_0] = cell_dff(pip_0_0, cfg_0_0_d, cfg_en);
    r[SWITCH_BOX_PIP_0_1] = cell_dff(pip_0_1, cfg_0_1_d, cfg_en);
    r[SWITCH_BOX_PIP_0_2] = cell_dff(pip_0_2, cfg_0_2_d, cfg_en);
    r[SWITCH_BOX_PIP_0_3] = cell_dff(pip_0_3, cfg_0_3_d, cfg_en);
    r[SWITCH_BOX_PIP_1_0] = cell_dff(pip_1_0, cfg_1_0_d, cfg_en);
    r[SWITCH_BOX_PIP_1_1] = cell_dff(pip_1_1, cfg_1_1_d, cfg_en);
    r[SWITCH_BOX_PIP_1_2] = cell_dff(pip_1_2, cfg_1_2_d, cfg_en);
    r[SWITCH_BOX_PIP_1_3] = cell_dff(pip_1_3, cfg_1_3_d, cfg_en);
    r[SWITCH_BOX_PIP_2_0] = cell_dff(pip_2_0, cfg_2_0_d, cfg_en);
    r[SWITCH_BOX_PIP_2_1] = cell_dff(pip_2_1, cfg_2_1_d, cfg_en);
    r[SWITCH_BOX_PIP_2_2] = cell_dff(pip_2_2, cfg_2_2_d, cfg_en);
    r[SWITCH_BOX_PIP_2_3] = cell_dff(pip_2_3, cfg_2_3_d, cfg_en);
    r[SWITCH_BOX_PIP_3_0] = cell_dff(pip_3_0, cfg_3_0_d, cfg_en);
    r[SWITCH_BOX_PIP_3_1] = cell_dff(pip_3_1, cfg_3_1_d, cfg_en);
    r[SWITCH_BOX_PIP_3_2] = cell_dff(pip_3_2, cfg_3_2_d, cfg_en);
    r[SWITCH_BOX_PIP_3_3] = cell_dff(pip_3_3, cfg_3_3_d, cfg_en);
    r[SWITCH_BOX_G_0_0] = g_0_0;
    r[SWITCH_BOX_G_0_1] = g_0_1;
    r[SWITCH_BOX_G_0_2] = g_0_2;
    r[SWITCH_BOX_G_0_3] = g_0_3;
    r[SWITCH_BOX_G_1_0] = g_1_0;
    r[SWITCH_BOX_G_1_1] = g_1_1;
    r[SWITCH_BOX_G_1_2] = g_1_2;
    r[SWITCH_BOX_G_1_3] = g_1_3;
    r[SWITCH_BOX_G_2_0] = g_2_0;
    r[SWITCH_BOX_G_2_1] = g_2_1;
    r[SWITCH_BOX_G_2_2] = g_2_2;
    r[SWITCH_BOX_G_2_3] = g_2_3;
    r[SWITCH_BOX_G_3_0] = g_3_0;
    r[SWITCH_BOX_G_3_1] = g_3_1;
    r[SWITCH_BOX_G_3_2] = g_3_2;
    r[SWITCH_BOX_G_3_3] = g_3_3;
    r[SWITCH_BOX_ACC_0_1] = acc_0_1;
    r[SWITCH_BOX_ACC_0_2] = acc_0_2;
    r[SWITCH_BOX_OUT_0_C] = out_0_c;
    r[SWITCH_BOX_ACC_1_1] = acc_1_1;
    r[SWITCH_BOX_ACC_1_2] = acc_1_2;
    r[SWITCH_BOX_OUT_1_C] = out_1_c;
    r[SWITCH_BOX_ACC_2_1] = acc_2_1;
    r[SWITCH_BOX_ACC_2_2] = acc_2_2;
    r[SWITCH_BOX_OUT_2_C] = out_2_c;
    r[SWITCH_BOX_ACC_3_1] = acc_3_1;
    r[SWITCH_BOX_ACC_3_2] = acc_3_2;
    r[SWITCH_BOX_OUT_3_C] = out_3_c;
    r[SWITCH_BOX_OUT_0] = out_0_c;
    r[SWITCH_BOX_OUT_1] = out_1_c;
    r[SWITCH_BOX_OUT_2] = out_2_c;
    r[SWITCH_BOX_OUT_3] = out_3_c;

}

/* switch_box_run: canonical free-running clock. Power on once; the clock
 * self-oscillates while the power bit is set. Nothing external steps it. */
static inline void switch_box_run(word_t *r) {
    switch_box_tick(r);
}

#endif /* SWITCH_BOX_GEN_H */
