#!/usr/bin/env python3
"""
assemble.py — Tool #3: build library.json from primitives.json + templates.py,
and CROSS-CHECK every block's ports against specgen's PDF extraction (spec conformance).

library.json becomes a GENERATED artifact — no hand editing. Port mismatches between
a template and the PDF are reported (so a template drifting from the spec is caught
automatically). Exit 0 ok (mismatches warn), 2 internal error.
"""
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import templates as T

PRIMS   = os.path.join(HERE, "primitives.json")
SPECGEN = os.path.join(HERE, "specgen_out.json")
LIB     = os.path.join(os.path.dirname(HERE), "device", "library.json")

# doc-caption quirks -> our canonical block name (mapping only; no device facts)
ALIAS = {"MMCME": "MMCME4_ADV", "MMCM": "MMCME4_ADV"}

def portset(ports): return {p["name"] for p in ports}

def run():
    try:
        prims = json.load(open(PRIMS)); prims.pop("_doc", None)
    except Exception as e:
        print(f"assemble: cannot read primitives.json: {e}"); return 2
    blocks = {}
    for name, builder in T.BLOCKS.items():
        b = builder(); b.setdefault("nets", []); blocks[name] = b

    mism = 0
    if os.path.exists(SPECGEN):
        spec = json.load(open(SPECGEN))
        ext = {}
        for ename, e in spec.items():
            ext.setdefault(ALIAS.get(ename, ename), set()).update(p["name"] for p in e["ports"])
        for name, b in blocks.items():
            if name in ext:
                tmpl, pdf = portset(b["ports"]), ext[name]
                miss, extra = pdf - tmpl, tmpl - pdf
                if miss or extra:
                    mism += 1
                    print(f"assemble: PORT MISMATCH {name}: pdf-only={sorted(miss)} template-only={sorted(extra)}")
                else:
                    print(f"assemble: ✓ {name} ports match PDF ({len(tmpl)})")

    lib = {"_doc": "GENERATED by assemble.py (primitives.json + templates.py, cross-checked vs specgen PDF extraction). DO NOT hand-edit — edit templates.py.",
           "primitives": prims, "blocks": blocks}
    json.dump(lib, open(LIB, "w"), indent=2)
    print(f"assemble: wrote library.json — {len(prims)} primitives, {len(blocks)} blocks"
          + (f"  ({mism} port mismatch)" if mism else "  (all cross-checked blocks match PDF)"))
    return 0

if __name__ == "__main__":
    try: sys.exit(run())
    except Exception:
        import traceback; traceback.print_exc(); sys.exit(2)
