#!/usr/bin/env python3
"""
gen_container.py — P2 realizer: emit the blank container as C from container.json. Each
physical element TYPE -> a lean struct + a static array sized to its authentic count (the
8.1M lives in array dimensions, code stays O(types) — scale architecture, no monolithic
file). A blank: storage, no design loaded. Grid (X,Y) is the array index = identity.

Emits container_gen.h (the fabric) + container_post.c (power-on POST that reports the cast).
TOOL OUTPUT — do not hand-edit. Usage: gen_container.py
"""
import json, os, re
HERE = os.path.dirname(os.path.abspath(__file__))
c = json.load(open(os.path.join(HERE, "container.json")))
def ident(s): return re.sub(r"[^A-Za-z0-9_]", "_", s).lower()

els = [e for e in c["elements"] if e.get("count")]              # counted types form the fabric arrays
lines = ["/* container_gen.h — GENERATED by gen_container.py from container.json. DO NOT EDIT. */",
         "#ifndef CONTAINER_GEN_H", "#define CONTAINER_GEN_H", "#include <stdint.h>", "",
         "/* one lean fabric-element record: state word + config word. Grid index = identity. */",
         "typedef struct { uint64_t state; uint64_t cfg; } fabric_element;", ""]
for e in els:
    lines.append(f"static fabric_element {ident(e['name'])}[{e['count']}]; "
                 f"/* {e['subsystem']} · {e['ports']}p · {e['configs']} configs */")
lines += ["", "typedef struct { const char *name; unsigned long long count; const char *sub; } cast_row;",
          "static const cast_row CAST[] = {"]
for e in els:
    lines.append(f'  {{"{e["name"]}", {e["count"]}ULL, "{e["subsystem"]}"}},')
lines += ["};", f"enum {{ CAST_TYPES = {len(els)} }};",
          f"static const unsigned long long CAST_TOTAL = {c['totals']['total_placed_instances']}ULL;",
          f"static const unsigned long long CAST_SLICES = {c['grid']['slices']}ULL;",
          "#endif"]
open(os.path.join(HERE, "container_gen.h"), "w").write("\n".join(lines) + "\n")

post = '''/* container_post.c — GENERATED power-on POST for the blank container. */
#include <stdio.h>
#include "container_gen.h"
int main(void){
    unsigned long long total=0;
    printf("== XCZU19EG blank container — POWER-ON POST ==\\n");
    printf("%-20s %14s  %s\\n","element","instances","subsystem");
    for(int i=0;i<CAST_TYPES;i++){ total+=CAST[i].count;
        printf("%-20s %14llu  %s\\n",CAST[i].name,CAST[i].count,CAST[i].sub); }
    printf("----\\n%d element types, %llu instances placed (manifest total %llu)\\n",
           CAST_TYPES, total, CAST_TOTAL);
    printf("slices=%llu  fabric arrays allocated: PASS\\n", CAST_SLICES);
    /* touch the largest arrays so they are linked, not dead-stripped */
    storage_element[0].state=1; lut6[0].cfg=1;
    return total==CAST_TOTAL?0:1;
}
'''
open(os.path.join(HERE, "container_post.c"), "w").write(post)
print(f"gen_container: emitted container_gen.h ({len(els)} fabric arrays) + container_post.c")
print(f"  total instances in arrays: {c['totals']['total_placed_instances']:,}")
