#!/usr/bin/env python3
"""
integrate.py — the INTEGRATION TOOL.

Merges three block sources into library.json, validates EVERYTHING via netc's
validator, and cross-checks ports vs the PDF (specgen):
  1. primitives.json        — Tier-0 leaf axioms
  2. templates.py BLOCKS     — Python decomposition builders (already-done blocks)
  3. blocks/*.json           — agent/tool-generated block-definition files (new blocks)

New blocks arrive as FILES produced by extraction agents — no hand-editing. Each file
is one block in {ports, cells, nets} form (the same shape netc/device.json use):
  {"name":"drp","group":"...","spec":"...","ports":[{name,dir,kind?,width?}],
   "cells":[{ref,type,conn}],"nets":[...],"abstract"?:true}

Usage: integrate.py [--check]   (--check = validate only, don't write library.json)
Exit 0 ok, 1 validation error, 2 internal.
"""
import json, os, sys, glob
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import templates as T
import netc

PRIMS = os.path.join(HERE, "primitives.json")
BDIR  = os.path.join(HERE, "blocks")
SPEC  = os.path.join(HERE, "specgen_out.json")
LIB   = os.path.join(os.path.dirname(HERE), "device", "library.json")
ALIAS = {"MMCME": "MMCME4_ADV", "MMCM": "MMCME4_ADV", "PLLE": "PLLE4_ADV", "PLL": "PLLE4_ADV"}

def load_blocks():
    blocks = {}
    for name, b in T.BLOCKS.items():
        blk = b(); blk.setdefault("nets", []); blocks[name] = blk
    nfiles = 0
    if os.path.isdir(BDIR):
        for f in sorted(glob.glob(os.path.join(BDIR, "*.json"))):
            try:
                d = json.load(open(f))
            except Exception as e:
                print(f"integrate: ✗ {os.path.basename(f)}: bad JSON: {e}"); raise
            name = d.pop("name", None) or os.path.splitext(os.path.basename(f))[0]
            d.setdefault("nets", []); blocks[name] = d; nfiles += 1
    return blocks, nfiles

def run(check=False):
    prims = json.load(open(PRIMS)); prims.pop("_doc", None)
    try:
        blocks, nfiles = load_blocks()
    except Exception:
        return 2
    lib = {"primitives": prims, "blocks": blocks}
    try:
        errs, warns = netc.validate(lib)
    except Exception:
        import traceback; traceback.print_exc(); return 2
    for w in warns: print(f"integrate: WARN {w}")
    if errs:
        print(f"integrate: {len(errs)} VALIDATION ERROR(S):")
        for e in errs: print(f"  ✗ {e}")
        return 1
    if os.path.exists(SPEC):
        spec = json.load(open(SPEC)); ext = {}
        for en, e in spec.items():
            ext.setdefault(ALIAS.get(en, en), set()).update(p["name"] for p in e["ports"])
        for name, b in blocks.items():
            if name in ext:
                t = {p["name"] for p in b["ports"]}; miss, xtra = ext[name] - t, t - ext[name]
                if miss or xtra:
                    print(f"integrate: PORT MISMATCH {name}: pdf-only={sorted(miss)} extra={sorted(xtra)}")
                else:
                    print(f"integrate: ✓ {name} ports match PDF ({len(t)})")
    if check:
        print(f"integrate: CHECK OK — {len(blocks)} blocks ({nfiles} from blocks/) validate")
        return 0
    lib["_doc"] = "GENERATED by integrate.py (primitives.json + templates.py + blocks/*.json). DO NOT hand-edit."
    json.dump(lib, open(LIB, "w"), indent=2)
    print(f"integrate: wrote library.json — {len(prims)} primitives, {len(blocks)} blocks ({nfiles} from blocks/)")
    return 0

if __name__ == "__main__":
    sys.exit(run("--check" in sys.argv))
