#!/usr/bin/env python3
"""
map.py — P5 design mapper. Loads the HFT design payload onto the routed container.

PURPOSE (P5 — Configuration / Load):
  Instantiate the design payload (modules: MAC, NIC, DOM, TAI, timeframe, indicators, adapter)
  onto the cast container (P2) via the router output (P3). The design is NOT placed on an empty
  blank — it is LOADED/CONFIGURED onto the interconnected container.

INPUTS:
  - device/container.json        P2 cast (tile array, native clocks/RAM/IO)
  - device/routes.json           P3 router output (PIP config, single-driver gate PASS)
  - design_payload.yaml or CONFIG env var (founder decision: which modules to load)

OUTPUTS:
  - device/design_netlist.json   instantiated cells + nets (design circuit mapped to container)
  - device/design_routes.json    merged PIP config (design-specific + container routes)
  - device/design_bitstream.bin  (P6 input; generated by bitstream emitter)

DESIGN PAYLOAD (P5 open decision, resolved at runtime):
  The payload is DECIDED SEPARATELY (not here). This tool:
  1. Reads config/payload.json or environment variable DESIGN_PAYLOAD
  2. For each module (adapter, nic, tai, dom, timeframe, indicators):
     - Load module HDL spec (if not pre-realized in P1)
     - Instantiate onto container via router
     - Merge routes into design_routes.json
  3. Emit design_netlist.json + design_routes.json
  4. Gate: module-contract (2i), index-doctrine (2h), build-purity (2j), arithmetic (2b)

SKELETON STATUS (2026-06-14):
  - Placeholder: reads config/design_payload.md and instantiates a test module
  - Full implementation blocked on founder decision: which design modules?
  - When decided: replace test_module() with real module instantiation from library.json

CODE STYLE:
  Python 3.9+, functional, matches catalog.py structure.
  All paths relative to repo root (use HERE/ROOT pattern).
  No hard-coded module names; read from config.

DEPENDENCIES:
  - route.py (needs container routes from device/routes.json)
  - library.json (P1 output; primitive library)
  - design_payload.md (config; to be created by founder)
"""
import sys, os, json, argparse
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DEVICE = os.path.join(ROOT, "device")
CONFIG = os.path.join(ROOT, "config")

def load_json(path, default=None):
    """Load JSON file, return default if missing."""
    try:
        return json.load(open(path))
    except (FileNotFoundError, json.JSONDecodeError):
        return default

def load_container():
    """Load P2 cast container (tile array, native clocks/RAM/IO)."""
    return load_json(os.path.join(DEVICE, "container.json"), {})

def load_router_output():
    """Load P3 router output (PIP config, verified single-driver)."""
    routes = load_json(os.path.join(DEVICE, "routes.json"), {})
    if not routes:
        print("ERROR: device/routes.json not found. Run route.py (P3) first.", file=sys.stderr)
        return None
    return routes

def load_library():
    """Load P1 primitive library (physical elements + config mappings)."""
    lib = load_json(os.path.join(DEVICE, "library.json"), {})
    if not lib:
        print("WARN: library.json not found (P1 incomplete?). Using empty library.", file=sys.stderr)
    return lib

def load_design_payload_config():
    """
    Load design payload configuration. Priority:
      1. DESIGN_PAYLOAD environment variable (JSON or path to file)
      2. config/design_payload.md
      3. Empty list (no modules — bare container only)

    Returns: dict with 'modules' list, each with 'name' and optional 'params'.
    """
    env_payload = os.environ.get("DESIGN_PAYLOAD")
    if env_payload:
        try:
            return json.loads(env_payload)
        except json.JSONDecodeError:
            if os.path.isfile(env_payload):
                return load_json(env_payload, {})

    config_path = os.path.join(CONFIG, "design_payload.md")
    if os.path.isfile(config_path):
        # TODO: parse YAML frontmatter from design_payload.md
        # For now, return empty config (founder decision pending).
        return {"modules": []}

    return {"modules": []}

def instantiate_module(module_spec, container, library, next_cell_id):
    """
    Instantiate a single module (e.g., 'adapter', 'nic', 'dom').

    Args:
      module_spec:  dict with 'name' (str) and optional 'params' (dict)
      container:    P2 cast (tile array)
      library:      P1 library (primitives)
      next_cell_id: int, starting cell ID for this module

    Returns:
      (cells, nets, next_cell_id) where:
        - cells: list of dicts with 'id', 'primitive', 'tile', 'params'
        - nets: list of dicts with 'src', 'dst' (connectivity within module)

    TODO:
      When modules are specified, replace this with real instantiation:
      1. Load module HDL / netlist
      2. Map nets through router
      3. Allocate cells on available tiles
    """
    name = module_spec.get("name", "test_module")
    cells = []
    nets = []

    # SKELETON: create a minimal test module for now
    # This is a placeholder until the founder decides on the actual design payload.
    if name == "test_module" or name not in library:
        # Create 3 test cells (CLB + BRAM + DSP) to validate the pipeline
        test_cells = [
            {"name": "slice_0", "primitive": "SLICEE", "params": {}},
            {"name": "bram_0", "primitive": "BRAM36E2", "params": {}},
            {"name": "dsp_0", "primitive": "DSP48E2", "params": {}},
        ]
        for cell in test_cells:
            cells.append({
                "id": f"{name}_{cell['name']}_{next_cell_id}",
                "module": name,
                "primitive": cell["primitive"],
                "tile": [0, 0],  # TODO: allocate real tile from container
                "params": cell["params"],
            })
            next_cell_id += 1

        # Test connectivity: chain cells with 3 nets
        nets = [
            {"src": cells[0]["id"], "dst": cells[1]["id"], "name": f"{name}_net_0"},
            {"src": cells[1]["id"], "dst": cells[2]["id"], "name": f"{name}_net_1"},
            {"src": cells[2]["id"], "dst": cells[0]["id"], "name": f"{name}_net_2"},
        ]
    else:
        # Real module instantiation (TBD)
        print(f"WARN: module '{name}' not in library and not recognized. Skipping.", file=sys.stderr)

    return cells, nets, next_cell_id

def build_design_netlist(container, library, payload_config):
    """
    Instantiate all design modules onto the container.

    Returns: dict with 'cells', 'nets', 'modules' listing.
    """
    all_cells = []
    all_nets = []
    cell_id = 0
    modules_instantiated = []

    for module_spec in payload_config.get("modules", []):
        cells, nets, cell_id = instantiate_module(module_spec, container, library, cell_id)
        all_cells.extend(cells)
        all_nets.extend(nets)
        modules_instantiated.append({
            "name": module_spec.get("name"),
            "cells": len(cells),
            "nets": len(nets),
        })

    # If no modules specified, still emit the bare structure
    if not all_cells:
        print("INFO: no modules instantiated; emitting bare container structure", file=sys.stderr)

    return {
        "cells": all_cells,
        "nets": all_nets,
        "modules": modules_instantiated,
        "total_cells": len(all_cells),
        "total_nets": len(all_nets),
    }

def merge_design_routes(container_routes, design_netlist):
    """
    Merge design-specific PIP routes with container routes.

    The router (P3) has already routed container nets via the INT-tile fabric.
    Now we add design-specific routes for design nets, ensuring:
      - single-driver-per-wire gate holds
      - no shorts (design nets don't collide with container nets)

    Returns: dict with merged routes, gate status.
    """
    routes = container_routes.copy() if container_routes else {
        "grid": [64, 64],
        "routes": [],
        "total_pips": 0,
    }

    design_routes = []
    for net in design_netlist.get("nets", []):
        # TODO: run router on design net endpoints (when modules are realized)
        # For now, emit empty design routes
        pass

    routes["design_nets_routed"] = len(design_routes)
    routes["design_routes"] = design_routes
    routes["total_pips"] += sum(r.get("hops", 0) for r in design_routes)

    # Re-check single-driver gate
    all_wires = [tuple(p["tile"]) + (p["out"], p["track"])
                 for r in routes.get("routes", [])
                 for p in r.get("pips", [])]
    for dr in design_routes:
        all_wires.extend([tuple(p["tile"]) + (p["out"], p["track"])
                          for p in dr.get("pips", [])])

    single_driver = len(all_wires) == len(set(all_wires))
    routes["single_driver"] = single_driver
    routes["no_shorts"] = single_driver

    return routes

def run(payload_source=None):
    """
    Main P5 flow: instantiate design modules onto the routed container.

    Exit codes:
      0 = success (gates PASS)
      1 = validation error (spec is wrong — fix design_payload.md)
      2 = internal/transient error (missing P2/P3 artifacts, retry)
    """
    # Load P3 router output (must exist)
    container_routes = load_router_output()
    if not container_routes:
        print("ERROR: P3 routes not found. P5 blocked on P3 completion.", file=sys.stderr)
        return 2

    # Load P2 container
    container = load_container()
    if not container:
        print("WARN: P2 container not found. Using minimal stub.", file=sys.stderr)
        container = {"grid": [64, 64], "tiles": []}

    # Load P1 library
    library = load_library()

    # Load design payload config
    payload_config = load_design_payload_config()

    # Instantiate design modules
    design_netlist = build_design_netlist(container, library, payload_config)

    # Merge design routes with container routes
    merged_routes = merge_design_routes(container_routes, design_netlist)

    # Gate: single-driver-per-wire (from P3, still holds after design routing)
    if not merged_routes.get("single_driver"):
        print("GATE FAIL: single-driver-per-wire", file=sys.stderr)
        return 1

    if not merged_routes.get("no_shorts"):
        print("GATE FAIL: no-shorts", file=sys.stderr)
        return 1

    # Emit design_netlist.json
    os.makedirs(DEVICE, exist_ok=True)
    netlist_path = os.path.join(DEVICE, "design_netlist.json")
    json.dump(design_netlist, open(netlist_path, "w"), indent=2)
    print(f"design_netlist.json: {design_netlist['total_cells']} cells, "
          f"{design_netlist['total_nets']} nets, {len(design_netlist['modules'])} modules",
          file=sys.stderr)

    # Emit design_routes.json
    routes_path = os.path.join(DEVICE, "design_routes.json")
    json.dump(merged_routes, open(routes_path, "w"), indent=2)
    print(f"design_routes.json: {merged_routes.get('total_pips', 0)} total PIPs, "
          f"{merged_routes.get('design_nets_routed', 0)} design nets routed",
          file=sys.stderr)

    print(f"P5 SUCCESS: {design_netlist['total_cells']} design cells loaded onto container", file=sys.stderr)
    return 0

if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="P5 design mapper: load payload onto routed container")
    ap.add_argument("--payload", type=str, help="design_payload.yaml or JSON file (overrides env/config)")
    ap.add_argument("--dry-run", action="store_true", help="validate only, no output")
    args = ap.parse_args()

    sys.exit(run(payload_source=args.payload))
