#!/usr/bin/env python3
"""gen_fpga_blank.py — cast an FPGA BLANK (board fabric) from a board profile.

Factory phase 2 tool (factory_toolchain.yaml). Consumes a board_profile YAML
(device_profiles/fpga-*.yaml — real-part-referenced facts) and emits the blank's
netlist: the internally-connected fabric REFERENCE.

A blank is PURE DEVICE REFERENCE (blank-enforcement law):
  * the fabric register file (capacity geometry) — the interconnect itself,
  * clock-domain table, I/O geometry, resource budget (real-part facts),
  * NO module allocation, NO logic, NO addresses (addressing is phase 3;
    install is phase 4 — both tool-only).

Usage:
    python3 gen_fpga_blank.py device_profiles/<board>.yaml > <board_dir>/<board>.net.json
"""
import json
import sys

try:
    import yaml
except ImportError:
    sys.stderr.write("gen_fpga_blank: PyYAML required\n")
    sys.exit(2)

REQUIRED = ("name", "part_ref", "registers", "clock_domains", "io", "address_space")


def die(msg):
    sys.stderr.write("gen_fpga_blank: " + msg + "\n")
    sys.exit(2)


def main():
    if len(sys.argv) < 2:
        die("usage: gen_fpga_blank.py device_profiles/<board>.yaml > <board>.net.json")
    prof = yaml.safe_load(open(sys.argv[1]))

    for f in REQUIRED:
        if f not in prof:
            die(f"board profile missing required field: {f} (format: board_profile)")

    name = prof["name"]                      # canonical board name (fpga-in)
    device = name.replace("-", "_")          # C-safe device identifier (fpga_in)
    regs = int(prof["registers"])
    if regs <= 0 or (regs & (regs - 1)) != 0:
        die(f"registers ({regs}) must be a positive power of two (fabric geometry)")

    aspace = prof["address_space"]
    for k in ("size", "slot_alignment", "cdc_region_size"):
        if k not in aspace:
            die(f"address_space missing geometry field: {k}")

    clocks = prof["clock_domains"]
    for cname, c in clocks.items():
        if "frequency_hz" not in c or not isinstance(c["frequency_hz"], int):
            die(f"clock domain {cname}: frequency_hz must be an integer (no floats)")

    net = {
        "device": device,
        "board": name,
        "kind": "fpga_blank",
        "part_ref": prof["part_ref"],
        "role": prof.get("role", ""),
        "comment": (
            f"GENERATED by gen_fpga_blank.py from device_profiles/{name}.yaml — DO NOT "
            "EDIT BY HAND. An FPGA BLANK: the internally-connected fabric reference "
            "(register-file geometry, clock-domain table, I/O + resource budget from the "
            "real part). NO module allocation, NO logic, NO addresses — modules are "
            "installed by the install tool (phase 4) after system-wide addressing "
            "(phase 3). The fabric register file IS the interconnect."
        ),
        # The fabric: a flat addressed word array of this capacity (geometry only).
        "fabric": {
            "registers": regs,
            "word_bits": 64,
        },
        "address_space_geometry": {
            "size": int(aspace["size"]),
            "slot_alignment": int(aspace["slot_alignment"]),
            "cdc_region_size": int(aspace["cdc_region_size"]),
        },
        # Descriptive tables (real-part facts). The oscillator MODULES own the
        # clocks (power + start/stop live there, per the clock rule) — a blank
        # owns no clock and no logic.
        "clock_domain_table": {
            cn: {"frequency_hz": int(c["frequency_hz"]), "source": c.get("source", "")}
            for cn, c in clocks.items()
        },
        "io_geometry": {k: int(v) for k, v in prof["io"].items()},
        "resource_budget": {
            rn: {"capacity": int(r["capacity"]), "unit": r.get("unit", "")}
            for rn, r in (prof.get("resources") or {}).items()
        },
        "intended_modules_doc": prof.get("intended_modules", []),
    }

    json.dump(net, sys.stdout, indent=2)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
