#!/usr/bin/env python3
"""gen_clb_slice.py — emit the authentic CLB SLICE spec: 8 LUT6 + 16 FF (UG574).

The slice is a repetitive composition (8 identical lut6 + 16 identical dff with their
pins exposed as connection points). Hand-writing ~120 nets is error-prone, so this
tool emits the spec mechanically — composition only, nothing invented. Emits BOTH
forms from one source so they can never drift:
  - descriptions/clb_slice.desc.yaml  (flat design; what the fabric elaborates)
  - library/components/clb_slice.comp.yaml  (component form; for later DFX use)

Every BEL pin is a slice port (a connection point bound at programming): each LUT6
exposes cfg_d/cfg_en (program the truth table) + i0..i5 (inputs) + y (output); each FF
exposes d/en (inputs) + q (output). Run: python3 gen_clb_slice.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
NLUT, NFF = 8, 16
LPINS = ["cfg_d", "cfg_en", "i0", "i1", "i2", "i3", "i4", "i5"]

in_ports, out_ports, instances, conns = [], [], [], []
for j in range(NLUT):
    for p in LPINS:
        in_ports.append(f"l{j}_{p}")
    out_ports.append(f"l{j}_y")
    instances.append((f"lut{j}", "lut6"))
    for p in LPINS:
        conns.append((f"l{j}_{p}", f"lut{j}.{p}"))
    conns.append((f"lut{j}.y", f"l{j}_y"))
for k in range(NFF):
    in_ports += [f"d_{k}", f"en_{k}"]
    out_ports.append(f"q_{k}")
    instances.append((f"ff{k}", "dff"))
    conns += [(f"d_{k}", f"ff{k}.d"), (f"en_{k}", f"ff{k}.en"), (f"ff{k}.q", f"q_{k}")]

HDR = ("# GENERATED by gen_clb_slice.py — authentic UltraScale+ CLB SLICE: 8 LUT6 + 16 FF\n"
       "# (UG574). Composition only. The 8 LUT truth-table registers are CONFIG storage,\n"
       "# NOT the 16 counted CLB flip-flops. Every BEL pin is a connection point.\n")


def fmt_ports():
    return ("ports:\n"
            f"  in:  [{', '.join(in_ports)}]\n"
            f"  out: [{', '.join(out_ports)}]\n")


def fmt_instances(indent, comp_key):
    L = []
    for nm, comp in instances:
        L.append(f"{indent}- {{name: {nm}, {comp_key}: {comp}, params: {{init: 0}}}}")
    return "\n".join(L)


def fmt_conns(indent):
    return "\n".join(f"{indent}- {{net: [{a}, {b}]}}" for a, b in conns)


# --- flat design (.desc.yaml) ---
desc = (HDR + "design: clb_slice\nkind: fabric_tile\n" + fmt_ports() +
        "instances:\n" + fmt_instances("  ", "component") + "\n" +
        "connections:\n" + fmt_conns("  ") + "\n")
with open(os.path.join(HERE, "descriptions", "clb_slice.desc.yaml"), "w") as f:
    f.write(desc)

# --- component (.comp.yaml) ---
comp = (HDR + "component: clb_slice\nparams:\n  init: 0\n" + fmt_ports() +
        "body:\n  instances:\n" + fmt_instances("    ", "component") + "\n" +
        "  connections:\n" + fmt_conns("    ") + "\n")
with open(os.path.join(HERE, "library", "components", "clb_slice.comp.yaml"), "w") as f:
    f.write(comp)

print(f"emitted clb_slice: {NLUT} LUT6 + {NFF} FF, {len(in_ports)} in / {len(out_ports)} out ports, {len(conns)} nets")
