#!/usr/bin/env python3
"""gen_fpga_device.py — UNIFY the per-tile fabrics into THE one FPGA hardware device.

This is the birth of the device: it assembles every tile type (flip-flop tiles as
arrays of their real register banks; conductor tiles as lane banks) into a single
fpga_device with one init / power / tick / display. HARDCODES NOTHING: tile counts
come from the device model when present, else an authentic count declared in the
assembly spec; per-tile flip-flop counts come from each tile's own netlist.

Assembly spec (YAML): device, tiles:[{type, klass: flipflop|conductor, module,
netlist, count?}]. Run each tile's component->elaborate/gennet FIRST so <module>_gen.h
exists; this tool only unifies.

Usage: python3 gen_fpga_device.py <assembly.yaml> <device_model.json> > fpga_device_gen.h
"""
import json
import os
import sys

try:
    import yaml
except Exception:
    sys.stderr.write("gen_fpga_device: PyYAML required\n"); sys.exit(2)


def die(m):
    sys.stderr.write("gen_fpga_device: " + m + "\n"); sys.exit(2)


def main():
    if len(sys.argv) != 3:
        die("usage: gen_fpga_device.py <assembly.yaml> <device_model.json> > fpga_device_gen.h")
    asm = yaml.safe_load(open(sys.argv[1]))
    model = json.load(open(sys.argv[2]))
    grid = model.get("grid") or {}
    dev = str(asm.get("device", model.get("device_model", "device"))).lower()

    ff_tiles, cond_tiles = [], []
    for t in asm.get("tiles", []):
        typ = t["type"]; mod = t["module"]; MOD = mod.upper(); klass = t["klass"]
        if klass == "conductor":
            cond_tiles.append({"type": typ, "mod": mod, "MOD": MOD})
            continue
        # flip-flop tile: count (model > spec), ff/tile from its netlist
        if typ in grid:
            count = int(grid[typ]["count"])
        elif "count" in t:
            count = int(t["count"])
        else:
            die(f"tile {typ}: no count in device model and none declared in assembly")
        net = json.load(open(t["netlist"]))
        ff = len(net.get("dff_nodes") or [])
        if ff <= 0:
            die(f"tile {typ}: netlist {t['netlist']} has no flip-flops")
        ff_tiles.append({"type": typ, "mod": mod, "MOD": MOD, "count": count, "ff": ff})

    L = []
    L.append("/* GENERATED by gen_fpga_device.py — THE FPGA hardware device: every tile")
    L.append(" * type unified into one device (flip-flop tiles as register-bank arrays,")
    L.append(" * conductor tiles as lane banks). Counts authentic; nothing hardcoded. */")
    L.append(f"#ifndef FPGA_{dev.upper()}_DEVICE_H")
    L.append(f"#define FPGA_{dev.upper()}_DEVICE_H")
    for t in ff_tiles + cond_tiles:
        L.append(f'#include "{t["mod"]}_gen.h"')
    L.append("#include <stdint.h>")
    L.append("#include <stdio.h>")
    L.append("static uint8_t fpga_master_power;")
    # storage: flip-flop tiles as arrays of register banks; conductors as lane banks
    for t in ff_tiles:
        lo = t["type"].lower()
        L.append(f"#define FPGA_{t['type']}_COUNT {t['count']}u")
        L.append(f"#define FPGA_{t['type']}_FF {t['ff']}u")
        L.append(f"static word_t fpga_{lo}[FPGA_{t['type']}_COUNT][{t['MOD']}_REG_COUNT];")
    for t in cond_tiles:
        lo = t["type"].lower()
        L.append(f"static {t['mod']}_word_t fpga_{lo}_lanes[{t['MOD']}_REG_COUNT];")
    # init
    L.append("static inline void fpga_device_init(void){")
    L.append("  fpga_master_power = 0u;")
    for t in ff_tiles:
        lo = t["type"].lower()
        L.append(f"  for (unsigned i=0;i<FPGA_{t['type']}_COUNT;i++) {t['mod']}_init(fpga_{lo}[i]);")
    for t in cond_tiles:
        lo = t["type"].lower()
        L.append(f"  for (unsigned i=0;i<{t['MOD']}_REG_COUNT;i++) fpga_{lo}_lanes[i]=0u;")
    L.append("}")
    L.append("static inline void fpga_device_power_on(void){ fpga_master_power=1u; }")
    L.append("static inline void fpga_device_power_off(void){ fpga_master_power=0u; }")
    # tick: flip-flop tiles tick (gated); conductors are passive (no tick)
    L.append("static inline void fpga_device_tick(void){")
    L.append("  if (!fpga_master_power) return;")
    for t in ff_tiles:
        lo = t["type"].lower()
        L.append(f"  for (unsigned i=0;i<FPGA_{t['type']}_COUNT;i++) {t['mod']}_tick(fpga_{lo}[i]);")
    L.append("}")
    # total flip-flops
    terms = " + ".join(f"(unsigned long)FPGA_{t['type']}_COUNT*FPGA_{t['type']}_FF" for t in ff_tiles) or "0"
    L.append(f"static inline unsigned long fpga_device_flipflops(void){{ return {terms}; }}")
    # display
    L.append("static inline void fpga_device_display(void){")
    L.append(f'  printf("FPGA %s device (power=%u): %lu real flip-flops\\n", "{dev}", fpga_master_power, fpga_device_flipflops());')
    for t in ff_tiles:
        L.append(f'  printf("  {t["type"]:<5}x%-8u  %u FF/tile  = %lu flip-flops\\n",'
                 f' FPGA_{t["type"]}_COUNT, FPGA_{t["type"]}_FF, (unsigned long)FPGA_{t["type"]}_COUNT*FPGA_{t["type"]}_FF);')
    for t in cond_tiles:
        L.append(f'  printf("  {t["type"]:<5}%u conductor lanes (passive)\\n", {t["MOD"]}_REG_COUNT);')
    L.append("}")
    L.append("#endif")
    sys.stdout.write("\n".join(L) + "\n")


if __name__ == "__main__":
    main()
