#!/usr/bin/env python3
"""gen_fpga_blank.py — cast THE FPGA BLANK from THE part profile (factory phase 2).

ALL BLANKS ARE IDENTICAL, and A BLANK ASSIGNS NOTHING.

There is ONE blank — the full real part, complete and UNDIFFERENTIATED — and the
boards are identical INSTANCES of it, named at addressing (phase 3). A blank is
PURE DEVICE REFERENCE: fabric register-file geometry (the interconnect),
address-space geometry, full-part I/O + resource budget. Nothing else.

CAPABILITY SEPARATION (enforced in this code, not in memory):
  * This tool is STRUCTURALLY INCAPABLE of assignment — it contains NO codepath
    that emits clock tables, module names, placements, slots, or addresses.
    Assignment belongs EXCLUSIVELY to the phase-3/4 meta tools (registry,
    install). A construction tool that can assign is a law violation in itself.
  * It REFUSES a poisoned spec: a part profile carrying any assignment or
    differentiation key (clock_domains, role, intended_modules, placement, ...)
    is rejected at intake — wrong specs cannot flow through.
  * The fileset it emits carries the same enforcement: the emitted validator
    rejects assignment keys in the netlist; the emitted generator has no
    assignment emission code. checks/check_blank_identity.py (gate stage 2k)
    enforces system-wide. A device that breaks ANY rule cannot pass validation.

This tool emits the COMPLETE component fileset in one invocation — generator,
validator, Makefile, thin test — zero hand assembly (factory law).

Usage:
    # netlist to stdout (the Makefile's emit step):
    python3 gen_fpga_blank.py device_profiles/vu9p.yaml > fpga_blank.net.json

    # emit the COMPLETE component fileset (then `make test` inside it):
    python3 gen_fpga_blank.py device_profiles/vu9p.yaml --emit-component fpga_blank
"""
import json
import os
import sys

try:
    import yaml
except ImportError:
    sys.stderr.write("gen_fpga_blank: PyYAML required\n")
    sys.exit(2)

# A part profile carries ONLY these (real-part facts; geometry/capacity).
REQUIRED = ("name", "part_ref", "registers", "io", "address_space")
ALLOWED = set(REQUIRED) | {"resources"}
# Poisoned-spec rejection: assignment/differentiation keys refused at intake.
POISON = ("clock_domains", "clock_domain_table", "clock", "role",
          "intended_modules", "installed_modules", "placement", "residents",
          "modules", "slots", "window_base", "addresses")
COMPONENT = "fpga_blank"   # THE one blank component (instances are names, phase 3)


def die(msg):
    sys.stderr.write("gen_fpga_blank: " + msg + "\n")
    sys.exit(2)


def load_profile(path):
    prof = yaml.safe_load(open(path))
    for f in REQUIRED:
        if f not in prof:
            die(f"part profile missing required field: {f} (format: part_profile)")
    for f in POISON:
        if prof.get(f):
            die(f"POISONED SPEC REFUSED: part profile carries '{f}' — a blank assigns "
                f"nothing (clock domains belong to oscillator modules and arrive at "
                f"install; roles/placement/addresses are phases 3/4)")
    unknown = set(prof) - ALLOWED
    if unknown:
        die(f"POISONED SPEC REFUSED: unknown part-profile fields {sorted(unknown)} — "
            f"a part profile carries ONLY real-part facts: {sorted(ALLOWED)}")
    regs = int(prof["registers"])
    if regs <= 0 or (regs & (regs - 1)) != 0:
        die(f"registers ({regs}) must be a positive power of two")
    for k in ("size", "slot_alignment", "cdc_region_size"):
        if k not in prof["address_space"]:
            die(f"address_space missing geometry field: {k}")
    return prof


def build_netlist(prof):
    """Construction ONLY: fabric geometry + part facts. There is deliberately no
    code here that could emit a clock table, a module name, a placement, or an
    address — this tool cannot assign."""
    aspace = prof["address_space"]
    return {
        "device": COMPONENT,
        "kind": "fpga_blank",
        "part_ref": prof["part_ref"],
        "comment": (
            "GENERATED by gen_fpga_blank.py from device_profiles/"
            f"{prof['name']}.yaml — DO NOT EDIT BY HAND. THE one identical FPGA "
            "blank: the internally-connected fabric reference (full real part, "
            "undifferentiated). A BLANK ASSIGNS NOTHING: no clock tables, no "
            "module names, no placements, no addresses — clocks arrive with the "
            "oscillator modules at install (phase 4); boards are identical "
            "instances named at addressing (phase 3)."
        ),
        "fabric": {"registers": int(prof["registers"]), "word_bits": 64},
        "address_space_geometry": {
            "size": int(aspace["size"]),
            "slot_alignment": int(aspace["slot_alignment"]),
            "cdc_region_size": int(aspace["cdc_region_size"]),
        },
        "io_geometry": {k: int(v) for k, v in prof["io"].items()},
        "resource_budget": {
            rn: {"capacity": int(r["capacity"]), "unit": r.get("unit", "")}
            for rn, r in (prof.get("resources") or {}).items()
        },
    }


# ---- the component fileset (templates live IN the tool — the machine) --------

GENNET = '''#!/usr/bin/env python3
"""gennet.py — FPGA-BLANK generator: fpga_blank.net.json -> fpga_blank_gen.h.

EMITTED BY gen_fpga_blank.py — DO NOT EDIT BY HAND (regenerate via the tool).
A blank is pure device reference, and A BLANK ASSIGNS NOTHING: this generator
is STRUCTURALLY INCAPABLE of emitting clock tables, module names, placements,
or addresses — it emits ONLY the fabric geometry (the interconnect),
address-space geometry constants (sizes, NOT addresses), full-part I/O +
resource budget, and a zero-init. It REFUSES a netlist carrying assignment.
"""
import json
import sys

# Assignment keys: their presence in the netlist means a poisoned spec upstream.
POISON = ("clock_domain_table", "clock_domains", "clock", "dff_nodes",
          "comb_nodes", "config_nodes", "window_base", "role",
          "intended_modules_doc", "intended_modules", "placement", "residents",
          "modules", "slots")


def main():
    net_path = sys.argv[1] if len(sys.argv) > 1 else "fpga_blank.net.json"
    net = json.load(open(net_path))
    if net.get("kind") != "fpga_blank":
        sys.stderr.write("gennet: not an fpga_blank netlist\\n")
        sys.exit(2)
    for k in POISON:
        if net.get(k):
            sys.stderr.write(f"gennet: REFUSED — netlist carries '{k}' (a blank "
                             f"assigns nothing; fix the spec upstream)\\n")
            sys.exit(3)

    dev = net["device"]
    DEV = dev.upper()
    fab = net["fabric"]
    geo = net["address_space_geometry"]

    out = []
    out.append(f"/* GENERATED by gennet.py from {net_path} — DO NOT EDIT BY HAND.")
    out.append(f" * THE identical FPGA blank ({net.get('part_ref', '')}).")
    out.append(" * Pure device reference: fabric geometry + full-part I/O/resource tables.")
    out.append(" * A BLANK ASSIGNS NOTHING: no clock tables, no module names, no")
    out.append(" * placements, no addresses. Clocks arrive with the oscillator modules at")
    out.append(" * install (phase 4); boards are identical instances named at addressing. */")
    out.append(f"#ifndef {DEV}_GEN_H")
    out.append(f"#define {DEV}_GEN_H")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f"typedef uint64_t {dev}_word_t;")
    out.append("")
    out.append("/* ---- fabric geometry (the interconnect) ---- */")
    out.append(f"#define {DEV}_FABRIC_REGS {fab['registers']}u")
    out.append(f"#define {DEV}_WORD_BITS {fab['word_bits']}u")
    out.append("")
    out.append("/* ---- address-space GEOMETRY (sizes only; addressing is phase 3) ---- */")
    out.append(f"#define {DEV}_ADDR_SPACE_SIZE {hex(geo['size'])}u")
    out.append(f"#define {DEV}_SLOT_ALIGNMENT {hex(geo['slot_alignment'])}u")
    out.append(f"#define {DEV}_CDC_REGION_SIZE {hex(geo['cdc_region_size'])}u")
    out.append("")
    out.append("/* ---- full-part I/O + resource budget (real-part facts, undivided) ---- */")
    for k, v in net.get("io_geometry", {}).items():
        out.append(f"#define {DEV}_IO_{k.upper()} {v}u")
    for rn, r in net.get("resource_budget", {}).items():
        out.append(f"#define {DEV}_RES_{rn.upper()}_CAPACITY {r['capacity']}u")
    out.append("")
    out.append(f"/* {dev}_init: zero the fabric (power-off reset). A blank runs no clock")
    out.append(" * and owns no logic; this is the only state operation it defines. */")
    out.append(f"static inline void {dev}_init({dev}_word_t *f) {{")
    out.append(f"    {dev}_word_t i = 0ULL;")
    out.append(f"    for (i = 0ULL; i < {DEV}_FABRIC_REGS; i = i + 1ULL) {{ f[i] = 0ULL; }}")
    out.append("}")
    out.append("")
    out.append(f"#endif /* {DEV}_GEN_H */")
    sys.stdout.write("\\n".join(out) + "\\n")


if __name__ == "__main__":
    main()
'''

VALIDATE = '''#!/usr/bin/env python3
"""validate.py — netlist validator for THE FPGA blank (the project gate).

EMITTED BY gen_fpga_blank.py — DO NOT EDIT BY HAND (regenerate via the tool).
Enforces the blank law IN CODE: pure device reference — NO logic, NO allocation,
NO addresses, NO differentiation, and A BLANK ASSIGNS NOTHING (no clock tables,
no module names, no placements). A device that breaks ANY rule does not pass.
(System-wide identity is additionally enforced by checks/check_blank_identity.py
at gate stage 2k.)
"""
import json
import sys

FORBIDDEN = ("dff_nodes", "comb_nodes", "config_nodes", "clock", "window_base",
             "role", "intended_modules_doc", "intended_modules", "placement",
             "residents", "clock_domain_table", "clock_domains", "modules", "slots")

# System module names — none may appear as a key anywhere in a blank.
MODULE_NAMES = {"mac", "internal", "taiosc", "tai", "adapter", "wire", "nic",
                "fifo_rx", "tai_cdc", "pip_resolver", "timeframe", "dom",
                "dom_bus", "candle", "footprint", "tpo", "harness"}


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "fpga_blank.net.json"
    net = json.load(open(path))
    errs = []

    if net.get("kind") != "fpga_blank":
        errs.append(f"kind must be 'fpga_blank' (got {net.get('kind')!r})")
    for forbidden in FORBIDDEN:
        if net.get(forbidden):
            errs.append(f"a blank must have NO {forbidden} (a blank assigns nothing; "
                        f"allocation/placement/clocks-by-install are phases 3/4)")

    def walk(o, path_=""):
        if isinstance(o, dict):
            for k, v in o.items():
                if str(k).lower() in MODULE_NAMES:
                    errs.append(f"'{path_}{k}' — system module named in the blank "
                                f"(part pre-assignment; install is phase 4)")
                walk(v, path_ + str(k) + ".")
        elif isinstance(o, list):
            for i, v in enumerate(o):
                walk(v, path_ + f"[{i}].")
    walk(net)

    fab = net.get("fabric") or {}
    regs = fab.get("registers", 0)
    if regs <= 0 or (regs & (regs - 1)) != 0:
        errs.append(f"fabric.registers ({regs}) must be a positive power of two")
    if fab.get("word_bits") != 64:
        errs.append("fabric.word_bits must be 64")
    if not net.get("part_ref"):
        errs.append("part_ref missing — a blank must be real-part referenced")
    geo = net.get("address_space_geometry") or {}
    for k in ("size", "slot_alignment", "cdc_region_size"):
        if not isinstance(geo.get(k), int) or geo.get(k) <= 0:
            errs.append(f"address_space_geometry.{k} must be a positive integer")

    if errs:
        for e in errs:
            sys.stderr.write(f"[validate] FAIL: {e}\\n")
        sys.exit(3)
    print(f"[validate] OK — THE fpga blank: fabric {regs} regs, full part, "
          f"undifferentiated, assigns nothing")


if __name__ == "__main__":
    main()
'''

MAKEFILE = '''# fpga_blank — THE identical FPGA blank (cast from device_profiles/vu9p.yaml).
# EMITTED BY gen_fpga_blank.py — DO NOT EDIT BY HAND (regenerate via the tool).
# Pure device reference: A BLANK ASSIGNS NOTHING (no clock tables, no module
# names, no placements, no addresses). Boards = identical instances of this
# blank, named at addressing (phase 3); clocks arrive at install (phase 4).
# Flow: part profile --emit--> netlist --validate--> --gennet--> fabric C --cc--> thin test.
CC=cc
CFLAGS=-std=c11 -Wall -Wextra -Werror -O2
PY=python3
PROFILE=../device_profiles/vu9p.yaml
NET=fpga_blank.net.json
GEN=fpga_blank_gen.h
.PHONY: all emit validate gen test clean
all: test
emit: ../gen_fpga_blank.py $(PROFILE)
\t$(PY) ../gen_fpga_blank.py $(PROFILE) > $(NET)
$(NET): ../gen_fpga_blank.py $(PROFILE)
\t$(PY) ../gen_fpga_blank.py $(PROFILE) > $(NET)
validate: $(NET)
\t$(PY) validate.py $(NET)
gen: validate
\t$(PY) gennet.py $(NET) > $(GEN)
test: gen
\t$(CC) $(CFLAGS) -o test_fpga_blank test_fpga_blank.c
\t./test_fpga_blank
clean:
\trm -f test_fpga_blank
'''

TEST = '''/* test_fpga_blank.c — thin test: power-on (zero fabric) + display geometry.
 * EMITTED BY gen_fpga_blank.py — DO NOT EDIT BY HAND (regenerate via the tool).
 * A blank owns no logic, runs no clock, and assigns nothing; the test proves
 * the fabric exists, inits, and the full-part constants are present. */
#include <stdio.h>
#include "fpga_blank_gen.h"

static fpga_blank_word_t f[FPGA_BLANK_FABRIC_REGS];

int main(void) {
    fpga_blank_init(f);
    printf("fpga blank: fabric=%u regs x %u bits (assigns nothing; clocks arrive at install)\\n",
           FPGA_BLANK_FABRIC_REGS, FPGA_BLANK_WORD_BITS);
    printf("full part: gty=%u banks=%u clb=%u bram=%u dsp=%u | geom addr=%#x align=%#x cdc=%#x\\n",
           FPGA_BLANK_IO_GTY_LANES, FPGA_BLANK_IO_IO_BANKS,
           FPGA_BLANK_RES_CLB_CAPACITY, FPGA_BLANK_RES_BRAM_CAPACITY, FPGA_BLANK_RES_DSP_CAPACITY,
           FPGA_BLANK_ADDR_SPACE_SIZE, FPGA_BLANK_SLOT_ALIGNMENT, FPGA_BLANK_CDC_REGION_SIZE);
    return 0;
}
'''

GITIGNORE = "test_fpga_blank\n*.dSYM/\n"


def emit_component(prof, comp_dir):
    os.makedirs(comp_dir, exist_ok=True)
    files = {
        "gennet.py": GENNET,
        "validate.py": VALIDATE,
        "Makefile": MAKEFILE,
        "test_fpga_blank.c": TEST,
        ".gitignore": GITIGNORE,
    }
    for name, content in files.items():
        with open(os.path.join(comp_dir, name), "w") as f:
            f.write(content)
    sys.stderr.write(f"gen_fpga_blank: emitted complete fileset -> {comp_dir}/ "
                     f"({', '.join(files)})\n"
                     f"gen_fpga_blank: now run `make test` inside {comp_dir}/ "
                     f"(emit -> validate -> gen -> test)\n")


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if not args:
        die("usage: gen_fpga_blank.py <part_profile.yaml> [--emit-component <dir>] "
            "[> fpga_blank.net.json]")
    prof = load_profile(args[0])

    if "--emit-component" in sys.argv:
        i = sys.argv.index("--emit-component")
        if i + 1 >= len(sys.argv):
            die("--emit-component needs a directory")
        emit_component(prof, sys.argv[i + 1])
        return

    json.dump(build_netlist(prof), sys.stdout, indent=2)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
