#!/usr/bin/env python3
"""gen_fpga_blank.py — cast THE FPGA BLANK from THE part profile (factory phase 2).

ALL BLANKS ARE IDENTICAL: there is ONE blank — the full real part, complete and
UNDIFFERENTIATED — and the boards are identical INSTANCES of it, named at
addressing (phase 3). A blank is PURE DEVICE REFERENCE (blank-enforcement law):
the fabric register-file geometry (the interconnect), the clock-domain table,
I/O + resource budget — NO role, NO slicing, NO intended modules, NO logic,
NO addresses. Enforced by checks/check_blank_identity.py.

This tool emits the COMPLETE component fileset in one invocation — netlist
generator, validator, Makefile, thin test — zero hand assembly (the factory
law: a tool emits the whole fileset; hand-assembling scaffolding is manual
coding).

Usage:
    # netlist to stdout (the Makefile's emit step):
    python3 gen_fpga_blank.py device_profiles/vu9p.yaml > fpga_blank.net.json

    # emit the COMPLETE component fileset (then `make test` inside it):
    python3 gen_fpga_blank.py device_profiles/vu9p.yaml --emit-component fpga_blank
"""
import json
import os
import sys

try:
    import yaml
except ImportError:
    sys.stderr.write("gen_fpga_blank: PyYAML required\n")
    sys.exit(2)

REQUIRED = ("name", "part_ref", "registers", "clock_domains", "io", "address_space")
FORBIDDEN = ("role", "intended_modules", "installed_modules", "placement", "residents")
COMPONENT = "fpga_blank"   # THE one blank component (instances are names, phase 3)


def die(msg):
    sys.stderr.write("gen_fpga_blank: " + msg + "\n")
    sys.exit(2)


def load_profile(path):
    prof = yaml.safe_load(open(path))
    for f in REQUIRED:
        if f not in prof:
            die(f"part profile missing required field: {f} (format: part_profile)")
    for f in FORBIDDEN:
        if prof.get(f):
            die(f"part profile carries '{f}' — DIFFERENTIATION IS FORBIDDEN "
                f"(all blanks are identical; roles/placement are phase-3/4)")
    regs = int(prof["registers"])
    if regs <= 0 or (regs & (regs - 1)) != 0:
        die(f"registers ({regs}) must be a positive power of two")
    for cn, c in prof["clock_domains"].items():
        if not isinstance(c.get("frequency_hz"), int):
            die(f"clock domain {cn}: frequency_hz must be an integer (no floats)")
    for k in ("size", "slot_alignment", "cdc_region_size"):
        if k not in prof["address_space"]:
            die(f"address_space missing geometry field: {k}")
    return prof


def build_netlist(prof):
    aspace = prof["address_space"]
    return {
        "device": COMPONENT,
        "kind": "fpga_blank",
        "part_ref": prof["part_ref"],
        "comment": (
            "GENERATED by gen_fpga_blank.py from device_profiles/"
            f"{prof['name']}.yaml — DO NOT EDIT BY HAND. THE one identical FPGA "
            "blank: the internally-connected fabric reference (full real part, "
            "undifferentiated). The boards are identical instances of this blank, "
            "named at addressing (phase 3); modules are installed by the install "
            "tool (phase 4). NO module allocation, NO logic, NO addresses."
        ),
        "fabric": {"registers": int(prof["registers"]), "word_bits": 64},
        "address_space_geometry": {
            "size": int(aspace["size"]),
            "slot_alignment": int(aspace["slot_alignment"]),
            "cdc_region_size": int(aspace["cdc_region_size"]),
        },
        "clock_domain_table": {
            cn: {"frequency_hz": int(c["frequency_hz"]), "source": c.get("source", "")}
            for cn, c in prof["clock_domains"].items()
        },
        "io_geometry": {k: int(v) for k, v in prof["io"].items()},
        "resource_budget": {
            rn: {"capacity": int(r["capacity"]), "unit": r.get("unit", "")}
            for rn, r in (prof.get("resources") or {}).items()
        },
    }


# ---- the component fileset (templates live IN the tool — the machine) --------

GENNET = '''#!/usr/bin/env python3
"""gennet.py — FPGA-BLANK generator: fpga_blank.net.json -> fpga_blank_gen.h.

EMITTED BY gen_fpga_blank.py — DO NOT EDIT BY HAND (regenerate via the tool).
A blank is pure device reference: emits ONLY the fabric geometry (the
interconnect), address-space geometry constants (sizes, NOT addresses), the
clock-domain table, I/O + resource budget, and a zero-init. NO logic, NO tick.
"""
import json
import sys


def main():
    net_path = sys.argv[1] if len(sys.argv) > 1 else "fpga_blank.net.json"
    net = json.load(open(net_path))
    if net.get("kind") != "fpga_blank":
        sys.stderr.write("gennet: not an fpga_blank netlist\\n")
        sys.exit(2)
    dev = net["device"]
    DEV = dev.upper()
    fab = net["fabric"]
    geo = net["address_space_geometry"]

    out = []
    out.append(f"/* GENERATED by gennet.py from {net_path} — DO NOT EDIT BY HAND.")
    out.append(f" * THE identical FPGA blank ({net.get('part_ref', '')}).")
    out.append(" * Pure device reference: fabric geometry + clock/I-O/resource tables.")
    out.append(" * NO module allocation, NO logic, NO addresses — boards are identical")
    out.append(" * instances named at addressing (phase 3); install is phase 4. */")
    out.append(f"#ifndef {DEV}_GEN_H")
    out.append(f"#define {DEV}_GEN_H")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f"typedef uint64_t {dev}_word_t;")
    out.append("")
    out.append("/* ---- fabric geometry (the interconnect) ---- */")
    out.append(f"#define {DEV}_FABRIC_REGS {fab['registers']}u")
    out.append(f"#define {DEV}_WORD_BITS {fab['word_bits']}u")
    out.append("")
    out.append("/* ---- address-space GEOMETRY (sizes only; addressing is phase 3) ---- */")
    out.append(f"#define {DEV}_ADDR_SPACE_SIZE {hex(geo['size'])}u")
    out.append(f"#define {DEV}_SLOT_ALIGNMENT {hex(geo['slot_alignment'])}u")
    out.append(f"#define {DEV}_CDC_REGION_SIZE {hex(geo['cdc_region_size'])}u")
    out.append("")
    out.append("/* ---- clock-domain table (descriptive; oscillator modules own the clocks) ---- */")
    for cn, c in net.get("clock_domain_table", {}).items():
        out.append(f"#define {DEV}_CLK_{cn.upper()}_HZ {c['frequency_hz']}u")
    out.append("")
    out.append("/* ---- full-part I/O + resource budget (real-part facts, undivided) ---- */")
    for k, v in net.get("io_geometry", {}).items():
        out.append(f"#define {DEV}_IO_{k.upper()} {v}u")
    for rn, r in net.get("resource_budget", {}).items():
        out.append(f"#define {DEV}_RES_{rn.upper()}_CAPACITY {r['capacity']}u")
    out.append("")
    out.append(f"/* {dev}_init: zero the fabric (power-off reset). A blank runs no clock")
    out.append(" * and owns no logic; this is the only state operation it defines. */")
    out.append(f"static inline void {dev}_init({dev}_word_t *f) {{")
    out.append(f"    {dev}_word_t i = 0ULL;")
    out.append(f"    for (i = 0ULL; i < {DEV}_FABRIC_REGS; i = i + 1ULL) {{ f[i] = 0ULL; }}")
    out.append("}")
    out.append("")
    out.append(f"#endif /* {DEV}_GEN_H */")
    sys.stdout.write("\\n".join(out) + "\\n")


if __name__ == "__main__":
    main()
'''

VALIDATE = '''#!/usr/bin/env python3
"""validate.py — netlist validator for THE FPGA blank (the project gate).

EMITTED BY gen_fpga_blank.py — DO NOT EDIT BY HAND (regenerate via the tool).
Enforces the blank law: pure device reference — NO logic, NO allocation, NO
addresses, NO differentiation. (System-wide identity across blanks is enforced
separately by checks/check_blank_identity.py at gate stage 2k.)
"""
import json
import sys


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "fpga_blank.net.json"
    net = json.load(open(path))
    errs = []

    if net.get("kind") != "fpga_blank":
        errs.append(f"kind must be 'fpga_blank' (got {net.get('kind')!r})")
    for forbidden in ("dff_nodes", "comb_nodes", "config_nodes", "clock", "window_base",
                      "role", "intended_modules_doc", "intended_modules", "placement",
                      "residents"):
        if net.get(forbidden):
            errs.append(f"a blank must have NO {forbidden} (pure undifferentiated "
                        f"device reference; allocation/placement are phases 3/4)")
    fab = net.get("fabric") or {}
    regs = fab.get("registers", 0)
    if regs <= 0 or (regs & (regs - 1)) != 0:
        errs.append(f"fabric.registers ({regs}) must be a positive power of two")
    if fab.get("word_bits") != 64:
        errs.append("fabric.word_bits must be 64")
    if not net.get("part_ref"):
        errs.append("part_ref missing — a blank must be real-part referenced")
    geo = net.get("address_space_geometry") or {}
    for k in ("size", "slot_alignment", "cdc_region_size"):
        if not isinstance(geo.get(k), int) or geo.get(k) <= 0:
            errs.append(f"address_space_geometry.{k} must be a positive integer")
    for cn, c in (net.get("clock_domain_table") or {}).items():
        if not isinstance(c.get("frequency_hz"), int):
            errs.append(f"clock domain {cn}: frequency_hz must be an integer")

    if errs:
        for e in errs:
            sys.stderr.write(f"[validate] FAIL: {e}\\n")
        sys.exit(3)
    print(f"[validate] OK — THE fpga blank: fabric {regs} regs, "
          f"{len(net.get('clock_domain_table', {}))} clock domains, full part, undifferentiated")


if __name__ == "__main__":
    main()
'''

MAKEFILE = '''# fpga_blank — THE identical FPGA blank (cast from device_profiles/vu9p.yaml).
# EMITTED BY gen_fpga_blank.py — DO NOT EDIT BY HAND (regenerate via the tool).
# Pure device reference: NO module allocation, NO logic, NO addresses (blank law).
# Boards = identical instances of this blank, named at addressing (phase 3).
# Flow: part profile --emit--> netlist --validate--> --gennet--> fabric C --cc--> thin test.
CC=cc
CFLAGS=-std=c11 -Wall -Wextra -Werror -O2
PY=python3
PROFILE=../device_profiles/vu9p.yaml
NET=fpga_blank.net.json
GEN=fpga_blank_gen.h
.PHONY: all emit validate gen test clean
all: test
emit: ../gen_fpga_blank.py $(PROFILE)
\t$(PY) ../gen_fpga_blank.py $(PROFILE) > $(NET)
$(NET): ../gen_fpga_blank.py $(PROFILE)
\t$(PY) ../gen_fpga_blank.py $(PROFILE) > $(NET)
validate: $(NET)
\t$(PY) validate.py $(NET)
gen: validate
\t$(PY) gennet.py $(NET) > $(GEN)
test: gen
\t$(CC) $(CFLAGS) -o test_fpga_blank test_fpga_blank.c
\t./test_fpga_blank
clean:
\trm -f test_fpga_blank
'''

TEST = '''/* test_fpga_blank.c — thin test: power-on (zero fabric) + display geometry.
 * EMITTED BY gen_fpga_blank.py — DO NOT EDIT BY HAND (regenerate via the tool).
 * A blank owns no logic and runs no clock; the test proves the fabric exists,
 * inits, and the full-part constants are present. Static storage — no heap. */
#include <stdio.h>
#include "fpga_blank_gen.h"

static fpga_blank_word_t f[FPGA_BLANK_FABRIC_REGS];

int main(void) {
    fpga_blank_init(f);
    printf("fpga blank: fabric=%u regs x %u bits | mac=%uHz internal=%uHz taiosc=%uHz\\n",
           FPGA_BLANK_FABRIC_REGS, FPGA_BLANK_WORD_BITS,
           FPGA_BLANK_CLK_MAC_HZ, FPGA_BLANK_CLK_INTERNAL_HZ, FPGA_BLANK_CLK_TAIOSC_HZ);
    printf("full part: gty=%u banks=%u clb=%u bram=%u dsp=%u | geom addr=%#x align=%#x cdc=%#x\\n",
           FPGA_BLANK_IO_GTY_LANES, FPGA_BLANK_IO_IO_BANKS,
           FPGA_BLANK_RES_CLB_CAPACITY, FPGA_BLANK_RES_BRAM_CAPACITY, FPGA_BLANK_RES_DSP_CAPACITY,
           FPGA_BLANK_ADDR_SPACE_SIZE, FPGA_BLANK_SLOT_ALIGNMENT, FPGA_BLANK_CDC_REGION_SIZE);
    return 0;
}
'''

GITIGNORE = "test_fpga_blank\n*.dSYM/\n"


def emit_component(prof, comp_dir):
    os.makedirs(comp_dir, exist_ok=True)
    files = {
        "gennet.py": GENNET,
        "validate.py": VALIDATE,
        "Makefile": MAKEFILE,
        "test_fpga_blank.c": TEST,
        ".gitignore": GITIGNORE,
    }
    for name, content in files.items():
        with open(os.path.join(comp_dir, name), "w") as f:
            f.write(content)
    sys.stderr.write(f"gen_fpga_blank: emitted complete fileset -> {comp_dir}/ "
                     f"({', '.join(files)})\n"
                     f"gen_fpga_blank: now run `make test` inside {comp_dir}/ "
                     f"(emit -> validate -> gen -> test)\n")


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if not args:
        die("usage: gen_fpga_blank.py <part_profile.yaml> [--emit-component <dir>] "
            "[> fpga_blank.net.json]")
    prof = load_profile(args[0])

    if "--emit-component" in sys.argv:
        i = sys.argv.index("--emit-component")
        if i + 1 >= len(sys.argv):
            die("--emit-component needs a directory")
        emit_component(prof, sys.argv[i + 1])
        return

    json.dump(build_netlist(prof), sys.stdout, indent=2)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
