#!/usr/bin/env python3
"""gen_fpga_fabric.py — emit the FPGA fabric C as the real tile component arrayed
across the authentic grid (the parametric representation: every flip-flop real, the
grid an array — not 147,750 flattened copies).

Does the inevitable manual labor (replicating the tile across the grid) as a TOOL.
HARDCODES NOTHING: the count comes from spec/<dev>_device_model.json; the per-tile
register layout + init/tick come from the tile component's own gennet output
(<tile>_gen.h). The fabric is an array of the real slice register-banks; the fabric
tick applies the tile's REAL tick to each (power-gated). Modules install later
(separate phase) — this only DESIGNS the fabric.

Usage: python3 gen_fpga_fabric.py <device_model.json> <tile_type> <tile_module> <tile_netlist.json> > fpga_gen.h
       e.g.  gen_fpga_fabric.py spec/vu9p_device_model.json CLB clb_slice fpga/clb_slice.net.json > fpga/fpga_gen.h
"""
import json
import sys


def die(m):
    sys.stderr.write("gen_fpga_fabric: " + m + "\n"); sys.exit(2)


def main():
    if len(sys.argv) not in (5, 6):
        die("usage: gen_fpga_fabric.py <device_model.json> <tile_type> <tile_module> <tile_netlist.json> [authentic_count] > fpga_gen.h")
    model = json.load(open(sys.argv[1]))
    tile_type = sys.argv[2]
    mod = sys.argv[3]                         # e.g. clb_slice
    MOD = mod.upper()
    # authentic FF-per-tile = the tile's real flip-flops, from its own netlist.
    tile_net = json.load(open(sys.argv[4]))
    ff_per_tile = len(tile_net.get("dff_nodes") or [])
    if ff_per_tile <= 0:
        die(f"tile netlist {sys.argv[4]} has no dff_nodes (no flip-flops?)")

    # count: from the materialized device model if present; else an explicit
    # authentic count (for tiles whose count is not yet in the model — e.g. BRAM/
    # URAM block counts, which the PSG gives only as Mb; the datasheet gives blocks).
    grid = model.get("grid") or {}
    if tile_type in grid:
        count = int(grid[tile_type]["count"])
    elif len(sys.argv) == 6:
        count = int(sys.argv[5])
    else:
        die(f"tile type '{tile_type}' not in device model — pass an authentic count")
    dev = str(model.get("device_model", "device")).lower()

    L = []
    L.append("/* GENERATED by gen_fpga_fabric.py — the FPGA fabric: the real tile")
    L.append(f" * component '{mod}' arrayed across the authentic grid ({count} {tile_type}).")
    L.append(" * Every flip-flop is real (the tile's cell_dff); the grid is an array,")
    L.append(" * not flattened. Count from the device model — nothing hardcoded. */")
    L.append(f"#ifndef FPGA_{dev.upper()}_GEN_H")
    L.append(f"#define FPGA_{dev.upper()}_GEN_H")
    L.append(f'#include "{mod}_gen.h"')
    L.append("#include <stdint.h>")
    L.append("#include <stdio.h>")
    L.append(f"#define FPGA_{tile_type}_COUNT {count}u")
    L.append(f"#define FPGA_{tile_type}_REGS {MOD}_REG_COUNT")
    L.append(f"#define FPGA_{tile_type}_FF_PER_TILE {ff_per_tile}u  /* authentic, from the tile netlist */")
    # the fabric: one register-bank per tile, plus a master power bit.
    L.append(f"static word_t fpga_{tile_type.lower()}[FPGA_{tile_type}_COUNT][FPGA_{tile_type}_REGS];")
    L.append("static uint8_t fpga_master_power;")
    # init: lay the grid, every tile's real init; power off (powers up via harness).
    L.append("static inline void fpga_init(void){")
    L.append("  fpga_master_power = 0u;")
    L.append(f"  for (unsigned i = 0u; i < FPGA_{tile_type}_COUNT; i++) {mod}_init(fpga_{tile_type.lower()}[i]);")
    L.append("}")
    L.append("static inline void fpga_power_on(void){ fpga_master_power = 1u; }")
    L.append("static inline void fpga_power_off(void){ fpga_master_power = 0u; }")
    # tick: structural replication of the tile's REAL tick across the grid, gated by
    # master power (a blank tile holds when unpowered). The loop is fabric replication
    # of identical tiles (not data-path branching).
    L.append("static inline void fpga_tick(void){")
    L.append("  word_t en = (word_t)(0u - (word_t)(fpga_master_power & 1u));  /* all-ones iff powered */")
    L.append("  (void)en;")
    L.append(f"  for (unsigned i = 0u; i < FPGA_{tile_type}_COUNT; i++)")
    L.append(f"    if (fpga_master_power) {mod}_tick(fpga_{tile_type.lower()}[i]);")
    L.append("}")
    # how many real flip-flops the fabric holds (count * the tile's FF BELs).
    L.append("static inline unsigned long fpga_flipflops(void){")
    L.append(f"  return (unsigned long)FPGA_{tile_type}_COUNT * FPGA_{tile_type}_FF_PER_TILE;")
    L.append("}")
    L.append("static inline void fpga_display(void){")
    L.append('  printf("FPGA %s fabric: %u %s tiles, %lu real flip-flops, master_power=%u\\n",')
    L.append(f'         "{dev}", FPGA_{tile_type}_COUNT, "{tile_type}", fpga_flipflops(), fpga_master_power);')
    L.append("}")
    L.append("#endif")
    sys.stdout.write("\n".join(L) + "\n")


if __name__ == "__main__":
    main()
