/* GENERATED by gennet.py from dom_bus.net.json — DO NOT EDIT BY HAND.
 * dom_bus: passive lock-free BARRIER bus — addressed lanes only, no clock,
 * no compute, no latch. Producer DEPOSITS (sole writer); consumers SAMPLE.
 * A module never reads another's registers directly; this bus is the medium. */
#ifndef DOM_BUS_GEN_H
#define DOM_BUS_GEN_H
#include <stdint.h>

typedef uint64_t dom_bus_word_t;
#define DOM_BUS_REG_COUNT 40u
#define DOM_BUS_DOMBUS_BID_ACT_0 0u
#define DOM_BUS_DOMBUS_BID_ACT_1 1u
#define DOM_BUS_DOMBUS_BID_ACT_2 2u
#define DOM_BUS_DOMBUS_BID_ACT_3 3u
#define DOM_BUS_DOMBUS_BID_ACT_4 4u
#define DOM_BUS_DOMBUS_BID_ACT_5 5u
#define DOM_BUS_DOMBUS_BID_ACT_6 6u
#define DOM_BUS_DOMBUS_BID_ACT_7 7u
#define DOM_BUS_DOMBUS_ASK_ACT_0 8u
#define DOM_BUS_DOMBUS_ASK_ACT_1 9u
#define DOM_BUS_DOMBUS_ASK_ACT_2 10u
#define DOM_BUS_DOMBUS_ASK_ACT_3 11u
#define DOM_BUS_DOMBUS_ASK_ACT_4 12u
#define DOM_BUS_DOMBUS_ASK_ACT_5 13u
#define DOM_BUS_DOMBUS_ASK_ACT_6 14u
#define DOM_BUS_DOMBUS_ASK_ACT_7 15u
#define DOM_BUS_DOMBUS_TOUCH_0 16u
#define DOM_BUS_DOMBUS_TOUCH_1 17u
#define DOM_BUS_DOMBUS_TOUCH_2 18u
#define DOM_BUS_DOMBUS_TOUCH_3 19u
#define DOM_BUS_DOMBUS_TOUCH_4 20u
#define DOM_BUS_DOMBUS_TOUCH_5 21u
#define DOM_BUS_DOMBUS_TOUCH_6 22u
#define DOM_BUS_DOMBUS_TOUCH_7 23u
#define DOM_BUS_DOMBUS_BEST_BID 24u
#define DOM_BUS_DOMBUS_BEST_ASK 25u
#define DOM_BUS_DOMBUS_BEST_BID_QTY 26u
#define DOM_BUS_DOMBUS_BEST_ASK_QTY 27u
#define DOM_BUS_DOMBUS_BAR_BOUNDARY 28u
#define DOM_BUS_DOMBUS_BAR_TIME 29u
#define DOM_BUS_DOMBUS_BAR_SEQ 30u
#define DOM_BUS_DOMBUS_VALID 31u
#define DOM_BUS_DOMBUS_TOTAL_BID_QTY 32u
#define DOM_BUS_DOMBUS_TOTAL_ASK_QTY 33u
#define DOM_BUS_DOMBUS_SPREAD 34u
#define DOM_BUS_DOMBUS_MID 35u
#define DOM_BUS_DOMBUS_ADD_COUNT 36u
#define DOM_BUS_DOMBUS_CANCEL_COUNT 37u
#define DOM_BUS_DOMBUS_TRADE_COUNT 38u
#define DOM_BUS_DOMBUS_LAST_FEED_TIME 39u

/* dom_bus_init: zero the passive bus (power-off reset). No clock runs here. */
static inline void dom_bus_init(dom_bus_word_t *b) {
    dom_bus_word_t i = 0ULL;
    for (i = 0ULL; i < DOM_BUS_REG_COUNT; i = i + 1ULL) { b[i] = 0ULL; }
}

#endif /* DOM_BUS_GEN_H */
