#!/usr/bin/env python3
"""gennet.py — generate the wire bus C from wire.net.json.

The wire is a PASSIVE addressed-memory bus: no clock, no compute, no logic of
its own (INGRESS_FLOW.md s3, feedback_hft_wire_and_barrier). So this generator
emits ONLY:

  - the address map (#define one slot per bus lane, in declaration order),
  - the window base + lane count,
  - an init that zeroes the memory (power-off / synchronous reset value),

and NOTHING ELSE: no _tick, no _run, no cells, no clock loop, no latch. The wire
writes nothing itself — the ADAPTER deposits into these slots (it drives the bus)
and the NIC samples them. A lane can't float in space; it needs an address — that
addressed storage IS the wire.
"""
import json
import sys


HEADER = """/* GENERATED by gennet.py from wire.net.json — DO NOT EDIT BY HAND.
 * The wire bus: a PASSIVE addressed-memory boundary. Just the address map of the
 * price-only lanes + a zero-init. NO clock, NO compute, NO latch — the wire
 * writes nothing itself. The adapter DEPOSITS into these slots (sole writer);
 * the NIC SAMPLES them. (INGRESS_FLOW.md s1/s3, feedback_hft_wire_and_barrier) */
#ifndef WIRE_GEN_H
#define WIRE_GEN_H
#include <stdint.h>

/* The bus holds 64-bit words, indexed by the lane addresses below. The whole
 * device state is this flat array — no logic accompanies it. */
typedef uint64_t wire_word_t;
"""


def main():
    net_path = sys.argv[1] if len(sys.argv) > 1 else "wire.net.json"
    with open(net_path) as f:
        net = json.load(f)

    nodes = [n["name"] for n in net.get("bus_nodes", [])]
    addr = {nm: i for i, nm in enumerate(nodes)}
    count = len(nodes)

    out = [HEADER]
    out.append(f"#define WIRE_REG_COUNT {count}u")
    out.append(f"#define WIRE_WINDOW_BASE {net['window_base']}u\n")
    for nm in nodes:
        out.append(f"#define WIRE_{nm} {addr[nm]}u")
    out.append("")

    # init: power-off reset — the bus holds nothing until the adapter deposits.
    # (Synchronous-reset model: zero every lane; no clock edge runs here.)
    out.append("/* wire_init: zero the passive bus (power-off reset value). The wire")
    out.append(" * runs no clock; this is the only state operation it owns. */")
    out.append("static inline void wire_init(wire_word_t *w) {")
    out.append("    wire_word_t i = 0ULL;")
    out.append("    for (i = 0ULL; i < WIRE_REG_COUNT; i = i + 1ULL) { w[i] = 0ULL; }")
    out.append("}")
    out.append("")
    out.append("#endif /* WIRE_GEN_H */")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
