#!/usr/bin/env python3
"""gennet.py — generate the timeframe device C from timeframe.net.json.

timeframe is the reference bar-boundary clock (SPEC_REGISTERS.md §2): a pure-
combinational rollover detector. The device logic is GENERATED from the netlist,
never hand-written.

The rollover tick (READ -> COMPUTE -> WRITE):
  READ    : TF_TAI_IN (sampled TAI value), TF_PERIOD_NS (bar period), POWER, and
            the current BAR_SEQ / BAR_CLOSED / BAR_START registers.
  COMPUTE : elapsed   = cell_addsub(tai, bar_start, 1)   (TAI - BAR_START, sub)
            lt        = cmp_lt(elapsed, period)          (carry-chain comparator)
            rollover  = cell_gate(lt ^ 1, power)         ((elapsed >= period) & powered)
            seq_next  = cell_addsub(bar_seq, rollover, 0) (BAR_SEQ + rollover)
            closed    = cell_gate(rollover, power)        (one-tick pulse, else 0)
            start_next= cell_mux(bar_start, tai, rollover)(re-anchor to TAI on roll)
  WRITE   : commit BAR_SEQ, BAR_CLOSED, BAR_START.

Generated data path contains ZERO if/switch/?: — selection is mask algebra in the
cells (cell_gate / cell_mux), the increment/subtract are the structural ripple-carry
cell_addsub (no native +/-), and the >= compare is the cmp_lt gate netlist (no native
relational operator). The free-running clock loop (power-bit gated, bounded by a
configured tick budget) lives here in the device, not in any test.
"""
import json
import sys


def emit_cmp_lt():
    """Emit cmp_lt(a, b) -> 1 iff a < b, built ONLY from cells (carry chain).

    a < b  <=>  a - b borrows out of bit 63  <=>  the carry-out of (a + ~b + 1)
    is 0. Pure gate netlist over cell_fa — no C relational operator. Generator-
    level unrolling, not a data-path branch. (elapsed >= period) is (cmp_lt ^ 1).
    """
    return """
/* cmp_lt: gate-netlist comparator. Returns 1 (bit0) iff a < b (unsigned).
 * a - b = a + (~b) + 1 via 64 full-adder cells; the carry-out of the top bit is
 * (a >= b). So (a < b) = carry ^ 1; the rollover uses (elapsed >= period) which
 * is (cmp_lt(elapsed, period) ^ 1) — still pure gate algebra, no C compare. */
static inline word_t cmp_lt(word_t a, word_t b) {
    word_t carry = 1ULL;                 /* +1 for two's-complement of b */
    word_t i = 0ULL;
    for (i = 0ULL; i < 64ULL; i = i + 1ULL) {
        const word_t aa = (a >> i) & 1ULL;
        const word_t nb = (cell_not(b) >> i) & 1ULL;     /* ~b bit */
        const word_t fa = cell_fa(aa, nb, carry);
        carry           = (fa >> 1) & 1ULL;              /* carry-out to next */
    }
    return (carry & 1ULL) ^ 1ULL;        /* carry==0 (borrow) == (a < b) */
}
"""


def main():
    net_path = sys.argv[1] if len(sys.argv) > 1 else "timeframe.net.json"
    with open(net_path) as f:
        net = json.load(f)

    dev = net["device"]              # "timeframe"
    DEV = dev.upper()                # "TIMEFRAME"
    pfx = DEV                        # register prefix

    order = []
    for grp in ("config_nodes", "dff_nodes"):
        for n in net.get(grp, []):
            order.append(n["name"])
    addr = {nm: i for i, nm in enumerate(order)}
    count = len(order)

    power = net["power"]
    tai = net["tai"]
    period = net["period"]
    bar_seq = net["bar_seq"]
    bar_closed = net["bar_closed"]
    bar_start = net["bar_start"]
    run = net["run"]

    out = []
    out.append(f"/* GENERATED by gennet.py from {net_path} — DO NOT EDIT BY HAND.")
    out.append(" * timeframe: the reference bar-boundary clock (SPEC_REGISTERS.md §2). A")
    out.append(" * pure-combinational rollover detector as a netlist of cells over addressed")
    out.append(" * registers. No if/switch/?: in the data path; the subtract/increment are")
    out.append(" * the structural cell_addsub ripple-carry adder and the >= compare is the")
    out.append(" * cmp_lt gate netlist (no native +/-*, no native relational operator). */")
    out.append(f"#ifndef {DEV}_GEN_H")
    out.append(f"#define {DEV}_GEN_H")
    out.append('#include "cells.h"')
    out.append("")
    out.append(f"#define {pfx}_REG_COUNT {count}u")
    out.append(f"#define {pfx}_WINDOW_BASE {net['window_base']}u\n")
    for nm in order:
        out.append(f"#define {pfx}_{nm} {addr[nm]}u")
    out.append("")
    out.append(emit_cmp_lt())
    out.append("")

    # ---- init: power-off synchronous reset value (everything zero). ----------
    out.append(f"static inline void {dev}_init(word_t *r) {{")
    out.append("    word_t i = 0ULL;")
    out.append(f"    for (i = 0ULL; i < {pfx}_REG_COUNT; i = i + 1ULL) {{ r[i] = 0ULL; }}")
    out.append("}")
    out.append("")

    # ---- one clock edge: READ -> COMPUTE -> WRITE. ---------------------------
    out.append(f"/* {dev}_tick: one clock edge. READ the sampled TAI value + bar period +")
    out.append(" * current bar registers, COMPUTE the elapsed subtract / period compare /")
    out.append(" * rollover, WRITE the bar sequence, closed pulse, and re-anchored start.")
    out.append(" * The WRITE phase is write-only; no read-after-write. */")
    out.append(f"static inline void {dev}_tick(word_t *r) {{")
    out.append("    /* READ phase — pre-read every operand from its register. */")
    out.append(f"    const word_t power      = r[{pfx}_{power}] & 1ULL;")
    out.append(f"    const word_t tai        = r[{pfx}_{tai}];")
    out.append(f"    const word_t period     = r[{pfx}_{period}];")
    out.append(f"    const word_t seq_cur    = r[{pfx}_{bar_seq}];")
    out.append(f"    const word_t start_cur  = r[{pfx}_{bar_start}];")
    out.append("")
    out.append("    /* COMPUTE phase — branchless. */")
    out.append("    /* elapsed = TAI - BAR_START via the structural two's-complement subtract. */")
    out.append("    const word_t elapsed = cell_addsub(tai, start_cur, 1ULL);")
    out.append("    /* rollover = (elapsed >= period) AND powered. (>=) is (cmp_lt ^ 1); the")
    out.append("     * power gate makes an unpowered tick a no-op (no spurious boundary). */")
    out.append("    const word_t ge       = cmp_lt(elapsed, period) ^ 1ULL;")
    out.append("    const word_t rollover = cell_gate(ge, power) & 1ULL;")
    out.append("    /* BAR_SEQ += rollover (structural adder); BAR_CLOSED pulses = rollover")
    out.append("     * (one tick — next tick re-anchored start makes elapsed small again);")
    out.append("     * BAR_START re-anchors to TAI on rollover, else holds (mask-algebra mux). */")
    out.append("    const word_t seq_next    = cell_addsub(seq_cur, rollover, 0ULL);")
    out.append("    const word_t closed_next = cell_gate(rollover, power) & 1ULL;")
    out.append("    const word_t start_next  = cell_mux(start_cur, tai, rollover);")
    out.append("")
    out.append("    /* WRITE phase — commit the registered hops. */")
    out.append(f"    r[{pfx}_{bar_seq}]    = seq_next;")
    out.append(f"    r[{pfx}_{bar_closed}] = closed_next;")
    out.append(f"    r[{pfx}_{bar_start}]  = start_next;")
    out.append("}")
    out.append("")

    # ---- the self-run loop (power-gated, bounded by a configured tick budget). -
    out.append(f"/* {dev}_run: the rollover detector self-runs while powered, bounded by a")
    out.append(" * configured tick budget (RUN_UNTIL) — config, not external stepping. The")
    out.append(" * tick counter is the configured TICKS register the device increments itself.")
    out.append(" * Nothing external advances it; the compare is the cmp_lt carry chain. */")
    out.append(f"static inline void {dev}_run(word_t *r) {{")
    rc = run["count"]
    rl = run["limit"]
    out.append(f"    while ((r[{pfx}_{run['power']}] & 1ULL)")
    out.append(f"           && cmp_lt(r[{pfx}_{rc}], r[{pfx}_{rl}])) {{")
    out.append(f"        {dev}_tick(r);")
    out.append(f"        r[{pfx}_{rc}] = cell_addsub(r[{pfx}_{rc}], 1ULL, 0ULL);")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append(f"#endif /* {DEV}_GEN_H */")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
