/* GENERATED by gennet.py from timeframe.net.json — DO NOT EDIT BY HAND.
 * timeframe: the reference bar-boundary clock (SPEC_REGISTERS.md §2). A
 * pure-combinational rollover detector as a netlist of cells over addressed
 * registers. No if/switch/?: in the data path; the subtract/increment are
 * the structural cell_addsub ripple-carry adder and the >= compare is the
 * cmp_lt gate netlist (no native +/-*, no native relational operator). */
#ifndef TIMEFRAME_GEN_H
#define TIMEFRAME_GEN_H
#include "cells.h"

#define TIMEFRAME_REG_COUNT 8u
#define TIMEFRAME_WINDOW_BASE 0x2000000u

#define TIMEFRAME_TF_POWER 0u
#define TIMEFRAME_TF_RUN_UNTIL 1u
#define TIMEFRAME_TF_TAI_IN 2u
#define TIMEFRAME_TF_PERIOD_NS 3u
#define TIMEFRAME_TF_TICKS 4u
#define TIMEFRAME_TF_BAR_SEQ 5u
#define TIMEFRAME_TF_BAR_CLOSED 6u
#define TIMEFRAME_TF_BAR_START 7u


/* cmp_lt: gate-netlist comparator. Returns 1 (bit0) iff a < b (unsigned).
 * a - b = a + (~b) + 1 via 64 full-adder cells; the carry-out of the top bit is
 * (a >= b). So (a < b) = carry ^ 1; the rollover uses (elapsed >= period) which
 * is (cmp_lt(elapsed, period) ^ 1) — still pure gate algebra, no C compare. */
static inline word_t cmp_lt(word_t a, word_t b) {
    word_t carry = 1ULL;                 /* +1 for two's-complement of b */
    word_t i = 0ULL;
    for (i = 0ULL; i < 64ULL; i = i + 1ULL) {
        const word_t aa = (a >> i) & 1ULL;
        const word_t nb = (cell_not(b) >> i) & 1ULL;     /* ~b bit */
        const word_t fa = cell_fa(aa, nb, carry);
        carry           = (fa >> 1) & 1ULL;              /* carry-out to next */
    }
    return (carry & 1ULL) ^ 1ULL;        /* carry==0 (borrow) == (a < b) */
}


static inline void timeframe_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < TIMEFRAME_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
}

/* timeframe_tick: one clock edge. READ the sampled TAI value + bar period +
 * current bar registers, COMPUTE the elapsed subtract / period compare /
 * rollover, WRITE the bar sequence, closed pulse, and re-anchored start.
 * The WRITE phase is write-only; no read-after-write. */
static inline void timeframe_tick(word_t *r) {
    /* READ phase — pre-read every operand from its register. */
    const word_t power      = r[TIMEFRAME_TF_POWER] & 1ULL;
    const word_t tai        = r[TIMEFRAME_TF_TAI_IN];
    const word_t period     = r[TIMEFRAME_TF_PERIOD_NS];
    const word_t seq_cur    = r[TIMEFRAME_TF_BAR_SEQ];
    const word_t start_cur  = r[TIMEFRAME_TF_BAR_START];

    /* COMPUTE phase — branchless. */
    /* elapsed = TAI - BAR_START via the structural two's-complement subtract. */
    const word_t elapsed = cell_addsub(tai, start_cur, 1ULL);
    /* rollover = (elapsed >= period) AND powered. (>=) is (cmp_lt ^ 1); the
     * power gate makes an unpowered tick a no-op (no spurious boundary). */
    const word_t ge       = cmp_lt(elapsed, period) ^ 1ULL;
    const word_t rollover = cell_gate(ge, power) & 1ULL;
    /* BAR_SEQ += rollover (structural adder); BAR_CLOSED pulses = rollover
     * (one tick — next tick re-anchored start makes elapsed small again);
     * BAR_START re-anchors to TAI on rollover, else holds (mask-algebra mux). */
    const word_t seq_next    = cell_addsub(seq_cur, rollover, 0ULL);
    const word_t closed_next = cell_gate(rollover, power) & 1ULL;
    const word_t start_next  = cell_mux(start_cur, tai, rollover);

    /* WRITE phase — commit the registered hops. */
    r[TIMEFRAME_TF_BAR_SEQ]    = seq_next;
    r[TIMEFRAME_TF_BAR_CLOSED] = closed_next;
    r[TIMEFRAME_TF_BAR_START]  = start_next;
}

/* timeframe_run: the rollover detector self-runs while powered, bounded by a
 * configured tick budget (RUN_UNTIL) — config, not external stepping. The
 * tick counter is the configured TICKS register the device increments itself.
 * Nothing external advances it; the compare is the cmp_lt carry chain. */
static inline void timeframe_run(word_t *r) {
    while ((r[TIMEFRAME_TF_POWER] & 1ULL)
           && cmp_lt(r[TIMEFRAME_TF_TICKS], r[TIMEFRAME_TF_RUN_UNTIL])) {
        timeframe_tick(r);
        r[TIMEFRAME_TF_TICKS] = cell_addsub(r[TIMEFRAME_TF_TICKS], 1ULL, 0ULL);
    }
}

#endif /* TIMEFRAME_GEN_H */
