/* GENERATED by gennet.py from fpga_main.net.json — DO NOT EDIT BY HAND.
 * fpga-main: FPGA BLANK — the internally-connected fabric reference.
 * Real part: Xilinx Virtex UltraScale+ VU9P (XILINX_VU9P_SPEC_EXTRACTION.md)
 * Pure device reference: fabric geometry + clock/I-O/resource tables. NO module
 * allocation, NO logic, NO addresses — install (phase 4) seats modules after
 * system-wide addressing (phase 3). The fabric register file IS the interconnect. */
#ifndef FPGA_MAIN_GEN_H
#define FPGA_MAIN_GEN_H
#include <stdint.h>

typedef uint64_t fpga_main_word_t;

/* ---- fabric geometry (the interconnect) ---- */
#define FPGA_MAIN_FABRIC_REGS 262144u
#define FPGA_MAIN_WORD_BITS 64u

/* ---- address-space GEOMETRY (sizes only; addresses are assigned in phase 3) ---- */
#define FPGA_MAIN_ADDR_SPACE_SIZE 0x10000000u
#define FPGA_MAIN_SLOT_ALIGNMENT 0x1000u
#define FPGA_MAIN_CDC_REGION_SIZE 0x100000u

/* ---- clock-domain table (descriptive; oscillator modules own the clocks) ---- */
#define FPGA_MAIN_CLK_INTERNAL_HZ 250000000u
#define FPGA_MAIN_CLK_TAIOSC_HZ 1000000u

/* ---- I/O + resource budget (real-part facts) ---- */
#define FPGA_MAIN_IO_GTY_LANES 16u
#define FPGA_MAIN_IO_IO_BANKS 20u
#define FPGA_MAIN_RES_CLB_CAPACITY 100000u
#define FPGA_MAIN_RES_BRAM_CAPACITY 1200u
#define FPGA_MAIN_RES_DSP_CAPACITY 4000u

/* fpga_main_init: zero the fabric (power-off reset). A blank runs no clock and
 * owns no logic; this is the only state operation it defines. */
static inline void fpga_main_init(fpga_main_word_t *f) {
    fpga_main_word_t i = 0ULL;
    for (i = 0ULL; i < FPGA_MAIN_FABRIC_REGS; i = i + 1ULL) { f[i] = 0ULL; }
}

#endif /* FPGA_MAIN_GEN_H */
