#!/usr/bin/env python3
"""gen_tpo_net.py — EMITTER: writes tpo.net.json.

This python file is the real deliverable (DESIGN_GUIDE step 3): it emits the
netlist describing tpo as addressed register nodes wired as cells
— branchless. gennet.py then GENERATES the device C from this netlist; the
device tick is never hand-written.

Hardware specification for building the Tpo (Indicator) component flip-flop-level from the netlist-generator (emitter-first workflow).

Auto-generated by partslist-to-emitter.py from TPO_PARTS_LIST.md
"""
import json

NET = {
    "device": "tpo",
    "window_base": "0x00000000",
    "kind": "market-data",
    "comment": (
        "Hardware specification for building the Tpo (Indicator) component flip-flop-level from the netlist-generator (emitter-first workflow). "
        "(auto-generated from PARTS_LIST)"
    ),

    # --- input lanes (driven from outside the netlist: set by the starter). ---
    "config_nodes": [
        {"name": "DOM_BID_QTY", "type": "u64",
         "comment": "Bid quantity per price level (indexed by PRICE_IDX)"},
        {"name": "DOM_ASK_QTY", "type": "u64",
         "comment": "Ask quantity per price level (indexed by PRICE_IDX)"},
        {"name": "DOM_TIME", "type": "u64",
         "comment": "Latest TAI timestamp per price level"},
        {"name": "DOM_COUNT", "type": "u64",
         "comment": "Event count per price level"},
        {"name": "TF_BAR_SEQ_REG", "type": "u64",
         "comment": "Timeframe bar sequence (for bar-boundary detection)"},
        {"name": "FIFO_RX_TAI", "type": "u64",
         "comment": "TAI timestamp from ingress"},
    ],

    # --- registered outputs (the device's sole writes). -----------------------
    # State registers referenced by the combinational logic (arch §2). These are
    # the live bar-running accumulators read in the READ phase and latched in WRITE.
    "dff_nodes": [
        {"name": "TPO_PREV_TAI", "type": "u64",
         "comment": "last TAI processed (subtrahend for elapsed-time, arch §2)"},
        {"name": "TPO_BAR_POC_TOTAL", "type": "u64",
         "comment": "total accumulated time at the running POC level (arch §2)"},
        {"name": "TPO_BID_TIME", "type": "u64",
         "comment": "cumulative bid-side time at the active price level (arch §2)"},
        {"name": "TPO_ASK_TIME", "type": "u64",
         "comment": "cumulative ask-side time at the active price level (arch §2)"},
        {"name": "TPO_LAST_TF_SEQ", "type": "u64",
         "comment": "last timeframe bar sequence seen (bar-boundary detect, arch §2)"},
        {"name": "TPO_BAR_PARITY", "type": "u64",
         "comment": "virtual-reset parity tag (flips on bar close, arch §2)"},
        {"name": "TPO_STATE", "type": "u64",
         "comment": "module state register"}
    ],

    # --- combinational logic (gate-level cells, arch §3.1-3.5). ---------------
    # Each node is one structural cell call. gennet translates {cell, inputs}
    # into a cell_*( ) call over READ-phase locals — NO native C operators.
    # Canonical cells.h argument order: cell_addsub(a,b,sub), cell_mux(a,b,sel),
    # cell_eqmask(a,b), cell_gate(val,en), cmp_lt(a,b).
    "comb_nodes": [
        # §3.1 elapsed = current_TAI - TPO_PREV_TAI (sub=1). Heart of TPO.
        {"name": "TPO_TIME_DELTA", "cell": "addsub",
         "inputs": ["fifo_rx_tai", "tpo_prev_tai", "1ULL"],
         "comment": "elapsed = FIFO_RX_TAI - TPO_PREV_TAI (sub) — ns since previous edge (arch §3.1)"},

        # §3.4 bar_same = (tf_seq == last_tf_seq); boundary crossed when this is 0.
        {"name": "TPO_BAR_CLOSED", "cell": "eqmask",
         "inputs": ["tf_bar_seq_reg", "tpo_last_tf_seq"],
         "comment": "bar_same = (TF_BAR_SEQ == TPO_LAST_TF_SEQ); boundary when 0 (arch §3.4)"},

        # §3.2 active = (DOM_TIME == current_TAI): which level is live this tick.
        {"name": "TPO_MIN_MAX", "cell": "eqmask",
         "inputs": ["dom_time", "fifo_rx_tai"],
         "comment": "active = (DOM_TIME == FIFO_RX_TAI); selects the live price level (arch §3.2/§3.3)"},

        # §3.2 charge = gate(elapsed, active): elapsed charged to the active level.
        {"name": "TPO_TIME_ACCUMULATE", "cell": "gate",
         "inputs": ["tpo_time_delta", "tpo_min_max"],
         "comment": "charge = elapsed if level active this tick, else 0 (arch §3.2)"},

        # §3.5 bid_charge = gate(charge, is_bid): route elapsed to the bid table.
        {"name": "BID_ASK_SPLIT", "cell": "gate",
         "inputs": ["tpo_time_accumulate", "dom_bid_qty"],
         "comment": "bid_charge = charge if bid event, else 0; ask = complement (arch §3.5)"},
    ],
}


def main():
    """Emit the netlist as JSON to stdout."""
    import sys
    json.dump(NET, sys.stdout, indent=2)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()