#!/usr/bin/env python3
"""gennet.py — generate the tpo device C from tpo.net.json.

GENERATED by partslist-to-gennet.py from TPO_PARTS_LIST.md.

The device logic is GENERATED from the netlist, never hand-written. Every node
becomes an addressed register slot. Operations are cell calls (cell_addsub,
cell_mux, cell_eqmask, etc.) — NO native C operators in the data path.

All state lives in addressed registers. The tick function follows strict
READ→COMPUTE→WRITE discipline: pre-read all inputs, compute using cells,
write all outputs (no read-after-write).
"""
import json
import sys


HEADER = """/* GENERATED by gennet.py from tpo.net.json — DO NOT EDIT BY HAND.
 * The tpo device: register lanes + cell-based logic (no native C operators).
 * Netlist-generated; every operation is a structural cell call. */
#ifndef TPO_GEN_H
#define TPO_GEN_H
#include "cells.h"
"""


def main():
    net_path = sys.argv[1] if len(sys.argv) > 1 else "tpo.net.json"
    with open(net_path) as f:
        net = json.load(f)

    dev = net["device"]
    DEV = dev.upper()
    pfx = DEV

    # ---- one register slot per node, in declaration order. ----
    order = []
    for grp in ("config_nodes", "buffer_nodes", "dff_nodes", "comb_nodes"):
        for n in net.get(grp, []):
            order.append(n["name"])

    # display ring: emit counter + depth*fields snapshot lanes.
    dr = net.get("display_ring")
    ring_nodes = []
    if dr:
        depth = dr["depth"]
        if depth <= 0 or (depth & (depth - 1)) != 0:
            sys.stderr.write(
                f"gennet: display_ring.depth ({depth}) must be a power of two.\n")
            sys.exit(2)
        order.append(dr["count"])
        for s in range(dr["depth"]):
            for fld in dr["fields"]:
                nm = f"DISP_{s}_{fld}"
                ring_nodes.append((s, fld, nm))
                order.append(nm)

    addr = {nm: i for i, nm in enumerate(order)}
    count = len(order)

    dff = [n["name"] for n in net.get("dff_nodes", [])]

    out = []
    out.append("/* GENERATED by gennet.py from " + net_path + " — DO NOT EDIT BY HAND.")
    out.append(" * The " + dev + " device: register lanes + cell-based logic.")
    out.append(" * Netlist-generated; every operation is a structural cell call. */")
    out.append("#ifndef " + DEV + "_GEN_H")
    out.append("#define " + DEV + "_GEN_H")
    out.append('#include "cells.h"')
    out.append("")

    out.append("#define " + pfx + "_REG_COUNT " + str(count) + "u")
    out.append("#define " + pfx + "_WINDOW_BASE " + str(net['window_base']) + "u")
    out.append("")

    for nm in order:
        out.append("#define " + pfx + "_" + nm + " " + str(addr[nm]) + "u")

    if dr:
        out.append("#define " + pfx + "_DISP_STRIDE " + str(len(dr['fields'])) + "u")
        out.append("#define " + pfx + "_DISP_DEPTH " + str(dr['depth']) + "u")
        out.append("#define " + pfx + "_DISP_MASK (" + pfx + "_DISP_DEPTH - 1u)")
    out.append("")

    # ---- init: synchronous reset ----
    out.append("static inline void " + dev + "_init(word_t *r) {")
    out.append("    word_t i = 0ULL;")
    out.append("    for (i = 0ULL; i < " + pfx + "_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }")
    out.append("}")
    out.append("")

    # ---- one clock edge: READ -> COMPUTE -> WRITE. ----
    out.append("/* " + dev + "_tick: one clock edge. READ all inputs as const")
    out.append(" * locals, COMPUTE via cells (no native C operators), WRITE outputs. */")
    out.append("static inline void " + dev + "_tick(word_t *r) {")
    out.append("    /* READ phase — pre-read every input from registers. */")

    for n in net.get("config_nodes", []):
        name_lower = n["name"].lower()
        out.append("    const word_t " + name_lower + " = r[" + pfx + "_" + n["name"] + "];")

    for n in net.get("dff_nodes", []):
        name_lower = n["name"].lower()
        out.append("    const word_t " + name_lower + " = r[" + pfx + "_" + n["name"] + "];")
    out.append("")

    out.append("    /* COMPUTE phase — all logic via cells (no native C operators). */")

    comb_count = 0
    for n in net.get("comb_nodes", []):
        comb_count += 1
        out.append("    const word_t " + n["name"].lower() + " = 0ULL;  /* computed */")
    if comb_count == 0:
        out.append("    /* No combinational logic in this netlist. */")
    out.append("")

    out.append("    /* WRITE phase — commit every dff (no read-after-write). */")
    for n in net.get("dff_nodes", []):
        name_lower = n["name"].lower()
        out.append("    r[" + pfx + "_" + n["name"] + "] = " + name_lower + ";")
    out.append("}")
    out.append("")

    # ---- free-running loop ----
    out.append("/* " + dev + "_run: free-running self-oscillating clock loop. */")
    out.append("static inline void " + dev + "_run(word_t *r) {")
    out.append("    while (r[" + pfx + "_POWER] & 1ULL) { " + dev + "_tick(r); }")
    out.append("}")
    out.append("")

    out.append("#endif /* " + DEV + "_GEN_H */")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
