/* GENERATED by gennet.py from harness.net.json — DO NOT EDIT BY HAND.
 * The harness device: register lanes + cell-based logic (READ->COMPUTE->WRITE).
 * Netlist-generated; every data operation is a structural cell call. */
#ifndef HARNESS_GEN_H
#define HARNESS_GEN_H
#include "cells.h"

#define HARNESS_REG_COUNT 23u

#define HARNESS_HARNESS_POWER 0u
#define HARNESS_HARNESS_RUN_UNTIL 1u
#define HARNESS_HARNESS_ONE 2u
#define HARNESS_HARNESS_TH_FPGA_CONTROL 3u
#define HARNESS_HARNESS_TH_FPGA_IN 4u
#define HARNESS_HARNESS_TH_FPGA_MAIN 5u
#define HARNESS_HARNESS_SEQ 6u
#define HARNESS_HARNESS_PWR_FPGA_CONTROL 7u
#define HARNESS_HARNESS_PWR_FPGA_IN 8u
#define HARNESS_HARNESS_PWR_FPGA_MAIN 9u
#define HARNESS_not_done 10u
#define HARNESS_running 11u
#define HARNESS_seq_step 12u
#define HARNESS_seq_next 13u
#define HARNESS_reached_fpga_control 14u
#define HARNESS_pwr_fpga_control 15u
#define HARNESS_reached_fpga_in 16u
#define HARNESS_pwr_fpga_in 17u
#define HARNESS_reached_fpga_main 18u
#define HARNESS_pwr_fpga_main 19u
#define HARNESS_HARNESS_PWR_FPGA_CONTROL_OUT 20u
#define HARNESS_HARNESS_PWR_FPGA_IN_OUT 21u
#define HARNESS_HARNESS_PWR_FPGA_MAIN_OUT 22u


/* cmp_lt: gate-netlist comparator. Returns 1 (bit0) iff a < b (unsigned).
 * a - b = a + (~b) + 1 via 64 full-adder cells; the carry-out of the top bit is
 * (a >= b). So (a < b) = carry ^ 1. Pure gate algebra, no native C compare. */
static inline word_t cmp_lt(word_t a, word_t b) {
    word_t carry = 1ULL;                 /* +1 for two's-complement of b */
    word_t i = 0ULL;
    for (i = 0ULL; i < 64ULL; i = i + 1ULL) {
        const word_t aa = (a >> i) & 1ULL;
        const word_t nb = (cell_not(b) >> i) & 1ULL;     /* ~b bit */
        const word_t fa = cell_fa(aa, nb, carry);
        carry           = (fa >> 1) & 1ULL;              /* carry-out to next */
    }
    return (carry & 1ULL) ^ 1ULL;        /* carry==0 (borrow) == (a < b) */
}


static inline void harness_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < HARNESS_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
    r[HARNESS_HARNESS_POWER] = 0ULL;
    r[HARNESS_HARNESS_RUN_UNTIL] = 64ULL;
    r[HARNESS_HARNESS_ONE] = 1ULL;
    r[HARNESS_HARNESS_TH_FPGA_CONTROL] = 0ULL;
    r[HARNESS_HARNESS_TH_FPGA_IN] = 4ULL;
    r[HARNESS_HARNESS_TH_FPGA_MAIN] = 8ULL;
}

/* harness_tick: one clock edge. READ inputs as const locals,
 * COMPUTE via cells (no native add/sub/mul on data), WRITE every register. */
static inline void harness_tick(word_t *r) {
    /* READ phase — pre-read every consumed register value. */
    const word_t harness_power = r[HARNESS_HARNESS_POWER];
    const word_t harness_run_until = r[HARNESS_HARNESS_RUN_UNTIL];
    const word_t harness_one = r[HARNESS_HARNESS_ONE];
    const word_t harness_th_fpga_control = r[HARNESS_HARNESS_TH_FPGA_CONTROL];
    const word_t harness_th_fpga_in = r[HARNESS_HARNESS_TH_FPGA_IN];
    const word_t harness_th_fpga_main = r[HARNESS_HARNESS_TH_FPGA_MAIN];
    const word_t harness_seq = r[HARNESS_HARNESS_SEQ];
    const word_t harness_pwr_fpga_control = r[HARNESS_HARNESS_PWR_FPGA_CONTROL];
    const word_t harness_pwr_fpga_in = r[HARNESS_HARNESS_PWR_FPGA_IN];
    const word_t harness_pwr_fpga_main = r[HARNESS_HARNESS_PWR_FPGA_MAIN];

    /* COMPUTE phase — combinational cell chain (declaration order). */
    const word_t not_done = cmp_lt(harness_seq, harness_run_until);
    const word_t running = cell_and(harness_power, not_done);
    const word_t seq_step = cell_gate(harness_one, running);
    const word_t seq_next = cell_addsub(harness_seq, seq_step, 0ULL);
    const word_t reached_fpga_control = (cmp_lt(harness_seq, harness_th_fpga_control) ^ 1ULL);
    const word_t pwr_fpga_control = cell_and(reached_fpga_control, harness_power);
    const word_t reached_fpga_in = (cmp_lt(harness_seq, harness_th_fpga_in) ^ 1ULL);
    const word_t pwr_fpga_in = cell_and(reached_fpga_in, harness_power);
    const word_t reached_fpga_main = (cmp_lt(harness_seq, harness_th_fpga_main) ^ 1ULL);
    const word_t pwr_fpga_main = cell_and(reached_fpga_main, harness_power);

    /* WRITE phase — gated dff commit: r[X] = cell_dff(q, fed_by, enable). */
    r[HARNESS_HARNESS_SEQ] = cell_dff(harness_seq, seq_next, 1ULL);
    r[HARNESS_HARNESS_PWR_FPGA_CONTROL] = cell_dff(harness_pwr_fpga_control, pwr_fpga_control, 1ULL);
    r[HARNESS_HARNESS_PWR_FPGA_IN] = cell_dff(harness_pwr_fpga_in, pwr_fpga_in, 1ULL);
    r[HARNESS_HARNESS_PWR_FPGA_MAIN] = cell_dff(harness_pwr_fpga_main, pwr_fpga_main, 1ULL);
    r[HARNESS_not_done] = not_done;
    r[HARNESS_running] = running;
    r[HARNESS_seq_step] = seq_step;
    r[HARNESS_seq_next] = seq_next;
    r[HARNESS_reached_fpga_control] = reached_fpga_control;
    r[HARNESS_pwr_fpga_control] = pwr_fpga_control;
    r[HARNESS_reached_fpga_in] = reached_fpga_in;
    r[HARNESS_pwr_fpga_in] = pwr_fpga_in;
    r[HARNESS_reached_fpga_main] = reached_fpga_main;
    r[HARNESS_pwr_fpga_main] = pwr_fpga_main;
    r[HARNESS_HARNESS_PWR_FPGA_CONTROL_OUT] = harness_pwr_fpga_control;
    r[HARNESS_HARNESS_PWR_FPGA_IN_OUT] = harness_pwr_fpga_in;
    r[HARNESS_HARNESS_PWR_FPGA_MAIN_OUT] = harness_pwr_fpga_main;

}

/* harness_run: canonical free-running clock. Power on once; the clock
 * self-oscillates while the power bit is set. Nothing external steps it. */
static inline void harness_run(word_t *r) {
    while (r[HARNESS_HARNESS_POWER] & 1ULL) { harness_tick(r); }
}

#endif /* HARNESS_GEN_H */
