/* GENERATED by gennet.py from footprint.net.json — DO NOT EDIT BY HAND.
 * The footprint device: register lanes + cell-based logic.
 * Netlist-generated; every operation is a structural cell call. */
#ifndef FOOTPRINT_GEN_H
#define FOOTPRINT_GEN_H
#include "cells.h"

#define FOOTPRINT_REG_COUNT 72u
#define FOOTPRINT_WINDOW_BASE 0x00000000u

#define FOOTPRINT_DOM_ASK_QTY 0u
#define FOOTPRINT_DOM_BID_QTY 1u
#define FOOTPRINT_DOM_COUNT 2u
#define FOOTPRINT_DOM_TIME 3u
#define FOOTPRINT_TF_BAR_SEQ_REG 4u
#define FOOTPRINT_FP_POC_PRICE 5u
#define FOOTPRINT_FP_POC_VOL 6u
#define FOOTPRINT_FP_POC_ASK_VOL 7u
#define FOOTPRINT_FP_POC_BID_VOL 8u
#define FOOTPRINT_FP_DELTA 9u
#define FOOTPRINT_FP_VAH_PRICE 10u
#define FOOTPRINT_FP_VAL_PRICE 11u
#define FOOTPRINT_FP_ASK_IMB_PRICE 12u
#define FOOTPRINT_FP_ASK_IMB_MAG 13u
#define FOOTPRINT_FP_BID_IMB_PRICE 14u
#define FOOTPRINT_FP_BID_IMB_MAG 15u
#define FOOTPRINT_FP_MIN_PRICE 16u
#define FOOTPRINT_FP_MAX_PRICE 17u
#define FOOTPRINT_FP_BAR_CUM_DELTA 18u
#define FOOTPRINT_FP_BAR_TOTAL_VOL 19u
#define FOOTPRINT_FP_BAR_PARITY 20u
#define FOOTPRINT_FP_LAST_TF_SEQ 21u
#define FOOTPRINT_FP_BAR_SEQ 22u
#define FOOTPRINT_FP_STACKED_IMB_BUY 23u
#define FOOTPRINT_FP_STACKED_IMB_SELL 24u
#define FOOTPRINT_new_ask 25u
#define FOOTPRINT_new_bid 26u
#define FOOTPRINT_level_vol 27u
#define FOOTPRINT_level_delta 28u
#define FOOTPRINT_is_new_max 29u
#define FOOTPRINT_new_poc_price 30u
#define FOOTPRINT_new_poc_vol 31u
#define FOOTPRINT_new_poc_ask 32u
#define FOOTPRINT_new_poc_bid 33u
#define FOOTPRINT_new_delta 34u
#define FOOTPRINT_ask_dom 35u
#define FOOTPRINT_bid_dom 36u
#define FOOTPRINT_vah_higher 37u
#define FOOTPRINT_take_vah 38u
#define FOOTPRINT_new_vah 39u
#define FOOTPRINT_val_lower 40u
#define FOOTPRINT_take_val 41u
#define FOOTPRINT_new_val 42u
#define FOOTPRINT_ask_mag 43u
#define FOOTPRINT_ask_stronger 44u
#define FOOTPRINT_take_hvn 45u
#define FOOTPRINT_new_ask_price 46u
#define FOOTPRINT_new_ask_mag 47u
#define FOOTPRINT_bid_excess_raw 48u
#define FOOTPRINT_bid_excess 49u
#define FOOTPRINT_bid_stronger 50u
#define FOOTPRINT_take_lvn 51u
#define FOOTPRINT_new_bid_price 52u
#define FOOTPRINT_new_bid_mag 53u
#define FOOTPRINT_quote_delta 54u
#define FOOTPRINT_new_cvd 55u
#define FOOTPRINT_quote_vol 56u
#define FOOTPRINT_new_total 57u
#define FOOTPRINT_is_lower 58u
#define FOOTPRINT_new_min 59u
#define FOOTPRINT_is_higher 60u
#define FOOTPRINT_new_max 61u
#define FOOTPRINT_above_poc 62u
#define FOOTPRINT_buy_qualifies 63u
#define FOOTPRINT_buy_inc 64u
#define FOOTPRINT_new_buy 65u
#define FOOTPRINT_below_poc 66u
#define FOOTPRINT_sell_qualifies 67u
#define FOOTPRINT_sell_inc 68u
#define FOOTPRINT_new_sell 69u
#define FOOTPRINT_seq_same 70u
#define FOOTPRINT_bar_pulse 71u

static inline void footprint_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < FOOTPRINT_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
}

/* footprint_tick: one clock edge. READ all inputs as const
 * locals, COMPUTE via cells (no native C operators), WRITE outputs. */
static inline void footprint_tick(word_t *r) {
    /* READ phase — pre-read every input from registers. */
    const word_t dom_ask_qty = r[FOOTPRINT_DOM_ASK_QTY];
    const word_t dom_bid_qty = r[FOOTPRINT_DOM_BID_QTY];
    const word_t dom_count = r[FOOTPRINT_DOM_COUNT];
    const word_t dom_time = r[FOOTPRINT_DOM_TIME];
    const word_t tf_bar_seq_reg = r[FOOTPRINT_TF_BAR_SEQ_REG];
    const word_t fp_poc_price = r[FOOTPRINT_FP_POC_PRICE];
    const word_t fp_poc_vol = r[FOOTPRINT_FP_POC_VOL];
    const word_t fp_poc_ask_vol = r[FOOTPRINT_FP_POC_ASK_VOL];
    const word_t fp_poc_bid_vol = r[FOOTPRINT_FP_POC_BID_VOL];
    const word_t fp_delta = r[FOOTPRINT_FP_DELTA];
    const word_t fp_vah_price = r[FOOTPRINT_FP_VAH_PRICE];
    const word_t fp_val_price = r[FOOTPRINT_FP_VAL_PRICE];
    const word_t fp_ask_imb_price = r[FOOTPRINT_FP_ASK_IMB_PRICE];
    const word_t fp_ask_imb_mag = r[FOOTPRINT_FP_ASK_IMB_MAG];
    const word_t fp_bid_imb_price = r[FOOTPRINT_FP_BID_IMB_PRICE];
    const word_t fp_bid_imb_mag = r[FOOTPRINT_FP_BID_IMB_MAG];
    const word_t fp_min_price = r[FOOTPRINT_FP_MIN_PRICE];
    const word_t fp_max_price = r[FOOTPRINT_FP_MAX_PRICE];
    const word_t fp_bar_cum_delta = r[FOOTPRINT_FP_BAR_CUM_DELTA];
    const word_t fp_bar_total_vol = r[FOOTPRINT_FP_BAR_TOTAL_VOL];
    const word_t fp_bar_parity = r[FOOTPRINT_FP_BAR_PARITY];
    const word_t fp_last_tf_seq = r[FOOTPRINT_FP_LAST_TF_SEQ];
    const word_t fp_bar_seq = r[FOOTPRINT_FP_BAR_SEQ];
    const word_t fp_stacked_imb_buy = r[FOOTPRINT_FP_STACKED_IMB_BUY];
    const word_t fp_stacked_imb_sell = r[FOOTPRINT_FP_STACKED_IMB_SELL];

    /* COMPUTE phase — all logic via cells (no native C operators). */
    const word_t new_ask = cell_addsub(fp_poc_ask_vol, dom_ask_qty, 0);  /* LEVEL_ASK_ACCUM: held_ask + DOM_ASK_QTY (sub=0, add) */
    const word_t new_bid = cell_addsub(fp_poc_bid_vol, dom_bid_qty, 0);  /* LEVEL_BID_ACCUM: held_bid + DOM_BID_QTY (sub=0, add) */
    const word_t level_vol = cell_addsub(new_ask, new_bid, 0);  /* LEVEL_TOTAL: ask+bid total level volume */
    const word_t level_delta = cell_addsub(new_ask, new_bid, 1);  /* LEVEL_DELTA: ask-bid (sub=1) */
    const word_t is_new_max = cmp_lt(fp_poc_vol, level_vol);  /* POC_PRICE_UPDATE: 1 iff current POC < this level */
    const word_t new_poc_price = cell_mux(fp_poc_price, dom_count, is_new_max);  /* POC_PRICE_UPDATE: hold | take cur_idx on new max */
    const word_t new_poc_vol = cell_mux(fp_poc_vol, level_vol, is_new_max);  /* POC_PRICE_UPDATE: hold | take level_vol on new max */
    const word_t new_poc_ask = cell_mux(fp_poc_ask_vol, new_ask, is_new_max);  /* POC_SIDE_VOL_UPDATE: ask vol at POC */
    const word_t new_poc_bid = cell_mux(fp_poc_bid_vol, new_bid, is_new_max);  /* POC_SIDE_VOL_UPDATE: bid vol at POC */
    const word_t new_delta = cell_mux(fp_delta, level_delta, is_new_max);  /* POC_DELTA: latch level delta only when new POC */
    const word_t ask_dom = cmp_lt(new_bid, new_ask);  /* IMBALANCE_CLASSIFY: 1 iff ask > bid (ask-imbalanced) */
    const word_t bid_dom = cmp_lt(new_ask, new_bid);  /* IMBALANCE_CLASSIFY: 1 iff bid > ask (bid-imbalanced) */
    const word_t vah_higher = cmp_lt(fp_vah_price, dom_count);  /* VAH_PRICE_UPDATE: 1 iff cur_idx > current VAH */
    const word_t take_vah = cell_and(ask_dom, vah_higher);  /* VAH_PRICE_UPDATE: ask-dominant AND higher */
    const word_t new_vah = cell_mux(fp_vah_price, dom_count, take_vah);  /* VAH_PRICE_UPDATE: extend value-area high */
    const word_t val_lower = cmp_lt(dom_count, fp_val_price);  /* VAL_PRICE_UPDATE: 1 iff cur_idx < current VAL */
    const word_t take_val = cell_and(bid_dom, val_lower);  /* VAL_PRICE_UPDATE: bid-dominant AND lower */
    const word_t new_val = cell_mux(fp_val_price, dom_count, take_val);  /* VAL_PRICE_UPDATE: extend value-area low */
    const word_t ask_mag = cell_gate(level_delta, ask_dom);  /* ASK_IMB_PRICE_UPDATE: delta if ask-dom else 0 */
    const word_t ask_stronger = cmp_lt(fp_ask_imb_mag, ask_mag);  /* ASK_IMB_PRICE_UPDATE: 1 iff new ask mag stronger */
    const word_t take_hvn = cell_and(ask_dom, ask_stronger);  /* ASK_IMB_PRICE_UPDATE: ask-dom AND stronger */
    const word_t new_ask_price = cell_mux(fp_ask_imb_price, dom_count, take_hvn);  /* ASK_IMB_PRICE_UPDATE: HVN price */
    const word_t new_ask_mag = cell_mux(fp_ask_imb_mag, ask_mag, take_hvn);  /* ASK_IMB_PRICE_UPDATE: HVN magnitude */
    const word_t bid_excess_raw = cell_addsub(new_bid, new_ask, 1);  /* BID_IMB_PRICE_UPDATE: bid-ask */
    const word_t bid_excess = cell_gate(bid_excess_raw, bid_dom);  /* BID_IMB_PRICE_UPDATE: (bid-ask) if bid-dom else 0 */
    const word_t bid_stronger = cmp_lt(fp_bid_imb_mag, bid_excess);  /* BID_IMB_PRICE_UPDATE: 1 iff new bid mag stronger */
    const word_t take_lvn = cell_and(bid_dom, bid_stronger);  /* BID_IMB_PRICE_UPDATE: bid-dom AND stronger */
    const word_t new_bid_price = cell_mux(fp_bid_imb_price, dom_count, take_lvn);  /* BID_IMB_PRICE_UPDATE: LVN price */
    const word_t new_bid_mag = cell_mux(fp_bid_imb_mag, bid_excess, take_lvn);  /* BID_IMB_PRICE_UPDATE: LVN magnitude */
    const word_t quote_delta = cell_addsub(dom_ask_qty, dom_bid_qty, 1);  /* BAR_CUM_DELTA: ask-bid quote delta */
    const word_t new_cvd = cell_addsub(fp_bar_cum_delta, quote_delta, 0);  /* BAR_CUM_DELTA: continuous accumulate into CVD */
    const word_t quote_vol = cell_addsub(dom_ask_qty, dom_bid_qty, 0);  /* BAR_TOTAL_VOL: ask+bid quote volume */
    const word_t new_total = cell_addsub(fp_bar_total_vol, quote_vol, 0);  /* BAR_TOTAL_VOL: accumulate bar total */
    const word_t is_lower = cmp_lt(dom_count, fp_min_price);  /* MIN_PRICE_UPDATE: 1 iff cur_idx < current min */
    const word_t new_min = cell_mux(fp_min_price, dom_count, is_lower);  /* MIN_PRICE_UPDATE: running minimum price */
    const word_t is_higher = cmp_lt(fp_max_price, dom_count);  /* MAX_PRICE_UPDATE: 1 iff cur_idx > current max */
    const word_t new_max = cell_mux(fp_max_price, dom_count, is_higher);  /* MAX_PRICE_UPDATE: running maximum price */
    const word_t above_poc = cmp_lt(fp_poc_price, dom_count);  /* STACKED_IMB_BUY: 1 iff cur_idx > POC */
    const word_t buy_qualifies = cell_and(ask_dom, above_poc);  /* STACKED_IMB_BUY: ask-dom AND above POC */
    const word_t buy_inc = cell_addsub(fp_stacked_imb_buy, 1, 0);  /* STACKED_IMB_BUY: count + 1 */
    const word_t new_buy = cell_gate(buy_inc, buy_qualifies);  /* STACKED_IMB_BUY: qualifies ? count+1 : 0 (reset-on-miss) */
    const word_t below_poc = cmp_lt(dom_count, fp_poc_price);  /* STACKED_IMB_SELL: 1 iff cur_idx < POC */
    const word_t sell_qualifies = cell_and(bid_dom, below_poc);  /* STACKED_IMB_SELL: bid-dom AND below POC */
    const word_t sell_inc = cell_addsub(fp_stacked_imb_sell, 1, 0);  /* STACKED_IMB_SELL: count + 1 */
    const word_t new_sell = cell_gate(sell_inc, sell_qualifies);  /* STACKED_IMB_SELL: qualifies ? count+1 : 0 (reset-on-miss) */
    const word_t seq_same = cell_eqmask(fp_last_tf_seq, tf_bar_seq_reg);  /* BAR_BOUNDARY_DETECTED: 1 iff seq unchanged */
    const word_t bar_pulse = cell_not(seq_same);  /* BAR_BOUNDARY_DETECTED: 1 iff bar boundary (seq changed) */

    /* WRITE phase — commit every dff (no read-after-write). */
    r[FOOTPRINT_FP_POC_PRICE] = fp_poc_price;
    r[FOOTPRINT_FP_POC_VOL] = fp_poc_vol;
    r[FOOTPRINT_FP_POC_ASK_VOL] = fp_poc_ask_vol;
    r[FOOTPRINT_FP_POC_BID_VOL] = fp_poc_bid_vol;
    r[FOOTPRINT_FP_DELTA] = fp_delta;
    r[FOOTPRINT_FP_VAH_PRICE] = fp_vah_price;
    r[FOOTPRINT_FP_VAL_PRICE] = fp_val_price;
    r[FOOTPRINT_FP_ASK_IMB_PRICE] = fp_ask_imb_price;
    r[FOOTPRINT_FP_ASK_IMB_MAG] = fp_ask_imb_mag;
    r[FOOTPRINT_FP_BID_IMB_PRICE] = fp_bid_imb_price;
    r[FOOTPRINT_FP_BID_IMB_MAG] = fp_bid_imb_mag;
    r[FOOTPRINT_FP_MIN_PRICE] = fp_min_price;
    r[FOOTPRINT_FP_MAX_PRICE] = fp_max_price;
    r[FOOTPRINT_FP_BAR_CUM_DELTA] = fp_bar_cum_delta;
    r[FOOTPRINT_FP_BAR_TOTAL_VOL] = fp_bar_total_vol;
    r[FOOTPRINT_FP_BAR_PARITY] = fp_bar_parity;
    r[FOOTPRINT_FP_LAST_TF_SEQ] = fp_last_tf_seq;
    r[FOOTPRINT_FP_BAR_SEQ] = fp_bar_seq;
    r[FOOTPRINT_FP_STACKED_IMB_BUY] = fp_stacked_imb_buy;
    r[FOOTPRINT_FP_STACKED_IMB_SELL] = fp_stacked_imb_sell;
}

/* footprint_run: free-running self-oscillating clock loop. */
static inline void footprint_run(word_t *r) {
    while (r[FOOTPRINT_POWER] & 1ULL) { footprint_tick(r); }
}

#endif /* FOOTPRINT_GEN_H */
