/* GENERATED by gennet.py from clocking/bufgce.net.json — DO NOT EDIT BY HAND.
 * The bufgce device: register lanes + cell-based logic (READ->COMPUTE->WRITE).
 * Netlist-generated; every data operation is a structural cell call. */
#ifndef BUFGCE_GEN_H
#define BUFGCE_GEN_H
#include "cells.h"

#define BUFGCE_REG_COUNT 4u

#define BUFGCE_CLK_IN 0u
#define BUFGCE_CE 1u
#define BUFGCE_CLK_OUT_C 2u
#define BUFGCE_CLK_OUT 3u

static inline void bufgce_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < BUFGCE_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
}

/* bufgce_tick: one clock edge. READ inputs as const locals,
 * COMPUTE via cells (no native add/sub/mul on data), WRITE every register. */
static inline void bufgce_tick(word_t *r) {
    /* READ phase — pre-read every consumed register value. */
    const word_t clk_in = r[BUFGCE_CLK_IN];
    const word_t ce = r[BUFGCE_CE];

    /* COMPUTE phase — combinational cell chain (declaration order). */
    const word_t clk_out_c = cell_gate(clk_in, ce);

    /* WRITE phase — gated dff commit: r[X] = cell_dff(q, fed_by, enable). */
    r[BUFGCE_CLK_OUT_C] = clk_out_c;
    r[BUFGCE_CLK_OUT] = clk_out_c;

}

/* bufgce_run: canonical free-running clock. Power on once; the clock
 * self-oscillates while the power bit is set. Nothing external steps it. */
static inline void bufgce_run(word_t *r) {
    bufgce_tick(r);
}

#endif /* BUFGCE_GEN_H */
