/* GENERATED by gennet.py from fpga_in.net.json — DO NOT EDIT BY HAND.
 * fpga-in: FPGA BLANK — the internally-connected fabric reference.
 * Real part: Xilinx Virtex UltraScale+ VU9P (XILINX_VU9P_SPEC_EXTRACTION.md)
 * Pure device reference: fabric geometry + clock/I-O/resource tables. NO module
 * allocation, NO logic, NO addresses — install (phase 4) seats modules after
 * system-wide addressing (phase 3). The fabric register file IS the interconnect. */
#ifndef FPGA_IN_GEN_H
#define FPGA_IN_GEN_H
#include <stdint.h>

typedef uint64_t fpga_in_word_t;

/* ---- fabric geometry (the interconnect) ---- */
#define FPGA_IN_FABRIC_REGS 65536u
#define FPGA_IN_WORD_BITS 64u

/* ---- address-space GEOMETRY (sizes only; addresses are assigned in phase 3) ---- */
#define FPGA_IN_ADDR_SPACE_SIZE 0x10000000u
#define FPGA_IN_SLOT_ALIGNMENT 0x1000u
#define FPGA_IN_CDC_REGION_SIZE 0x100000u

/* ---- clock-domain table (descriptive; oscillator modules own the clocks) ---- */
#define FPGA_IN_CLK_MAC_HZ 125000000u
#define FPGA_IN_CLK_INTERNAL_HZ 250000000u
#define FPGA_IN_CLK_TAIOSC_HZ 1000000u

/* ---- I/O + resource budget (real-part facts) ---- */
#define FPGA_IN_IO_GTY_LANES 8u
#define FPGA_IN_IO_IO_BANKS 12u
#define FPGA_IN_RES_CLB_CAPACITY 40000u
#define FPGA_IN_RES_BRAM_CAPACITY 480u
#define FPGA_IN_RES_DSP_CAPACITY 800u

/* fpga_in_init: zero the fabric (power-off reset). A blank runs no clock and
 * owns no logic; this is the only state operation it defines. */
static inline void fpga_in_init(fpga_in_word_t *f) {
    fpga_in_word_t i = 0ULL;
    for (i = 0ULL; i < FPGA_IN_FABRIC_REGS; i = i + 1ULL) { f[i] = 0ULL; }
}

#endif /* FPGA_IN_GEN_H */
