/* GENERATED by gennet.py from internal.net.json — DO NOT EDIT BY HAND.
 * The internal clock: a free-running counter (+ optional edge strobe) as a
 * netlist of cells over addressed registers. No if/switch/?: in the data
 * path; the increment is the structural cell_addsub ripple-carry adder. */
#ifndef INTERNAL_GEN_H
#define INTERNAL_GEN_H
#include "cells.h"

#define INTERNAL_REG_COUNT 4u
#define INTERNAL_INTERNAL_POWER 0u
#define INTERNAL_INTERNAL_RUN_UNTIL 1u
#define INTERNAL_INTERNAL_CYCLE 2u
#define INTERNAL_INTERNAL_EDGE 3u


/* cmp_lt: gate-netlist comparator. Returns 1 (bit0) iff a < b (unsigned).
 * a - b = a + (~b) + 1 via 64 full-adder cells; the carry-out of the top bit is
 * (a >= b). So (a < b) = 1 - carry, expressed branchlessly as (carry ^ 1). */
static inline word_t cmp_lt(word_t a, word_t b) {
    word_t carry = 1ULL;                 /* +1 for two's-complement of b */
    word_t i = 0ULL;
    for (i = 0ULL; i < 64ULL; i = i + 1ULL) {
        const word_t aa = (a >> i) & 1ULL;
        const word_t nb = (cell_not(b) >> i) & 1ULL;     /* ~b bit */
        const word_t fa = cell_fa(aa, nb, carry);
        carry           = (fa >> 1) & 1ULL;              /* carry-out to next */
    }
    return (carry & 1ULL) ^ 1ULL;        /* carry==0 (borrow) == (a < b) */
}


static inline void internal_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < INTERNAL_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
}

/* internal_tick: one clock edge. READ inputs as const locals, COMPUTE the
 * gated step + ripple-carry increment, WRITE the counter (and edge). The
 * WRITE phase is write-only; no read-after-write. */
static inline void internal_tick(word_t *r) {
    /* READ phase — pre-read every operand from its register. */
    const word_t power = r[INTERNAL_INTERNAL_POWER] & 1ULL;
    const word_t cur   = r[INTERNAL_INTERNAL_CYCLE];

    /* COMPUTE phase — branchless. */
    /* step: advance by 1 while powered, 0 while off (power-gated). */
    const word_t step = cell_gate(1ULL, power);
    /* increment via the structural ripple-carry adder (no native +). */
    const word_t cnt_next = cell_addsub(cur, step, 0ULL);
    /* edge strobe: high every powered tick (the oscillator edge). */
    const word_t edge_next = cell_gate(1ULL, power) & 1ULL;

    /* WRITE phase — commit the registered hop(s). */
    r[INTERNAL_INTERNAL_CYCLE] = cnt_next;
    r[INTERNAL_INTERNAL_EDGE] = edge_next;
}

/* internal_run: the canonical clock primitive. Power on once; the clock
 * self-oscillates from the power bit. Nothing external advances it.
 * Bounded by a CONFIGURED stop count (set once by the starter) — exactly
 * as the adapter self-runs bounded by its finite buffer. The bound is
 * configuration, not external stepping; the compare is the cmp_lt carry
 * chain (no C relational operator in the loop condition's intent). */
static inline void internal_run(word_t *r) {
    while ((r[INTERNAL_INTERNAL_POWER] & 1ULL)
           && cmp_lt(r[INTERNAL_INTERNAL_CYCLE], r[INTERNAL_INTERNAL_RUN_UNTIL])) { internal_tick(r); }
}

#endif /* INTERNAL_GEN_H */
