#!/usr/bin/env python3
"""gennet.py — generate the tai_cdc device C from tai_cdc.net.json.

tai_cdc is the gray-code 2-FF synchronizer that brings the TAI counter VALUE
from the taisoc/tai domain into the MAC domain, metastability-safe (Cummings).
The device logic is GENERATED from the netlist, never hand-written.

The CDC tick, clocked on the MAC edge:
  READ    : TAI_IN (the sampled tai value, an input lane), POWER, the sync regs.
  COMPUTE : gray-encode TAI_IN  -> g  = in ^ (in >> 1)            (branchless)
            stage-1 latch        : SYNC1 <= g     (gated dff on MAC edge)
            stage-2 latch        : SYNC2 <= SYNC1 (gated dff on MAC edge)
            gray-decode SYNC2    -> TAI_MAC (XOR fold; generator-unrolled,
                                   pure XOR/shift — no native +/-/*).
  WRITE   : commit SYNC1, SYNC2, TAI_MAC.

Gray encode/decode are bitwise (XOR/shift) only — they are NOT arithmetic, so
gate stage 2b (no native +/-/*) passes. The decode fold is generator-level
straight-line composition (like the adapter's cmp_le), not a data-path branch.
"""
import json
import sys


def emit_gray_decode():
    """Emit gray_decode(g) -> binary, built from XOR + shift only (no +/-/*).

    Parallel-prefix XOR fold: b = g; b ^= b>>1; b ^= b>>2; ... b ^= b>>32.
    For a 64-bit word the fold is the 6 power-of-two shift stages. This is
    generator-emitted straight-line cell composition (cell_xor), not a branch.
    """
    return """
/* gray_decode: gray-coded word -> binary. Parallel-prefix XOR fold (XOR + shift
 * only; no arithmetic operator). b ^= b>>k for k = 1,2,4,8,16,32 covers all 64
 * bits. Pure combinational gate netlist — the MSB passes through, each lower bit
 * is the running XOR of all higher gray bits. */
static inline word_t gray_decode(word_t g) {
    word_t b = g;
    b = cell_xor(b, b >> 1);
    b = cell_xor(b, b >> 2);
    b = cell_xor(b, b >> 4);
    b = cell_xor(b, b >> 8);
    b = cell_xor(b, b >> 16);
    b = cell_xor(b, b >> 32);
    return b;
}
"""


def main():
    net_path = sys.argv[1] if len(sys.argv) > 1 else "tai_cdc.net.json"
    with open(net_path) as f:
        net = json.load(f)

    dev = net["device"]              # "tai_cdc"
    DEV = dev.upper()                # "TAI_CDC"
    pfx = DEV                        # register prefix

    order = []
    for grp in ("config_nodes", "dff_nodes", "comb_nodes"):
        for n in net.get(grp, []):
            order.append(n["name"])
    addr = {nm: i for i, nm in enumerate(order)}
    count = len(order)

    config = [n["name"] for n in net.get("config_nodes", [])]
    src = net["source"]             # the TAI_IN input lane
    power = net["power"]            # the CDC enable / power bit
    enc = net["encode"]            # {"in": TAI_IN, "out": TAI_GRAY}
    s1 = net["sync1"]              # {"reg": ..., "from": TAI_GRAY}
    s2 = net["sync2"]              # {"reg": ..., "from": sync1}
    dec = net["decode"]            # {"in": sync2, "out": TAI_MAC}
    run = net["run"]               # {"power": ..., "count": <mac counter cfg>, "limit": ...}

    out = []
    out.append(f"/* GENERATED by gennet.py from {net_path} — DO NOT EDIT BY HAND.")
    out.append(" * tai_cdc: gray-code 2-FF synchronizer bringing the TAI value into the MAC")
    out.append(" * domain (Cummings). gray encode/decode are XOR/shift only; the two sync")
    out.append(" * stages are gated dffs latched on the MAC edge. No if/switch/?: ; no")
    out.append(" * native add/sub/mul in the data path. */")
    out.append(f"#ifndef {DEV}_GEN_H")
    out.append(f"#define {DEV}_GEN_H")
    out.append('#include "cells.h"')
    out.append("")
    out.append(f"#define {pfx}_REG_COUNT {count}u")
    for nm in order:
        out.append(f"#define {pfx}_{nm} {addr[nm]}u")
    out.append("")
    out.append(emit_gray_decode())
    out.append("")

    # ---- init: power-off synchronous reset value (everything zero). ----------
    out.append(f"static inline void {dev}_init(word_t *r) {{")
    out.append("    word_t i = 0ULL;")
    out.append(f"    for (i = 0ULL; i < {pfx}_REG_COUNT; i = i + 1ULL) {{ r[i] = 0ULL; }}")
    out.append("}")
    out.append("")

    # ---- one MAC clock edge: READ -> COMPUTE -> WRITE. -----------------------
    out.append(f"/* {dev}_tick: one MAC clock edge. READ the sampled TAI value + sync regs,")
    out.append(" * COMPUTE the gray encode / 2-FF sync / gray decode, WRITE the sync stages")
    out.append(" * and the decoded MAC-domain output. Write-only WRITE phase. */")
    out.append(f"static inline void {dev}_tick(word_t *r) {{")
    out.append("    /* READ phase — pre-read every operand from its register. */")
    out.append(f"    const word_t power     = r[{pfx}_{power}] & 1ULL;")
    out.append(f"    const word_t tai_in    = r[{pfx}_{src}];")
    out.append(f"    const word_t sync1_cur = r[{pfx}_{s1['reg']}];")
    out.append(f"    const word_t sync2_cur = r[{pfx}_{s2['reg']}];")
    out.append("")
    out.append("    /* COMPUTE phase — branchless. */")
    out.append("    /* gray encode: g = in ^ (in >> 1)  (XOR/shift only). */")
    out.append(f"    const word_t gray = cell_xor(tai_in, tai_in >> 1);")
    out.append("    /* 2-FF synchronizer: stage 1 latches the (async) gray word; stage 2")
    out.append("     * latches stage 1. Both are power-gated dffs on the MAC edge. */")
    out.append(f"    const word_t sync1_next = cell_dff(sync1_cur, gray,      power);")
    out.append(f"    const word_t sync2_next = cell_dff(sync2_cur, sync1_cur, power);")
    out.append("    /* gray decode the STABLE stage-2 word -> MAC-domain binary value. */")
    out.append(f"    const word_t mac_next = gray_decode(sync2_next);")
    out.append("")
    out.append("    /* WRITE phase — commit the registered hops + the decoded output. */")
    out.append(f"    r[{pfx}_{s1['reg']}]  = sync1_next;")
    out.append(f"    r[{pfx}_{s2['reg']}]  = sync2_next;")
    out.append(f"    r[{pfx}_{dec['out']}] = mac_next;")
    out.append("}")
    out.append("")

    # ---- emit cmp_lt for the bounded self-run, mirroring the counter family. -
    out.append("/* cmp_lt: gate-netlist comparator (a < b), carry chain over cell_fa. The")
    out.append(" * bounded self-run uses it on a configured tick budget (config, not steps). */")
    out.append("static inline word_t cmp_lt(word_t a, word_t b) {")
    out.append("    word_t carry = 1ULL;")
    out.append("    word_t i = 0ULL;")
    out.append("    for (i = 0ULL; i < 64ULL; i = i + 1ULL) {")
    out.append("        const word_t aa = (a >> i) & 1ULL;")
    out.append("        const word_t nb = (cell_not(b) >> i) & 1ULL;")
    out.append("        const word_t fa = cell_fa(aa, nb, carry);")
    out.append("        carry           = (fa >> 1) & 1ULL;")
    out.append("    }")
    out.append("    return (carry & 1ULL) ^ 1ULL;")
    out.append("}")
    out.append("")

    # ---- the self-run loop (MAC-edge clocked), bounded by a configured tick. --
    out.append(f"/* {dev}_run: the CDC self-runs on the MAC edge while powered, bounded by a")
    out.append(" * configured tick budget (RUN_UNTIL) — config, not external stepping. The")
    out.append(" * tick counter is the configured TICKS register the CDC increments itself. */")
    out.append(f"static inline void {dev}_run(word_t *r) {{")
    rc = run["count"]
    rl = run["limit"]
    out.append(f"    while ((r[{pfx}_{run['power']}] & 1ULL)")
    out.append(f"           && cmp_lt(r[{pfx}_{rc}], r[{pfx}_{rl}])) {{")
    out.append(f"        {dev}_tick(r);")
    out.append(f"        r[{pfx}_{rc}] = cell_addsub(r[{pfx}_{rc}], 1ULL, 0ULL);")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append(f"#endif /* {DEV}_GEN_H */")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
