/* GENERATED by gennet.py from fpga/dsp48e2.net.json — DO NOT EDIT BY HAND.
 * The dsp48e2 device: register lanes + cell-based logic (READ->COMPUTE->WRITE).
 * Netlist-generated; every data operation is a structural cell call. */
#ifndef DSP48E2_GEN_H
#define DSP48E2_GEN_H
#include "cells.h"

#define DSP48E2_REG_COUNT 56u

#define DSP48E2_a1_d 0u
#define DSP48E2_a1_en 1u
#define DSP48E2_a2_d 2u
#define DSP48E2_a2_en 3u
#define DSP48E2_b1_d 4u
#define DSP48E2_b1_en 5u
#define DSP48E2_b2_d 6u
#define DSP48E2_b2_en 7u
#define DSP48E2_c_d 8u
#define DSP48E2_c_en 9u
#define DSP48E2_d_d 10u
#define DSP48E2_d_en 11u
#define DSP48E2_ad_d 12u
#define DSP48E2_ad_en 13u
#define DSP48E2_m_d 14u
#define DSP48E2_m_en 15u
#define DSP48E2_p_d 16u
#define DSP48E2_p_en 17u
#define DSP48E2_carryin_d 18u
#define DSP48E2_carryin_en 19u
#define DSP48E2_inmode_d 20u
#define DSP48E2_inmode_en 21u
#define DSP48E2_opmode_d 22u
#define DSP48E2_opmode_en 23u
#define DSP48E2_alumode_d 24u
#define DSP48E2_alumode_en 25u
#define DSP48E2_carryinsel_d 26u
#define DSP48E2_carryinsel_en 27u
#define DSP48E2_top_dsp_r_a1 28u
#define DSP48E2_top_dsp_r_a2 29u
#define DSP48E2_top_dsp_r_b1 30u
#define DSP48E2_top_dsp_r_b2 31u
#define DSP48E2_top_dsp_r_c 32u
#define DSP48E2_top_dsp_r_d 33u
#define DSP48E2_top_dsp_r_ad 34u
#define DSP48E2_top_dsp_r_m 35u
#define DSP48E2_top_dsp_r_p 36u
#define DSP48E2_top_dsp_r_carryin 37u
#define DSP48E2_top_dsp_r_inmode 38u
#define DSP48E2_top_dsp_r_opmode 39u
#define DSP48E2_top_dsp_r_alumode 40u
#define DSP48E2_top_dsp_r_carryinsel 41u
#define DSP48E2_OUT_a1_q 42u
#define DSP48E2_OUT_a2_q 43u
#define DSP48E2_OUT_b1_q 44u
#define DSP48E2_OUT_b2_q 45u
#define DSP48E2_OUT_c_q 46u
#define DSP48E2_OUT_d_q 47u
#define DSP48E2_OUT_ad_q 48u
#define DSP48E2_OUT_m_q 49u
#define DSP48E2_OUT_p_q 50u
#define DSP48E2_OUT_carryin_q 51u
#define DSP48E2_OUT_inmode_q 52u
#define DSP48E2_OUT_opmode_q 53u
#define DSP48E2_OUT_alumode_q 54u
#define DSP48E2_OUT_carryinsel_q 55u

static inline void dsp48e2_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < DSP48E2_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
}

/* dsp48e2_tick: one clock edge. READ inputs as const locals,
 * COMPUTE via cells (no native add/sub/mul on data), WRITE every register. */
static inline void dsp48e2_tick(word_t *r) {
    /* READ phase — pre-read every consumed register value. */
    const word_t a1_d = r[DSP48E2_a1_d];
    const word_t a1_en = r[DSP48E2_a1_en];
    const word_t a2_d = r[DSP48E2_a2_d];
    const word_t a2_en = r[DSP48E2_a2_en];
    const word_t b1_d = r[DSP48E2_b1_d];
    const word_t b1_en = r[DSP48E2_b1_en];
    const word_t b2_d = r[DSP48E2_b2_d];
    const word_t b2_en = r[DSP48E2_b2_en];
    const word_t c_d = r[DSP48E2_c_d];
    const word_t c_en = r[DSP48E2_c_en];
    const word_t d_d = r[DSP48E2_d_d];
    const word_t d_en = r[DSP48E2_d_en];
    const word_t ad_d = r[DSP48E2_ad_d];
    const word_t ad_en = r[DSP48E2_ad_en];
    const word_t m_d = r[DSP48E2_m_d];
    const word_t m_en = r[DSP48E2_m_en];
    const word_t p_d = r[DSP48E2_p_d];
    const word_t p_en = r[DSP48E2_p_en];
    const word_t carryin_d = r[DSP48E2_carryin_d];
    const word_t carryin_en = r[DSP48E2_carryin_en];
    const word_t inmode_d = r[DSP48E2_inmode_d];
    const word_t inmode_en = r[DSP48E2_inmode_en];
    const word_t opmode_d = r[DSP48E2_opmode_d];
    const word_t opmode_en = r[DSP48E2_opmode_en];
    const word_t alumode_d = r[DSP48E2_alumode_d];
    const word_t alumode_en = r[DSP48E2_alumode_en];
    const word_t carryinsel_d = r[DSP48E2_carryinsel_d];
    const word_t carryinsel_en = r[DSP48E2_carryinsel_en];
    const word_t top_dsp_r_a1 = r[DSP48E2_top_dsp_r_a1];
    const word_t top_dsp_r_a2 = r[DSP48E2_top_dsp_r_a2];
    const word_t top_dsp_r_b1 = r[DSP48E2_top_dsp_r_b1];
    const word_t top_dsp_r_b2 = r[DSP48E2_top_dsp_r_b2];
    const word_t top_dsp_r_c = r[DSP48E2_top_dsp_r_c];
    const word_t top_dsp_r_d = r[DSP48E2_top_dsp_r_d];
    const word_t top_dsp_r_ad = r[DSP48E2_top_dsp_r_ad];
    const word_t top_dsp_r_m = r[DSP48E2_top_dsp_r_m];
    const word_t top_dsp_r_p = r[DSP48E2_top_dsp_r_p];
    const word_t top_dsp_r_carryin = r[DSP48E2_top_dsp_r_carryin];
    const word_t top_dsp_r_inmode = r[DSP48E2_top_dsp_r_inmode];
    const word_t top_dsp_r_opmode = r[DSP48E2_top_dsp_r_opmode];
    const word_t top_dsp_r_alumode = r[DSP48E2_top_dsp_r_alumode];
    const word_t top_dsp_r_carryinsel = r[DSP48E2_top_dsp_r_carryinsel];

    /* COMPUTE phase — combinational cell chain (declaration order). */

    /* WRITE phase — gated dff commit: r[X] = cell_dff(q, fed_by, enable). */
    r[DSP48E2_top_dsp_r_a1] = cell_dff(top_dsp_r_a1, a1_d, a1_en);
    r[DSP48E2_top_dsp_r_a2] = cell_dff(top_dsp_r_a2, a2_d, a2_en);
    r[DSP48E2_top_dsp_r_b1] = cell_dff(top_dsp_r_b1, b1_d, b1_en);
    r[DSP48E2_top_dsp_r_b2] = cell_dff(top_dsp_r_b2, b2_d, b2_en);
    r[DSP48E2_top_dsp_r_c] = cell_dff(top_dsp_r_c, c_d, c_en);
    r[DSP48E2_top_dsp_r_d] = cell_dff(top_dsp_r_d, d_d, d_en);
    r[DSP48E2_top_dsp_r_ad] = cell_dff(top_dsp_r_ad, ad_d, ad_en);
    r[DSP48E2_top_dsp_r_m] = cell_dff(top_dsp_r_m, m_d, m_en);
    r[DSP48E2_top_dsp_r_p] = cell_dff(top_dsp_r_p, p_d, p_en);
    r[DSP48E2_top_dsp_r_carryin] = cell_dff(top_dsp_r_carryin, carryin_d, carryin_en);
    r[DSP48E2_top_dsp_r_inmode] = cell_dff(top_dsp_r_inmode, inmode_d, inmode_en);
    r[DSP48E2_top_dsp_r_opmode] = cell_dff(top_dsp_r_opmode, opmode_d, opmode_en);
    r[DSP48E2_top_dsp_r_alumode] = cell_dff(top_dsp_r_alumode, alumode_d, alumode_en);
    r[DSP48E2_top_dsp_r_carryinsel] = cell_dff(top_dsp_r_carryinsel, carryinsel_d, carryinsel_en);
    r[DSP48E2_OUT_a1_q] = top_dsp_r_a1;
    r[DSP48E2_OUT_a2_q] = top_dsp_r_a2;
    r[DSP48E2_OUT_b1_q] = top_dsp_r_b1;
    r[DSP48E2_OUT_b2_q] = top_dsp_r_b2;
    r[DSP48E2_OUT_c_q] = top_dsp_r_c;
    r[DSP48E2_OUT_d_q] = top_dsp_r_d;
    r[DSP48E2_OUT_ad_q] = top_dsp_r_ad;
    r[DSP48E2_OUT_m_q] = top_dsp_r_m;
    r[DSP48E2_OUT_p_q] = top_dsp_r_p;
    r[DSP48E2_OUT_carryin_q] = top_dsp_r_carryin;
    r[DSP48E2_OUT_inmode_q] = top_dsp_r_inmode;
    r[DSP48E2_OUT_opmode_q] = top_dsp_r_opmode;
    r[DSP48E2_OUT_alumode_q] = top_dsp_r_alumode;
    r[DSP48E2_OUT_carryinsel_q] = top_dsp_r_carryinsel;

}

/* dsp48e2_run: canonical free-running clock. Power on once; the clock
 * self-oscillates while the power bit is set. Nothing external steps it. */
static inline void dsp48e2_run(word_t *r) {
    dsp48e2_tick(r);
}

#endif /* DSP48E2_GEN_H */
