/* GENERATED by gen_fpga_device.py — THE FPGA hardware device: every tile
 * type unified into one device (flip-flop tiles as register-bank arrays,
 * conductor tiles as lane banks). Counts authentic; nothing hardcoded. */
#ifndef FPGA_BBHFT_DEVICE_H
#define FPGA_BBHFT_DEVICE_H
#include "clb_slice_gen.h"
#include "dsp48e2_gen.h"
#include "bram_block_gen.h"
#include "uram_block_gen.h"
#include "mmcm_gen.h"
#include "pll_gen.h"
#include "int_tile_gen.h"
#include "gty_gen.h"
#include <stdint.h>
#include <stdio.h>
static uint8_t fpga_master_power;
#define FPGA_CLB_COUNT 147750u
#define FPGA_CLB_FF 16u
#define FPGA_CLB_LUT 8u
static word_t fpga_clb[FPGA_CLB_COUNT][CLB_SLICE_REG_COUNT];
#define FPGA_DSP_COUNT 6840u
#define FPGA_DSP_FF 14u
#define FPGA_DSP_LUT 0u
static word_t fpga_dsp[FPGA_DSP_COUNT][DSP48E2_REG_COUNT];
#define FPGA_BRAM_COUNT 2160u
#define FPGA_BRAM_FF 576u
#define FPGA_BRAM_LUT 0u
static word_t fpga_bram[FPGA_BRAM_COUNT][BRAM_BLOCK_REG_COUNT];
#define FPGA_URAM_COUNT 960u
#define FPGA_URAM_FF 4608u
#define FPGA_URAM_LUT 0u
static word_t fpga_uram[FPGA_URAM_COUNT][URAM_BLOCK_REG_COUNT];
#define FPGA_MMCM_COUNT 30u
#define FPGA_MMCM_FF 15u
#define FPGA_MMCM_LUT 0u
static word_t fpga_mmcm[FPGA_MMCM_COUNT][MMCM_REG_COUNT];
#define FPGA_PLL_COUNT 60u
#define FPGA_PLL_FF 9u
#define FPGA_PLL_LUT 0u
static word_t fpga_pll[FPGA_PLL_COUNT][PLL_REG_COUNT];
#define FPGA_INT_COUNT 256u
#define FPGA_INT_FF 64u
#define FPGA_INT_LUT 0u
static word_t fpga_int[FPGA_INT_COUNT][INT_TILE_REG_COUNT];
static gty_word_t fpga_gty_lanes[GTY_REG_COUNT];
static inline void fpga_device_init(void){
  fpga_master_power = 0u;
  for (unsigned i=0;i<FPGA_CLB_COUNT;i++) clb_slice_init(fpga_clb[i]);
  for (unsigned i=0;i<FPGA_DSP_COUNT;i++) dsp48e2_init(fpga_dsp[i]);
  for (unsigned i=0;i<FPGA_BRAM_COUNT;i++) bram_block_init(fpga_bram[i]);
  for (unsigned i=0;i<FPGA_URAM_COUNT;i++) uram_block_init(fpga_uram[i]);
  for (unsigned i=0;i<FPGA_MMCM_COUNT;i++) mmcm_init(fpga_mmcm[i]);
  for (unsigned i=0;i<FPGA_PLL_COUNT;i++) pll_init(fpga_pll[i]);
  for (unsigned i=0;i<FPGA_INT_COUNT;i++) int_tile_init(fpga_int[i]);
  for (unsigned i=0;i<GTY_REG_COUNT;i++) fpga_gty_lanes[i]=0u;
}
static inline void fpga_device_power_on(void){ fpga_master_power=1u; }
static inline void fpga_device_power_off(void){ fpga_master_power=0u; }
static inline void fpga_device_tick(void){
  if (!fpga_master_power) return;
  for (unsigned i=0;i<FPGA_CLB_COUNT;i++) clb_slice_tick(fpga_clb[i]);
  for (unsigned i=0;i<FPGA_DSP_COUNT;i++) dsp48e2_tick(fpga_dsp[i]);
  for (unsigned i=0;i<FPGA_BRAM_COUNT;i++) bram_block_tick(fpga_bram[i]);
  for (unsigned i=0;i<FPGA_URAM_COUNT;i++) uram_block_tick(fpga_uram[i]);
  for (unsigned i=0;i<FPGA_MMCM_COUNT;i++) mmcm_tick(fpga_mmcm[i]);
  for (unsigned i=0;i<FPGA_PLL_COUNT;i++) pll_tick(fpga_pll[i]);
  for (unsigned i=0;i<FPGA_INT_COUNT;i++) int_tile_tick(fpga_int[i]);
}
static inline unsigned long fpga_device_flipflops(void){ return (unsigned long)FPGA_CLB_COUNT*FPGA_CLB_FF + (unsigned long)FPGA_DSP_COUNT*FPGA_DSP_FF + (unsigned long)FPGA_BRAM_COUNT*FPGA_BRAM_FF + (unsigned long)FPGA_URAM_COUNT*FPGA_URAM_FF + (unsigned long)FPGA_MMCM_COUNT*FPGA_MMCM_FF + (unsigned long)FPGA_PLL_COUNT*FPGA_PLL_FF + (unsigned long)FPGA_INT_COUNT*FPGA_INT_FF; }
static inline unsigned long fpga_device_luts(void){ return (unsigned long)FPGA_CLB_COUNT*FPGA_CLB_LUT + (unsigned long)FPGA_DSP_COUNT*FPGA_DSP_LUT + (unsigned long)FPGA_BRAM_COUNT*FPGA_BRAM_LUT + (unsigned long)FPGA_URAM_COUNT*FPGA_URAM_LUT + (unsigned long)FPGA_MMCM_COUNT*FPGA_MMCM_LUT + (unsigned long)FPGA_PLL_COUNT*FPGA_PLL_LUT + (unsigned long)FPGA_INT_COUNT*FPGA_INT_LUT; }
static inline void fpga_device_display(void){
  printf("FPGA %s device (power=%u): %lu real flip-flops, %lu LUTs\n", "bbhft", fpga_master_power, fpga_device_flipflops(), fpga_device_luts());
  printf("  CLB  x%-8u  %u FF/tile  = %lu flip-flops\n", FPGA_CLB_COUNT, FPGA_CLB_FF, (unsigned long)FPGA_CLB_COUNT*FPGA_CLB_FF);
  printf("  DSP  x%-8u  %u FF/tile  = %lu flip-flops\n", FPGA_DSP_COUNT, FPGA_DSP_FF, (unsigned long)FPGA_DSP_COUNT*FPGA_DSP_FF);
  printf("  BRAM x%-8u  %u FF/tile  = %lu flip-flops\n", FPGA_BRAM_COUNT, FPGA_BRAM_FF, (unsigned long)FPGA_BRAM_COUNT*FPGA_BRAM_FF);
  printf("  URAM x%-8u  %u FF/tile  = %lu flip-flops\n", FPGA_URAM_COUNT, FPGA_URAM_FF, (unsigned long)FPGA_URAM_COUNT*FPGA_URAM_FF);
  printf("  MMCM x%-8u  %u FF/tile  = %lu flip-flops\n", FPGA_MMCM_COUNT, FPGA_MMCM_FF, (unsigned long)FPGA_MMCM_COUNT*FPGA_MMCM_FF);
  printf("  PLL  x%-8u  %u FF/tile  = %lu flip-flops\n", FPGA_PLL_COUNT, FPGA_PLL_FF, (unsigned long)FPGA_PLL_COUNT*FPGA_PLL_FF);
  printf("  INT  x%-8u  %u FF/tile  = %lu flip-flops\n", FPGA_INT_COUNT, FPGA_INT_FF, (unsigned long)FPGA_INT_COUNT*FPGA_INT_FF);
  printf("  GTY  %u conductor lanes (passive)\n", GTY_REG_COUNT);
}
#endif
