/* GENERATED by gennet.py from fpga/gty.net.json — DO NOT EDIT BY HAND.
 * gty: passive lock-free BARRIER bus — addressed lanes only, no clock,
 * no compute, no latch. Producer DEPOSITS (sole writer); consumers SAMPLE.
 * A module never reads another's registers directly; this bus is the medium. */
#ifndef GTY_GEN_H
#define GTY_GEN_H
#include <stdint.h>

typedef uint64_t gty_word_t;
#define GTY_REG_COUNT 120u
#define GTY_GTY_LANE_0 0u
#define GTY_GTY_LANE_1 1u
#define GTY_GTY_LANE_2 2u
#define GTY_GTY_LANE_3 3u
#define GTY_GTY_LANE_4 4u
#define GTY_GTY_LANE_5 5u
#define GTY_GTY_LANE_6 6u
#define GTY_GTY_LANE_7 7u
#define GTY_GTY_LANE_8 8u
#define GTY_GTY_LANE_9 9u
#define GTY_GTY_LANE_10 10u
#define GTY_GTY_LANE_11 11u
#define GTY_GTY_LANE_12 12u
#define GTY_GTY_LANE_13 13u
#define GTY_GTY_LANE_14 14u
#define GTY_GTY_LANE_15 15u
#define GTY_GTY_LANE_16 16u
#define GTY_GTY_LANE_17 17u
#define GTY_GTY_LANE_18 18u
#define GTY_GTY_LANE_19 19u
#define GTY_GTY_LANE_20 20u
#define GTY_GTY_LANE_21 21u
#define GTY_GTY_LANE_22 22u
#define GTY_GTY_LANE_23 23u
#define GTY_GTY_LANE_24 24u
#define GTY_GTY_LANE_25 25u
#define GTY_GTY_LANE_26 26u
#define GTY_GTY_LANE_27 27u
#define GTY_GTY_LANE_28 28u
#define GTY_GTY_LANE_29 29u
#define GTY_GTY_LANE_30 30u
#define GTY_GTY_LANE_31 31u
#define GTY_GTY_LANE_32 32u
#define GTY_GTY_LANE_33 33u
#define GTY_GTY_LANE_34 34u
#define GTY_GTY_LANE_35 35u
#define GTY_GTY_LANE_36 36u
#define GTY_GTY_LANE_37 37u
#define GTY_GTY_LANE_38 38u
#define GTY_GTY_LANE_39 39u
#define GTY_GTY_LANE_40 40u
#define GTY_GTY_LANE_41 41u
#define GTY_GTY_LANE_42 42u
#define GTY_GTY_LANE_43 43u
#define GTY_GTY_LANE_44 44u
#define GTY_GTY_LANE_45 45u
#define GTY_GTY_LANE_46 46u
#define GTY_GTY_LANE_47 47u
#define GTY_GTY_LANE_48 48u
#define GTY_GTY_LANE_49 49u
#define GTY_GTY_LANE_50 50u
#define GTY_GTY_LANE_51 51u
#define GTY_GTY_LANE_52 52u
#define GTY_GTY_LANE_53 53u
#define GTY_GTY_LANE_54 54u
#define GTY_GTY_LANE_55 55u
#define GTY_GTY_LANE_56 56u
#define GTY_GTY_LANE_57 57u
#define GTY_GTY_LANE_58 58u
#define GTY_GTY_LANE_59 59u
#define GTY_GTY_LANE_60 60u
#define GTY_GTY_LANE_61 61u
#define GTY_GTY_LANE_62 62u
#define GTY_GTY_LANE_63 63u
#define GTY_GTY_LANE_64 64u
#define GTY_GTY_LANE_65 65u
#define GTY_GTY_LANE_66 66u
#define GTY_GTY_LANE_67 67u
#define GTY_GTY_LANE_68 68u
#define GTY_GTY_LANE_69 69u
#define GTY_GTY_LANE_70 70u
#define GTY_GTY_LANE_71 71u
#define GTY_GTY_LANE_72 72u
#define GTY_GTY_LANE_73 73u
#define GTY_GTY_LANE_74 74u
#define GTY_GTY_LANE_75 75u
#define GTY_GTY_LANE_76 76u
#define GTY_GTY_LANE_77 77u
#define GTY_GTY_LANE_78 78u
#define GTY_GTY_LANE_79 79u
#define GTY_GTY_LANE_80 80u
#define GTY_GTY_LANE_81 81u
#define GTY_GTY_LANE_82 82u
#define GTY_GTY_LANE_83 83u
#define GTY_GTY_LANE_84 84u
#define GTY_GTY_LANE_85 85u
#define GTY_GTY_LANE_86 86u
#define GTY_GTY_LANE_87 87u
#define GTY_GTY_LANE_88 88u
#define GTY_GTY_LANE_89 89u
#define GTY_GTY_LANE_90 90u
#define GTY_GTY_LANE_91 91u
#define GTY_GTY_LANE_92 92u
#define GTY_GTY_LANE_93 93u
#define GTY_GTY_LANE_94 94u
#define GTY_GTY_LANE_95 95u
#define GTY_GTY_LANE_96 96u
#define GTY_GTY_LANE_97 97u
#define GTY_GTY_LANE_98 98u
#define GTY_GTY_LANE_99 99u
#define GTY_GTY_LANE_100 100u
#define GTY_GTY_LANE_101 101u
#define GTY_GTY_LANE_102 102u
#define GTY_GTY_LANE_103 103u
#define GTY_GTY_LANE_104 104u
#define GTY_GTY_LANE_105 105u
#define GTY_GTY_LANE_106 106u
#define GTY_GTY_LANE_107 107u
#define GTY_GTY_LANE_108 108u
#define GTY_GTY_LANE_109 109u
#define GTY_GTY_LANE_110 110u
#define GTY_GTY_LANE_111 111u
#define GTY_GTY_LANE_112 112u
#define GTY_GTY_LANE_113 113u
#define GTY_GTY_LANE_114 114u
#define GTY_GTY_LANE_115 115u
#define GTY_GTY_LANE_116 116u
#define GTY_GTY_LANE_117 117u
#define GTY_GTY_LANE_118 118u
#define GTY_GTY_LANE_119 119u

/* gty_init: zero the passive bus (power-off reset). No clock runs here. */
static inline void gty_init(gty_word_t *b) {
    gty_word_t i = 0ULL;
    for (i = 0ULL; i < GTY_REG_COUNT; i = i + 1ULL) { b[i] = 0ULL; }
}

#endif /* GTY_GEN_H */
