/* GENERATED by gennet.py from interconnect/int_tile.net.json — DO NOT EDIT BY HAND.
 * The int_tile device: register lanes + cell-based logic (READ->COMPUTE->WRITE).
 * Netlist-generated; every data operation is a structural cell call. */
#ifndef INT_TILE_GEN_H
#define INT_TILE_GEN_H
#include "cells.h"

#define INT_TILE_REG_COUNT 265u

#define INT_TILE_IN_0 0u
#define INT_TILE_IN_1 1u
#define INT_TILE_IN_2 2u
#define INT_TILE_IN_3 3u
#define INT_TILE_IN_4 4u
#define INT_TILE_IN_5 5u
#define INT_TILE_IN_6 6u
#define INT_TILE_IN_7 7u
#define INT_TILE_CFG_0_0_D 8u
#define INT_TILE_CFG_0_1_D 9u
#define INT_TILE_CFG_0_2_D 10u
#define INT_TILE_CFG_0_3_D 11u
#define INT_TILE_CFG_0_4_D 12u
#define INT_TILE_CFG_0_5_D 13u
#define INT_TILE_CFG_0_6_D 14u
#define INT_TILE_CFG_0_7_D 15u
#define INT_TILE_CFG_1_0_D 16u
#define INT_TILE_CFG_1_1_D 17u
#define INT_TILE_CFG_1_2_D 18u
#define INT_TILE_CFG_1_3_D 19u
#define INT_TILE_CFG_1_4_D 20u
#define INT_TILE_CFG_1_5_D 21u
#define INT_TILE_CFG_1_6_D 22u
#define INT_TILE_CFG_1_7_D 23u
#define INT_TILE_CFG_2_0_D 24u
#define INT_TILE_CFG_2_1_D 25u
#define INT_TILE_CFG_2_2_D 26u
#define INT_TILE_CFG_2_3_D 27u
#define INT_TILE_CFG_2_4_D 28u
#define INT_TILE_CFG_2_5_D 29u
#define INT_TILE_CFG_2_6_D 30u
#define INT_TILE_CFG_2_7_D 31u
#define INT_TILE_CFG_3_0_D 32u
#define INT_TILE_CFG_3_1_D 33u
#define INT_TILE_CFG_3_2_D 34u
#define INT_TILE_CFG_3_3_D 35u
#define INT_TILE_CFG_3_4_D 36u
#define INT_TILE_CFG_3_5_D 37u
#define INT_TILE_CFG_3_6_D 38u
#define INT_TILE_CFG_3_7_D 39u
#define INT_TILE_CFG_4_0_D 40u
#define INT_TILE_CFG_4_1_D 41u
#define INT_TILE_CFG_4_2_D 42u
#define INT_TILE_CFG_4_3_D 43u
#define INT_TILE_CFG_4_4_D 44u
#define INT_TILE_CFG_4_5_D 45u
#define INT_TILE_CFG_4_6_D 46u
#define INT_TILE_CFG_4_7_D 47u
#define INT_TILE_CFG_5_0_D 48u
#define INT_TILE_CFG_5_1_D 49u
#define INT_TILE_CFG_5_2_D 50u
#define INT_TILE_CFG_5_3_D 51u
#define INT_TILE_CFG_5_4_D 52u
#define INT_TILE_CFG_5_5_D 53u
#define INT_TILE_CFG_5_6_D 54u
#define INT_TILE_CFG_5_7_D 55u
#define INT_TILE_CFG_6_0_D 56u
#define INT_TILE_CFG_6_1_D 57u
#define INT_TILE_CFG_6_2_D 58u
#define INT_TILE_CFG_6_3_D 59u
#define INT_TILE_CFG_6_4_D 60u
#define INT_TILE_CFG_6_5_D 61u
#define INT_TILE_CFG_6_6_D 62u
#define INT_TILE_CFG_6_7_D 63u
#define INT_TILE_CFG_7_0_D 64u
#define INT_TILE_CFG_7_1_D 65u
#define INT_TILE_CFG_7_2_D 66u
#define INT_TILE_CFG_7_3_D 67u
#define INT_TILE_CFG_7_4_D 68u
#define INT_TILE_CFG_7_5_D 69u
#define INT_TILE_CFG_7_6_D 70u
#define INT_TILE_CFG_7_7_D 71u
#define INT_TILE_CFG_EN 72u
#define INT_TILE_PIP_0_0 73u
#define INT_TILE_PIP_0_1 74u
#define INT_TILE_PIP_0_2 75u
#define INT_TILE_PIP_0_3 76u
#define INT_TILE_PIP_0_4 77u
#define INT_TILE_PIP_0_5 78u
#define INT_TILE_PIP_0_6 79u
#define INT_TILE_PIP_0_7 80u
#define INT_TILE_PIP_1_0 81u
#define INT_TILE_PIP_1_1 82u
#define INT_TILE_PIP_1_2 83u
#define INT_TILE_PIP_1_3 84u
#define INT_TILE_PIP_1_4 85u
#define INT_TILE_PIP_1_5 86u
#define INT_TILE_PIP_1_6 87u
#define INT_TILE_PIP_1_7 88u
#define INT_TILE_PIP_2_0 89u
#define INT_TILE_PIP_2_1 90u
#define INT_TILE_PIP_2_2 91u
#define INT_TILE_PIP_2_3 92u
#define INT_TILE_PIP_2_4 93u
#define INT_TILE_PIP_2_5 94u
#define INT_TILE_PIP_2_6 95u
#define INT_TILE_PIP_2_7 96u
#define INT_TILE_PIP_3_0 97u
#define INT_TILE_PIP_3_1 98u
#define INT_TILE_PIP_3_2 99u
#define INT_TILE_PIP_3_3 100u
#define INT_TILE_PIP_3_4 101u
#define INT_TILE_PIP_3_5 102u
#define INT_TILE_PIP_3_6 103u
#define INT_TILE_PIP_3_7 104u
#define INT_TILE_PIP_4_0 105u
#define INT_TILE_PIP_4_1 106u
#define INT_TILE_PIP_4_2 107u
#define INT_TILE_PIP_4_3 108u
#define INT_TILE_PIP_4_4 109u
#define INT_TILE_PIP_4_5 110u
#define INT_TILE_PIP_4_6 111u
#define INT_TILE_PIP_4_7 112u
#define INT_TILE_PIP_5_0 113u
#define INT_TILE_PIP_5_1 114u
#define INT_TILE_PIP_5_2 115u
#define INT_TILE_PIP_5_3 116u
#define INT_TILE_PIP_5_4 117u
#define INT_TILE_PIP_5_5 118u
#define INT_TILE_PIP_5_6 119u
#define INT_TILE_PIP_5_7 120u
#define INT_TILE_PIP_6_0 121u
#define INT_TILE_PIP_6_1 122u
#define INT_TILE_PIP_6_2 123u
#define INT_TILE_PIP_6_3 124u
#define INT_TILE_PIP_6_4 125u
#define INT_TILE_PIP_6_5 126u
#define INT_TILE_PIP_6_6 127u
#define INT_TILE_PIP_6_7 128u
#define INT_TILE_PIP_7_0 129u
#define INT_TILE_PIP_7_1 130u
#define INT_TILE_PIP_7_2 131u
#define INT_TILE_PIP_7_3 132u
#define INT_TILE_PIP_7_4 133u
#define INT_TILE_PIP_7_5 134u
#define INT_TILE_PIP_7_6 135u
#define INT_TILE_PIP_7_7 136u
#define INT_TILE_G_0_0 137u
#define INT_TILE_G_0_1 138u
#define INT_TILE_G_0_2 139u
#define INT_TILE_G_0_3 140u
#define INT_TILE_G_0_4 141u
#define INT_TILE_G_0_5 142u
#define INT_TILE_G_0_6 143u
#define INT_TILE_G_0_7 144u
#define INT_TILE_G_1_0 145u
#define INT_TILE_G_1_1 146u
#define INT_TILE_G_1_2 147u
#define INT_TILE_G_1_3 148u
#define INT_TILE_G_1_4 149u
#define INT_TILE_G_1_5 150u
#define INT_TILE_G_1_6 151u
#define INT_TILE_G_1_7 152u
#define INT_TILE_G_2_0 153u
#define INT_TILE_G_2_1 154u
#define INT_TILE_G_2_2 155u
#define INT_TILE_G_2_3 156u
#define INT_TILE_G_2_4 157u
#define INT_TILE_G_2_5 158u
#define INT_TILE_G_2_6 159u
#define INT_TILE_G_2_7 160u
#define INT_TILE_G_3_0 161u
#define INT_TILE_G_3_1 162u
#define INT_TILE_G_3_2 163u
#define INT_TILE_G_3_3 164u
#define INT_TILE_G_3_4 165u
#define INT_TILE_G_3_5 166u
#define INT_TILE_G_3_6 167u
#define INT_TILE_G_3_7 168u
#define INT_TILE_G_4_0 169u
#define INT_TILE_G_4_1 170u
#define INT_TILE_G_4_2 171u
#define INT_TILE_G_4_3 172u
#define INT_TILE_G_4_4 173u
#define INT_TILE_G_4_5 174u
#define INT_TILE_G_4_6 175u
#define INT_TILE_G_4_7 176u
#define INT_TILE_G_5_0 177u
#define INT_TILE_G_5_1 178u
#define INT_TILE_G_5_2 179u
#define INT_TILE_G_5_3 180u
#define INT_TILE_G_5_4 181u
#define INT_TILE_G_5_5 182u
#define INT_TILE_G_5_6 183u
#define INT_TILE_G_5_7 184u
#define INT_TILE_G_6_0 185u
#define INT_TILE_G_6_1 186u
#define INT_TILE_G_6_2 187u
#define INT_TILE_G_6_3 188u
#define INT_TILE_G_6_4 189u
#define INT_TILE_G_6_5 190u
#define INT_TILE_G_6_6 191u
#define INT_TILE_G_6_7 192u
#define INT_TILE_G_7_0 193u
#define INT_TILE_G_7_1 194u
#define INT_TILE_G_7_2 195u
#define INT_TILE_G_7_3 196u
#define INT_TILE_G_7_4 197u
#define INT_TILE_G_7_5 198u
#define INT_TILE_G_7_6 199u
#define INT_TILE_G_7_7 200u
#define INT_TILE_ACC_0_1 201u
#define INT_TILE_ACC_0_2 202u
#define INT_TILE_ACC_0_3 203u
#define INT_TILE_ACC_0_4 204u
#define INT_TILE_ACC_0_5 205u
#define INT_TILE_ACC_0_6 206u
#define INT_TILE_OUT_0_C 207u
#define INT_TILE_ACC_1_1 208u
#define INT_TILE_ACC_1_2 209u
#define INT_TILE_ACC_1_3 210u
#define INT_TILE_ACC_1_4 211u
#define INT_TILE_ACC_1_5 212u
#define INT_TILE_ACC_1_6 213u
#define INT_TILE_OUT_1_C 214u
#define INT_TILE_ACC_2_1 215u
#define INT_TILE_ACC_2_2 216u
#define INT_TILE_ACC_2_3 217u
#define INT_TILE_ACC_2_4 218u
#define INT_TILE_ACC_2_5 219u
#define INT_TILE_ACC_2_6 220u
#define INT_TILE_OUT_2_C 221u
#define INT_TILE_ACC_3_1 222u
#define INT_TILE_ACC_3_2 223u
#define INT_TILE_ACC_3_3 224u
#define INT_TILE_ACC_3_4 225u
#define INT_TILE_ACC_3_5 226u
#define INT_TILE_ACC_3_6 227u
#define INT_TILE_OUT_3_C 228u
#define INT_TILE_ACC_4_1 229u
#define INT_TILE_ACC_4_2 230u
#define INT_TILE_ACC_4_3 231u
#define INT_TILE_ACC_4_4 232u
#define INT_TILE_ACC_4_5 233u
#define INT_TILE_ACC_4_6 234u
#define INT_TILE_OUT_4_C 235u
#define INT_TILE_ACC_5_1 236u
#define INT_TILE_ACC_5_2 237u
#define INT_TILE_ACC_5_3 238u
#define INT_TILE_ACC_5_4 239u
#define INT_TILE_ACC_5_5 240u
#define INT_TILE_ACC_5_6 241u
#define INT_TILE_OUT_5_C 242u
#define INT_TILE_ACC_6_1 243u
#define INT_TILE_ACC_6_2 244u
#define INT_TILE_ACC_6_3 245u
#define INT_TILE_ACC_6_4 246u
#define INT_TILE_ACC_6_5 247u
#define INT_TILE_ACC_6_6 248u
#define INT_TILE_OUT_6_C 249u
#define INT_TILE_ACC_7_1 250u
#define INT_TILE_ACC_7_2 251u
#define INT_TILE_ACC_7_3 252u
#define INT_TILE_ACC_7_4 253u
#define INT_TILE_ACC_7_5 254u
#define INT_TILE_ACC_7_6 255u
#define INT_TILE_OUT_7_C 256u
#define INT_TILE_OUT_0 257u
#define INT_TILE_OUT_1 258u
#define INT_TILE_OUT_2 259u
#define INT_TILE_OUT_3 260u
#define INT_TILE_OUT_4 261u
#define INT_TILE_OUT_5 262u
#define INT_TILE_OUT_6 263u
#define INT_TILE_OUT_7 264u

static inline void int_tile_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < INT_TILE_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
}

/* int_tile_tick: one clock edge. READ inputs as const locals,
 * COMPUTE via cells (no native add/sub/mul on data), WRITE every register. */
static inline void int_tile_tick(word_t *r) {
    /* READ phase — pre-read every consumed register value. */
    const word_t in_0 = r[INT_TILE_IN_0];
    const word_t in_1 = r[INT_TILE_IN_1];
    const word_t in_2 = r[INT_TILE_IN_2];
    const word_t in_3 = r[INT_TILE_IN_3];
    const word_t in_4 = r[INT_TILE_IN_4];
    const word_t in_5 = r[INT_TILE_IN_5];
    const word_t in_6 = r[INT_TILE_IN_6];
    const word_t in_7 = r[INT_TILE_IN_7];
    const word_t cfg_0_0_d = r[INT_TILE_CFG_0_0_D];
    const word_t cfg_0_1_d = r[INT_TILE_CFG_0_1_D];
    const word_t cfg_0_2_d = r[INT_TILE_CFG_0_2_D];
    const word_t cfg_0_3_d = r[INT_TILE_CFG_0_3_D];
    const word_t cfg_0_4_d = r[INT_TILE_CFG_0_4_D];
    const word_t cfg_0_5_d = r[INT_TILE_CFG_0_5_D];
    const word_t cfg_0_6_d = r[INT_TILE_CFG_0_6_D];
    const word_t cfg_0_7_d = r[INT_TILE_CFG_0_7_D];
    const word_t cfg_1_0_d = r[INT_TILE_CFG_1_0_D];
    const word_t cfg_1_1_d = r[INT_TILE_CFG_1_1_D];
    const word_t cfg_1_2_d = r[INT_TILE_CFG_1_2_D];
    const word_t cfg_1_3_d = r[INT_TILE_CFG_1_3_D];
    const word_t cfg_1_4_d = r[INT_TILE_CFG_1_4_D];
    const word_t cfg_1_5_d = r[INT_TILE_CFG_1_5_D];
    const word_t cfg_1_6_d = r[INT_TILE_CFG_1_6_D];
    const word_t cfg_1_7_d = r[INT_TILE_CFG_1_7_D];
    const word_t cfg_2_0_d = r[INT_TILE_CFG_2_0_D];
    const word_t cfg_2_1_d = r[INT_TILE_CFG_2_1_D];
    const word_t cfg_2_2_d = r[INT_TILE_CFG_2_2_D];
    const word_t cfg_2_3_d = r[INT_TILE_CFG_2_3_D];
    const word_t cfg_2_4_d = r[INT_TILE_CFG_2_4_D];
    const word_t cfg_2_5_d = r[INT_TILE_CFG_2_5_D];
    const word_t cfg_2_6_d = r[INT_TILE_CFG_2_6_D];
    const word_t cfg_2_7_d = r[INT_TILE_CFG_2_7_D];
    const word_t cfg_3_0_d = r[INT_TILE_CFG_3_0_D];
    const word_t cfg_3_1_d = r[INT_TILE_CFG_3_1_D];
    const word_t cfg_3_2_d = r[INT_TILE_CFG_3_2_D];
    const word_t cfg_3_3_d = r[INT_TILE_CFG_3_3_D];
    const word_t cfg_3_4_d = r[INT_TILE_CFG_3_4_D];
    const word_t cfg_3_5_d = r[INT_TILE_CFG_3_5_D];
    const word_t cfg_3_6_d = r[INT_TILE_CFG_3_6_D];
    const word_t cfg_3_7_d = r[INT_TILE_CFG_3_7_D];
    const word_t cfg_4_0_d = r[INT_TILE_CFG_4_0_D];
    const word_t cfg_4_1_d = r[INT_TILE_CFG_4_1_D];
    const word_t cfg_4_2_d = r[INT_TILE_CFG_4_2_D];
    const word_t cfg_4_3_d = r[INT_TILE_CFG_4_3_D];
    const word_t cfg_4_4_d = r[INT_TILE_CFG_4_4_D];
    const word_t cfg_4_5_d = r[INT_TILE_CFG_4_5_D];
    const word_t cfg_4_6_d = r[INT_TILE_CFG_4_6_D];
    const word_t cfg_4_7_d = r[INT_TILE_CFG_4_7_D];
    const word_t cfg_5_0_d = r[INT_TILE_CFG_5_0_D];
    const word_t cfg_5_1_d = r[INT_TILE_CFG_5_1_D];
    const word_t cfg_5_2_d = r[INT_TILE_CFG_5_2_D];
    const word_t cfg_5_3_d = r[INT_TILE_CFG_5_3_D];
    const word_t cfg_5_4_d = r[INT_TILE_CFG_5_4_D];
    const word_t cfg_5_5_d = r[INT_TILE_CFG_5_5_D];
    const word_t cfg_5_6_d = r[INT_TILE_CFG_5_6_D];
    const word_t cfg_5_7_d = r[INT_TILE_CFG_5_7_D];
    const word_t cfg_6_0_d = r[INT_TILE_CFG_6_0_D];
    const word_t cfg_6_1_d = r[INT_TILE_CFG_6_1_D];
    const word_t cfg_6_2_d = r[INT_TILE_CFG_6_2_D];
    const word_t cfg_6_3_d = r[INT_TILE_CFG_6_3_D];
    const word_t cfg_6_4_d = r[INT_TILE_CFG_6_4_D];
    const word_t cfg_6_5_d = r[INT_TILE_CFG_6_5_D];
    const word_t cfg_6_6_d = r[INT_TILE_CFG_6_6_D];
    const word_t cfg_6_7_d = r[INT_TILE_CFG_6_7_D];
    const word_t cfg_7_0_d = r[INT_TILE_CFG_7_0_D];
    const word_t cfg_7_1_d = r[INT_TILE_CFG_7_1_D];
    const word_t cfg_7_2_d = r[INT_TILE_CFG_7_2_D];
    const word_t cfg_7_3_d = r[INT_TILE_CFG_7_3_D];
    const word_t cfg_7_4_d = r[INT_TILE_CFG_7_4_D];
    const word_t cfg_7_5_d = r[INT_TILE_CFG_7_5_D];
    const word_t cfg_7_6_d = r[INT_TILE_CFG_7_6_D];
    const word_t cfg_7_7_d = r[INT_TILE_CFG_7_7_D];
    const word_t cfg_en = r[INT_TILE_CFG_EN];
    const word_t pip_0_0 = r[INT_TILE_PIP_0_0];
    const word_t pip_0_1 = r[INT_TILE_PIP_0_1];
    const word_t pip_0_2 = r[INT_TILE_PIP_0_2];
    const word_t pip_0_3 = r[INT_TILE_PIP_0_3];
    const word_t pip_0_4 = r[INT_TILE_PIP_0_4];
    const word_t pip_0_5 = r[INT_TILE_PIP_0_5];
    const word_t pip_0_6 = r[INT_TILE_PIP_0_6];
    const word_t pip_0_7 = r[INT_TILE_PIP_0_7];
    const word_t pip_1_0 = r[INT_TILE_PIP_1_0];
    const word_t pip_1_1 = r[INT_TILE_PIP_1_1];
    const word_t pip_1_2 = r[INT_TILE_PIP_1_2];
    const word_t pip_1_3 = r[INT_TILE_PIP_1_3];
    const word_t pip_1_4 = r[INT_TILE_PIP_1_4];
    const word_t pip_1_5 = r[INT_TILE_PIP_1_5];
    const word_t pip_1_6 = r[INT_TILE_PIP_1_6];
    const word_t pip_1_7 = r[INT_TILE_PIP_1_7];
    const word_t pip_2_0 = r[INT_TILE_PIP_2_0];
    const word_t pip_2_1 = r[INT_TILE_PIP_2_1];
    const word_t pip_2_2 = r[INT_TILE_PIP_2_2];
    const word_t pip_2_3 = r[INT_TILE_PIP_2_3];
    const word_t pip_2_4 = r[INT_TILE_PIP_2_4];
    const word_t pip_2_5 = r[INT_TILE_PIP_2_5];
    const word_t pip_2_6 = r[INT_TILE_PIP_2_6];
    const word_t pip_2_7 = r[INT_TILE_PIP_2_7];
    const word_t pip_3_0 = r[INT_TILE_PIP_3_0];
    const word_t pip_3_1 = r[INT_TILE_PIP_3_1];
    const word_t pip_3_2 = r[INT_TILE_PIP_3_2];
    const word_t pip_3_3 = r[INT_TILE_PIP_3_3];
    const word_t pip_3_4 = r[INT_TILE_PIP_3_4];
    const word_t pip_3_5 = r[INT_TILE_PIP_3_5];
    const word_t pip_3_6 = r[INT_TILE_PIP_3_6];
    const word_t pip_3_7 = r[INT_TILE_PIP_3_7];
    const word_t pip_4_0 = r[INT_TILE_PIP_4_0];
    const word_t pip_4_1 = r[INT_TILE_PIP_4_1];
    const word_t pip_4_2 = r[INT_TILE_PIP_4_2];
    const word_t pip_4_3 = r[INT_TILE_PIP_4_3];
    const word_t pip_4_4 = r[INT_TILE_PIP_4_4];
    const word_t pip_4_5 = r[INT_TILE_PIP_4_5];
    const word_t pip_4_6 = r[INT_TILE_PIP_4_6];
    const word_t pip_4_7 = r[INT_TILE_PIP_4_7];
    const word_t pip_5_0 = r[INT_TILE_PIP_5_0];
    const word_t pip_5_1 = r[INT_TILE_PIP_5_1];
    const word_t pip_5_2 = r[INT_TILE_PIP_5_2];
    const word_t pip_5_3 = r[INT_TILE_PIP_5_3];
    const word_t pip_5_4 = r[INT_TILE_PIP_5_4];
    const word_t pip_5_5 = r[INT_TILE_PIP_5_5];
    const word_t pip_5_6 = r[INT_TILE_PIP_5_6];
    const word_t pip_5_7 = r[INT_TILE_PIP_5_7];
    const word_t pip_6_0 = r[INT_TILE_PIP_6_0];
    const word_t pip_6_1 = r[INT_TILE_PIP_6_1];
    const word_t pip_6_2 = r[INT_TILE_PIP_6_2];
    const word_t pip_6_3 = r[INT_TILE_PIP_6_3];
    const word_t pip_6_4 = r[INT_TILE_PIP_6_4];
    const word_t pip_6_5 = r[INT_TILE_PIP_6_5];
    const word_t pip_6_6 = r[INT_TILE_PIP_6_6];
    const word_t pip_6_7 = r[INT_TILE_PIP_6_7];
    const word_t pip_7_0 = r[INT_TILE_PIP_7_0];
    const word_t pip_7_1 = r[INT_TILE_PIP_7_1];
    const word_t pip_7_2 = r[INT_TILE_PIP_7_2];
    const word_t pip_7_3 = r[INT_TILE_PIP_7_3];
    const word_t pip_7_4 = r[INT_TILE_PIP_7_4];
    const word_t pip_7_5 = r[INT_TILE_PIP_7_5];
    const word_t pip_7_6 = r[INT_TILE_PIP_7_6];
    const word_t pip_7_7 = r[INT_TILE_PIP_7_7];

    /* COMPUTE phase — combinational cell chain (declaration order). */
    const word_t g_0_0 = cell_gate(in_0, pip_0_0);
    const word_t g_0_1 = cell_gate(in_0, pip_0_1);
    const word_t g_0_2 = cell_gate(in_0, pip_0_2);
    const word_t g_0_3 = cell_gate(in_0, pip_0_3);
    const word_t g_0_4 = cell_gate(in_0, pip_0_4);
    const word_t g_0_5 = cell_gate(in_0, pip_0_5);
    const word_t g_0_6 = cell_gate(in_0, pip_0_6);
    const word_t g_0_7 = cell_gate(in_0, pip_0_7);
    const word_t g_1_0 = cell_gate(in_1, pip_1_0);
    const word_t g_1_1 = cell_gate(in_1, pip_1_1);
    const word_t g_1_2 = cell_gate(in_1, pip_1_2);
    const word_t g_1_3 = cell_gate(in_1, pip_1_3);
    const word_t g_1_4 = cell_gate(in_1, pip_1_4);
    const word_t g_1_5 = cell_gate(in_1, pip_1_5);
    const word_t g_1_6 = cell_gate(in_1, pip_1_6);
    const word_t g_1_7 = cell_gate(in_1, pip_1_7);
    const word_t g_2_0 = cell_gate(in_2, pip_2_0);
    const word_t g_2_1 = cell_gate(in_2, pip_2_1);
    const word_t g_2_2 = cell_gate(in_2, pip_2_2);
    const word_t g_2_3 = cell_gate(in_2, pip_2_3);
    const word_t g_2_4 = cell_gate(in_2, pip_2_4);
    const word_t g_2_5 = cell_gate(in_2, pip_2_5);
    const word_t g_2_6 = cell_gate(in_2, pip_2_6);
    const word_t g_2_7 = cell_gate(in_2, pip_2_7);
    const word_t g_3_0 = cell_gate(in_3, pip_3_0);
    const word_t g_3_1 = cell_gate(in_3, pip_3_1);
    const word_t g_3_2 = cell_gate(in_3, pip_3_2);
    const word_t g_3_3 = cell_gate(in_3, pip_3_3);
    const word_t g_3_4 = cell_gate(in_3, pip_3_4);
    const word_t g_3_5 = cell_gate(in_3, pip_3_5);
    const word_t g_3_6 = cell_gate(in_3, pip_3_6);
    const word_t g_3_7 = cell_gate(in_3, pip_3_7);
    const word_t g_4_0 = cell_gate(in_4, pip_4_0);
    const word_t g_4_1 = cell_gate(in_4, pip_4_1);
    const word_t g_4_2 = cell_gate(in_4, pip_4_2);
    const word_t g_4_3 = cell_gate(in_4, pip_4_3);
    const word_t g_4_4 = cell_gate(in_4, pip_4_4);
    const word_t g_4_5 = cell_gate(in_4, pip_4_5);
    const word_t g_4_6 = cell_gate(in_4, pip_4_6);
    const word_t g_4_7 = cell_gate(in_4, pip_4_7);
    const word_t g_5_0 = cell_gate(in_5, pip_5_0);
    const word_t g_5_1 = cell_gate(in_5, pip_5_1);
    const word_t g_5_2 = cell_gate(in_5, pip_5_2);
    const word_t g_5_3 = cell_gate(in_5, pip_5_3);
    const word_t g_5_4 = cell_gate(in_5, pip_5_4);
    const word_t g_5_5 = cell_gate(in_5, pip_5_5);
    const word_t g_5_6 = cell_gate(in_5, pip_5_6);
    const word_t g_5_7 = cell_gate(in_5, pip_5_7);
    const word_t g_6_0 = cell_gate(in_6, pip_6_0);
    const word_t g_6_1 = cell_gate(in_6, pip_6_1);
    const word_t g_6_2 = cell_gate(in_6, pip_6_2);
    const word_t g_6_3 = cell_gate(in_6, pip_6_3);
    const word_t g_6_4 = cell_gate(in_6, pip_6_4);
    const word_t g_6_5 = cell_gate(in_6, pip_6_5);
    const word_t g_6_6 = cell_gate(in_6, pip_6_6);
    const word_t g_6_7 = cell_gate(in_6, pip_6_7);
    const word_t g_7_0 = cell_gate(in_7, pip_7_0);
    const word_t g_7_1 = cell_gate(in_7, pip_7_1);
    const word_t g_7_2 = cell_gate(in_7, pip_7_2);
    const word_t g_7_3 = cell_gate(in_7, pip_7_3);
    const word_t g_7_4 = cell_gate(in_7, pip_7_4);
    const word_t g_7_5 = cell_gate(in_7, pip_7_5);
    const word_t g_7_6 = cell_gate(in_7, pip_7_6);
    const word_t g_7_7 = cell_gate(in_7, pip_7_7);
    const word_t acc_0_1 = cell_or(g_0_0, g_1_0);
    const word_t acc_0_2 = cell_or(acc_0_1, g_2_0);
    const word_t acc_0_3 = cell_or(acc_0_2, g_3_0);
    const word_t acc_0_4 = cell_or(acc_0_3, g_4_0);
    const word_t acc_0_5 = cell_or(acc_0_4, g_5_0);
    const word_t acc_0_6 = cell_or(acc_0_5, g_6_0);
    const word_t out_0_c = cell_or(acc_0_6, g_7_0);
    const word_t acc_1_1 = cell_or(g_0_1, g_1_1);
    const word_t acc_1_2 = cell_or(acc_1_1, g_2_1);
    const word_t acc_1_3 = cell_or(acc_1_2, g_3_1);
    const word_t acc_1_4 = cell_or(acc_1_3, g_4_1);
    const word_t acc_1_5 = cell_or(acc_1_4, g_5_1);
    const word_t acc_1_6 = cell_or(acc_1_5, g_6_1);
    const word_t out_1_c = cell_or(acc_1_6, g_7_1);
    const word_t acc_2_1 = cell_or(g_0_2, g_1_2);
    const word_t acc_2_2 = cell_or(acc_2_1, g_2_2);
    const word_t acc_2_3 = cell_or(acc_2_2, g_3_2);
    const word_t acc_2_4 = cell_or(acc_2_3, g_4_2);
    const word_t acc_2_5 = cell_or(acc_2_4, g_5_2);
    const word_t acc_2_6 = cell_or(acc_2_5, g_6_2);
    const word_t out_2_c = cell_or(acc_2_6, g_7_2);
    const word_t acc_3_1 = cell_or(g_0_3, g_1_3);
    const word_t acc_3_2 = cell_or(acc_3_1, g_2_3);
    const word_t acc_3_3 = cell_or(acc_3_2, g_3_3);
    const word_t acc_3_4 = cell_or(acc_3_3, g_4_3);
    const word_t acc_3_5 = cell_or(acc_3_4, g_5_3);
    const word_t acc_3_6 = cell_or(acc_3_5, g_6_3);
    const word_t out_3_c = cell_or(acc_3_6, g_7_3);
    const word_t acc_4_1 = cell_or(g_0_4, g_1_4);
    const word_t acc_4_2 = cell_or(acc_4_1, g_2_4);
    const word_t acc_4_3 = cell_or(acc_4_2, g_3_4);
    const word_t acc_4_4 = cell_or(acc_4_3, g_4_4);
    const word_t acc_4_5 = cell_or(acc_4_4, g_5_4);
    const word_t acc_4_6 = cell_or(acc_4_5, g_6_4);
    const word_t out_4_c = cell_or(acc_4_6, g_7_4);
    const word_t acc_5_1 = cell_or(g_0_5, g_1_5);
    const word_t acc_5_2 = cell_or(acc_5_1, g_2_5);
    const word_t acc_5_3 = cell_or(acc_5_2, g_3_5);
    const word_t acc_5_4 = cell_or(acc_5_3, g_4_5);
    const word_t acc_5_5 = cell_or(acc_5_4, g_5_5);
    const word_t acc_5_6 = cell_or(acc_5_5, g_6_5);
    const word_t out_5_c = cell_or(acc_5_6, g_7_5);
    const word_t acc_6_1 = cell_or(g_0_6, g_1_6);
    const word_t acc_6_2 = cell_or(acc_6_1, g_2_6);
    const word_t acc_6_3 = cell_or(acc_6_2, g_3_6);
    const word_t acc_6_4 = cell_or(acc_6_3, g_4_6);
    const word_t acc_6_5 = cell_or(acc_6_4, g_5_6);
    const word_t acc_6_6 = cell_or(acc_6_5, g_6_6);
    const word_t out_6_c = cell_or(acc_6_6, g_7_6);
    const word_t acc_7_1 = cell_or(g_0_7, g_1_7);
    const word_t acc_7_2 = cell_or(acc_7_1, g_2_7);
    const word_t acc_7_3 = cell_or(acc_7_2, g_3_7);
    const word_t acc_7_4 = cell_or(acc_7_3, g_4_7);
    const word_t acc_7_5 = cell_or(acc_7_4, g_5_7);
    const word_t acc_7_6 = cell_or(acc_7_5, g_6_7);
    const word_t out_7_c = cell_or(acc_7_6, g_7_7);

    /* WRITE phase — gated dff commit: r[X] = cell_dff(q, fed_by, enable). */
    r[INT_TILE_PIP_0_0] = cell_dff(pip_0_0, cfg_0_0_d, cfg_en);
    r[INT_TILE_PIP_0_1] = cell_dff(pip_0_1, cfg_0_1_d, cfg_en);
    r[INT_TILE_PIP_0_2] = cell_dff(pip_0_2, cfg_0_2_d, cfg_en);
    r[INT_TILE_PIP_0_3] = cell_dff(pip_0_3, cfg_0_3_d, cfg_en);
    r[INT_TILE_PIP_0_4] = cell_dff(pip_0_4, cfg_0_4_d, cfg_en);
    r[INT_TILE_PIP_0_5] = cell_dff(pip_0_5, cfg_0_5_d, cfg_en);
    r[INT_TILE_PIP_0_6] = cell_dff(pip_0_6, cfg_0_6_d, cfg_en);
    r[INT_TILE_PIP_0_7] = cell_dff(pip_0_7, cfg_0_7_d, cfg_en);
    r[INT_TILE_PIP_1_0] = cell_dff(pip_1_0, cfg_1_0_d, cfg_en);
    r[INT_TILE_PIP_1_1] = cell_dff(pip_1_1, cfg_1_1_d, cfg_en);
    r[INT_TILE_PIP_1_2] = cell_dff(pip_1_2, cfg_1_2_d, cfg_en);
    r[INT_TILE_PIP_1_3] = cell_dff(pip_1_3, cfg_1_3_d, cfg_en);
    r[INT_TILE_PIP_1_4] = cell_dff(pip_1_4, cfg_1_4_d, cfg_en);
    r[INT_TILE_PIP_1_5] = cell_dff(pip_1_5, cfg_1_5_d, cfg_en);
    r[INT_TILE_PIP_1_6] = cell_dff(pip_1_6, cfg_1_6_d, cfg_en);
    r[INT_TILE_PIP_1_7] = cell_dff(pip_1_7, cfg_1_7_d, cfg_en);
    r[INT_TILE_PIP_2_0] = cell_dff(pip_2_0, cfg_2_0_d, cfg_en);
    r[INT_TILE_PIP_2_1] = cell_dff(pip_2_1, cfg_2_1_d, cfg_en);
    r[INT_TILE_PIP_2_2] = cell_dff(pip_2_2, cfg_2_2_d, cfg_en);
    r[INT_TILE_PIP_2_3] = cell_dff(pip_2_3, cfg_2_3_d, cfg_en);
    r[INT_TILE_PIP_2_4] = cell_dff(pip_2_4, cfg_2_4_d, cfg_en);
    r[INT_TILE_PIP_2_5] = cell_dff(pip_2_5, cfg_2_5_d, cfg_en);
    r[INT_TILE_PIP_2_6] = cell_dff(pip_2_6, cfg_2_6_d, cfg_en);
    r[INT_TILE_PIP_2_7] = cell_dff(pip_2_7, cfg_2_7_d, cfg_en);
    r[INT_TILE_PIP_3_0] = cell_dff(pip_3_0, cfg_3_0_d, cfg_en);
    r[INT_TILE_PIP_3_1] = cell_dff(pip_3_1, cfg_3_1_d, cfg_en);
    r[INT_TILE_PIP_3_2] = cell_dff(pip_3_2, cfg_3_2_d, cfg_en);
    r[INT_TILE_PIP_3_3] = cell_dff(pip_3_3, cfg_3_3_d, cfg_en);
    r[INT_TILE_PIP_3_4] = cell_dff(pip_3_4, cfg_3_4_d, cfg_en);
    r[INT_TILE_PIP_3_5] = cell_dff(pip_3_5, cfg_3_5_d, cfg_en);
    r[INT_TILE_PIP_3_6] = cell_dff(pip_3_6, cfg_3_6_d, cfg_en);
    r[INT_TILE_PIP_3_7] = cell_dff(pip_3_7, cfg_3_7_d, cfg_en);
    r[INT_TILE_PIP_4_0] = cell_dff(pip_4_0, cfg_4_0_d, cfg_en);
    r[INT_TILE_PIP_4_1] = cell_dff(pip_4_1, cfg_4_1_d, cfg_en);
    r[INT_TILE_PIP_4_2] = cell_dff(pip_4_2, cfg_4_2_d, cfg_en);
    r[INT_TILE_PIP_4_3] = cell_dff(pip_4_3, cfg_4_3_d, cfg_en);
    r[INT_TILE_PIP_4_4] = cell_dff(pip_4_4, cfg_4_4_d, cfg_en);
    r[INT_TILE_PIP_4_5] = cell_dff(pip_4_5, cfg_4_5_d, cfg_en);
    r[INT_TILE_PIP_4_6] = cell_dff(pip_4_6, cfg_4_6_d, cfg_en);
    r[INT_TILE_PIP_4_7] = cell_dff(pip_4_7, cfg_4_7_d, cfg_en);
    r[INT_TILE_PIP_5_0] = cell_dff(pip_5_0, cfg_5_0_d, cfg_en);
    r[INT_TILE_PIP_5_1] = cell_dff(pip_5_1, cfg_5_1_d, cfg_en);
    r[INT_TILE_PIP_5_2] = cell_dff(pip_5_2, cfg_5_2_d, cfg_en);
    r[INT_TILE_PIP_5_3] = cell_dff(pip_5_3, cfg_5_3_d, cfg_en);
    r[INT_TILE_PIP_5_4] = cell_dff(pip_5_4, cfg_5_4_d, cfg_en);
    r[INT_TILE_PIP_5_5] = cell_dff(pip_5_5, cfg_5_5_d, cfg_en);
    r[INT_TILE_PIP_5_6] = cell_dff(pip_5_6, cfg_5_6_d, cfg_en);
    r[INT_TILE_PIP_5_7] = cell_dff(pip_5_7, cfg_5_7_d, cfg_en);
    r[INT_TILE_PIP_6_0] = cell_dff(pip_6_0, cfg_6_0_d, cfg_en);
    r[INT_TILE_PIP_6_1] = cell_dff(pip_6_1, cfg_6_1_d, cfg_en);
    r[INT_TILE_PIP_6_2] = cell_dff(pip_6_2, cfg_6_2_d, cfg_en);
    r[INT_TILE_PIP_6_3] = cell_dff(pip_6_3, cfg_6_3_d, cfg_en);
    r[INT_TILE_PIP_6_4] = cell_dff(pip_6_4, cfg_6_4_d, cfg_en);
    r[INT_TILE_PIP_6_5] = cell_dff(pip_6_5, cfg_6_5_d, cfg_en);
    r[INT_TILE_PIP_6_6] = cell_dff(pip_6_6, cfg_6_6_d, cfg_en);
    r[INT_TILE_PIP_6_7] = cell_dff(pip_6_7, cfg_6_7_d, cfg_en);
    r[INT_TILE_PIP_7_0] = cell_dff(pip_7_0, cfg_7_0_d, cfg_en);
    r[INT_TILE_PIP_7_1] = cell_dff(pip_7_1, cfg_7_1_d, cfg_en);
    r[INT_TILE_PIP_7_2] = cell_dff(pip_7_2, cfg_7_2_d, cfg_en);
    r[INT_TILE_PIP_7_3] = cell_dff(pip_7_3, cfg_7_3_d, cfg_en);
    r[INT_TILE_PIP_7_4] = cell_dff(pip_7_4, cfg_7_4_d, cfg_en);
    r[INT_TILE_PIP_7_5] = cell_dff(pip_7_5, cfg_7_5_d, cfg_en);
    r[INT_TILE_PIP_7_6] = cell_dff(pip_7_6, cfg_7_6_d, cfg_en);
    r[INT_TILE_PIP_7_7] = cell_dff(pip_7_7, cfg_7_7_d, cfg_en);
    r[INT_TILE_G_0_0] = g_0_0;
    r[INT_TILE_G_0_1] = g_0_1;
    r[INT_TILE_G_0_2] = g_0_2;
    r[INT_TILE_G_0_3] = g_0_3;
    r[INT_TILE_G_0_4] = g_0_4;
    r[INT_TILE_G_0_5] = g_0_5;
    r[INT_TILE_G_0_6] = g_0_6;
    r[INT_TILE_G_0_7] = g_0_7;
    r[INT_TILE_G_1_0] = g_1_0;
    r[INT_TILE_G_1_1] = g_1_1;
    r[INT_TILE_G_1_2] = g_1_2;
    r[INT_TILE_G_1_3] = g_1_3;
    r[INT_TILE_G_1_4] = g_1_4;
    r[INT_TILE_G_1_5] = g_1_5;
    r[INT_TILE_G_1_6] = g_1_6;
    r[INT_TILE_G_1_7] = g_1_7;
    r[INT_TILE_G_2_0] = g_2_0;
    r[INT_TILE_G_2_1] = g_2_1;
    r[INT_TILE_G_2_2] = g_2_2;
    r[INT_TILE_G_2_3] = g_2_3;
    r[INT_TILE_G_2_4] = g_2_4;
    r[INT_TILE_G_2_5] = g_2_5;
    r[INT_TILE_G_2_6] = g_2_6;
    r[INT_TILE_G_2_7] = g_2_7;
    r[INT_TILE_G_3_0] = g_3_0;
    r[INT_TILE_G_3_1] = g_3_1;
    r[INT_TILE_G_3_2] = g_3_2;
    r[INT_TILE_G_3_3] = g_3_3;
    r[INT_TILE_G_3_4] = g_3_4;
    r[INT_TILE_G_3_5] = g_3_5;
    r[INT_TILE_G_3_6] = g_3_6;
    r[INT_TILE_G_3_7] = g_3_7;
    r[INT_TILE_G_4_0] = g_4_0;
    r[INT_TILE_G_4_1] = g_4_1;
    r[INT_TILE_G_4_2] = g_4_2;
    r[INT_TILE_G_4_3] = g_4_3;
    r[INT_TILE_G_4_4] = g_4_4;
    r[INT_TILE_G_4_5] = g_4_5;
    r[INT_TILE_G_4_6] = g_4_6;
    r[INT_TILE_G_4_7] = g_4_7;
    r[INT_TILE_G_5_0] = g_5_0;
    r[INT_TILE_G_5_1] = g_5_1;
    r[INT_TILE_G_5_2] = g_5_2;
    r[INT_TILE_G_5_3] = g_5_3;
    r[INT_TILE_G_5_4] = g_5_4;
    r[INT_TILE_G_5_5] = g_5_5;
    r[INT_TILE_G_5_6] = g_5_6;
    r[INT_TILE_G_5_7] = g_5_7;
    r[INT_TILE_G_6_0] = g_6_0;
    r[INT_TILE_G_6_1] = g_6_1;
    r[INT_TILE_G_6_2] = g_6_2;
    r[INT_TILE_G_6_3] = g_6_3;
    r[INT_TILE_G_6_4] = g_6_4;
    r[INT_TILE_G_6_5] = g_6_5;
    r[INT_TILE_G_6_6] = g_6_6;
    r[INT_TILE_G_6_7] = g_6_7;
    r[INT_TILE_G_7_0] = g_7_0;
    r[INT_TILE_G_7_1] = g_7_1;
    r[INT_TILE_G_7_2] = g_7_2;
    r[INT_TILE_G_7_3] = g_7_3;
    r[INT_TILE_G_7_4] = g_7_4;
    r[INT_TILE_G_7_5] = g_7_5;
    r[INT_TILE_G_7_6] = g_7_6;
    r[INT_TILE_G_7_7] = g_7_7;
    r[INT_TILE_ACC_0_1] = acc_0_1;
    r[INT_TILE_ACC_0_2] = acc_0_2;
    r[INT_TILE_ACC_0_3] = acc_0_3;
    r[INT_TILE_ACC_0_4] = acc_0_4;
    r[INT_TILE_ACC_0_5] = acc_0_5;
    r[INT_TILE_ACC_0_6] = acc_0_6;
    r[INT_TILE_OUT_0_C] = out_0_c;
    r[INT_TILE_ACC_1_1] = acc_1_1;
    r[INT_TILE_ACC_1_2] = acc_1_2;
    r[INT_TILE_ACC_1_3] = acc_1_3;
    r[INT_TILE_ACC_1_4] = acc_1_4;
    r[INT_TILE_ACC_1_5] = acc_1_5;
    r[INT_TILE_ACC_1_6] = acc_1_6;
    r[INT_TILE_OUT_1_C] = out_1_c;
    r[INT_TILE_ACC_2_1] = acc_2_1;
    r[INT_TILE_ACC_2_2] = acc_2_2;
    r[INT_TILE_ACC_2_3] = acc_2_3;
    r[INT_TILE_ACC_2_4] = acc_2_4;
    r[INT_TILE_ACC_2_5] = acc_2_5;
    r[INT_TILE_ACC_2_6] = acc_2_6;
    r[INT_TILE_OUT_2_C] = out_2_c;
    r[INT_TILE_ACC_3_1] = acc_3_1;
    r[INT_TILE_ACC_3_2] = acc_3_2;
    r[INT_TILE_ACC_3_3] = acc_3_3;
    r[INT_TILE_ACC_3_4] = acc_3_4;
    r[INT_TILE_ACC_3_5] = acc_3_5;
    r[INT_TILE_ACC_3_6] = acc_3_6;
    r[INT_TILE_OUT_3_C] = out_3_c;
    r[INT_TILE_ACC_4_1] = acc_4_1;
    r[INT_TILE_ACC_4_2] = acc_4_2;
    r[INT_TILE_ACC_4_3] = acc_4_3;
    r[INT_TILE_ACC_4_4] = acc_4_4;
    r[INT_TILE_ACC_4_5] = acc_4_5;
    r[INT_TILE_ACC_4_6] = acc_4_6;
    r[INT_TILE_OUT_4_C] = out_4_c;
    r[INT_TILE_ACC_5_1] = acc_5_1;
    r[INT_TILE_ACC_5_2] = acc_5_2;
    r[INT_TILE_ACC_5_3] = acc_5_3;
    r[INT_TILE_ACC_5_4] = acc_5_4;
    r[INT_TILE_ACC_5_5] = acc_5_5;
    r[INT_TILE_ACC_5_6] = acc_5_6;
    r[INT_TILE_OUT_5_C] = out_5_c;
    r[INT_TILE_ACC_6_1] = acc_6_1;
    r[INT_TILE_ACC_6_2] = acc_6_2;
    r[INT_TILE_ACC_6_3] = acc_6_3;
    r[INT_TILE_ACC_6_4] = acc_6_4;
    r[INT_TILE_ACC_6_5] = acc_6_5;
    r[INT_TILE_ACC_6_6] = acc_6_6;
    r[INT_TILE_OUT_6_C] = out_6_c;
    r[INT_TILE_ACC_7_1] = acc_7_1;
    r[INT_TILE_ACC_7_2] = acc_7_2;
    r[INT_TILE_ACC_7_3] = acc_7_3;
    r[INT_TILE_ACC_7_4] = acc_7_4;
    r[INT_TILE_ACC_7_5] = acc_7_5;
    r[INT_TILE_ACC_7_6] = acc_7_6;
    r[INT_TILE_OUT_7_C] = out_7_c;
    r[INT_TILE_OUT_0] = out_0_c;
    r[INT_TILE_OUT_1] = out_1_c;
    r[INT_TILE_OUT_2] = out_2_c;
    r[INT_TILE_OUT_3] = out_3_c;
    r[INT_TILE_OUT_4] = out_4_c;
    r[INT_TILE_OUT_5] = out_5_c;
    r[INT_TILE_OUT_6] = out_6_c;
    r[INT_TILE_OUT_7] = out_7_c;

}

/* int_tile_run: canonical free-running clock. Power on once; the clock
 * self-oscillates while the power bit is set. Nothing external steps it. */
static inline void int_tile_run(word_t *r) {
    int_tile_tick(r);
}

#endif /* INT_TILE_GEN_H */
