/* GENERATED by gennet.py from clocking/mmcm.net.json — DO NOT EDIT BY HAND.
 * The mmcm device: register lanes + cell-based logic (READ->COMPUTE->WRITE).
 * Netlist-generated; every data operation is a structural cell call. */
#ifndef MMCM_GEN_H
#define MMCM_GEN_H
#include "cells.h"

#define MMCM_REG_COUNT 57u

#define MMCM_CLK_POWER 0u
#define MMCM_CLK_RUN_UNTIL 1u
#define MMCM_DIV_0_D 2u
#define MMCM_DIV_1_D 3u
#define MMCM_DIV_2_D 4u
#define MMCM_DIV_3_D 5u
#define MMCM_DIV_4_D 6u
#define MMCM_DIV_5_D 7u
#define MMCM_DIV_6_D 8u
#define MMCM_DIV_CFG_EN 9u
#define MMCM_ONE 10u
#define MMCM_ZERO 11u
#define MMCM_CLK_TICKS 12u
#define MMCM_DIV_0 13u
#define MMCM_CNT_0 14u
#define MMCM_DIV_1 15u
#define MMCM_CNT_1 16u
#define MMCM_DIV_2 17u
#define MMCM_CNT_2 18u
#define MMCM_DIV_3 19u
#define MMCM_CNT_3 20u
#define MMCM_DIV_4 21u
#define MMCM_CNT_4 22u
#define MMCM_DIV_5 23u
#define MMCM_CNT_5 24u
#define MMCM_DIV_6 25u
#define MMCM_CNT_6 26u
#define MMCM_STEP 27u
#define MMCM_TICKS_NEXT 28u
#define MMCM_INC_0 29u
#define MMCM_WRAP_0 30u
#define MMCM_CNT_NEXT_0 31u
#define MMCM_INC_1 32u
#define MMCM_WRAP_1 33u
#define MMCM_CNT_NEXT_1 34u
#define MMCM_INC_2 35u
#define MMCM_WRAP_2 36u
#define MMCM_CNT_NEXT_2 37u
#define MMCM_INC_3 38u
#define MMCM_WRAP_3 39u
#define MMCM_CNT_NEXT_3 40u
#define MMCM_INC_4 41u
#define MMCM_WRAP_4 42u
#define MMCM_CNT_NEXT_4 43u
#define MMCM_INC_5 44u
#define MMCM_WRAP_5 45u
#define MMCM_CNT_NEXT_5 46u
#define MMCM_INC_6 47u
#define MMCM_WRAP_6 48u
#define MMCM_CNT_NEXT_6 49u
#define MMCM_CLKOUT_0 50u
#define MMCM_CLKOUT_1 51u
#define MMCM_CLKOUT_2 52u
#define MMCM_CLKOUT_3 53u
#define MMCM_CLKOUT_4 54u
#define MMCM_CLKOUT_5 55u
#define MMCM_CLKOUT_6 56u

static inline void mmcm_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < MMCM_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
    r[MMCM_ONE] = 1ULL;
    r[MMCM_ZERO] = 0ULL;
}

/* mmcm_tick: one clock edge. READ inputs as const locals,
 * COMPUTE via cells (no native add/sub/mul on data), WRITE every register. */
static inline void mmcm_tick(word_t *r) {
    /* READ phase — pre-read every consumed register value. */
    const word_t clk_power = r[MMCM_CLK_POWER];
    const word_t div_0_d = r[MMCM_DIV_0_D];
    const word_t div_1_d = r[MMCM_DIV_1_D];
    const word_t div_2_d = r[MMCM_DIV_2_D];
    const word_t div_3_d = r[MMCM_DIV_3_D];
    const word_t div_4_d = r[MMCM_DIV_4_D];
    const word_t div_5_d = r[MMCM_DIV_5_D];
    const word_t div_6_d = r[MMCM_DIV_6_D];
    const word_t div_cfg_en = r[MMCM_DIV_CFG_EN];
    const word_t one = r[MMCM_ONE];
    const word_t zero = r[MMCM_ZERO];
    const word_t clk_ticks = r[MMCM_CLK_TICKS];
    const word_t div_0 = r[MMCM_DIV_0];
    const word_t cnt_0 = r[MMCM_CNT_0];
    const word_t div_1 = r[MMCM_DIV_1];
    const word_t cnt_1 = r[MMCM_CNT_1];
    const word_t div_2 = r[MMCM_DIV_2];
    const word_t cnt_2 = r[MMCM_CNT_2];
    const word_t div_3 = r[MMCM_DIV_3];
    const word_t cnt_3 = r[MMCM_CNT_3];
    const word_t div_4 = r[MMCM_DIV_4];
    const word_t cnt_4 = r[MMCM_CNT_4];
    const word_t div_5 = r[MMCM_DIV_5];
    const word_t cnt_5 = r[MMCM_CNT_5];
    const word_t div_6 = r[MMCM_DIV_6];
    const word_t cnt_6 = r[MMCM_CNT_6];

    /* COMPUTE phase — combinational cell chain (declaration order). */
    const word_t step = cell_gate(one, clk_power);
    const word_t ticks_next = cell_addsub(clk_ticks, step, 0ULL);
    const word_t inc_0 = cell_addsub(cnt_0, step, 0ULL);
    const word_t wrap_0 = cell_eqmask(inc_0, div_0);
    const word_t cnt_next_0 = cell_mux(inc_0, zero, wrap_0);
    const word_t inc_1 = cell_addsub(cnt_1, step, 0ULL);
    const word_t wrap_1 = cell_eqmask(inc_1, div_1);
    const word_t cnt_next_1 = cell_mux(inc_1, zero, wrap_1);
    const word_t inc_2 = cell_addsub(cnt_2, step, 0ULL);
    const word_t wrap_2 = cell_eqmask(inc_2, div_2);
    const word_t cnt_next_2 = cell_mux(inc_2, zero, wrap_2);
    const word_t inc_3 = cell_addsub(cnt_3, step, 0ULL);
    const word_t wrap_3 = cell_eqmask(inc_3, div_3);
    const word_t cnt_next_3 = cell_mux(inc_3, zero, wrap_3);
    const word_t inc_4 = cell_addsub(cnt_4, step, 0ULL);
    const word_t wrap_4 = cell_eqmask(inc_4, div_4);
    const word_t cnt_next_4 = cell_mux(inc_4, zero, wrap_4);
    const word_t inc_5 = cell_addsub(cnt_5, step, 0ULL);
    const word_t wrap_5 = cell_eqmask(inc_5, div_5);
    const word_t cnt_next_5 = cell_mux(inc_5, zero, wrap_5);
    const word_t inc_6 = cell_addsub(cnt_6, step, 0ULL);
    const word_t wrap_6 = cell_eqmask(inc_6, div_6);
    const word_t cnt_next_6 = cell_mux(inc_6, zero, wrap_6);

    /* WRITE phase — gated dff commit: r[X] = cell_dff(q, fed_by, enable). */
    r[MMCM_CLK_TICKS] = cell_dff(clk_ticks, ticks_next, one);
    r[MMCM_DIV_0] = cell_dff(div_0, div_0_d, div_cfg_en);
    r[MMCM_CNT_0] = cell_dff(cnt_0, cnt_next_0, one);
    r[MMCM_DIV_1] = cell_dff(div_1, div_1_d, div_cfg_en);
    r[MMCM_CNT_1] = cell_dff(cnt_1, cnt_next_1, one);
    r[MMCM_DIV_2] = cell_dff(div_2, div_2_d, div_cfg_en);
    r[MMCM_CNT_2] = cell_dff(cnt_2, cnt_next_2, one);
    r[MMCM_DIV_3] = cell_dff(div_3, div_3_d, div_cfg_en);
    r[MMCM_CNT_3] = cell_dff(cnt_3, cnt_next_3, one);
    r[MMCM_DIV_4] = cell_dff(div_4, div_4_d, div_cfg_en);
    r[MMCM_CNT_4] = cell_dff(cnt_4, cnt_next_4, one);
    r[MMCM_DIV_5] = cell_dff(div_5, div_5_d, div_cfg_en);
    r[MMCM_CNT_5] = cell_dff(cnt_5, cnt_next_5, one);
    r[MMCM_DIV_6] = cell_dff(div_6, div_6_d, div_cfg_en);
    r[MMCM_CNT_6] = cell_dff(cnt_6, cnt_next_6, one);
    r[MMCM_STEP] = step;
    r[MMCM_TICKS_NEXT] = ticks_next;
    r[MMCM_INC_0] = inc_0;
    r[MMCM_WRAP_0] = wrap_0;
    r[MMCM_CNT_NEXT_0] = cnt_next_0;
    r[MMCM_INC_1] = inc_1;
    r[MMCM_WRAP_1] = wrap_1;
    r[MMCM_CNT_NEXT_1] = cnt_next_1;
    r[MMCM_INC_2] = inc_2;
    r[MMCM_WRAP_2] = wrap_2;
    r[MMCM_CNT_NEXT_2] = cnt_next_2;
    r[MMCM_INC_3] = inc_3;
    r[MMCM_WRAP_3] = wrap_3;
    r[MMCM_CNT_NEXT_3] = cnt_next_3;
    r[MMCM_INC_4] = inc_4;
    r[MMCM_WRAP_4] = wrap_4;
    r[MMCM_CNT_NEXT_4] = cnt_next_4;
    r[MMCM_INC_5] = inc_5;
    r[MMCM_WRAP_5] = wrap_5;
    r[MMCM_CNT_NEXT_5] = cnt_next_5;
    r[MMCM_INC_6] = inc_6;
    r[MMCM_WRAP_6] = wrap_6;
    r[MMCM_CNT_NEXT_6] = cnt_next_6;
    r[MMCM_CLKOUT_0] = wrap_0;
    r[MMCM_CLKOUT_1] = wrap_1;
    r[MMCM_CLKOUT_2] = wrap_2;
    r[MMCM_CLKOUT_3] = wrap_3;
    r[MMCM_CLKOUT_4] = wrap_4;
    r[MMCM_CLKOUT_5] = wrap_5;
    r[MMCM_CLKOUT_6] = wrap_6;

}

/* mmcm_run: canonical free-running clock. Power on once; the clock
 * self-oscillates while the power bit is set. Nothing external steps it. */
static inline void mmcm_run(word_t *r) {
    while (r[MMCM_CLK_POWER] & 1ULL) { mmcm_tick(r); }
}

#endif /* MMCM_GEN_H */
