/* GENERATED by gennet.py from cbr.net.json — DO NOT EDIT BY HAND.
 * The cbr device: register lanes + cell-based logic.
 * Netlist-generated; every operation is a structural cell call. */
#ifndef CBR_GEN_H
#define CBR_GEN_H
#include "cells.h"

#define CBR_REG_COUNT 43u
#define CBR_WINDOW_BASE 0x00000000u

#define CBR_CAND_CURR_BID_VOL 0u
#define CBR_CAND_CURR_ASK_VOL 1u
#define CBR_CAND_CURR_BID_TR 2u
#define CBR_CAND_CURR_ASK_TR 3u
#define CBR_CAND_CURR_INTRABAR 4u
#define CBR_FP_CURR_CUM_DELTA 5u
#define CBR_TF_BAR_SEQ_REG 6u
#define CBR_CBR_BID_VOL_DELTA_REG 7u
#define CBR_CBR_ASK_VOL_DELTA_REG 8u
#define CBR_CBR_BID_TR_DELTA_REG 9u
#define CBR_CBR_ASK_TR_DELTA_REG 10u
#define CBR_CBR_FOOTPRINT_DELTA_REG 11u
#define CBR_CBR_INTRABAR_DELTA_REG 12u
#define CBR_CBR_BID_VOL_HW_REG 13u
#define CBR_CBR_ASK_VOL_HW_REG 14u
#define CBR_CBR_BID_TR_HW_REG 15u
#define CBR_CBR_ASK_TR_HW_REG 16u
#define CBR_CBR_PREV_BID_VOL_REG 17u
#define CBR_CBR_PREV_ASK_VOL_REG 18u
#define CBR_CBR_PREV_BID_TR_REG 19u
#define CBR_CBR_PREV_ASK_TR_REG 20u
#define CBR_CBR_LAST_TF_SEQ_REG 21u
#define CBR_CBR_BAR_BOUNDARY 23u
#define CBR_CBR_BAR_BOUNDARY 23u
#define CBR_CBR_BID_VOL_DELTA_REG_UPDATE 24u
#define CBR_CBR_ASK_VOL_DELTA_REG_UPDATE 25u
#define CBR_CBR_BID_TR_DELTA_REG_UPDATE 26u
#define CBR_CBR_ASK_TR_DELTA_REG_UPDATE 27u
#define CBR_CBR_FOOTPRINT_DELTA_REG_UPDATE 28u
#define CBR_CBR_INTRABAR_DELTA_REG_UPDATE 29u
#define CBR_CBR_BID_VOL_HW_SEL 30u
#define CBR_CBR_BID_VOL_HW_REG_UPDATE 31u
#define CBR_CBR_ASK_VOL_HW_SEL 32u
#define CBR_CBR_ASK_VOL_HW_REG_UPDATE 33u
#define CBR_CBR_BID_TR_HW_SEL 34u
#define CBR_CBR_BID_TR_HW_REG_UPDATE 35u
#define CBR_CBR_ASK_TR_HW_SEL 36u
#define CBR_CBR_ASK_TR_HW_REG_UPDATE 37u
#define CBR_CBR_PREV_BID_VOL_REG_UPDATE 38u
#define CBR_CBR_PREV_ASK_VOL_REG_UPDATE 39u
#define CBR_CBR_PREV_BID_TR_REG_UPDATE 40u
#define CBR_CBR_PREV_ASK_TR_REG_UPDATE 41u
#define CBR_CBR_LAST_TF_SEQ_REG_UPDATE 42u


/* cmp_lt: gate-netlist comparator. Returns 1 (bit0) iff a < b (unsigned).
 * a - b = a + (~b) + 1 via 64 full-adder cells; the carry-out of the top bit is
 * (a >= b). So (a < b) = carry ^ 1. Pure gate algebra, no native C compare. */
static inline word_t cmp_lt(word_t a, word_t b) {
    word_t carry = 1ULL;                 /* +1 for two's-complement of b */
    word_t i = 0ULL;
    for (i = 0ULL; i < 64ULL; i = i + 1ULL) {
        const word_t aa = (a >> i) & 1ULL;
        const word_t nb = (cell_not(b) >> i) & 1ULL;     /* ~b bit */
        const word_t fa = cell_fa(aa, nb, carry);
        carry           = (fa >> 1) & 1ULL;              /* carry-out to next */
    }
    return (carry & 1ULL) ^ 1ULL;        /* carry==0 (borrow) == (a < b) */
}


static inline void cbr_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < CBR_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
}

/* cbr_tick: one clock edge. READ all inputs as const
 * locals, COMPUTE via cells (no native C operators), WRITE outputs. */
static inline void cbr_tick(word_t *r) {
    /* READ phase — pre-read every input from registers. */
    const word_t cand_curr_bid_vol = r[CBR_CAND_CURR_BID_VOL];
    const word_t cand_curr_ask_vol = r[CBR_CAND_CURR_ASK_VOL];
    const word_t cand_curr_bid_tr = r[CBR_CAND_CURR_BID_TR];
    const word_t cand_curr_ask_tr = r[CBR_CAND_CURR_ASK_TR];
    const word_t cand_curr_intrabar = r[CBR_CAND_CURR_INTRABAR];
    const word_t fp_curr_cum_delta = r[CBR_FP_CURR_CUM_DELTA];
    const word_t tf_bar_seq_reg = r[CBR_TF_BAR_SEQ_REG];
    const word_t cbr_bid_vol_hw_reg = r[CBR_CBR_BID_VOL_HW_REG];
    const word_t cbr_ask_vol_hw_reg = r[CBR_CBR_ASK_VOL_HW_REG];
    const word_t cbr_bid_tr_hw_reg = r[CBR_CBR_BID_TR_HW_REG];
    const word_t cbr_ask_tr_hw_reg = r[CBR_CBR_ASK_TR_HW_REG];
    const word_t cbr_prev_bid_vol_reg = r[CBR_CBR_PREV_BID_VOL_REG];
    const word_t cbr_prev_ask_vol_reg = r[CBR_CBR_PREV_ASK_VOL_REG];
    const word_t cbr_prev_bid_tr_reg = r[CBR_CBR_PREV_BID_TR_REG];
    const word_t cbr_prev_ask_tr_reg = r[CBR_CBR_PREV_ASK_TR_REG];
    const word_t cbr_last_tf_seq_reg = r[CBR_CBR_LAST_TF_SEQ_REG];
    (void)0;

    /* COMPUTE phase — all logic via cells (no native C operators). */
    const word_t cbr_bar_boundary = (cell_eqmask(cbr_last_tf_seq_reg, tf_bar_seq_reg) ^ 1ULL);
    const word_t cbr_bid_vol_delta_reg_update = cell_addsub(cand_curr_bid_vol, cbr_prev_bid_vol_reg, 1ULL);
    const word_t cbr_ask_vol_delta_reg_update = cell_addsub(cand_curr_ask_vol, cbr_prev_ask_vol_reg, 1ULL);
    const word_t cbr_bid_tr_delta_reg_update = cell_addsub(cand_curr_bid_tr, cbr_prev_bid_tr_reg, 1ULL);
    const word_t cbr_ask_tr_delta_reg_update = cell_addsub(cand_curr_ask_tr, cbr_prev_ask_tr_reg, 1ULL);
    const word_t cbr_footprint_delta_reg_update = cell_addsub(fp_curr_cum_delta, cbr_prev_bid_vol_reg, 1ULL);
    const word_t cbr_intrabar_delta_reg_update = cell_addsub(cand_curr_intrabar, cbr_prev_ask_vol_reg, 1ULL);
    const word_t cbr_bid_vol_hw_sel = cmp_lt(cbr_bid_vol_hw_reg, cbr_bid_vol_delta_reg_update);
    const word_t cbr_bid_vol_hw_reg_update = cell_mux(cbr_bid_vol_hw_reg, cbr_bid_vol_delta_reg_update, cbr_bid_vol_hw_sel);
    const word_t cbr_ask_vol_hw_sel = cmp_lt(cbr_ask_vol_hw_reg, cbr_ask_vol_delta_reg_update);
    const word_t cbr_ask_vol_hw_reg_update = cell_mux(cbr_ask_vol_hw_reg, cbr_ask_vol_delta_reg_update, cbr_ask_vol_hw_sel);
    const word_t cbr_bid_tr_hw_sel = cmp_lt(cbr_bid_tr_hw_reg, cbr_bid_tr_delta_reg_update);
    const word_t cbr_bid_tr_hw_reg_update = cell_mux(cbr_bid_tr_hw_reg, cbr_bid_tr_delta_reg_update, cbr_bid_tr_hw_sel);
    const word_t cbr_ask_tr_hw_sel = cmp_lt(cbr_ask_tr_hw_reg, cbr_ask_tr_delta_reg_update);
    const word_t cbr_ask_tr_hw_reg_update = cell_mux(cbr_ask_tr_hw_reg, cbr_ask_tr_delta_reg_update, cbr_ask_tr_hw_sel);
    const word_t cbr_prev_bid_vol_reg_update = cell_mux(cbr_prev_bid_vol_reg, cand_curr_bid_vol, cbr_bar_boundary);
    const word_t cbr_prev_ask_vol_reg_update = cell_mux(cbr_prev_ask_vol_reg, cand_curr_ask_vol, cbr_bar_boundary);
    const word_t cbr_prev_bid_tr_reg_update = cell_mux(cbr_prev_bid_tr_reg, cand_curr_bid_tr, cbr_bar_boundary);
    const word_t cbr_prev_ask_tr_reg_update = cell_mux(cbr_prev_ask_tr_reg, cand_curr_ask_tr, cbr_bar_boundary);
    const word_t cbr_last_tf_seq_reg_update = cell_buf(tf_bar_seq_reg);

    /* WRITE phase — commit every dff (no read-after-write). */
    r[CBR_CBR_BID_VOL_DELTA_REG] = cbr_bid_vol_delta_reg_update;
    r[CBR_CBR_ASK_VOL_DELTA_REG] = cbr_ask_vol_delta_reg_update;
    r[CBR_CBR_BID_TR_DELTA_REG] = cbr_bid_tr_delta_reg_update;
    r[CBR_CBR_ASK_TR_DELTA_REG] = cbr_ask_tr_delta_reg_update;
    r[CBR_CBR_FOOTPRINT_DELTA_REG] = cbr_footprint_delta_reg_update;
    r[CBR_CBR_INTRABAR_DELTA_REG] = cbr_intrabar_delta_reg_update;
    r[CBR_CBR_BID_VOL_HW_REG] = cbr_bid_vol_hw_reg_update;
    r[CBR_CBR_ASK_VOL_HW_REG] = cbr_ask_vol_hw_reg_update;
    r[CBR_CBR_BID_TR_HW_REG] = cbr_bid_tr_hw_reg_update;
    r[CBR_CBR_ASK_TR_HW_REG] = cbr_ask_tr_hw_reg_update;
    r[CBR_CBR_PREV_BID_VOL_REG] = cbr_prev_bid_vol_reg_update;
    r[CBR_CBR_PREV_ASK_VOL_REG] = cbr_prev_ask_vol_reg_update;
    r[CBR_CBR_PREV_BID_TR_REG] = cbr_prev_bid_tr_reg_update;
    r[CBR_CBR_PREV_ASK_TR_REG] = cbr_prev_ask_tr_reg_update;
    r[CBR_CBR_LAST_TF_SEQ_REG] = cbr_last_tf_seq_reg_update;
    r[CBR_CBR_BAR_BOUNDARY] = cbr_bar_boundary;
}

/* cbr_run: free-running self-oscillating clock loop. */
static inline void cbr_run(word_t *r) {
    cbr_tick(r);
}

#endif /* CBR_GEN_H */
