#!/usr/bin/env python3
"""gennet.py — generate the candle device C from candle.net.json.

GENERATED by partslist-to-gennet.py from CANDLE_PARTS_LIST.md.

The device logic is GENERATED from the netlist, never hand-written. Every node
becomes an addressed register slot. Operations are cell calls (cell_addsub,
cell_mux, cell_eqmask, etc.) — NO native C operators in the data path.

All state lives in addressed registers. The tick function follows strict
READ->COMPUTE->WRITE discipline: pre-read all inputs, compute using cells,
write all outputs (no read-after-write).

Each comb_node in the netlist (candle_architecture.md §3) names ONE gate cell
and its inputs; this generator expands each into exactly one structural cell
call. Recognised cells: buf, eqmask, mux, addsub, cmp_lt. Optional modifiers:
  "invert": True       -> XOR 1ULL on the result (eqmask -> "changed")
  "sub": 0|1           -> addsub direction operand (add / two's-complement sub)
  "shift_right": n     -> >> n on the result (structural power-of-two divide)
"""
import json
import sys


CMP_LT_HELPER = """
/* cmp_lt: gate-netlist comparator. Returns 1 (bit0) iff a < b (unsigned).
 * a - b = a + (~b) + 1 via 64 full-adder cells; the carry-out of the top bit is
 * (a >= b). So (a < b) = carry ^ 1. Pure gate algebra, no native C compare. */
static inline word_t cmp_lt(word_t a, word_t b) {
    word_t carry = 1ULL;                 /* +1 for two's-complement of b */
    word_t i = 0ULL;
    for (i = 0ULL; i < 64ULL; i = i + 1ULL) {
        const word_t aa = (a >> i) & 1ULL;
        const word_t nb = (cell_not(b) >> i) & 1ULL;     /* ~b bit */
        const word_t fa = cell_fa(aa, nb, carry);
        carry           = (fa >> 1) & 1ULL;              /* carry-out to next */
    }
    return (carry & 1ULL) ^ 1ULL;        /* carry==0 (borrow) == (a < b) */
}
"""


def emit_comb(node, pfx):
    """Expand one comb_node into a single structural cell call expression.

    Inputs are register reads r[PFX_NAME]; the result is bound to a const local
    named after the comb_node (lower-case). No native C operators on data — the
    only native tokens are the optional ^ 1ULL invert and >> n shift, which are
    boolean/shift, not add/sub/mul (gate stage 2b permits shifts and XOR-1).
    """
    cell = node["cell"]
    name = node["name"].lower()
    # Inputs reference READ-phase const locals (pre-read window) or, when an input
    # is itself recomputed this tick, the COMPUTE-phase comb local of the same
    # lower-case name. Either way the token is the input name lower-cased.
    args = [i.lower() for i in node["inputs"]]

    if cell == "buf":
        expr = "cell_buf(" + args[0] + ")"
    elif cell == "eqmask":
        expr = "cell_eqmask(" + args[0] + ", " + args[1] + ")"
    elif cell == "mux":
        expr = "cell_mux(" + args[0] + ", " + args[1] + ", " + args[2] + ")"
    elif cell == "addsub":
        sub = str(int(node.get("sub", 0))) + "ULL"
        expr = "cell_addsub(" + args[0] + ", " + args[1] + ", " + sub + ")"
    elif cell == "cmp_lt":
        expr = "cmp_lt(" + args[0] + ", " + args[1] + ")"
    else:
        sys.stderr.write("gennet: unknown cell type '" + cell + "' for "
                         + node["name"] + "\n")
        sys.exit(2)

    if node.get("invert"):
        expr = "(" + expr + " ^ 1ULL)"
    sr = node.get("shift_right")
    if sr:
        expr = "(" + expr + " >> " + str(int(sr)) + "ULL)"

    return "    const word_t " + name + " = " + expr + ";"


def main():
    net_path = sys.argv[1] if len(sys.argv) > 1 else "candle.net.json"
    with open(net_path) as f:
        net = json.load(f)

    dev = net["device"]
    DEV = dev.upper()
    pfx = DEV

    # ---- one register slot per node, in declaration order. ----
    order = []
    for grp in ("config_nodes", "buffer_nodes", "const_nodes", "dff_nodes",
                "comb_nodes"):
        for n in net.get(grp, []):
            order.append(n["name"])

    # display ring: emit counter + depth*fields snapshot lanes.
    dr = net.get("display_ring")
    ring_nodes = []
    if dr:
        depth = dr["depth"]
        if depth <= 0 or (depth & (depth - 1)) != 0:
            sys.stderr.write(
                f"gennet: display_ring.depth ({depth}) must be a power of two.\n")
            sys.exit(2)
        order.append(dr["count"])
        for s in range(dr["depth"]):
            for fld in dr["fields"]:
                nm = f"DISP_{s}_{fld}"
                ring_nodes.append((s, fld, nm))
                order.append(nm)

    addr = {nm: i for i, nm in enumerate(order)}
    count = len(order)

    has_cmp_lt = any(n.get("cell") == "cmp_lt" for n in net.get("comb_nodes", []))

    out = []
    out.append("/* GENERATED by gennet.py from " + net_path + " — DO NOT EDIT BY HAND.")
    out.append(" * The " + dev + " device: register lanes + cell-based logic.")
    out.append(" * Netlist-generated; every operation is a structural cell call. */")
    out.append("#ifndef " + DEV + "_GEN_H")
    out.append("#define " + DEV + "_GEN_H")
    out.append('#include "cells.h"')
    out.append("")

    out.append("#define " + pfx + "_REG_COUNT " + str(count) + "u")
    out.append("#define " + pfx + "_WINDOW_BASE " + str(net['window_base']) + "u")
    out.append("")

    for nm in order:
        out.append("#define " + pfx + "_" + nm + " " + str(addr[nm]) + "u")

    if dr:
        out.append("#define " + pfx + "_DISP_STRIDE " + str(len(dr['fields'])) + "u")
        out.append("#define " + pfx + "_DISP_DEPTH " + str(dr['depth']) + "u")
        out.append("#define " + pfx + "_DISP_MASK (" + pfx + "_DISP_DEPTH - 1u)")
    out.append("")

    # ---- comparator helper (gate-netlist; emitted only when used). ----
    if has_cmp_lt:
        out.append(CMP_LT_HELPER)
        out.append("")

    # ---- init: synchronous reset ----
    out.append("static inline void " + dev + "_init(word_t *r) {")
    out.append("    word_t i = 0ULL;")
    out.append("    for (i = 0ULL; i < " + pfx + "_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }")
    # const lanes latch their reset value (driven once, never by the tick).
    for n in net.get("const_nodes", []):
        out.append("    r[" + pfx + "_" + n["name"] + "] = "
                   + str(int(n.get("value", 0))) + "ULL;")
    out.append("}")
    out.append("")

    # ---- one clock edge: READ -> COMPUTE -> WRITE. ----
    out.append("/* " + dev + "_tick: one clock edge. READ all inputs as const")
    out.append(" * locals, COMPUTE via cells (no native C operators), WRITE outputs. */")
    out.append("static inline void " + dev + "_tick(word_t *r) {")
    out.append("    /* READ phase — pre-read every input from registers. */")

    # comb cell calls read registers directly (single source of truth), so the
    # explicit READ-phase locals are documentation of the sampled window. A dff
    # that is recomputed this tick (a same-named comb_node exists) does NOT get a
    # READ-phase local — its value comes from the COMPUTE-phase comb, and a second
    # same-named local would be a C redefinition.
    comb_self = {n["name"] for n in net.get("comb_nodes", [])}
    # A READ-phase local is emitted only when it is actually consumed: either an
    # input to some comb_node, or a hold-dff (no comb writer) whose prior value
    # the WRITE phase re-commits. Emitting an unread local trips -Werror
    # -Wunused-variable; a self-recomputed dff's value comes from its comb local.
    consumed = set()
    for n in net.get("comb_nodes", []):
        consumed.update(n["inputs"])
    comb_writes = set()
    for n in net.get("comb_nodes", []):
        comb_writes.add(n["name"])
    for n in net.get("dff_nodes", []):
        nm = n["name"]
        if nm + "_UPDATE" not in comb_writes and nm not in comb_writes:
            consumed.add(nm)  # hold-dff: WRITE re-commits its read value
    for grp in ("config_nodes", "const_nodes", "dff_nodes"):
        for n in net.get(grp, []):
            if n["name"] in comb_self:
                continue
            if n["name"] not in consumed:
                continue
            name_lower = n["name"].lower()
            out.append("    const word_t " + name_lower + " = r[" + pfx + "_" + n["name"] + "];")
    out.append("    (void)0;")
    out.append("")

    out.append("    /* COMPUTE phase — all logic via cells (no native C operators). */")
    comb = net.get("comb_nodes", [])
    if comb:
        for n in comb:
            out.append(emit_comb(n, pfx))
    else:
        out.append("    /* No combinational logic in this netlist. */")
    out.append("")

    out.append("    /* WRITE phase — commit every dff (no read-after-write). */")
    # Each dff latches the matching *_UPDATE comb result when one exists; the
    # tick-detect / boundary dffs latch their own same-named comb node.
    comb_names = {n["name"] for n in comb}
    for n in net.get("dff_nodes", []):
        nm = n["name"]
        if nm + "_UPDATE" in comb_names:
            src = (nm + "_UPDATE").lower()
        elif nm in comb_names:
            src = nm.lower()
        else:
            src = nm.lower()  # holds prior value (read in READ phase)
        out.append("    r[" + pfx + "_" + nm + "] = " + src + ";")
    out.append("}")
    out.append("")

    # ---- free-running loop (only when the netlist defines a POWER lane) ----
    has_power = any(n["name"] == "POWER"
                    for grp in ("config_nodes", "const_nodes", "dff_nodes")
                    for n in net.get(grp, []))
    out.append("/* " + dev + "_run: free-running self-oscillating clock loop. */")
    out.append("static inline void " + dev + "_run(word_t *r) {")
    if has_power:
        out.append("    while (r[" + pfx + "_POWER] & 1ULL) { " + dev + "_tick(r); }")
    else:
        # No power lane declared yet: a single edge keeps the header self-consistent
        # (no reference to an undefined POWER address). The starter drives ticks.
        out.append("    " + dev + "_tick(r);")
    out.append("}")
    out.append("")

    out.append("#endif /* " + DEV + "_GEN_H */")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
