/* container_gen.h — GENERATED by gen_container.py from container.json. DO NOT EDIT. */
#ifndef CONTAINER_GEN_H
#define CONTAINER_GEN_H
#include <stdint.h>

/* one lean fabric-element record: state word + config word. Grid index = identity. */
typedef struct { uint64_t state; uint64_t cfg; } fabric_element;

static fabric_element storage_element[1045440]; /* REGISTER · 10p · 6 configs */
static fabric_element lut6[522720]; /* CLB · 61p · 25 configs */
static fabric_element muxf7[261360]; /* CLB · 4p · 1 configs */
static fabric_element muxf8[130680]; /* CLB · 4p · 1 configs */
static fabric_element carry8[65340]; /* CLB · 6p · 1 configs */
static fabric_element muxf9[65340]; /* CLB · 4p · 1 configs */
static fabric_element dsp48e2[1968]; /* ARITHMETIC · 54p · 1 configs */
static fabric_element ramb18e2[1968]; /* BLOCKRAM · 87p · 2 configs */
static fabric_element ramb36e2[984]; /* BLOCKRAM · 100p · 2 configs */
static fabric_element io_buffer[668]; /* I · 25p · 31 configs */
static fabric_element ibuf_analog[668]; /* I · 2p · 1 configs */
static fabric_element idelaye3[668]; /* I · 14p · 1 configs */
static fabric_element iserdese3[668]; /* I · 10p · 1 configs */
static fabric_element odelaye3[668]; /* I · 13p · 1 configs */
static fabric_element oserdese3[668]; /* I · 7p · 1 configs */
static fabric_element rxtx_bitslice[668]; /* I · 33p · 1 configs */
static fabric_element rx_bitslice[668]; /* I · 27p · 1 configs */
static fabric_element tx_bitslice[668]; /* I · 18p · 1 configs */
static fabric_element tx_bitslice_tri[668]; /* I · 12p · 1 configs */
static fabric_element uram288[128]; /* BLOCKRAM · 66p · 2 configs */
static fabric_element gthe4_channel[44]; /* ADVANCED · 246p · 1 configs */
static fabric_element gthe4_common[44]; /* ADVANCED · 76p · 1 configs */
static fabric_element gtye4_channel[28]; /* ADVANCED · 238p · 1 configs */
static fabric_element gtye4_common[28]; /* ADVANCED · 77p · 1 configs */
static fabric_element bufg[11]; /* CLOCK · 2p · 1 configs */
static fabric_element bufgce[11]; /* CLOCK · 3p · 1 configs */
static fabric_element bufgce_1[11]; /* CLOCK · 3p · 1 configs */
static fabric_element bufgce_div[11]; /* CLOCK · 4p · 1 configs */
static fabric_element bufgctrl[11]; /* CLOCK · 9p · 1 configs */
static fabric_element bufgmux[11]; /* CLOCK · 4p · 1 configs */
static fabric_element bufgmux_1[11]; /* CLOCK · 4p · 1 configs */
static fabric_element bufgmux_ctrl[11]; /* CLOCK · 4p · 1 configs */
static fabric_element bufg_gt[11]; /* CLOCK · 7p · 1 configs */
static fabric_element bufg_gt_sync[11]; /* CLOCK · 5p · 1 configs */
static fabric_element bufg_ps[11]; /* CLOCK · 2p · 1 configs */
static fabric_element mmcme3_adv[11]; /* CLOCK · 42p · 1 configs */
static fabric_element mmcme3_base[11]; /* CLOCK · 23p · 1 configs */
static fabric_element mmcme4_adv[11]; /* CLOCK · 35p · 1 configs */
static fabric_element mmcme4_base[11]; /* CLOCK · 18p · 1 configs */
static fabric_element plle3_adv[11]; /* CLOCK · 23p · 1 configs */
static fabric_element plle3_base[11]; /* CLOCK · 15p · 1 configs */
static fabric_element plle4_adv[11]; /* CLOCK · 19p · 1 configs */
static fabric_element plle4_base[11]; /* CLOCK · 12p · 1 configs */

typedef struct { const char *name; unsigned long long count; const char *sub; } cast_row;
static const cast_row CAST[] = {
  {"storage_element", 1045440ULL, "REGISTER"},
  {"LUT6", 522720ULL, "CLB"},
  {"MUXF7", 261360ULL, "CLB"},
  {"MUXF8", 130680ULL, "CLB"},
  {"CARRY8", 65340ULL, "CLB"},
  {"MUXF9", 65340ULL, "CLB"},
  {"DSP48E2", 1968ULL, "ARITHMETIC"},
  {"RAMB18E2", 1968ULL, "BLOCKRAM"},
  {"RAMB36E2", 984ULL, "BLOCKRAM"},
  {"IO_BUFFER", 668ULL, "I"},
  {"IBUF_ANALOG", 668ULL, "I"},
  {"IDELAYE3", 668ULL, "I"},
  {"ISERDESE3", 668ULL, "I"},
  {"ODELAYE3", 668ULL, "I"},
  {"OSERDESE3", 668ULL, "I"},
  {"RXTX_BITSLICE", 668ULL, "I"},
  {"RX_BITSLICE", 668ULL, "I"},
  {"TX_BITSLICE", 668ULL, "I"},
  {"TX_BITSLICE_TRI", 668ULL, "I"},
  {"URAM288", 128ULL, "BLOCKRAM"},
  {"GTHE4_CHANNEL", 44ULL, "ADVANCED"},
  {"GTHE4_COMMON", 44ULL, "ADVANCED"},
  {"GTYE4_CHANNEL", 28ULL, "ADVANCED"},
  {"GTYE4_COMMON", 28ULL, "ADVANCED"},
  {"BUFG", 11ULL, "CLOCK"},
  {"BUFGCE", 11ULL, "CLOCK"},
  {"BUFGCE_1", 11ULL, "CLOCK"},
  {"BUFGCE_DIV", 11ULL, "CLOCK"},
  {"BUFGCTRL", 11ULL, "CLOCK"},
  {"BUFGMUX", 11ULL, "CLOCK"},
  {"BUFGMUX_1", 11ULL, "CLOCK"},
  {"BUFGMUX_CTRL", 11ULL, "CLOCK"},
  {"BUFG_GT", 11ULL, "CLOCK"},
  {"BUFG_GT_SYNC", 11ULL, "CLOCK"},
  {"BUFG_PS", 11ULL, "CLOCK"},
  {"MMCME3_ADV", 11ULL, "CLOCK"},
  {"MMCME3_BASE", 11ULL, "CLOCK"},
  {"MMCME4_ADV", 11ULL, "CLOCK"},
  {"MMCME4_BASE", 11ULL, "CLOCK"},
  {"PLLE3_ADV", 11ULL, "CLOCK"},
  {"PLLE3_BASE", 11ULL, "CLOCK"},
  {"PLLE4_ADV", 11ULL, "CLOCK"},
  {"PLLE4_BASE", 11ULL, "CLOCK"},
};
enum { CAST_TYPES = 43 };
static const unsigned long long CAST_TOTAL = 2102961ULL;
static const unsigned long long CAST_SLICES = 65340ULL;
#endif
