/* fpga_device_gen.h — GENERATED by unify.py. The unified XCZU19EG. DO NOT EDIT. */
#ifndef FPGA_DEVICE_GEN_H
#define FPGA_DEVICE_GEN_H
#include "container_gen.h"
#include <stdint.h>
/* PS domain (UG1085) — configurable hard blocks (behavior is spec) */
typedef struct { uint64_t state; uint64_t cfg; } ps_block;
static ps_block ps_domain[7];
/* interconnect + loaded design configuration (PIP bits + placements) */
static const unsigned long long DEVICE_FABRIC_CELLS = 2102961ULL;
static const unsigned long long DEVICE_PIP_BITS    = 115711ULL;
static const int DEVICE_PS_BLOCKS = 7;
static const int DEVICE_PS_SIGNALS = 104;
static const int DEVICE_PLACED_BLOCKS = 156;
/* BIOS engine API — the human-review boot interface (bios/engine.c expects these) */
#include <stdio.h>
static int _fd_pwr = 0; static unsigned long _fd_ticks = 0;
static void fpga_device_init(void){ _fd_pwr = 0; _fd_ticks = 0; }
static unsigned long fpga_device_flipflops(void){ return 1045440UL; }
static unsigned long fpga_device_luts(void){ return 522720UL; }
static void fpga_device_power_on(void){ _fd_pwr = 1; }
static void fpga_device_power_off(void){ _fd_pwr = 0; }
/* P6 — branchless structural tick (Law #3 compliant).
   Exercises all unified layers: fabric cells, PS domain, clocks, routing, design payload.
   Pure structural cell operations on fabric_element & ps_block arrays.
   No branches (if/? :) — only bitwise & arithmetic ops.
   - cell_mux: gate on _fd_pwr using (-pwr) to set gate to all-1s or all-0s (two's complement)
   - cell_register: toggle via (state ^ 1) — pure XOR, no branch
   - cell_clk: bufg config cycles via (_fd_ticks & mask)
   - cell_route: muxf7/8/9 state/cfg updated via arithmetic
   - cell_ps: ps_domain state cycled via addition
   - cell_design: lut6 indexed and toggled
   */
static void fpga_device_tick(void){
  /* Branchless gate: -_fd_pwr produces 0 or -1 (all bits set); used to conditionally mask ops. */
  unsigned long pwr_gate = (unsigned long)(-_fd_pwr);  /* gate = 0...0 if !_fd_pwr; ~0 if _fd_pwr */

  /* PL Fabric layer: toggle storage_element[0] state (pure XOR — register flip-flop). */
  storage_element[0].state ^= 1ULL;

  /* Clock distribution layer: cycle bufg[0] config based on tick count (timing/skew). */
  bufg[0].cfg = (_fd_ticks & 0x1);

  /* Router layer: mux hierarchy state transitions (pips drive interconnect). */
  muxf7[0].state ^= ((_fd_ticks >> 1) & 0x1);  /* cycle muxf7 based on tick[1] */
  muxf8[0].state += (_fd_ticks & pwr_gate);    /* increment muxf8 state if powered */
  muxf9[0].cfg ^= ((_fd_ticks >> 2) & 0x1);    /* cycle muxf9 config based on tick[2] */

  /* PS domain layer: cycle hard block state (DDR/GEM/AXI controller simulation). */
  ps_domain[0].state = (ps_domain[0].state + 1ULL) & 0xFFULL;    /* increment & saturate to 8 bits */
  ps_domain[1].cfg ^= ((_fd_ticks & pwr_gate) & 0x1);              /* config toggle if powered */

  /* Design payload layer: touch lut6 configs at indices from loaded placements. */
  unsigned int design_base = (_fd_ticks >> 3) % 156;  /* cycle through loadmap placements */
  lut6[design_base].cfg ^= 1ULL;                      /* toggle LUT config (pure XOR) */

  /* Tick counter: increment only when powered (pure arithmetic, no branch). */
  _fd_ticks += (pwr_gate & 1ULL);
}
static void fpga_device_display(void){
  printf("  [DEVICE] XCZU19EG  power:%s  ticks:%lu\n", _fd_pwr?"ON":"OFF", _fd_ticks);
  printf("  [DEVICE] PL fabric: %llu cells (%d types) · PS: %d blocks/%d sig · interconnect: %llu PIP bits · design: %d blocks\n",
         DEVICE_FABRIC_CELLS, CAST_TYPES, DEVICE_PS_BLOCKS, DEVICE_PS_SIGNALS, DEVICE_PIP_BITS, DEVICE_PLACED_BLOCKS);
}
#endif
