/* fpga_device_gen.h — GENERATED by unify.py. The unified XCZU19EG. DO NOT EDIT. */
#ifndef FPGA_DEVICE_GEN_H
#define FPGA_DEVICE_GEN_H
#include "container_gen.h"
#include <stdint.h>
/* PS domain (UG1085) — configurable hard blocks (behavior is spec) */
typedef struct { uint64_t state; uint64_t cfg; } ps_block;
static ps_block ps_domain[7];
/* interconnect + loaded design configuration (PIP bits + placements) */
static const unsigned long long DEVICE_FABRIC_CELLS = 2126341ULL;
static const unsigned long long DEVICE_PIP_BITS    = 121671ULL;
static const int DEVICE_PS_BLOCKS = 7;
static const int DEVICE_PS_SIGNALS = 104;
static const int DEVICE_PLACED_BLOCKS = 156;
#endif
