#!/usr/bin/env python3
"""gen_footprint_net.py — EMITTER: writes footprint.net.json.

This python file is the real deliverable (DESIGN_GUIDE step 3): it emits the
netlist describing footprint as addressed register nodes wired as cells
— branchless. gennet.py then GENERATES the device C from this netlist; the
device tick is never hand-written.

Hardware specification for building the Footprint (Indicator) component flip-flop-level from the netlist-generator (emitter-first workflow).

Auto-generated by partslist-to-emitter.py from FOOTPRINT_PARTS_LIST.md
"""
import json

NET = {
    "device": "footprint",
    "window_base": "0x00000000",
    "kind": "market-data",
    "comment": (
        "Hardware specification for building the Footprint (Indicator) component flip-flop-level from the netlist-generator (emitter-first workflow). "
        "(auto-generated from PARTS_LIST)"
    ),

    # --- input lanes (driven from outside the netlist: set by the starter). ---
    "config_nodes": [
        {"name": "DOM_BID_QTY", "type": "u64",
         "comment": "Bid quantity per price level (indexed)"},
        {"name": "DOM_ASK_QTY", "type": "u64",
         "comment": "Ask quantity per price level (indexed)"},
        {"name": "DOM_COUNT", "type": "u64",
         "comment": "Event count per price level"},
        {"name": "DOM_TIME", "type": "u64",
         "comment": "Latest TAI timestamp per price level"},
    ],

    # --- registered outputs (the device's sole writes). -----------------------
    "dff_nodes": [
        {"name": "FOOTPRINT_STATE", "type": "u64",
         "comment": "module state register"}
    ],
}


def main():
    """Emit the netlist as JSON."""
    with open("footprint.net.json", "w") as f:
        json.dump(NET, f, indent=2)
        f.write("\n")
    print("emitted footprint.net.json")


if __name__ == "__main__":
    main()