#!/usr/bin/env python3
"""partslist-to-gennet.py — generate gennet.py from a PARTS_LIST.md specification.

This tool reads an architectural parts list (Markdown format) and produces a
code generator script (gennet.py) that:

1. Reads a netlist.json (the declarative circuit produced by the emitter)
2. Assigns addresses to all nodes (registers, tables, display ring)
3. Generates C code with READ→COMPUTE→WRITE phases
4. Emits structural cell calls (no native operators in COMPUTE)
5. Produces a _gen.h header (the device C code)

The generated gennet.py is a standalone Python script ready to run on any
netlist produced by the emitter (gen_*_net.py). It embeds the C generation
logic directly, using string templates and netlist introspection.

Usage:
    python3 partslist-to-gennet.py PARTS_LIST.md > gennet.py
    chmod +x gennet.py
    python3 gennet.py <device>.net.json > <device>_gen.h
"""
import sys
import re
from pathlib import Path

def extract_device_name(parts_list_text: str) -> str:
    """Extract device name from the PARTS_LIST heading."""
    for line in parts_list_text.split('\n'):
        m = re.match(r'#\s+(\w+)\s+Architectural?\s+Parts', line, re.IGNORECASE)
        if m:
            return m.group(1).lower()
    raise ValueError("Could not extract device name from PARTS_LIST heading")

def generate_gennet(device: str, parts_list_file: str) -> str:
    """Generate gennet.py script for the given device."""
    dev = device
    DEV = device.upper()

    # Build the Python script as lines
    lines = [
        "#!/usr/bin/env python3",
        f'"""gennet.py — generate the {dev} device C from {dev}.net.json.',
        "",
        f"GENERATED by partslist-to-gennet.py from {Path(parts_list_file).name}.",
        "",
        "The device logic is GENERATED from the netlist, never hand-written. Every node",
        "becomes an addressed register slot. Operations are cell calls (cell_addsub,",
        "cell_mux, cell_eqmask, etc.) — NO native C operators in the data path.",
        "",
        "All state lives in addressed registers. The tick function follows strict",
        "READ→COMPUTE→WRITE discipline: pre-read all inputs, compute using cells,",
        "write all outputs (no read-after-write).",
        '"""',
        "import json",
        "import sys",
        "",
        "",
        'HEADER = """/* GENERATED by gennet.py from {0}.net.json — DO NOT EDIT BY HAND.'.format(dev),
        " * The {0} device: register lanes + cell-based logic (no native C operators).".format(dev),
        " * Netlist-generated; every operation is a structural cell call. */",
        "#ifndef {0}_GEN_H".format(DEV),
        "#define {0}_GEN_H".format(DEV),
        '#include "cells.h"',
        '"""',
        "",
        "",
        "def main():",
        '    net_path = sys.argv[1] if len(sys.argv) > 1 else "{0}.net.json"'.format(dev),
        "    with open(net_path) as f:",
        "        net = json.load(f)",
        "",
        "    dev = net[\"device\"]",
        "    DEV = dev.upper()",
        "    pfx = DEV",
        "",
        "    # ---- one register slot per node, in declaration order. ----",
        "    order = []",
        "    for grp in (\"config_nodes\", \"buffer_nodes\", \"dff_nodes\", \"comb_nodes\"):",
        "        for n in net.get(grp, []):",
        "            order.append(n[\"name\"])",
        "",
        "    # display ring: emit counter + depth*fields snapshot lanes.",
        "    dr = net.get(\"display_ring\")",
        "    ring_nodes = []",
        "    if dr:",
        "        depth = dr[\"depth\"]",
        "        if depth <= 0 or (depth & (depth - 1)) != 0:",
        "            sys.stderr.write(",
        '                f"gennet: display_ring.depth ({depth}) must be a power of two.\\n")',
        "            sys.exit(2)",
        "        order.append(dr[\"count\"])",
        "        for s in range(dr[\"depth\"]):",
        "            for fld in dr[\"fields\"]:",
        '                nm = f"DISP_{s}_{fld}"',
        "                ring_nodes.append((s, fld, nm))",
        "                order.append(nm)",
        "",
        "    addr = {nm: i for i, nm in enumerate(order)}",
        "    count = len(order)",
        "",
        "    dff = [n[\"name\"] for n in net.get(\"dff_nodes\", [])]",
        "",
        "    out = []",
        "    out.append(\"/* GENERATED by gennet.py from \" + net_path + \" — DO NOT EDIT BY HAND.\")",
        "    out.append(\" * The \" + dev + \" device: register lanes + cell-based logic.\")",
        "    out.append(\" * Netlist-generated; every operation is a structural cell call. */\")",
        "    out.append(\"#ifndef \" + DEV + \"_GEN_H\")",
        "    out.append(\"#define \" + DEV + \"_GEN_H\")",
        '    out.append(\'#include "cells.h"\')',
        '    out.append("")',
        "",
        "    out.append(\"#define \" + pfx + \"_REG_COUNT \" + str(count) + \"u\")",
        "    out.append(\"#define \" + pfx + \"_WINDOW_BASE \" + str(net['window_base']) + \"u\")",
        "    out.append(\"\")",
        "",
        "    for nm in order:",
        "        out.append(\"#define \" + pfx + \"_\" + nm + \" \" + str(addr[nm]) + \"u\")",
        "",
        "    if dr:",
        "        out.append(\"#define \" + pfx + \"_DISP_STRIDE \" + str(len(dr['fields'])) + \"u\")",
        "        out.append(\"#define \" + pfx + \"_DISP_DEPTH \" + str(dr['depth']) + \"u\")",
        "        out.append(\"#define \" + pfx + \"_DISP_MASK (\" + pfx + \"_DISP_DEPTH - 1u)\")",
        "    out.append(\"\")",
        "",
        "    # ---- init: synchronous reset ----",
        "    out.append(\"static inline void \" + dev + \"_init(word_t *r) {\")",
        "    out.append(\"    word_t i = 0ULL;\")",
        "    out.append(\"    for (i = 0ULL; i < \" + pfx + \"_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }\")",
        "    out.append(\"}\")",
        "    out.append(\"\")",
        "",
        "    # ---- one clock edge: READ -> COMPUTE -> WRITE. ----",
        "    out.append(\"/* \" + dev + \"_tick: one clock edge. READ all inputs as const\")",
        "    out.append(\" * locals, COMPUTE via cells (no native C operators), WRITE outputs. */\")",
        "    out.append(\"static inline void \" + dev + \"_tick(word_t *r) {\")",
        "    out.append(\"    /* READ phase — pre-read every input from registers. */\")",
        "",
        "    for n in net.get(\"config_nodes\", []):",
        "        name_lower = n[\"name\"].lower()",
        "        out.append(\"    const word_t \" + name_lower + \" = r[\" + pfx + \"_\" + n[\"name\"] + \"];\")",
        "",
        "    for n in net.get(\"dff_nodes\", []):",
        "        name_lower = n[\"name\"].lower()",
        "        out.append(\"    const word_t \" + name_lower + \" = r[\" + pfx + \"_\" + n[\"name\"] + \"];\")",
        "    out.append(\"\")",
        "",
        "    out.append(\"    /* COMPUTE phase — all logic via cells (no native C operators). */\")",
        "",
        "    comb_nodes = net.get(\"comb_nodes\", [])",
        "    if comb_nodes:",
        "        for node in comb_nodes:",
        "            cell = node.get(\"cell\")",
        "            inputs = node.get(\"inputs\", [])",
        "            name = node.get(\"name\", \"\").lower()",
        "            if cell == \"addsub\":",
        "                # cell_addsub(a, b, sub) — inputs[2] is the sub flag",
        "                if len(inputs) >= 3:",
        "                    args = \", \".join(inputs[:3])",
        "                elif len(inputs) == 2:",
        "                    args = inputs[0] + \", \" + inputs[1] + \", 0ULL\"",
        "                else:",
        "                    args = \", \".join(inputs)",
        "                out.append(\"    const word_t \" + name + \" = cell_addsub(\" + args + \");\")",
        "            elif cell == \"mux\":",
        "                # cell_mux(false_case, true_case, sel) — order matters",
        "                if len(inputs) == 3:",
        "                    out.append(\"    const word_t \" + name + \" = cell_mux(\" + inputs[0] + \", \" + inputs[1] + \", \" + inputs[2] + \");\")",
        "            elif cell == \"cmp_lt\":",
        "                # cmp_lt(a, b)",
        "                if len(inputs) >= 2:",
        "                    out.append(\"    const word_t \" + name + \" = cmp_lt(\" + inputs[0] + \", \" + inputs[1] + \");\")",
        "            elif cell in (\"eqmask\", \"gate\", \"buf\", \"and\", \"or\", \"xor\", \"not\", \"dff\"):",
        "                # cell_<op>(args...)",
        "                args = \", \".join(inputs)",
        "                out.append(\"    const word_t \" + name + \" = cell_\" + cell + \"(\" + args + \");\")",
        "            else:",
        "                out.append(\"    const word_t \" + name + \" = 0ULL; /* WARNING: unknown cell '\" + str(cell) + \"' */\")",
        "    else:",
        "        out.append(\"    /* No combinational logic in this netlist. */\")",
        "    out.append(\"\")",
        "",
        "    out.append(\"    /* WRITE phase — commit every dff (no read-after-write). */\")",
        "    for n in net.get(\"dff_nodes\", []):",
        "        name_lower = n[\"name\"].lower()",
        "        out.append(\"    r[\" + pfx + \"_\" + n[\"name\"] + \"] = \" + name_lower + \";\")",
        "    out.append(\"}\")",
        "    out.append(\"\")",
        "",
        "    # ---- free-running loop ----",
        "    out.append(\"/* \" + dev + \"_run: free-running self-oscillating clock loop. */\")",
        "    out.append(\"static inline void \" + dev + \"_run(word_t *r) {\")",
        "    out.append(\"    while (r[\" + pfx + \"_POWER] & 1ULL) { \" + dev + \"_tick(r); }\")",
        "    out.append(\"}\")",
        "    out.append(\"\")",
        "",
        "    out.append(\"#endif /* \" + DEV + \"_GEN_H */\")",
        "",
        '    sys.stdout.write("\\n".join(out) + "\\n")',
        "",
        "",
        "if __name__ == \"__main__\":",
        "    main()",
    ]

    return "\n".join(lines)

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 partslist-to-gennet.py PARTS_LIST.md > gennet.py", file=sys.stderr)
        sys.exit(1)

    parts_list_path = sys.argv[1]

    try:
        with open(parts_list_path) as f:
            parts_list_text = f.read()
    except FileNotFoundError:
        print(f"Error: {parts_list_path} not found", file=sys.stderr)
        sys.exit(1)

    try:
        device = extract_device_name(parts_list_text)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    # Generate and output the gennet.py script
    gennet_code = generate_gennet(device, parts_list_path)
    print(gennet_code)

if __name__ == "__main__":
    main()
