/* GENERATED by gennet.py from candle.net.json — DO NOT EDIT BY HAND.
 * The candle device: register lanes + cell-based logic.
 * Netlist-generated; every operation is a structural cell call. */
#ifndef CANDLE_GEN_H
#define CANDLE_GEN_H
#include "cells.h"

#define CANDLE_REG_COUNT 44u
#define CANDLE_WINDOW_BASE 0x00000000u

#define CANDLE_DOM_BID_PRICE 0u
#define CANDLE_DOM_ASK_PRICE 1u
#define CANDLE_DOM_BID_QTY 2u
#define CANDLE_DOM_ASK_QTY 3u
#define CANDLE_TF_BAR_SEQ_REG 4u
#define CANDLE_CANDLE_OPEN_SET_HOLD 5u
#define CANDLE_CANDLE_OPEN_SET_FRESH 6u
#define CANDLE_CANDLE_BID_OPEN 7u
#define CANDLE_CANDLE_BID_HIGH 8u
#define CANDLE_CANDLE_BID_LOW 9u
#define CANDLE_CANDLE_BID_CLOSE 10u
#define CANDLE_CANDLE_ASK_OPEN 11u
#define CANDLE_CANDLE_ASK_HIGH 12u
#define CANDLE_CANDLE_ASK_LOW 13u
#define CANDLE_CANDLE_ASK_CLOSE 14u
#define CANDLE_CANDLE_VOLUME_BID 15u
#define CANDLE_CANDLE_VOLUME_ASK 16u
#define CANDLE_CANDLE_TRUE_RANGE_BID 17u
#define CANDLE_CANDLE_TRUE_RANGE_ASK 18u
#define CANDLE_CANDLE_INTRABAR_QTY_DELTA 19u
#define CANDLE_CANDLE_MID 20u
#define CANDLE_CANDLE_OPEN_SET 21u
#define CANDLE_CANDLE_LAST_TF_SEQ 22u
#define CANDLE_CANDLE_BID_TICK 26u
#define CANDLE_CANDLE_ASK_TICK 27u
#define CANDLE_CANDLE_BAR_BOUNDARY 42u
#define CANDLE_CANDLE_BID_TICK 26u
#define CANDLE_CANDLE_ASK_TICK 27u
#define CANDLE_CANDLE_BID_OPEN_UPDATE 28u
#define CANDLE_CANDLE_BID_HIGH_UPDATE 29u
#define CANDLE_CANDLE_BID_LOW_UPDATE 30u
#define CANDLE_CANDLE_BID_CLOSE_UPDATE 31u
#define CANDLE_CANDLE_ASK_OPEN_UPDATE 32u
#define CANDLE_CANDLE_ASK_HIGH_UPDATE 33u
#define CANDLE_CANDLE_ASK_LOW_UPDATE 34u
#define CANDLE_CANDLE_ASK_CLOSE_UPDATE 35u
#define CANDLE_CANDLE_VOLUME_BID_UPDATE 36u
#define CANDLE_CANDLE_VOLUME_ASK_UPDATE 37u
#define CANDLE_CANDLE_TRUE_RANGE_BID_UPDATE 38u
#define CANDLE_CANDLE_TRUE_RANGE_ASK_UPDATE 39u
#define CANDLE_CANDLE_INTRABAR_QTY_DELTA_UPDATE 40u
#define CANDLE_CANDLE_MID_UPDATE 41u
#define CANDLE_CANDLE_BAR_BOUNDARY 42u
#define CANDLE_CANDLE_OPEN_SET_UPDATE 43u


/* cmp_lt: gate-netlist comparator. Returns 1 (bit0) iff a < b (unsigned).
 * a - b = a + (~b) + 1 via 64 full-adder cells; the carry-out of the top bit is
 * (a >= b). So (a < b) = carry ^ 1. Pure gate algebra, no native C compare. */
static inline word_t cmp_lt(word_t a, word_t b) {
    word_t carry = 1ULL;                 /* +1 for two's-complement of b */
    word_t i = 0ULL;
    for (i = 0ULL; i < 64ULL; i = i + 1ULL) {
        const word_t aa = (a >> i) & 1ULL;
        const word_t nb = (cell_not(b) >> i) & 1ULL;     /* ~b bit */
        const word_t fa = cell_fa(aa, nb, carry);
        carry           = (fa >> 1) & 1ULL;              /* carry-out to next */
    }
    return (carry & 1ULL) ^ 1ULL;        /* carry==0 (borrow) == (a < b) */
}


static inline void candle_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < CANDLE_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
    r[CANDLE_CANDLE_OPEN_SET_HOLD] = 1ULL;
    r[CANDLE_CANDLE_OPEN_SET_FRESH] = 0ULL;
}

/* candle_tick: one clock edge. READ all inputs as const
 * locals, COMPUTE via cells (no native C operators), WRITE outputs. */
static inline void candle_tick(word_t *r) {
    /* READ phase — pre-read every input from registers. */
    const word_t dom_bid_price = r[CANDLE_DOM_BID_PRICE];
    const word_t dom_ask_price = r[CANDLE_DOM_ASK_PRICE];
    const word_t dom_bid_qty = r[CANDLE_DOM_BID_QTY];
    const word_t dom_ask_qty = r[CANDLE_DOM_ASK_QTY];
    const word_t tf_bar_seq_reg = r[CANDLE_TF_BAR_SEQ_REG];
    const word_t candle_open_set_hold = r[CANDLE_CANDLE_OPEN_SET_HOLD];
    const word_t candle_open_set_fresh = r[CANDLE_CANDLE_OPEN_SET_FRESH];
    const word_t candle_bid_open = r[CANDLE_CANDLE_BID_OPEN];
    const word_t candle_bid_high = r[CANDLE_CANDLE_BID_HIGH];
    const word_t candle_bid_low = r[CANDLE_CANDLE_BID_LOW];
    const word_t candle_bid_close = r[CANDLE_CANDLE_BID_CLOSE];
    const word_t candle_ask_open = r[CANDLE_CANDLE_ASK_OPEN];
    const word_t candle_ask_high = r[CANDLE_CANDLE_ASK_HIGH];
    const word_t candle_ask_low = r[CANDLE_CANDLE_ASK_LOW];
    const word_t candle_ask_close = r[CANDLE_CANDLE_ASK_CLOSE];
    const word_t candle_volume_bid = r[CANDLE_CANDLE_VOLUME_BID];
    const word_t candle_volume_ask = r[CANDLE_CANDLE_VOLUME_ASK];
    const word_t candle_open_set = r[CANDLE_CANDLE_OPEN_SET];
    const word_t candle_last_tf_seq = r[CANDLE_CANDLE_LAST_TF_SEQ];
    (void)0;

    /* COMPUTE phase — all logic via cells (no native C operators). */
    const word_t candle_bid_tick = (cell_eqmask(dom_bid_price, candle_bid_close) ^ 1ULL);
    const word_t candle_ask_tick = (cell_eqmask(dom_ask_price, candle_ask_close) ^ 1ULL);
    const word_t candle_bid_open_update = cell_mux(dom_bid_price, candle_bid_open, candle_open_set);
    const word_t candle_bid_high_update = cmp_lt(candle_bid_high, dom_bid_price);
    const word_t candle_bid_low_update = cmp_lt(dom_bid_price, candle_bid_low);
    const word_t candle_bid_close_update = cell_buf(dom_bid_price);
    const word_t candle_ask_open_update = cell_mux(dom_ask_price, candle_ask_open, candle_open_set);
    const word_t candle_ask_high_update = cmp_lt(candle_ask_high, dom_ask_price);
    const word_t candle_ask_low_update = cmp_lt(dom_ask_price, candle_ask_low);
    const word_t candle_ask_close_update = cell_buf(dom_ask_price);
    const word_t candle_volume_bid_update = cell_addsub(candle_volume_bid, candle_bid_tick, 0ULL);
    const word_t candle_volume_ask_update = cell_addsub(candle_volume_ask, candle_ask_tick, 0ULL);
    const word_t candle_true_range_bid_update = cell_addsub(candle_bid_high, candle_bid_low, 1ULL);
    const word_t candle_true_range_ask_update = cell_addsub(candle_ask_high, candle_ask_low, 1ULL);
    const word_t candle_intrabar_qty_delta_update = cell_addsub(dom_ask_qty, dom_bid_qty, 1ULL);
    const word_t candle_mid_update = (cell_addsub(candle_bid_high, candle_ask_low, 0ULL) >> 1ULL);
    const word_t candle_bar_boundary = (cell_eqmask(candle_last_tf_seq, tf_bar_seq_reg) ^ 1ULL);
    const word_t candle_open_set_update = cell_mux(candle_open_set_hold, candle_open_set_fresh, candle_bar_boundary);

    /* WRITE phase — commit every dff (no read-after-write). */
    r[CANDLE_CANDLE_BID_OPEN] = candle_bid_open_update;
    r[CANDLE_CANDLE_BID_HIGH] = candle_bid_high_update;
    r[CANDLE_CANDLE_BID_LOW] = candle_bid_low_update;
    r[CANDLE_CANDLE_BID_CLOSE] = candle_bid_close_update;
    r[CANDLE_CANDLE_ASK_OPEN] = candle_ask_open_update;
    r[CANDLE_CANDLE_ASK_HIGH] = candle_ask_high_update;
    r[CANDLE_CANDLE_ASK_LOW] = candle_ask_low_update;
    r[CANDLE_CANDLE_ASK_CLOSE] = candle_ask_close_update;
    r[CANDLE_CANDLE_VOLUME_BID] = candle_volume_bid_update;
    r[CANDLE_CANDLE_VOLUME_ASK] = candle_volume_ask_update;
    r[CANDLE_CANDLE_TRUE_RANGE_BID] = candle_true_range_bid_update;
    r[CANDLE_CANDLE_TRUE_RANGE_ASK] = candle_true_range_ask_update;
    r[CANDLE_CANDLE_INTRABAR_QTY_DELTA] = candle_intrabar_qty_delta_update;
    r[CANDLE_CANDLE_MID] = candle_mid_update;
    r[CANDLE_CANDLE_OPEN_SET] = candle_open_set_update;
    r[CANDLE_CANDLE_LAST_TF_SEQ] = candle_last_tf_seq;
    r[CANDLE_CANDLE_BID_TICK] = candle_bid_tick;
    r[CANDLE_CANDLE_ASK_TICK] = candle_ask_tick;
    r[CANDLE_CANDLE_BAR_BOUNDARY] = candle_bar_boundary;
}

/* candle_run: free-running self-oscillating clock loop. */
static inline void candle_run(word_t *r) {
    candle_tick(r);
}

#endif /* CANDLE_GEN_H */
