#!/usr/bin/env python3
"""gennet.py — generate the adapter device C from adapter.net.json.

The device logic is GENERATED from the netlist, never hand-written (nothing for
an AI to abuse). Every node becomes an addressed register slot; every operation
becomes a cell call between register slots. The comparator (<=) is emitted as a
bit-serial GATE NETLIST of cell_fa/cell_not — not a C compare.

Generated data path contains ZERO if/switch/?: — selection is mask algebra in
the cells. The free-running clock loop (power-bit gated) is the canonical clock
primitive and lives here in the device, not in any test.
"""
import json
import sys


HEADER = """/* GENERATED by gennet.py from adapter.net.json — DO NOT EDIT BY HAND.
 * The adapter device: clock + buffer interface + pacer + write-out, all as a
 * netlist of cells over addressed registers. No if/switch/?: in the data path. */
#ifndef ADAPTER_GEN_H
#define ADAPTER_GEN_H
#include "cells.h"
#include "buffer.h"
#include "wire_gen.h"   /* the wire's CANONICAL bus lane map (generated from
                         * ../wire/wire.net.json by the wire's gennet — single
                         * source of truth). The adapter deposits into these lanes;
                         * it does NOT keep a private copy of the map. */
"""


def emit_cmp_le_function():
    """Emit cmp_le(ts, now) -> 1 iff ts <= now, built ONLY from cells.

    ts <= now  <=>  now - ts does not borrow out of bit 63.
    now - ts = now + (~ts) + 1. Bit-serial through cell_fa; the final carry-out
    (cout from bit 63) is 1 exactly when now >= ts (unsigned). That carry bit
    is the <= result. Pure gate netlist — no C relational operator.
    """
    return """
/* cmp_le: gate-netlist comparator. Returns 1 (bit0) iff ts <= now.
 * Implemented as unsigned (now - ts) via 64 full-adder cells over (~ts)+1;
 * the carry-out of the top bit is the (now >= ts) i.e. (ts <= now) result. */
static inline word_t cmp_le(word_t ts, word_t now) {
    word_t carry = 1ULL;                 /* +1 for two's-complement of ts */
    word_t i = 0ULL;
    /* This loop is the GENERATOR-level unrolling of a 64-cell gate netlist,
     * not a data-path branch: it is straight-line cell composition. No
     * conditional selects the result — the carry chain does. */
    for (i = 0ULL; i < 64ULL; i = i + 1ULL) {
        const word_t a   = (now >> i) & 1ULL;
        const word_t nb  = (cell_not(ts) >> i) & 1ULL;   /* ~ts bit */
        const word_t fa  = cell_fa(a, nb, carry);
        carry            = (fa >> 1) & 1ULL;             /* carry-out to next */
    }
    return carry & 1ULL;                 /* final carry-out == (ts <= now) */
}
"""


def main():
    net_path = sys.argv[1] if len(sys.argv) > 1 else "adapter.net.json"
    with open(net_path) as f:
        net = json.load(f)

    # ---- assign addresses: one register slot per node, in declaration order.
    order = []
    for grp in ("config_nodes", "buffer_nodes", "dff_nodes", "comb_nodes"):
        for n in net.get(grp, []):
            order.append(n["name"])

    # display ring: an emit counter + depth*fields snapshot lanes (addressed regs).
    dr = net.get("display_ring")
    ring_nodes = []
    if dr:
        depth = dr["depth"]
        if depth <= 0 or (depth & (depth - 1)) != 0:
            sys.stderr.write(
                f"gennet: display_ring.depth ({depth}) must be a power of two "
                f"(ring index is a branchless mask cell: emit_cnt & (depth-1)).\n")
            sys.exit(2)
        order.append(dr["count"])              # DISP_EMIT_COUNT
        for s in range(dr["depth"]):
            for fld in dr["fields"]:
                nm = f"DISP_{s}_{fld}"
                ring_nodes.append((s, fld, nm))
                order.append(nm)

    addr = {nm: i for i, nm in enumerate(order)}
    count = len(order)

    dff = [n["name"] for n in net.get("dff_nodes", [])]
    clk = net["clock"]
    pos = net["pos"]
    wo = net["writeout"]
    dep = net.get("deposit")

    out = [HEADER]
    out.append(f"#define ADP_REG_COUNT {count}u")
    out.append(f"#define ADP_WINDOW_BASE {net['window_base']}u\n")
    for nm in order:
        out.append(f"#define ADP_{nm} {addr[nm]}u")
    if dr:
        out.append(f"#define ADP_DISP_STRIDE {len(dr['fields'])}u")
        out.append(f"#define ADP_DISP_DEPTH {dr['depth']}u")
        # Ring wrap mask DERIVED from depth (power of two) — not a second literal.
        # Depth changes propagate; the ring index is cell_and(emit_cnt, ADP_DISP_MASK).
        out.append("#define ADP_DISP_MASK (ADP_DISP_DEPTH - 1u)")
    out.append("")
    out.append(emit_cmp_le_function())

    # ---- init: power-off reset values (synchronous reset model: zero everything;
    #      static config + power are set by the starter before run). ------------
    out.append("static inline void adapter_init(word_t *r) {")
    out.append("    word_t i = 0ULL;")
    out.append("    for (i = 0ULL; i < ADP_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }")
    out.append("}")
    out.append("")

    # ---- one clock edge: READ -> COMPUTE -> WRITE. -------------------------
    out.append("/* adapter_tick: one real-world clock edge. READ all inputs as const")
    out.append(" * locals, COMPUTE the pacer (gate comparator) and write-out selects,")
    out.append(" * WRITE every dff. Write-only WRITE phase; no read-after-write. */")
    out.append("static inline void adapter_tick(word_t *r, wire_word_t *bus) {")
    out.append("    /* READ phase — pre-read every operand from its register. */")
    out.append("    const word_t power   = r[ADP_ADP_POWER] & 1ULL;")
    out.append("    const word_t clk     = r[ADP_ADP_CLK];")
    out.append("    const word_t pos_cur = r[ADP_POS];")
    # buffer presents records[POS] into the buffer input registers before tick.
    out.append("    buffer_present(r, pos_cur);")
    out.append("    const word_t rx_ts    = r[ADP_RX_TS];")
    out.append("    const word_t in_range = r[ADP_IN_RANGE] & 1ULL;")
    out.append("    const word_t raw_bid  = r[ADP_RAW_BID];")
    out.append("    const word_t raw_ask  = r[ADP_RAW_ASK];")
    out.append("    const word_t rx_seq   = r[ADP_RX_SEQ];")
    out.append("    const word_t cfg_sym  = r[ADP_WIRE_SYMBOL];")
    out.append("    const word_t cfg_pip  = r[ADP_WIRE_PIP];")
    out.append("    const word_t cfg_com  = r[ADP_WIRE_COMMISSION];")
    out.append("    const word_t cfg_speed = r[ADP_SPEED];")
    out.append("")
    out.append("    /* COMPUTE phase — pacer: DUE = (RX_TS <= now) & IN_RANGE (gates). */")
    out.append("    const word_t ts_le_now = cmp_le(rx_ts, clk);")
    out.append("    const word_t due       = cell_and(ts_le_now, in_range) & 1ULL;")
    out.append("    /* clock step: SPEED while powered, 0 while off (register-backed gate). */")
    out.append("    const word_t clk_step  = cell_gate(cfg_speed, power);")
    out.append("    /* clock: free-running while powered, real-world rate scaled by SPEED. */")
    out.append("    const word_t clk_next  = cell_addsub(clk, clk_step, 0ULL);")
    out.append("    /* pos: consume on emit (POS += DUE). */")
    out.append("    const word_t pos_next  = cell_addsub(pos_cur, due, 0ULL);")
    out.append("    /* write-out selects: en=DUE gated dffs (mask-algebra mux in cell_dff). */")
    out.append("    const word_t bid_next  = cell_dff(r[ADP_WIRE_BID_PX],       raw_bid, due);")
    out.append("    const word_t ask_next  = cell_dff(r[ADP_WIRE_ASK_PX],       raw_ask, due);")
    out.append("    const word_t time_next = cell_dff(r[ADP_WIRE_TIME],         rx_ts,   due);")
    out.append("    const word_t seq_next  = cell_dff(r[ADP_WIRE_SEQ],          rx_seq,  due);")
    out.append("    const word_t sym_next  = cell_dff(r[ADP_WIRE_SYMBOL_O],     cfg_sym, due);")
    out.append("    const word_t pip_next  = cell_dff(r[ADP_WIRE_PIP_O],        cfg_pip, due);")
    out.append("    const word_t com_next  = cell_dff(r[ADP_WIRE_COMMISSION_O], cfg_com, due);")
    out.append("    /* WIRE_VALID <= DUE, latched while powered. */")
    out.append("    const word_t valid_next = cell_dff(r[ADP_WIRE_VALID], due, power);")
    out.append("")

    # display ring append: snapshot the emission into slot DISP_EMIT_COUNT.
    ring_writes = []
    if dr:
        out.append("    /* display ring: append a snapshot on emit, wrapping at depth so the")
        out.append("     * newest `depth` emits are retained. Write slot = emit_cnt & (depth-1)")
        out.append("     * — a branchless mask cell (depth is a power of two); no %, no if.")
        out.append("     * A display surface (addressed regs), scanned raw off-clock. */")
        out.append("    const word_t emit_cnt = r[ADP_" + dr["count"] + "];")
        out.append("    const word_t wr_slot  = cell_and(emit_cnt, ADP_DISP_MASK);")
        field_src = {
            "WIRE_VALID": "due",
            "WIRE_BID_PX": "raw_bid",
            "WIRE_ASK_PX": "raw_ask",
            "WIRE_TIME": "rx_ts",
            "WIRE_SEQ": "rx_seq",
            "ADP_CLK_AT_EMIT": "clk",
        }
        for (s, fld, nm) in ring_nodes:
            sel = f"(cell_eqmask(wr_slot, {s}ULL) & due)"
            src = field_src[fld]
            out.append(f"    const word_t rw_{nm} = cell_dff(r[ADP_{nm}], {src}, {sel});")
            ring_writes.append(nm)
        out.append("    const word_t emit_cnt_next = cell_addsub(emit_cnt, due, 0ULL);")
        out.append("")
    out.append("    /* WRITE phase — commit every dff (registered hop). */")
    out.append("    r[ADP_ADP_CLK]            = clk_next;")
    out.append("    r[ADP_POS]               = pos_next;")
    out.append("    r[ADP_TS_LE_NOW]         = ts_le_now;")
    out.append("    r[ADP_DUE]               = due;")
    out.append("    r[ADP_CLK_STEP]          = clk_step;")
    out.append("    r[ADP_WIRE_BID_PX]       = bid_next;")
    out.append("    r[ADP_WIRE_ASK_PX]       = ask_next;")
    out.append("    r[ADP_WIRE_TIME]         = time_next;")
    out.append("    r[ADP_WIRE_SEQ]          = seq_next;")
    out.append("    r[ADP_WIRE_SYMBOL_O]     = sym_next;")
    out.append("    r[ADP_WIRE_PIP_O]        = pip_next;")
    out.append("    r[ADP_WIRE_COMMISSION_O] = com_next;")
    out.append("    r[ADP_WIRE_VALID]        = valid_next;")
    if dr:
        for nm in ring_writes:
            out.append(f"    r[ADP_{nm}] = rw_{nm};")
        out.append("    r[ADP_" + dr["count"] + "] = emit_cnt_next;")
    if dep:
        out.append("")
        out.append("    /* DEPOSIT phase — DRIVE the passive wire bus. The adapter is the")
        out.append("     * bus's sole writer: copy the registered output flops into the wire")
        out.append("     * window (where the WIRE_* lanes live and the NIC samples). Plain")
        out.append("     * register writes of already-computed gated values — branchless. */")
        for lane in dep["lanes"]:
            out.append(f"    bus[WIRE_{lane['bus']}] = {lane['from']};")
    out.append("}")
    out.append("")

    # ---- the canonical free-running clock loop (power-bit gated). -----------
    out.append("/* adapter_run: the canonical clock primitive. Power on once; the clock")
    out.append(" * self-oscillates until the buffer is exhausted (POS == count). Nothing")
    out.append(" * external advances it. The starter sets ADP_POWER and calls this, then")
    out.append(" * steps away — there is no main() the device slaves to. */")
    out.append("static inline void adapter_run(word_t *r, wire_word_t *bus) {")
    out.append("    while ((r[ADP_ADP_POWER] & 1ULL) && buffer_in_range(r[ADP_POS])) {")
    out.append("        adapter_tick(r, bus);")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append("#endif /* ADAPTER_GEN_H */")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
