/* GENERATED by gennet.py from rebuild/fractal.net.json — DO NOT EDIT BY HAND.
 * The fractal device: register lanes + cell-based logic (READ->COMPUTE->WRITE).
 * Netlist-generated; every data operation is a structural cell call. */
#ifndef FRACTAL_GEN_H
#define FRACTAL_GEN_H
#include "cells.h"

#define FRACTAL_REG_COUNT 41u

#define FRACTAL_TF_BAR_SEQ_REG 0u
#define FRACTAL_H0 1u
#define FRACTAL_H1 2u
#define FRACTAL_H2 3u
#define FRACTAL_H3 4u
#define FRACTAL_H4 5u
#define FRACTAL_L0 6u
#define FRACTAL_L1 7u
#define FRACTAL_L2 8u
#define FRACTAL_L3 9u
#define FRACTAL_L4 10u
#define FRACTAL_ONE 11u
#define FRACTAL_FRAC_THREE 12u
#define FRACTAL_FRAC_FIVE 13u
#define FRACTAL_MASK255 14u
#define FRACTAL_IND_FRAC_UP_PRICE_REG 15u
#define FRACTAL_IND_FRAC_DN_PRICE_REG 16u
#define FRACTAL_CS2_RAW 17u
#define FRACTAL_CS2 18u
#define FRACTAL_SEQ_LT5 19u
#define FRACTAL_SEQ_GE5 20u
#define FRACTAL_UP_GT0 21u
#define FRACTAL_UP_GT1 22u
#define FRACTAL_UP_GT3 23u
#define FRACTAL_UP_GT4 24u
#define FRACTAL_UP_AND_A 25u
#define FRACTAL_UP_AND_B 26u
#define FRACTAL_UP_AND_C 27u
#define FRACTAL_IS_UP 28u
#define FRACTAL_DN_LT0 29u
#define FRACTAL_DN_LT1 30u
#define FRACTAL_DN_LT3 31u
#define FRACTAL_DN_LT4 32u
#define FRACTAL_DN_AND_A 33u
#define FRACTAL_DN_AND_B 34u
#define FRACTAL_DN_AND_C 35u
#define FRACTAL_IS_DN 36u
#define FRACTAL_UP_PRICE_UPDATE 37u
#define FRACTAL_DN_PRICE_UPDATE 38u
#define FRACTAL_IND_FRAC_UP_PRICE_OUT 39u
#define FRACTAL_IND_FRAC_DN_PRICE_OUT 40u


/* cmp_lt: gate-netlist comparator. Returns 1 (bit0) iff a < b (unsigned).
 * a - b = a + (~b) + 1 via 64 full-adder cells; the carry-out of the top bit is
 * (a >= b). So (a < b) = carry ^ 1. Pure gate algebra, no native C compare. */
static inline word_t cmp_lt(word_t a, word_t b) {
    word_t carry = 1ULL;                 /* +1 for two's-complement of b */
    word_t i = 0ULL;
    for (i = 0ULL; i < 64ULL; i = i + 1ULL) {
        const word_t aa = (a >> i) & 1ULL;
        const word_t nb = (cell_not(b) >> i) & 1ULL;     /* ~b bit */
        const word_t fa = cell_fa(aa, nb, carry);
        carry           = (fa >> 1) & 1ULL;              /* carry-out to next */
    }
    return (carry & 1ULL) ^ 1ULL;        /* carry==0 (borrow) == (a < b) */
}


static inline void fractal_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < FRACTAL_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
    r[FRACTAL_ONE] = 1ULL;
    r[FRACTAL_FRAC_THREE] = 3ULL;
    r[FRACTAL_FRAC_FIVE] = 5ULL;
    r[FRACTAL_MASK255] = 255ULL;
}

/* fractal_tick: one clock edge. READ inputs as const locals,
 * COMPUTE via cells (no native add/sub/mul on data), WRITE every register. */
static inline void fractal_tick(word_t *r) {
    /* READ phase — pre-read every consumed register value. */
    const word_t tf_bar_seq_reg = r[FRACTAL_TF_BAR_SEQ_REG];
    const word_t h0 = r[FRACTAL_H0];
    const word_t h1 = r[FRACTAL_H1];
    const word_t h2 = r[FRACTAL_H2];
    const word_t h3 = r[FRACTAL_H3];
    const word_t h4 = r[FRACTAL_H4];
    const word_t l0 = r[FRACTAL_L0];
    const word_t l1 = r[FRACTAL_L1];
    const word_t l2 = r[FRACTAL_L2];
    const word_t l3 = r[FRACTAL_L3];
    const word_t l4 = r[FRACTAL_L4];
    const word_t one = r[FRACTAL_ONE];
    const word_t frac_three = r[FRACTAL_FRAC_THREE];
    const word_t frac_five = r[FRACTAL_FRAC_FIVE];
    const word_t mask255 = r[FRACTAL_MASK255];
    const word_t ind_frac_up_price_reg = r[FRACTAL_IND_FRAC_UP_PRICE_REG];
    const word_t ind_frac_dn_price_reg = r[FRACTAL_IND_FRAC_DN_PRICE_REG];

    /* COMPUTE phase — combinational cell chain (declaration order). */
    const word_t cs2_raw = cell_addsub(tf_bar_seq_reg, frac_three, 1ULL);
    const word_t cs2 = cell_and(cs2_raw, mask255);
    const word_t seq_lt5 = cmp_lt(tf_bar_seq_reg, frac_five);
    const word_t seq_ge5 = cell_xor(seq_lt5, one);
    const word_t up_gt0 = cmp_lt(h0, h2);
    const word_t up_gt1 = cmp_lt(h1, h2);
    const word_t up_gt3 = cmp_lt(h3, h2);
    const word_t up_gt4 = cmp_lt(h4, h2);
    const word_t up_and_a = cell_and(up_gt0, up_gt1);
    const word_t up_and_b = cell_and(up_gt3, up_gt4);
    const word_t up_and_c = cell_and(up_and_a, up_and_b);
    const word_t is_up = cell_and(up_and_c, seq_ge5);
    const word_t dn_lt0 = cmp_lt(l2, l0);
    const word_t dn_lt1 = cmp_lt(l2, l1);
    const word_t dn_lt3 = cmp_lt(l2, l3);
    const word_t dn_lt4 = cmp_lt(l2, l4);
    const word_t dn_and_a = cell_and(dn_lt0, dn_lt1);
    const word_t dn_and_b = cell_and(dn_lt3, dn_lt4);
    const word_t dn_and_c = cell_and(dn_and_a, dn_and_b);
    const word_t is_dn = cell_and(dn_and_c, seq_ge5);
    const word_t up_price_update = cell_mux(ind_frac_up_price_reg, h2, is_up);
    const word_t dn_price_update = cell_mux(ind_frac_dn_price_reg, l2, is_dn);

    /* WRITE phase — gated dff commit: r[X] = cell_dff(q, fed_by, enable). */
    r[FRACTAL_IND_FRAC_UP_PRICE_REG] = cell_dff(ind_frac_up_price_reg, up_price_update, one);
    r[FRACTAL_IND_FRAC_DN_PRICE_REG] = cell_dff(ind_frac_dn_price_reg, dn_price_update, one);
    r[FRACTAL_CS2_RAW] = cs2_raw;
    r[FRACTAL_CS2] = cs2;
    r[FRACTAL_SEQ_LT5] = seq_lt5;
    r[FRACTAL_SEQ_GE5] = seq_ge5;
    r[FRACTAL_UP_GT0] = up_gt0;
    r[FRACTAL_UP_GT1] = up_gt1;
    r[FRACTAL_UP_GT3] = up_gt3;
    r[FRACTAL_UP_GT4] = up_gt4;
    r[FRACTAL_UP_AND_A] = up_and_a;
    r[FRACTAL_UP_AND_B] = up_and_b;
    r[FRACTAL_UP_AND_C] = up_and_c;
    r[FRACTAL_IS_UP] = is_up;
    r[FRACTAL_DN_LT0] = dn_lt0;
    r[FRACTAL_DN_LT1] = dn_lt1;
    r[FRACTAL_DN_LT3] = dn_lt3;
    r[FRACTAL_DN_LT4] = dn_lt4;
    r[FRACTAL_DN_AND_A] = dn_and_a;
    r[FRACTAL_DN_AND_B] = dn_and_b;
    r[FRACTAL_DN_AND_C] = dn_and_c;
    r[FRACTAL_IS_DN] = is_dn;
    r[FRACTAL_UP_PRICE_UPDATE] = up_price_update;
    r[FRACTAL_DN_PRICE_UPDATE] = dn_price_update;
    r[FRACTAL_IND_FRAC_UP_PRICE_OUT] = ind_frac_up_price_reg;
    r[FRACTAL_IND_FRAC_DN_PRICE_OUT] = ind_frac_dn_price_reg;

}

/* fractal_run: canonical free-running clock. Power on once; the clock
 * self-oscillates while the power bit is set. Nothing external steps it. */
static inline void fractal_run(word_t *r) {
    fractal_tick(r);
}

#endif /* FRACTAL_GEN_H */
