/* GENERATED by gennet.py from rebuild/internal.net.json — DO NOT EDIT BY HAND.
 * The internal device: register lanes + cell-based logic (READ->COMPUTE->WRITE).
 * Netlist-generated; every data operation is a structural cell call. */
#ifndef INTERNAL_GEN_H
#define INTERNAL_GEN_H
#include "cells.h"

#define INTERNAL_REG_COUNT 10u

#define INTERNAL_INTERNAL_POWER 0u
#define INTERNAL_INTERNAL_RUN_UNTIL 1u
#define INTERNAL_ONE 2u
#define INTERNAL_INTERNAL_CYCLE 3u
#define INTERNAL_INTERNAL_EDGE 4u
#define INTERNAL_STEP 5u
#define INTERNAL_CNT_NEXT 6u
#define INTERNAL_EDGE_NEXT 7u
#define INTERNAL_INTERNAL_CYCLE_OUT 8u
#define INTERNAL_INTERNAL_EDGE_OUT 9u

static inline void internal_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < INTERNAL_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
    r[INTERNAL_ONE] = 1ULL;
}

/* internal_tick: one clock edge. READ inputs as const locals,
 * COMPUTE via cells (no native add/sub/mul on data), WRITE every register. */
static inline void internal_tick(word_t *r) {
    /* READ phase — pre-read every consumed register value. */
    const word_t internal_power = r[INTERNAL_INTERNAL_POWER];
    const word_t one = r[INTERNAL_ONE];
    const word_t internal_cycle = r[INTERNAL_INTERNAL_CYCLE];
    const word_t internal_edge = r[INTERNAL_INTERNAL_EDGE];

    /* COMPUTE phase — combinational cell chain (declaration order). */
    const word_t step = cell_gate(one, internal_power);
    const word_t cnt_next = cell_addsub(internal_cycle, step, 0ULL);
    const word_t edge_next = cell_gate(one, internal_power);

    /* WRITE phase — gated dff commit: r[X] = cell_dff(q, fed_by, enable). */
    r[INTERNAL_INTERNAL_CYCLE] = cell_dff(internal_cycle, cnt_next, one);
    r[INTERNAL_INTERNAL_EDGE] = cell_dff(internal_edge, edge_next, one);
    r[INTERNAL_STEP] = step;
    r[INTERNAL_CNT_NEXT] = cnt_next;
    r[INTERNAL_EDGE_NEXT] = edge_next;
    r[INTERNAL_INTERNAL_CYCLE_OUT] = internal_cycle;
    r[INTERNAL_INTERNAL_EDGE_OUT] = internal_edge;

}

/* internal_run: canonical free-running clock. Power on once; the clock
 * self-oscillates while the power bit is set. Nothing external steps it. */
static inline void internal_run(word_t *r) {
    while (r[INTERNAL_INTERNAL_POWER] & 1ULL) { internal_tick(r); }
}

#endif /* INTERNAL_GEN_H */
