/* GENERATED by gennet.py from rebuild/mac.net.json — DO NOT EDIT BY HAND.
 * The mac device: register lanes + cell-based logic (READ->COMPUTE->WRITE).
 * Netlist-generated; every data operation is a structural cell call. */
#ifndef MAC_GEN_H
#define MAC_GEN_H
#include "cells.h"

#define MAC_REG_COUNT 10u

#define MAC_MAC_POWER 0u
#define MAC_MAC_RUN_UNTIL 1u
#define MAC_ONE 2u
#define MAC_MAC_CYCLE 3u
#define MAC_MAC_EDGE 4u
#define MAC_STEP 5u
#define MAC_CNT_NEXT 6u
#define MAC_EDGE_NEXT 7u
#define MAC_MAC_CYCLE_OUT 8u
#define MAC_MAC_EDGE_OUT 9u

static inline void mac_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < MAC_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
    r[MAC_ONE] = 1ULL;
}

/* mac_tick: one clock edge. READ inputs as const locals,
 * COMPUTE via cells (no native add/sub/mul on data), WRITE every register. */
static inline void mac_tick(word_t *r) {
    /* READ phase — pre-read every consumed register value. */
    const word_t mac_power = r[MAC_MAC_POWER];
    const word_t one = r[MAC_ONE];
    const word_t mac_cycle = r[MAC_MAC_CYCLE];
    const word_t mac_edge = r[MAC_MAC_EDGE];

    /* COMPUTE phase — combinational cell chain (declaration order). */
    const word_t step = cell_gate(one, mac_power);
    const word_t cnt_next = cell_addsub(mac_cycle, step, 0ULL);
    const word_t edge_next = cell_gate(one, mac_power);

    /* WRITE phase — gated dff commit: r[X] = cell_dff(q, fed_by, enable). */
    r[MAC_MAC_CYCLE] = cell_dff(mac_cycle, cnt_next, one);
    r[MAC_MAC_EDGE] = cell_dff(mac_edge, edge_next, one);
    r[MAC_STEP] = step;
    r[MAC_CNT_NEXT] = cnt_next;
    r[MAC_EDGE_NEXT] = edge_next;
    r[MAC_MAC_CYCLE_OUT] = mac_cycle;
    r[MAC_MAC_EDGE_OUT] = mac_edge;

}

/* mac_run: canonical free-running clock. Power on once; the clock
 * self-oscillates while the power bit is set. Nothing external steps it. */
static inline void mac_run(word_t *r) {
    while (r[MAC_MAC_POWER] & 1ULL) { mac_tick(r); }
}

#endif /* MAC_GEN_H */
