/* GENERATED by gennet.py from rebuild/nic.net.json — DO NOT EDIT BY HAND.
 * The nic device: register lanes + cell-based logic (READ->COMPUTE->WRITE).
 * Netlist-generated; every data operation is a structural cell call. */
#ifndef NIC_GEN_H
#define NIC_GEN_H
#include "cells.h"

#define NIC_REG_COUNT 195u

#define NIC_NIC_POWER 0u
#define NIC_NIC_RUN_UNTIL 1u
#define NIC_WIRE_BID_PX 2u
#define NIC_WIRE_ASK_PX 3u
#define NIC_WIRE_TIME 4u
#define NIC_WIRE_SYMBOL 5u
#define NIC_WIRE_PIP 6u
#define NIC_WIRE_COMMISSION 7u
#define NIC_WIRE_SEQ 8u
#define NIC_WIRE_VALID 9u
#define NIC_TAI_MAC 10u
#define NIC_ONE 11u
#define NIC_MASK 12u
#define NIC_IDX_0 13u
#define NIC_IDX_1 14u
#define NIC_IDX_2 15u
#define NIC_IDX_3 16u
#define NIC_IDX_4 17u
#define NIC_IDX_5 18u
#define NIC_IDX_6 19u
#define NIC_IDX_7 20u
#define NIC_IDX_8 21u
#define NIC_IDX_9 22u
#define NIC_IDX_10 23u
#define NIC_IDX_11 24u
#define NIC_IDX_12 25u
#define NIC_IDX_13 26u
#define NIC_IDX_14 27u
#define NIC_IDX_15 28u
#define NIC_NIC_TICKS 29u
#define NIC_SEAM_BID_PX 30u
#define NIC_SEAM_ASK_PX 31u
#define NIC_SEAM_TIME 32u
#define NIC_SEAM_SRC_TIME 33u
#define NIC_SEAM_SYMBOL 34u
#define NIC_SEAM_PIP 35u
#define NIC_SEAM_COMMISSION 36u
#define NIC_SEAM_SEQ 37u
#define NIC_SEAM_VALID 38u
#define NIC_SEAM_STROBE 39u
#define NIC_SEAM_DEDUP_MARK 40u
#define NIC_NIC_RING_SEQ_0 41u
#define NIC_NIC_RING_VALID_0 42u
#define NIC_NIC_RING_SEQ_1 43u
#define NIC_NIC_RING_VALID_1 44u
#define NIC_NIC_RING_SEQ_2 45u
#define NIC_NIC_RING_VALID_2 46u
#define NIC_NIC_RING_SEQ_3 47u
#define NIC_NIC_RING_VALID_3 48u
#define NIC_NIC_RING_SEQ_4 49u
#define NIC_NIC_RING_VALID_4 50u
#define NIC_NIC_RING_SEQ_5 51u
#define NIC_NIC_RING_VALID_5 52u
#define NIC_NIC_RING_SEQ_6 53u
#define NIC_NIC_RING_VALID_6 54u
#define NIC_NIC_RING_SEQ_7 55u
#define NIC_NIC_RING_VALID_7 56u
#define NIC_NIC_RING_SEQ_8 57u
#define NIC_NIC_RING_VALID_8 58u
#define NIC_NIC_RING_SEQ_9 59u
#define NIC_NIC_RING_VALID_9 60u
#define NIC_NIC_RING_SEQ_10 61u
#define NIC_NIC_RING_VALID_10 62u
#define NIC_NIC_RING_SEQ_11 63u
#define NIC_NIC_RING_VALID_11 64u
#define NIC_NIC_RING_SEQ_12 65u
#define NIC_NIC_RING_VALID_12 66u
#define NIC_NIC_RING_SEQ_13 67u
#define NIC_NIC_RING_VALID_13 68u
#define NIC_NIC_RING_SEQ_14 69u
#define NIC_NIC_RING_VALID_14 70u
#define NIC_NIC_RING_SEQ_15 71u
#define NIC_NIC_RING_VALID_15 72u
#define NIC_IDX 73u
#define NIC_EQ_0 74u
#define NIC_EQ_1 75u
#define NIC_EQ_2 76u
#define NIC_EQ_3 77u
#define NIC_EQ_4 78u
#define NIC_EQ_5 79u
#define NIC_EQ_6 80u
#define NIC_EQ_7 81u
#define NIC_EQ_8 82u
#define NIC_EQ_9 83u
#define NIC_EQ_10 84u
#define NIC_EQ_11 85u
#define NIC_EQ_12 86u
#define NIC_EQ_13 87u
#define NIC_EQ_14 88u
#define NIC_EQ_15 89u
#define NIC_SS_0 90u
#define NIC_SS_1 91u
#define NIC_SS_2 92u
#define NIC_SS_3 93u
#define NIC_SS_4 94u
#define NIC_SS_5 95u
#define NIC_SS_6 96u
#define NIC_SS_7 97u
#define NIC_SS_8 98u
#define NIC_SS_9 99u
#define NIC_SS_10 100u
#define NIC_SS_11 101u
#define NIC_SS_12 102u
#define NIC_SS_13 103u
#define NIC_SS_14 104u
#define NIC_SS_15 105u
#define NIC_SV_0 106u
#define NIC_SV_1 107u
#define NIC_SV_2 108u
#define NIC_SV_3 109u
#define NIC_SV_4 110u
#define NIC_SV_5 111u
#define NIC_SV_6 112u
#define NIC_SV_7 113u
#define NIC_SV_8 114u
#define NIC_SV_9 115u
#define NIC_SV_10 116u
#define NIC_SV_11 117u
#define NIC_SV_12 118u
#define NIC_SV_13 119u
#define NIC_SV_14 120u
#define NIC_SV_15 121u
#define NIC_SLOTSEQ_1 122u
#define NIC_SLOTSEQ_2 123u
#define NIC_SLOTSEQ_3 124u
#define NIC_SLOTSEQ_4 125u
#define NIC_SLOTSEQ_5 126u
#define NIC_SLOTSEQ_6 127u
#define NIC_SLOTSEQ_7 128u
#define NIC_SLOTSEQ_8 129u
#define NIC_SLOTSEQ_9 130u
#define NIC_SLOTSEQ_10 131u
#define NIC_SLOTSEQ_11 132u
#define NIC_SLOTSEQ_12 133u
#define NIC_SLOTSEQ_13 134u
#define NIC_SLOTSEQ_14 135u
#define NIC_SLOT_SEQ 136u
#define NIC_SLOTVAL_1 137u
#define NIC_SLOTVAL_2 138u
#define NIC_SLOTVAL_3 139u
#define NIC_SLOTVAL_4 140u
#define NIC_SLOTVAL_5 141u
#define NIC_SLOTVAL_6 142u
#define NIC_SLOTVAL_7 143u
#define NIC_SLOTVAL_8 144u
#define NIC_SLOTVAL_9 145u
#define NIC_SLOTVAL_10 146u
#define NIC_SLOTVAL_11 147u
#define NIC_SLOTVAL_12 148u
#define NIC_SLOTVAL_13 149u
#define NIC_SLOTVAL_14 150u
#define NIC_SLOT_VAL 151u
#define NIC_SEQ_MATCH 152u
#define NIC_VS 153u
#define NIC_DUP 154u
#define NIC_NDUP 155u
#define NIC_PASS 156u
#define NIC_WEN_0 157u
#define NIC_WEN_1 158u
#define NIC_WEN_2 159u
#define NIC_WEN_3 160u
#define NIC_WEN_4 161u
#define NIC_WEN_5 162u
#define NIC_WEN_6 163u
#define NIC_WEN_7 164u
#define NIC_WEN_8 165u
#define NIC_WEN_9 166u
#define NIC_WEN_10 167u
#define NIC_WEN_11 168u
#define NIC_WEN_12 169u
#define NIC_WEN_13 170u
#define NIC_WEN_14 171u
#define NIC_WEN_15 172u
#define NIC_WIRE_BID_PX_BUF 173u
#define NIC_WIRE_ASK_PX_BUF 174u
#define NIC_WIRE_TIME_BUF 175u
#define NIC_WIRE_SYMBOL_BUF 176u
#define NIC_WIRE_PIP_BUF 177u
#define NIC_WIRE_COMMISSION_BUF 178u
#define NIC_WIRE_SEQ_BUF 179u
#define NIC_TAI_BUF 180u
#define NIC_PASS_BUF 181u
#define NIC_DUP_BUF 182u
#define NIC_STEP 183u
#define NIC_TICKS_NEXT 184u
#define NIC_SEAM_BID_PX_OUT 185u
#define NIC_SEAM_ASK_PX_OUT 186u
#define NIC_SEAM_TIME_OUT 187u
#define NIC_SEAM_SRC_TIME_OUT 188u
#define NIC_SEAM_SYMBOL_OUT 189u
#define NIC_SEAM_PIP_OUT 190u
#define NIC_SEAM_COMMISSION_OUT 191u
#define NIC_SEAM_SEQ_OUT 192u
#define NIC_SEAM_VALID_OUT 193u
#define NIC_SEAM_STROBE_OUT 194u

static inline void nic_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < NIC_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
    r[NIC_ONE] = 1ULL;
    r[NIC_MASK] = 15ULL;
    r[NIC_IDX_0] = 0ULL;
    r[NIC_IDX_1] = 1ULL;
    r[NIC_IDX_2] = 2ULL;
    r[NIC_IDX_3] = 3ULL;
    r[NIC_IDX_4] = 4ULL;
    r[NIC_IDX_5] = 5ULL;
    r[NIC_IDX_6] = 6ULL;
    r[NIC_IDX_7] = 7ULL;
    r[NIC_IDX_8] = 8ULL;
    r[NIC_IDX_9] = 9ULL;
    r[NIC_IDX_10] = 10ULL;
    r[NIC_IDX_11] = 11ULL;
    r[NIC_IDX_12] = 12ULL;
    r[NIC_IDX_13] = 13ULL;
    r[NIC_IDX_14] = 14ULL;
    r[NIC_IDX_15] = 15ULL;
}

/* nic_tick: one clock edge. READ inputs as const locals,
 * COMPUTE via cells (no native add/sub/mul on data), WRITE every register. */
static inline void nic_tick(word_t *r) {
    /* READ phase — pre-read every consumed register value. */
    const word_t nic_power = r[NIC_NIC_POWER];
    const word_t wire_bid_px = r[NIC_WIRE_BID_PX];
    const word_t wire_ask_px = r[NIC_WIRE_ASK_PX];
    const word_t wire_time = r[NIC_WIRE_TIME];
    const word_t wire_symbol = r[NIC_WIRE_SYMBOL];
    const word_t wire_pip = r[NIC_WIRE_PIP];
    const word_t wire_commission = r[NIC_WIRE_COMMISSION];
    const word_t wire_seq = r[NIC_WIRE_SEQ];
    const word_t wire_valid = r[NIC_WIRE_VALID];
    const word_t tai_mac = r[NIC_TAI_MAC];
    const word_t one = r[NIC_ONE];
    const word_t mask = r[NIC_MASK];
    const word_t idx_0 = r[NIC_IDX_0];
    const word_t idx_1 = r[NIC_IDX_1];
    const word_t idx_2 = r[NIC_IDX_2];
    const word_t idx_3 = r[NIC_IDX_3];
    const word_t idx_4 = r[NIC_IDX_4];
    const word_t idx_5 = r[NIC_IDX_5];
    const word_t idx_6 = r[NIC_IDX_6];
    const word_t idx_7 = r[NIC_IDX_7];
    const word_t idx_8 = r[NIC_IDX_8];
    const word_t idx_9 = r[NIC_IDX_9];
    const word_t idx_10 = r[NIC_IDX_10];
    const word_t idx_11 = r[NIC_IDX_11];
    const word_t idx_12 = r[NIC_IDX_12];
    const word_t idx_13 = r[NIC_IDX_13];
    const word_t idx_14 = r[NIC_IDX_14];
    const word_t idx_15 = r[NIC_IDX_15];
    const word_t nic_ticks = r[NIC_NIC_TICKS];
    const word_t seam_bid_px = r[NIC_SEAM_BID_PX];
    const word_t seam_ask_px = r[NIC_SEAM_ASK_PX];
    const word_t seam_time = r[NIC_SEAM_TIME];
    const word_t seam_src_time = r[NIC_SEAM_SRC_TIME];
    const word_t seam_symbol = r[NIC_SEAM_SYMBOL];
    const word_t seam_pip = r[NIC_SEAM_PIP];
    const word_t seam_commission = r[NIC_SEAM_COMMISSION];
    const word_t seam_seq = r[NIC_SEAM_SEQ];
    const word_t seam_valid = r[NIC_SEAM_VALID];
    const word_t seam_strobe = r[NIC_SEAM_STROBE];
    const word_t seam_dedup_mark = r[NIC_SEAM_DEDUP_MARK];
    const word_t nic_ring_seq_0 = r[NIC_NIC_RING_SEQ_0];
    const word_t nic_ring_valid_0 = r[NIC_NIC_RING_VALID_0];
    const word_t nic_ring_seq_1 = r[NIC_NIC_RING_SEQ_1];
    const word_t nic_ring_valid_1 = r[NIC_NIC_RING_VALID_1];
    const word_t nic_ring_seq_2 = r[NIC_NIC_RING_SEQ_2];
    const word_t nic_ring_valid_2 = r[NIC_NIC_RING_VALID_2];
    const word_t nic_ring_seq_3 = r[NIC_NIC_RING_SEQ_3];
    const word_t nic_ring_valid_3 = r[NIC_NIC_RING_VALID_3];
    const word_t nic_ring_seq_4 = r[NIC_NIC_RING_SEQ_4];
    const word_t nic_ring_valid_4 = r[NIC_NIC_RING_VALID_4];
    const word_t nic_ring_seq_5 = r[NIC_NIC_RING_SEQ_5];
    const word_t nic_ring_valid_5 = r[NIC_NIC_RING_VALID_5];
    const word_t nic_ring_seq_6 = r[NIC_NIC_RING_SEQ_6];
    const word_t nic_ring_valid_6 = r[NIC_NIC_RING_VALID_6];
    const word_t nic_ring_seq_7 = r[NIC_NIC_RING_SEQ_7];
    const word_t nic_ring_valid_7 = r[NIC_NIC_RING_VALID_7];
    const word_t nic_ring_seq_8 = r[NIC_NIC_RING_SEQ_8];
    const word_t nic_ring_valid_8 = r[NIC_NIC_RING_VALID_8];
    const word_t nic_ring_seq_9 = r[NIC_NIC_RING_SEQ_9];
    const word_t nic_ring_valid_9 = r[NIC_NIC_RING_VALID_9];
    const word_t nic_ring_seq_10 = r[NIC_NIC_RING_SEQ_10];
    const word_t nic_ring_valid_10 = r[NIC_NIC_RING_VALID_10];
    const word_t nic_ring_seq_11 = r[NIC_NIC_RING_SEQ_11];
    const word_t nic_ring_valid_11 = r[NIC_NIC_RING_VALID_11];
    const word_t nic_ring_seq_12 = r[NIC_NIC_RING_SEQ_12];
    const word_t nic_ring_valid_12 = r[NIC_NIC_RING_VALID_12];
    const word_t nic_ring_seq_13 = r[NIC_NIC_RING_SEQ_13];
    const word_t nic_ring_valid_13 = r[NIC_NIC_RING_VALID_13];
    const word_t nic_ring_seq_14 = r[NIC_NIC_RING_SEQ_14];
    const word_t nic_ring_valid_14 = r[NIC_NIC_RING_VALID_14];
    const word_t nic_ring_seq_15 = r[NIC_NIC_RING_SEQ_15];
    const word_t nic_ring_valid_15 = r[NIC_NIC_RING_VALID_15];

    /* COMPUTE phase — combinational cell chain (declaration order). */
    const word_t idx = cell_and(wire_seq, mask);
    const word_t eq_0 = cell_eqmask(idx, idx_0);
    const word_t eq_1 = cell_eqmask(idx, idx_1);
    const word_t eq_2 = cell_eqmask(idx, idx_2);
    const word_t eq_3 = cell_eqmask(idx, idx_3);
    const word_t eq_4 = cell_eqmask(idx, idx_4);
    const word_t eq_5 = cell_eqmask(idx, idx_5);
    const word_t eq_6 = cell_eqmask(idx, idx_6);
    const word_t eq_7 = cell_eqmask(idx, idx_7);
    const word_t eq_8 = cell_eqmask(idx, idx_8);
    const word_t eq_9 = cell_eqmask(idx, idx_9);
    const word_t eq_10 = cell_eqmask(idx, idx_10);
    const word_t eq_11 = cell_eqmask(idx, idx_11);
    const word_t eq_12 = cell_eqmask(idx, idx_12);
    const word_t eq_13 = cell_eqmask(idx, idx_13);
    const word_t eq_14 = cell_eqmask(idx, idx_14);
    const word_t eq_15 = cell_eqmask(idx, idx_15);
    const word_t ss_0 = cell_gate(nic_ring_seq_0, eq_0);
    const word_t ss_1 = cell_gate(nic_ring_seq_1, eq_1);
    const word_t ss_2 = cell_gate(nic_ring_seq_2, eq_2);
    const word_t ss_3 = cell_gate(nic_ring_seq_3, eq_3);
    const word_t ss_4 = cell_gate(nic_ring_seq_4, eq_4);
    const word_t ss_5 = cell_gate(nic_ring_seq_5, eq_5);
    const word_t ss_6 = cell_gate(nic_ring_seq_6, eq_6);
    const word_t ss_7 = cell_gate(nic_ring_seq_7, eq_7);
    const word_t ss_8 = cell_gate(nic_ring_seq_8, eq_8);
    const word_t ss_9 = cell_gate(nic_ring_seq_9, eq_9);
    const word_t ss_10 = cell_gate(nic_ring_seq_10, eq_10);
    const word_t ss_11 = cell_gate(nic_ring_seq_11, eq_11);
    const word_t ss_12 = cell_gate(nic_ring_seq_12, eq_12);
    const word_t ss_13 = cell_gate(nic_ring_seq_13, eq_13);
    const word_t ss_14 = cell_gate(nic_ring_seq_14, eq_14);
    const word_t ss_15 = cell_gate(nic_ring_seq_15, eq_15);
    const word_t sv_0 = cell_gate(nic_ring_valid_0, eq_0);
    const word_t sv_1 = cell_gate(nic_ring_valid_1, eq_1);
    const word_t sv_2 = cell_gate(nic_ring_valid_2, eq_2);
    const word_t sv_3 = cell_gate(nic_ring_valid_3, eq_3);
    const word_t sv_4 = cell_gate(nic_ring_valid_4, eq_4);
    const word_t sv_5 = cell_gate(nic_ring_valid_5, eq_5);
    const word_t sv_6 = cell_gate(nic_ring_valid_6, eq_6);
    const word_t sv_7 = cell_gate(nic_ring_valid_7, eq_7);
    const word_t sv_8 = cell_gate(nic_ring_valid_8, eq_8);
    const word_t sv_9 = cell_gate(nic_ring_valid_9, eq_9);
    const word_t sv_10 = cell_gate(nic_ring_valid_10, eq_10);
    const word_t sv_11 = cell_gate(nic_ring_valid_11, eq_11);
    const word_t sv_12 = cell_gate(nic_ring_valid_12, eq_12);
    const word_t sv_13 = cell_gate(nic_ring_valid_13, eq_13);
    const word_t sv_14 = cell_gate(nic_ring_valid_14, eq_14);
    const word_t sv_15 = cell_gate(nic_ring_valid_15, eq_15);
    const word_t slotseq_1 = cell_or(ss_0, ss_1);
    const word_t slotseq_2 = cell_or(slotseq_1, ss_2);
    const word_t slotseq_3 = cell_or(slotseq_2, ss_3);
    const word_t slotseq_4 = cell_or(slotseq_3, ss_4);
    const word_t slotseq_5 = cell_or(slotseq_4, ss_5);
    const word_t slotseq_6 = cell_or(slotseq_5, ss_6);
    const word_t slotseq_7 = cell_or(slotseq_6, ss_7);
    const word_t slotseq_8 = cell_or(slotseq_7, ss_8);
    const word_t slotseq_9 = cell_or(slotseq_8, ss_9);
    const word_t slotseq_10 = cell_or(slotseq_9, ss_10);
    const word_t slotseq_11 = cell_or(slotseq_10, ss_11);
    const word_t slotseq_12 = cell_or(slotseq_11, ss_12);
    const word_t slotseq_13 = cell_or(slotseq_12, ss_13);
    const word_t slotseq_14 = cell_or(slotseq_13, ss_14);
    const word_t slot_seq = cell_or(slotseq_14, ss_15);
    const word_t slotval_1 = cell_or(sv_0, sv_1);
    const word_t slotval_2 = cell_or(slotval_1, sv_2);
    const word_t slotval_3 = cell_or(slotval_2, sv_3);
    const word_t slotval_4 = cell_or(slotval_3, sv_4);
    const word_t slotval_5 = cell_or(slotval_4, sv_5);
    const word_t slotval_6 = cell_or(slotval_5, sv_6);
    const word_t slotval_7 = cell_or(slotval_6, sv_7);
    const word_t slotval_8 = cell_or(slotval_7, sv_8);
    const word_t slotval_9 = cell_or(slotval_8, sv_9);
    const word_t slotval_10 = cell_or(slotval_9, sv_10);
    const word_t slotval_11 = cell_or(slotval_10, sv_11);
    const word_t slotval_12 = cell_or(slotval_11, sv_12);
    const word_t slotval_13 = cell_or(slotval_12, sv_13);
    const word_t slotval_14 = cell_or(slotval_13, sv_14);
    const word_t slot_val = cell_or(slotval_14, sv_15);
    const word_t seq_match = cell_eqmask(slot_seq, wire_seq);
    const word_t vs = cell_and(wire_valid, slot_val);
    const word_t dup = cell_and(vs, seq_match);
    const word_t ndup = cell_not(dup);
    const word_t pass = cell_and(wire_valid, ndup);
    const word_t wen_0 = cell_and(eq_0, pass);
    const word_t wen_1 = cell_and(eq_1, pass);
    const word_t wen_2 = cell_and(eq_2, pass);
    const word_t wen_3 = cell_and(eq_3, pass);
    const word_t wen_4 = cell_and(eq_4, pass);
    const word_t wen_5 = cell_and(eq_5, pass);
    const word_t wen_6 = cell_and(eq_6, pass);
    const word_t wen_7 = cell_and(eq_7, pass);
    const word_t wen_8 = cell_and(eq_8, pass);
    const word_t wen_9 = cell_and(eq_9, pass);
    const word_t wen_10 = cell_and(eq_10, pass);
    const word_t wen_11 = cell_and(eq_11, pass);
    const word_t wen_12 = cell_and(eq_12, pass);
    const word_t wen_13 = cell_and(eq_13, pass);
    const word_t wen_14 = cell_and(eq_14, pass);
    const word_t wen_15 = cell_and(eq_15, pass);
    const word_t wire_bid_px_buf = cell_buf(wire_bid_px);
    const word_t wire_ask_px_buf = cell_buf(wire_ask_px);
    const word_t wire_time_buf = cell_buf(wire_time);
    const word_t wire_symbol_buf = cell_buf(wire_symbol);
    const word_t wire_pip_buf = cell_buf(wire_pip);
    const word_t wire_commission_buf = cell_buf(wire_commission);
    const word_t wire_seq_buf = cell_buf(wire_seq);
    const word_t tai_buf = cell_buf(tai_mac);
    const word_t pass_buf = cell_buf(pass);
    const word_t dup_buf = cell_buf(dup);
    const word_t step = cell_gate(one, nic_power);
    const word_t ticks_next = cell_addsub(nic_ticks, step, 0ULL);

    /* WRITE phase — gated dff commit: r[X] = cell_dff(q, fed_by, enable). */
    r[NIC_NIC_TICKS] = cell_dff(nic_ticks, ticks_next, one);
    r[NIC_SEAM_BID_PX] = cell_dff(seam_bid_px, wire_bid_px_buf, pass);
    r[NIC_SEAM_ASK_PX] = cell_dff(seam_ask_px, wire_ask_px_buf, pass);
    r[NIC_SEAM_TIME] = cell_dff(seam_time, tai_buf, pass);
    r[NIC_SEAM_SRC_TIME] = cell_dff(seam_src_time, wire_time_buf, pass);
    r[NIC_SEAM_SYMBOL] = cell_dff(seam_symbol, wire_symbol_buf, pass);
    r[NIC_SEAM_PIP] = cell_dff(seam_pip, wire_pip_buf, pass);
    r[NIC_SEAM_COMMISSION] = cell_dff(seam_commission, wire_commission_buf, pass);
    r[NIC_SEAM_SEQ] = cell_dff(seam_seq, wire_seq_buf, pass);
    r[NIC_SEAM_VALID] = cell_dff(seam_valid, pass_buf, nic_power);
    r[NIC_SEAM_STROBE] = cell_dff(seam_strobe, pass_buf, nic_power);
    r[NIC_SEAM_DEDUP_MARK] = cell_dff(seam_dedup_mark, dup_buf, nic_power);
    r[NIC_NIC_RING_SEQ_0] = cell_dff(nic_ring_seq_0, wire_seq_buf, wen_0);
    r[NIC_NIC_RING_VALID_0] = cell_dff(nic_ring_valid_0, one, wen_0);
    r[NIC_NIC_RING_SEQ_1] = cell_dff(nic_ring_seq_1, wire_seq_buf, wen_1);
    r[NIC_NIC_RING_VALID_1] = cell_dff(nic_ring_valid_1, one, wen_1);
    r[NIC_NIC_RING_SEQ_2] = cell_dff(nic_ring_seq_2, wire_seq_buf, wen_2);
    r[NIC_NIC_RING_VALID_2] = cell_dff(nic_ring_valid_2, one, wen_2);
    r[NIC_NIC_RING_SEQ_3] = cell_dff(nic_ring_seq_3, wire_seq_buf, wen_3);
    r[NIC_NIC_RING_VALID_3] = cell_dff(nic_ring_valid_3, one, wen_3);
    r[NIC_NIC_RING_SEQ_4] = cell_dff(nic_ring_seq_4, wire_seq_buf, wen_4);
    r[NIC_NIC_RING_VALID_4] = cell_dff(nic_ring_valid_4, one, wen_4);
    r[NIC_NIC_RING_SEQ_5] = cell_dff(nic_ring_seq_5, wire_seq_buf, wen_5);
    r[NIC_NIC_RING_VALID_5] = cell_dff(nic_ring_valid_5, one, wen_5);
    r[NIC_NIC_RING_SEQ_6] = cell_dff(nic_ring_seq_6, wire_seq_buf, wen_6);
    r[NIC_NIC_RING_VALID_6] = cell_dff(nic_ring_valid_6, one, wen_6);
    r[NIC_NIC_RING_SEQ_7] = cell_dff(nic_ring_seq_7, wire_seq_buf, wen_7);
    r[NIC_NIC_RING_VALID_7] = cell_dff(nic_ring_valid_7, one, wen_7);
    r[NIC_NIC_RING_SEQ_8] = cell_dff(nic_ring_seq_8, wire_seq_buf, wen_8);
    r[NIC_NIC_RING_VALID_8] = cell_dff(nic_ring_valid_8, one, wen_8);
    r[NIC_NIC_RING_SEQ_9] = cell_dff(nic_ring_seq_9, wire_seq_buf, wen_9);
    r[NIC_NIC_RING_VALID_9] = cell_dff(nic_ring_valid_9, one, wen_9);
    r[NIC_NIC_RING_SEQ_10] = cell_dff(nic_ring_seq_10, wire_seq_buf, wen_10);
    r[NIC_NIC_RING_VALID_10] = cell_dff(nic_ring_valid_10, one, wen_10);
    r[NIC_NIC_RING_SEQ_11] = cell_dff(nic_ring_seq_11, wire_seq_buf, wen_11);
    r[NIC_NIC_RING_VALID_11] = cell_dff(nic_ring_valid_11, one, wen_11);
    r[NIC_NIC_RING_SEQ_12] = cell_dff(nic_ring_seq_12, wire_seq_buf, wen_12);
    r[NIC_NIC_RING_VALID_12] = cell_dff(nic_ring_valid_12, one, wen_12);
    r[NIC_NIC_RING_SEQ_13] = cell_dff(nic_ring_seq_13, wire_seq_buf, wen_13);
    r[NIC_NIC_RING_VALID_13] = cell_dff(nic_ring_valid_13, one, wen_13);
    r[NIC_NIC_RING_SEQ_14] = cell_dff(nic_ring_seq_14, wire_seq_buf, wen_14);
    r[NIC_NIC_RING_VALID_14] = cell_dff(nic_ring_valid_14, one, wen_14);
    r[NIC_NIC_RING_SEQ_15] = cell_dff(nic_ring_seq_15, wire_seq_buf, wen_15);
    r[NIC_NIC_RING_VALID_15] = cell_dff(nic_ring_valid_15, one, wen_15);
    r[NIC_IDX] = idx;
    r[NIC_EQ_0] = eq_0;
    r[NIC_EQ_1] = eq_1;
    r[NIC_EQ_2] = eq_2;
    r[NIC_EQ_3] = eq_3;
    r[NIC_EQ_4] = eq_4;
    r[NIC_EQ_5] = eq_5;
    r[NIC_EQ_6] = eq_6;
    r[NIC_EQ_7] = eq_7;
    r[NIC_EQ_8] = eq_8;
    r[NIC_EQ_9] = eq_9;
    r[NIC_EQ_10] = eq_10;
    r[NIC_EQ_11] = eq_11;
    r[NIC_EQ_12] = eq_12;
    r[NIC_EQ_13] = eq_13;
    r[NIC_EQ_14] = eq_14;
    r[NIC_EQ_15] = eq_15;
    r[NIC_SS_0] = ss_0;
    r[NIC_SS_1] = ss_1;
    r[NIC_SS_2] = ss_2;
    r[NIC_SS_3] = ss_3;
    r[NIC_SS_4] = ss_4;
    r[NIC_SS_5] = ss_5;
    r[NIC_SS_6] = ss_6;
    r[NIC_SS_7] = ss_7;
    r[NIC_SS_8] = ss_8;
    r[NIC_SS_9] = ss_9;
    r[NIC_SS_10] = ss_10;
    r[NIC_SS_11] = ss_11;
    r[NIC_SS_12] = ss_12;
    r[NIC_SS_13] = ss_13;
    r[NIC_SS_14] = ss_14;
    r[NIC_SS_15] = ss_15;
    r[NIC_SV_0] = sv_0;
    r[NIC_SV_1] = sv_1;
    r[NIC_SV_2] = sv_2;
    r[NIC_SV_3] = sv_3;
    r[NIC_SV_4] = sv_4;
    r[NIC_SV_5] = sv_5;
    r[NIC_SV_6] = sv_6;
    r[NIC_SV_7] = sv_7;
    r[NIC_SV_8] = sv_8;
    r[NIC_SV_9] = sv_9;
    r[NIC_SV_10] = sv_10;
    r[NIC_SV_11] = sv_11;
    r[NIC_SV_12] = sv_12;
    r[NIC_SV_13] = sv_13;
    r[NIC_SV_14] = sv_14;
    r[NIC_SV_15] = sv_15;
    r[NIC_SLOTSEQ_1] = slotseq_1;
    r[NIC_SLOTSEQ_2] = slotseq_2;
    r[NIC_SLOTSEQ_3] = slotseq_3;
    r[NIC_SLOTSEQ_4] = slotseq_4;
    r[NIC_SLOTSEQ_5] = slotseq_5;
    r[NIC_SLOTSEQ_6] = slotseq_6;
    r[NIC_SLOTSEQ_7] = slotseq_7;
    r[NIC_SLOTSEQ_8] = slotseq_8;
    r[NIC_SLOTSEQ_9] = slotseq_9;
    r[NIC_SLOTSEQ_10] = slotseq_10;
    r[NIC_SLOTSEQ_11] = slotseq_11;
    r[NIC_SLOTSEQ_12] = slotseq_12;
    r[NIC_SLOTSEQ_13] = slotseq_13;
    r[NIC_SLOTSEQ_14] = slotseq_14;
    r[NIC_SLOT_SEQ] = slot_seq;
    r[NIC_SLOTVAL_1] = slotval_1;
    r[NIC_SLOTVAL_2] = slotval_2;
    r[NIC_SLOTVAL_3] = slotval_3;
    r[NIC_SLOTVAL_4] = slotval_4;
    r[NIC_SLOTVAL_5] = slotval_5;
    r[NIC_SLOTVAL_6] = slotval_6;
    r[NIC_SLOTVAL_7] = slotval_7;
    r[NIC_SLOTVAL_8] = slotval_8;
    r[NIC_SLOTVAL_9] = slotval_9;
    r[NIC_SLOTVAL_10] = slotval_10;
    r[NIC_SLOTVAL_11] = slotval_11;
    r[NIC_SLOTVAL_12] = slotval_12;
    r[NIC_SLOTVAL_13] = slotval_13;
    r[NIC_SLOTVAL_14] = slotval_14;
    r[NIC_SLOT_VAL] = slot_val;
    r[NIC_SEQ_MATCH] = seq_match;
    r[NIC_VS] = vs;
    r[NIC_DUP] = dup;
    r[NIC_NDUP] = ndup;
    r[NIC_PASS] = pass;
    r[NIC_WEN_0] = wen_0;
    r[NIC_WEN_1] = wen_1;
    r[NIC_WEN_2] = wen_2;
    r[NIC_WEN_3] = wen_3;
    r[NIC_WEN_4] = wen_4;
    r[NIC_WEN_5] = wen_5;
    r[NIC_WEN_6] = wen_6;
    r[NIC_WEN_7] = wen_7;
    r[NIC_WEN_8] = wen_8;
    r[NIC_WEN_9] = wen_9;
    r[NIC_WEN_10] = wen_10;
    r[NIC_WEN_11] = wen_11;
    r[NIC_WEN_12] = wen_12;
    r[NIC_WEN_13] = wen_13;
    r[NIC_WEN_14] = wen_14;
    r[NIC_WEN_15] = wen_15;
    r[NIC_WIRE_BID_PX_BUF] = wire_bid_px_buf;
    r[NIC_WIRE_ASK_PX_BUF] = wire_ask_px_buf;
    r[NIC_WIRE_TIME_BUF] = wire_time_buf;
    r[NIC_WIRE_SYMBOL_BUF] = wire_symbol_buf;
    r[NIC_WIRE_PIP_BUF] = wire_pip_buf;
    r[NIC_WIRE_COMMISSION_BUF] = wire_commission_buf;
    r[NIC_WIRE_SEQ_BUF] = wire_seq_buf;
    r[NIC_TAI_BUF] = tai_buf;
    r[NIC_PASS_BUF] = pass_buf;
    r[NIC_DUP_BUF] = dup_buf;
    r[NIC_STEP] = step;
    r[NIC_TICKS_NEXT] = ticks_next;
    r[NIC_SEAM_BID_PX_OUT] = seam_bid_px;
    r[NIC_SEAM_ASK_PX_OUT] = seam_ask_px;
    r[NIC_SEAM_TIME_OUT] = seam_time;
    r[NIC_SEAM_SRC_TIME_OUT] = seam_src_time;
    r[NIC_SEAM_SYMBOL_OUT] = seam_symbol;
    r[NIC_SEAM_PIP_OUT] = seam_pip;
    r[NIC_SEAM_COMMISSION_OUT] = seam_commission;
    r[NIC_SEAM_SEQ_OUT] = seam_seq;
    r[NIC_SEAM_VALID_OUT] = seam_valid;
    r[NIC_SEAM_STROBE_OUT] = seam_strobe;

}

/* nic_run: canonical free-running clock. Power on once; the clock
 * self-oscillates while the power bit is set. Nothing external steps it. */
static inline void nic_run(word_t *r) {
    while (r[NIC_NIC_POWER] & 1ULL) { nic_tick(r); }
}

#endif /* NIC_GEN_H */
