/* GENERATED by gennet.py from rebuild/pip_resolver.net.json — DO NOT EDIT BY HAND.
 * The pip_resolver device: register lanes + cell-based logic (READ->COMPUTE->WRITE).
 * Netlist-generated; every data operation is a structural cell call. */
#ifndef PIP_RESOLVER_GEN_H
#define PIP_RESOLVER_GEN_H
#include "cells.h"

#define PIP_RESOLVER_REG_COUNT 96u

#define PIP_RESOLVER_PIP_POWER 0u
#define PIP_RESOLVER_PIP_RUN_UNTIL 1u
#define PIP_RESOLVER_SEAM_SYMBOL 2u
#define PIP_RESOLVER_SEAM_VALID 3u
#define PIP_RESOLVER_PIP_CFG_TABLE_0 4u
#define PIP_RESOLVER_PIP_CFG_TABLE_1 5u
#define PIP_RESOLVER_PIP_CFG_TABLE_2 6u
#define PIP_RESOLVER_PIP_CFG_TABLE_3 7u
#define PIP_RESOLVER_PIP_CFG_TABLE_4 8u
#define PIP_RESOLVER_PIP_CFG_TABLE_5 9u
#define PIP_RESOLVER_PIP_CFG_TABLE_6 10u
#define PIP_RESOLVER_PIP_CFG_TABLE_7 11u
#define PIP_RESOLVER_PIP_CFG_TABLE_8 12u
#define PIP_RESOLVER_PIP_CFG_TABLE_9 13u
#define PIP_RESOLVER_PIP_CFG_TABLE_10 14u
#define PIP_RESOLVER_PIP_CFG_TABLE_11 15u
#define PIP_RESOLVER_PIP_CFG_TABLE_12 16u
#define PIP_RESOLVER_PIP_CFG_TABLE_13 17u
#define PIP_RESOLVER_PIP_CFG_TABLE_14 18u
#define PIP_RESOLVER_PIP_CFG_TABLE_15 19u
#define PIP_RESOLVER_ONE 20u
#define PIP_RESOLVER_MASK 21u
#define PIP_RESOLVER_IDX_0 22u
#define PIP_RESOLVER_IDX_1 23u
#define PIP_RESOLVER_IDX_2 24u
#define PIP_RESOLVER_IDX_3 25u
#define PIP_RESOLVER_IDX_4 26u
#define PIP_RESOLVER_IDX_5 27u
#define PIP_RESOLVER_IDX_6 28u
#define PIP_RESOLVER_IDX_7 29u
#define PIP_RESOLVER_IDX_8 30u
#define PIP_RESOLVER_IDX_9 31u
#define PIP_RESOLVER_IDX_10 32u
#define PIP_RESOLVER_IDX_11 33u
#define PIP_RESOLVER_IDX_12 34u
#define PIP_RESOLVER_IDX_13 35u
#define PIP_RESOLVER_IDX_14 36u
#define PIP_RESOLVER_IDX_15 37u
#define PIP_RESOLVER_PIP_TICKS 38u
#define PIP_RESOLVER_PIP_RESOLUTION_REG 39u
#define PIP_RESOLVER_PIP_SYMBOL 40u
#define PIP_RESOLVER_PIP_VALID 41u
#define PIP_RESOLVER_IDX 42u
#define PIP_RESOLVER_EQ_0 43u
#define PIP_RESOLVER_EQ_1 44u
#define PIP_RESOLVER_EQ_2 45u
#define PIP_RESOLVER_EQ_3 46u
#define PIP_RESOLVER_EQ_4 47u
#define PIP_RESOLVER_EQ_5 48u
#define PIP_RESOLVER_EQ_6 49u
#define PIP_RESOLVER_EQ_7 50u
#define PIP_RESOLVER_EQ_8 51u
#define PIP_RESOLVER_EQ_9 52u
#define PIP_RESOLVER_EQ_10 53u
#define PIP_RESOLVER_EQ_11 54u
#define PIP_RESOLVER_EQ_12 55u
#define PIP_RESOLVER_EQ_13 56u
#define PIP_RESOLVER_EQ_14 57u
#define PIP_RESOLVER_EQ_15 58u
#define PIP_RESOLVER_SEL_0 59u
#define PIP_RESOLVER_SEL_1 60u
#define PIP_RESOLVER_SEL_2 61u
#define PIP_RESOLVER_SEL_3 62u
#define PIP_RESOLVER_SEL_4 63u
#define PIP_RESOLVER_SEL_5 64u
#define PIP_RESOLVER_SEL_6 65u
#define PIP_RESOLVER_SEL_7 66u
#define PIP_RESOLVER_SEL_8 67u
#define PIP_RESOLVER_SEL_9 68u
#define PIP_RESOLVER_SEL_10 69u
#define PIP_RESOLVER_SEL_11 70u
#define PIP_RESOLVER_SEL_12 71u
#define PIP_RESOLVER_SEL_13 72u
#define PIP_RESOLVER_SEL_14 73u
#define PIP_RESOLVER_SEL_15 74u
#define PIP_RESOLVER_ACC_1 75u
#define PIP_RESOLVER_ACC_2 76u
#define PIP_RESOLVER_ACC_3 77u
#define PIP_RESOLVER_ACC_4 78u
#define PIP_RESOLVER_ACC_5 79u
#define PIP_RESOLVER_ACC_6 80u
#define PIP_RESOLVER_ACC_7 81u
#define PIP_RESOLVER_ACC_8 82u
#define PIP_RESOLVER_ACC_9 83u
#define PIP_RESOLVER_ACC_10 84u
#define PIP_RESOLVER_ACC_11 85u
#define PIP_RESOLVER_ACC_12 86u
#define PIP_RESOLVER_ACC_13 87u
#define PIP_RESOLVER_ACC_14 88u
#define PIP_RESOLVER_RES 89u
#define PIP_RESOLVER_SYM_BUF 90u
#define PIP_RESOLVER_VALID_BUF 91u
#define PIP_RESOLVER_STEP 92u
#define PIP_RESOLVER_TICKS_NEXT 93u
#define PIP_RESOLVER_PIP_RESOLUTION_OUT 94u
#define PIP_RESOLVER_PIP_VALID_OUT 95u

static inline void pip_resolver_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < PIP_RESOLVER_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
    r[PIP_RESOLVER_ONE] = 1ULL;
    r[PIP_RESOLVER_MASK] = 15ULL;
    r[PIP_RESOLVER_IDX_0] = 0ULL;
    r[PIP_RESOLVER_IDX_1] = 1ULL;
    r[PIP_RESOLVER_IDX_2] = 2ULL;
    r[PIP_RESOLVER_IDX_3] = 3ULL;
    r[PIP_RESOLVER_IDX_4] = 4ULL;
    r[PIP_RESOLVER_IDX_5] = 5ULL;
    r[PIP_RESOLVER_IDX_6] = 6ULL;
    r[PIP_RESOLVER_IDX_7] = 7ULL;
    r[PIP_RESOLVER_IDX_8] = 8ULL;
    r[PIP_RESOLVER_IDX_9] = 9ULL;
    r[PIP_RESOLVER_IDX_10] = 10ULL;
    r[PIP_RESOLVER_IDX_11] = 11ULL;
    r[PIP_RESOLVER_IDX_12] = 12ULL;
    r[PIP_RESOLVER_IDX_13] = 13ULL;
    r[PIP_RESOLVER_IDX_14] = 14ULL;
    r[PIP_RESOLVER_IDX_15] = 15ULL;
}

/* pip_resolver_tick: one clock edge. READ inputs as const locals,
 * COMPUTE via cells (no native add/sub/mul on data), WRITE every register. */
static inline void pip_resolver_tick(word_t *r) {
    /* READ phase — pre-read every consumed register value. */
    const word_t pip_power = r[PIP_RESOLVER_PIP_POWER];
    const word_t seam_symbol = r[PIP_RESOLVER_SEAM_SYMBOL];
    const word_t seam_valid = r[PIP_RESOLVER_SEAM_VALID];
    const word_t pip_cfg_table_0 = r[PIP_RESOLVER_PIP_CFG_TABLE_0];
    const word_t pip_cfg_table_1 = r[PIP_RESOLVER_PIP_CFG_TABLE_1];
    const word_t pip_cfg_table_2 = r[PIP_RESOLVER_PIP_CFG_TABLE_2];
    const word_t pip_cfg_table_3 = r[PIP_RESOLVER_PIP_CFG_TABLE_3];
    const word_t pip_cfg_table_4 = r[PIP_RESOLVER_PIP_CFG_TABLE_4];
    const word_t pip_cfg_table_5 = r[PIP_RESOLVER_PIP_CFG_TABLE_5];
    const word_t pip_cfg_table_6 = r[PIP_RESOLVER_PIP_CFG_TABLE_6];
    const word_t pip_cfg_table_7 = r[PIP_RESOLVER_PIP_CFG_TABLE_7];
    const word_t pip_cfg_table_8 = r[PIP_RESOLVER_PIP_CFG_TABLE_8];
    const word_t pip_cfg_table_9 = r[PIP_RESOLVER_PIP_CFG_TABLE_9];
    const word_t pip_cfg_table_10 = r[PIP_RESOLVER_PIP_CFG_TABLE_10];
    const word_t pip_cfg_table_11 = r[PIP_RESOLVER_PIP_CFG_TABLE_11];
    const word_t pip_cfg_table_12 = r[PIP_RESOLVER_PIP_CFG_TABLE_12];
    const word_t pip_cfg_table_13 = r[PIP_RESOLVER_PIP_CFG_TABLE_13];
    const word_t pip_cfg_table_14 = r[PIP_RESOLVER_PIP_CFG_TABLE_14];
    const word_t pip_cfg_table_15 = r[PIP_RESOLVER_PIP_CFG_TABLE_15];
    const word_t one = r[PIP_RESOLVER_ONE];
    const word_t mask = r[PIP_RESOLVER_MASK];
    const word_t idx_0 = r[PIP_RESOLVER_IDX_0];
    const word_t idx_1 = r[PIP_RESOLVER_IDX_1];
    const word_t idx_2 = r[PIP_RESOLVER_IDX_2];
    const word_t idx_3 = r[PIP_RESOLVER_IDX_3];
    const word_t idx_4 = r[PIP_RESOLVER_IDX_4];
    const word_t idx_5 = r[PIP_RESOLVER_IDX_5];
    const word_t idx_6 = r[PIP_RESOLVER_IDX_6];
    const word_t idx_7 = r[PIP_RESOLVER_IDX_7];
    const word_t idx_8 = r[PIP_RESOLVER_IDX_8];
    const word_t idx_9 = r[PIP_RESOLVER_IDX_9];
    const word_t idx_10 = r[PIP_RESOLVER_IDX_10];
    const word_t idx_11 = r[PIP_RESOLVER_IDX_11];
    const word_t idx_12 = r[PIP_RESOLVER_IDX_12];
    const word_t idx_13 = r[PIP_RESOLVER_IDX_13];
    const word_t idx_14 = r[PIP_RESOLVER_IDX_14];
    const word_t idx_15 = r[PIP_RESOLVER_IDX_15];
    const word_t pip_ticks = r[PIP_RESOLVER_PIP_TICKS];
    const word_t pip_resolution_reg = r[PIP_RESOLVER_PIP_RESOLUTION_REG];
    const word_t pip_symbol = r[PIP_RESOLVER_PIP_SYMBOL];
    const word_t pip_valid = r[PIP_RESOLVER_PIP_VALID];

    /* COMPUTE phase — combinational cell chain (declaration order). */
    const word_t idx = cell_and(seam_symbol, mask);
    const word_t eq_0 = cell_eqmask(idx, idx_0);
    const word_t eq_1 = cell_eqmask(idx, idx_1);
    const word_t eq_2 = cell_eqmask(idx, idx_2);
    const word_t eq_3 = cell_eqmask(idx, idx_3);
    const word_t eq_4 = cell_eqmask(idx, idx_4);
    const word_t eq_5 = cell_eqmask(idx, idx_5);
    const word_t eq_6 = cell_eqmask(idx, idx_6);
    const word_t eq_7 = cell_eqmask(idx, idx_7);
    const word_t eq_8 = cell_eqmask(idx, idx_8);
    const word_t eq_9 = cell_eqmask(idx, idx_9);
    const word_t eq_10 = cell_eqmask(idx, idx_10);
    const word_t eq_11 = cell_eqmask(idx, idx_11);
    const word_t eq_12 = cell_eqmask(idx, idx_12);
    const word_t eq_13 = cell_eqmask(idx, idx_13);
    const word_t eq_14 = cell_eqmask(idx, idx_14);
    const word_t eq_15 = cell_eqmask(idx, idx_15);
    const word_t sel_0 = cell_gate(pip_cfg_table_0, eq_0);
    const word_t sel_1 = cell_gate(pip_cfg_table_1, eq_1);
    const word_t sel_2 = cell_gate(pip_cfg_table_2, eq_2);
    const word_t sel_3 = cell_gate(pip_cfg_table_3, eq_3);
    const word_t sel_4 = cell_gate(pip_cfg_table_4, eq_4);
    const word_t sel_5 = cell_gate(pip_cfg_table_5, eq_5);
    const word_t sel_6 = cell_gate(pip_cfg_table_6, eq_6);
    const word_t sel_7 = cell_gate(pip_cfg_table_7, eq_7);
    const word_t sel_8 = cell_gate(pip_cfg_table_8, eq_8);
    const word_t sel_9 = cell_gate(pip_cfg_table_9, eq_9);
    const word_t sel_10 = cell_gate(pip_cfg_table_10, eq_10);
    const word_t sel_11 = cell_gate(pip_cfg_table_11, eq_11);
    const word_t sel_12 = cell_gate(pip_cfg_table_12, eq_12);
    const word_t sel_13 = cell_gate(pip_cfg_table_13, eq_13);
    const word_t sel_14 = cell_gate(pip_cfg_table_14, eq_14);
    const word_t sel_15 = cell_gate(pip_cfg_table_15, eq_15);
    const word_t acc_1 = cell_or(sel_0, sel_1);
    const word_t acc_2 = cell_or(acc_1, sel_2);
    const word_t acc_3 = cell_or(acc_2, sel_3);
    const word_t acc_4 = cell_or(acc_3, sel_4);
    const word_t acc_5 = cell_or(acc_4, sel_5);
    const word_t acc_6 = cell_or(acc_5, sel_6);
    const word_t acc_7 = cell_or(acc_6, sel_7);
    const word_t acc_8 = cell_or(acc_7, sel_8);
    const word_t acc_9 = cell_or(acc_8, sel_9);
    const word_t acc_10 = cell_or(acc_9, sel_10);
    const word_t acc_11 = cell_or(acc_10, sel_11);
    const word_t acc_12 = cell_or(acc_11, sel_12);
    const word_t acc_13 = cell_or(acc_12, sel_13);
    const word_t acc_14 = cell_or(acc_13, sel_14);
    const word_t res = cell_or(acc_14, sel_15);
    const word_t sym_buf = cell_buf(seam_symbol);
    const word_t valid_buf = cell_buf(seam_valid);
    const word_t step = cell_gate(one, pip_power);
    const word_t ticks_next = cell_addsub(pip_ticks, step, 0ULL);

    /* WRITE phase — gated dff commit: r[X] = cell_dff(q, fed_by, enable). */
    r[PIP_RESOLVER_PIP_TICKS] = cell_dff(pip_ticks, ticks_next, one);
    r[PIP_RESOLVER_PIP_RESOLUTION_REG] = cell_dff(pip_resolution_reg, res, seam_valid);
    r[PIP_RESOLVER_PIP_SYMBOL] = cell_dff(pip_symbol, sym_buf, seam_valid);
    r[PIP_RESOLVER_PIP_VALID] = cell_dff(pip_valid, valid_buf, pip_power);
    r[PIP_RESOLVER_IDX] = idx;
    r[PIP_RESOLVER_EQ_0] = eq_0;
    r[PIP_RESOLVER_EQ_1] = eq_1;
    r[PIP_RESOLVER_EQ_2] = eq_2;
    r[PIP_RESOLVER_EQ_3] = eq_3;
    r[PIP_RESOLVER_EQ_4] = eq_4;
    r[PIP_RESOLVER_EQ_5] = eq_5;
    r[PIP_RESOLVER_EQ_6] = eq_6;
    r[PIP_RESOLVER_EQ_7] = eq_7;
    r[PIP_RESOLVER_EQ_8] = eq_8;
    r[PIP_RESOLVER_EQ_9] = eq_9;
    r[PIP_RESOLVER_EQ_10] = eq_10;
    r[PIP_RESOLVER_EQ_11] = eq_11;
    r[PIP_RESOLVER_EQ_12] = eq_12;
    r[PIP_RESOLVER_EQ_13] = eq_13;
    r[PIP_RESOLVER_EQ_14] = eq_14;
    r[PIP_RESOLVER_EQ_15] = eq_15;
    r[PIP_RESOLVER_SEL_0] = sel_0;
    r[PIP_RESOLVER_SEL_1] = sel_1;
    r[PIP_RESOLVER_SEL_2] = sel_2;
    r[PIP_RESOLVER_SEL_3] = sel_3;
    r[PIP_RESOLVER_SEL_4] = sel_4;
    r[PIP_RESOLVER_SEL_5] = sel_5;
    r[PIP_RESOLVER_SEL_6] = sel_6;
    r[PIP_RESOLVER_SEL_7] = sel_7;
    r[PIP_RESOLVER_SEL_8] = sel_8;
    r[PIP_RESOLVER_SEL_9] = sel_9;
    r[PIP_RESOLVER_SEL_10] = sel_10;
    r[PIP_RESOLVER_SEL_11] = sel_11;
    r[PIP_RESOLVER_SEL_12] = sel_12;
    r[PIP_RESOLVER_SEL_13] = sel_13;
    r[PIP_RESOLVER_SEL_14] = sel_14;
    r[PIP_RESOLVER_SEL_15] = sel_15;
    r[PIP_RESOLVER_ACC_1] = acc_1;
    r[PIP_RESOLVER_ACC_2] = acc_2;
    r[PIP_RESOLVER_ACC_3] = acc_3;
    r[PIP_RESOLVER_ACC_4] = acc_4;
    r[PIP_RESOLVER_ACC_5] = acc_5;
    r[PIP_RESOLVER_ACC_6] = acc_6;
    r[PIP_RESOLVER_ACC_7] = acc_7;
    r[PIP_RESOLVER_ACC_8] = acc_8;
    r[PIP_RESOLVER_ACC_9] = acc_9;
    r[PIP_RESOLVER_ACC_10] = acc_10;
    r[PIP_RESOLVER_ACC_11] = acc_11;
    r[PIP_RESOLVER_ACC_12] = acc_12;
    r[PIP_RESOLVER_ACC_13] = acc_13;
    r[PIP_RESOLVER_ACC_14] = acc_14;
    r[PIP_RESOLVER_RES] = res;
    r[PIP_RESOLVER_SYM_BUF] = sym_buf;
    r[PIP_RESOLVER_VALID_BUF] = valid_buf;
    r[PIP_RESOLVER_STEP] = step;
    r[PIP_RESOLVER_TICKS_NEXT] = ticks_next;
    r[PIP_RESOLVER_PIP_RESOLUTION_OUT] = pip_resolution_reg;
    r[PIP_RESOLVER_PIP_VALID_OUT] = pip_valid;

}

/* pip_resolver_run: canonical free-running clock. Power on once; the clock
 * self-oscillates while the power bit is set. Nothing external steps it. */
static inline void pip_resolver_run(word_t *r) {
    while (r[PIP_RESOLVER_PIP_POWER] & 1ULL) { pip_resolver_tick(r); }
}

#endif /* PIP_RESOLVER_GEN_H */
