/* GENERATED by gennet.py from rebuild/tai_cdc.net.json — DO NOT EDIT BY HAND.
 * The tai_cdc device: register lanes + cell-based logic (READ->COMPUTE->WRITE).
 * Netlist-generated; every data operation is a structural cell call. */
#ifndef TAI_CDC_GEN_H
#define TAI_CDC_GEN_H
#include "cells.h"

#define TAI_CDC_REG_COUNT 41u

#define TAI_CDC_TAI_CDC_POWER 0u
#define TAI_CDC_TAI_CDC_RUN_UNTIL 1u
#define TAI_CDC_TAI_IN 2u
#define TAI_CDC_ONE 3u
#define TAI_CDC_ZERO 4u
#define TAI_CDC_LMASK_1 5u
#define TAI_CDC_LMASK_2 6u
#define TAI_CDC_LMASK_4 7u
#define TAI_CDC_LMASK_8 8u
#define TAI_CDC_LMASK_16 9u
#define TAI_CDC_LMASK_32 10u
#define TAI_CDC_TAI_CDC_TICKS 11u
#define TAI_CDC_TAI_SYNC1_GRAY 12u
#define TAI_CDC_TAI_SYNC2_GRAY 13u
#define TAI_CDC_TAI_MAC 14u
#define TAI_CDC_ENC_S1_SAR 15u
#define TAI_CDC_ENC_S1 16u
#define TAI_CDC_GRAY 17u
#define TAI_CDC_SYNC1_NEXT 18u
#define TAI_CDC_SYNC2_NEXT 19u
#define TAI_CDC_DEC1_LSR_SAR 20u
#define TAI_CDC_DEC1_LSR 21u
#define TAI_CDC_DEC1 22u
#define TAI_CDC_DEC2_LSR_SAR 23u
#define TAI_CDC_DEC2_LSR 24u
#define TAI_CDC_DEC2 25u
#define TAI_CDC_DEC4_LSR_SAR 26u
#define TAI_CDC_DEC4_LSR 27u
#define TAI_CDC_DEC4 28u
#define TAI_CDC_DEC8_LSR_SAR 29u
#define TAI_CDC_DEC8_LSR 30u
#define TAI_CDC_DEC8 31u
#define TAI_CDC_DEC16_LSR_SAR 32u
#define TAI_CDC_DEC16_LSR 33u
#define TAI_CDC_DEC16 34u
#define TAI_CDC_DEC32_LSR_SAR 35u
#define TAI_CDC_DEC32_LSR 36u
#define TAI_CDC_TAI_MAC_DEC 37u
#define TAI_CDC_STEP 38u
#define TAI_CDC_TICKS_NEXT 39u
#define TAI_CDC_TAI_MAC_OUT 40u

static inline void tai_cdc_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < TAI_CDC_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
    r[TAI_CDC_ONE] = 1ULL;
    r[TAI_CDC_ZERO] = 0ULL;
    r[TAI_CDC_LMASK_1] = 9223372036854775807ULL;
    r[TAI_CDC_LMASK_2] = 4611686018427387903ULL;
    r[TAI_CDC_LMASK_4] = 1152921504606846975ULL;
    r[TAI_CDC_LMASK_8] = 72057594037927935ULL;
    r[TAI_CDC_LMASK_16] = 281474976710655ULL;
    r[TAI_CDC_LMASK_32] = 4294967295ULL;
}

/* tai_cdc_tick: one clock edge. READ inputs as const locals,
 * COMPUTE via cells (no native add/sub/mul on data), WRITE every register. */
static inline void tai_cdc_tick(word_t *r) {
    /* READ phase — pre-read every consumed register value. */
    const word_t tai_cdc_power = r[TAI_CDC_TAI_CDC_POWER];
    const word_t tai_in = r[TAI_CDC_TAI_IN];
    const word_t one = r[TAI_CDC_ONE];
    const word_t zero = r[TAI_CDC_ZERO];
    const word_t lmask_1 = r[TAI_CDC_LMASK_1];
    const word_t lmask_2 = r[TAI_CDC_LMASK_2];
    const word_t lmask_4 = r[TAI_CDC_LMASK_4];
    const word_t lmask_8 = r[TAI_CDC_LMASK_8];
    const word_t lmask_16 = r[TAI_CDC_LMASK_16];
    const word_t lmask_32 = r[TAI_CDC_LMASK_32];
    const word_t tai_cdc_ticks = r[TAI_CDC_TAI_CDC_TICKS];
    const word_t tai_sync1_gray = r[TAI_CDC_TAI_SYNC1_GRAY];
    const word_t tai_sync2_gray = r[TAI_CDC_TAI_SYNC2_GRAY];
    const word_t tai_mac = r[TAI_CDC_TAI_MAC];

    /* COMPUTE phase — combinational cell chain (declaration order). */
    const word_t enc_s1_sar = cell_sar(cell_addsub(tai_in, zero, 0ULL), 1u);
    const word_t enc_s1 = cell_and(enc_s1_sar, lmask_1);
    const word_t gray = cell_xor(tai_in, enc_s1);
    const word_t sync1_next = cell_mux(tai_sync1_gray, gray, tai_cdc_power);
    const word_t sync2_next = cell_mux(tai_sync2_gray, tai_sync1_gray, tai_cdc_power);
    const word_t dec1_lsr_sar = cell_sar(cell_addsub(sync2_next, zero, 0ULL), 1u);
    const word_t dec1_lsr = cell_and(dec1_lsr_sar, lmask_1);
    const word_t dec1 = cell_xor(sync2_next, dec1_lsr);
    const word_t dec2_lsr_sar = cell_sar(cell_addsub(dec1, zero, 0ULL), 2u);
    const word_t dec2_lsr = cell_and(dec2_lsr_sar, lmask_2);
    const word_t dec2 = cell_xor(dec1, dec2_lsr);
    const word_t dec4_lsr_sar = cell_sar(cell_addsub(dec2, zero, 0ULL), 4u);
    const word_t dec4_lsr = cell_and(dec4_lsr_sar, lmask_4);
    const word_t dec4 = cell_xor(dec2, dec4_lsr);
    const word_t dec8_lsr_sar = cell_sar(cell_addsub(dec4, zero, 0ULL), 8u);
    const word_t dec8_lsr = cell_and(dec8_lsr_sar, lmask_8);
    const word_t dec8 = cell_xor(dec4, dec8_lsr);
    const word_t dec16_lsr_sar = cell_sar(cell_addsub(dec8, zero, 0ULL), 16u);
    const word_t dec16_lsr = cell_and(dec16_lsr_sar, lmask_16);
    const word_t dec16 = cell_xor(dec8, dec16_lsr);
    const word_t dec32_lsr_sar = cell_sar(cell_addsub(dec16, zero, 0ULL), 32u);
    const word_t dec32_lsr = cell_and(dec32_lsr_sar, lmask_32);
    const word_t tai_mac_dec = cell_xor(dec16, dec32_lsr);
    const word_t step = cell_gate(one, tai_cdc_power);
    const word_t ticks_next = cell_addsub(tai_cdc_ticks, step, 0ULL);

    /* WRITE phase — gated dff commit: r[X] = cell_dff(q, fed_by, enable). */
    r[TAI_CDC_TAI_CDC_TICKS] = cell_dff(tai_cdc_ticks, ticks_next, one);
    r[TAI_CDC_TAI_SYNC1_GRAY] = cell_dff(tai_sync1_gray, sync1_next, one);
    r[TAI_CDC_TAI_SYNC2_GRAY] = cell_dff(tai_sync2_gray, sync2_next, one);
    r[TAI_CDC_TAI_MAC] = cell_dff(tai_mac, tai_mac_dec, one);
    r[TAI_CDC_ENC_S1_SAR] = enc_s1_sar;
    r[TAI_CDC_ENC_S1] = enc_s1;
    r[TAI_CDC_GRAY] = gray;
    r[TAI_CDC_SYNC1_NEXT] = sync1_next;
    r[TAI_CDC_SYNC2_NEXT] = sync2_next;
    r[TAI_CDC_DEC1_LSR_SAR] = dec1_lsr_sar;
    r[TAI_CDC_DEC1_LSR] = dec1_lsr;
    r[TAI_CDC_DEC1] = dec1;
    r[TAI_CDC_DEC2_LSR_SAR] = dec2_lsr_sar;
    r[TAI_CDC_DEC2_LSR] = dec2_lsr;
    r[TAI_CDC_DEC2] = dec2;
    r[TAI_CDC_DEC4_LSR_SAR] = dec4_lsr_sar;
    r[TAI_CDC_DEC4_LSR] = dec4_lsr;
    r[TAI_CDC_DEC4] = dec4;
    r[TAI_CDC_DEC8_LSR_SAR] = dec8_lsr_sar;
    r[TAI_CDC_DEC8_LSR] = dec8_lsr;
    r[TAI_CDC_DEC8] = dec8;
    r[TAI_CDC_DEC16_LSR_SAR] = dec16_lsr_sar;
    r[TAI_CDC_DEC16_LSR] = dec16_lsr;
    r[TAI_CDC_DEC16] = dec16;
    r[TAI_CDC_DEC32_LSR_SAR] = dec32_lsr_sar;
    r[TAI_CDC_DEC32_LSR] = dec32_lsr;
    r[TAI_CDC_TAI_MAC_DEC] = tai_mac_dec;
    r[TAI_CDC_STEP] = step;
    r[TAI_CDC_TICKS_NEXT] = ticks_next;
    r[TAI_CDC_TAI_MAC_OUT] = tai_mac;

}

/* tai_cdc_run: canonical free-running clock. Power on once; the clock
 * self-oscillates while the power bit is set. Nothing external steps it. */
static inline void tai_cdc_run(word_t *r) {
    while (r[TAI_CDC_TAI_CDC_POWER] & 1ULL) { tai_cdc_tick(r); }
}

#endif /* TAI_CDC_GEN_H */
