/* GENERATED by gennet.py from rebuild/tai.net.json — DO NOT EDIT BY HAND.
 * The tai device: register lanes + cell-based logic (READ->COMPUTE->WRITE).
 * Netlist-generated; every data operation is a structural cell call. */
#ifndef TAI_GEN_H
#define TAI_GEN_H
#include "cells.h"

#define TAI_REG_COUNT 7u

#define TAI_TAI_POWER 0u
#define TAI_TAI_RUN_UNTIL 1u
#define TAI_ONE 2u
#define TAI_TAI_NS 3u
#define TAI_STEP 4u
#define TAI_NS_NEXT 5u
#define TAI_TAI_NS_OUT 6u

static inline void tai_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < TAI_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
    r[TAI_ONE] = 1ULL;
}

/* tai_tick: one clock edge. READ inputs as const locals,
 * COMPUTE via cells (no native add/sub/mul on data), WRITE every register. */
static inline void tai_tick(word_t *r) {
    /* READ phase — pre-read every consumed register value. */
    const word_t tai_power = r[TAI_TAI_POWER];
    const word_t one = r[TAI_ONE];
    const word_t tai_ns = r[TAI_TAI_NS];

    /* COMPUTE phase — combinational cell chain (declaration order). */
    const word_t step = cell_gate(one, tai_power);
    const word_t ns_next = cell_addsub(tai_ns, step, 0ULL);

    /* WRITE phase — gated dff commit: r[X] = cell_dff(q, fed_by, enable). */
    r[TAI_TAI_NS] = cell_dff(tai_ns, ns_next, one);
    r[TAI_STEP] = step;
    r[TAI_NS_NEXT] = ns_next;
    r[TAI_TAI_NS_OUT] = tai_ns;

}

/* tai_run: canonical free-running clock. Power on once; the clock
 * self-oscillates while the power bit is set. Nothing external steps it. */
static inline void tai_run(word_t *r) {
    while (r[TAI_TAI_POWER] & 1ULL) { tai_tick(r); }
}

#endif /* TAI_GEN_H */
