/* GENERATED by gennet.py from rebuild/timeframe.net.json — DO NOT EDIT BY HAND.
 * The timeframe device: register lanes + cell-based logic (READ->COMPUTE->WRITE).
 * Netlist-generated; every data operation is a structural cell call. */
#ifndef TIMEFRAME_GEN_H
#define TIMEFRAME_GEN_H
#include "cells.h"

#define TIMEFRAME_REG_COUNT 21u

#define TIMEFRAME_TF_POWER 0u
#define TIMEFRAME_TF_RUN_UNTIL 1u
#define TIMEFRAME_TF_TAI_IN 2u
#define TIMEFRAME_TF_PERIOD_NS 3u
#define TIMEFRAME_ONE 4u
#define TIMEFRAME_TF_TICKS 5u
#define TIMEFRAME_TF_BAR_SEQ 6u
#define TIMEFRAME_TF_BAR_CLOSED 7u
#define TIMEFRAME_TF_BAR_START 8u
#define TIMEFRAME_ELAPSED 9u
#define TIMEFRAME_LT 10u
#define TIMEFRAME_GE 11u
#define TIMEFRAME_ROLLOVER 12u
#define TIMEFRAME_SEQ_NEXT 13u
#define TIMEFRAME_CLOSED_NEXT 14u
#define TIMEFRAME_START_NEXT 15u
#define TIMEFRAME_STEP 16u
#define TIMEFRAME_TICKS_NEXT 17u
#define TIMEFRAME_TF_BAR_SEQ_OUT 18u
#define TIMEFRAME_TF_BAR_CLOSED_OUT 19u
#define TIMEFRAME_TF_BAR_START_OUT 20u


/* cmp_lt: gate-netlist comparator. Returns 1 (bit0) iff a < b (unsigned).
 * a - b = a + (~b) + 1 via 64 full-adder cells; the carry-out of the top bit is
 * (a >= b). So (a < b) = carry ^ 1. Pure gate algebra, no native C compare. */
static inline word_t cmp_lt(word_t a, word_t b) {
    word_t carry = 1ULL;                 /* +1 for two's-complement of b */
    word_t i = 0ULL;
    for (i = 0ULL; i < 64ULL; i = i + 1ULL) {
        const word_t aa = (a >> i) & 1ULL;
        const word_t nb = (cell_not(b) >> i) & 1ULL;     /* ~b bit */
        const word_t fa = cell_fa(aa, nb, carry);
        carry           = (fa >> 1) & 1ULL;              /* carry-out to next */
    }
    return (carry & 1ULL) ^ 1ULL;        /* carry==0 (borrow) == (a < b) */
}


static inline void timeframe_init(word_t *r) {
    word_t i = 0ULL;
    for (i = 0ULL; i < TIMEFRAME_REG_COUNT; i = i + 1ULL) { r[i] = 0ULL; }
    r[TIMEFRAME_ONE] = 1ULL;
}

/* timeframe_tick: one clock edge. READ inputs as const locals,
 * COMPUTE via cells (no native add/sub/mul on data), WRITE every register. */
static inline void timeframe_tick(word_t *r) {
    /* READ phase — pre-read every consumed register value. */
    const word_t tf_power = r[TIMEFRAME_TF_POWER];
    const word_t tf_tai_in = r[TIMEFRAME_TF_TAI_IN];
    const word_t tf_period_ns = r[TIMEFRAME_TF_PERIOD_NS];
    const word_t one = r[TIMEFRAME_ONE];
    const word_t tf_ticks = r[TIMEFRAME_TF_TICKS];
    const word_t tf_bar_seq = r[TIMEFRAME_TF_BAR_SEQ];
    const word_t tf_bar_closed = r[TIMEFRAME_TF_BAR_CLOSED];
    const word_t tf_bar_start = r[TIMEFRAME_TF_BAR_START];

    /* COMPUTE phase — combinational cell chain (declaration order). */
    const word_t elapsed = cell_addsub(tf_tai_in, tf_bar_start, 1ULL);
    const word_t lt = cmp_lt(elapsed, tf_period_ns);
    const word_t ge = cell_xor(lt, one);
    const word_t rollover = cell_gate(ge, tf_power);
    const word_t seq_next = cell_addsub(tf_bar_seq, rollover, 0ULL);
    const word_t closed_next = cell_gate(rollover, tf_power);
    const word_t start_next = cell_mux(tf_bar_start, tf_tai_in, rollover);
    const word_t step = cell_gate(one, tf_power);
    const word_t ticks_next = cell_addsub(tf_ticks, step, 0ULL);

    /* WRITE phase — gated dff commit: r[X] = cell_dff(q, fed_by, enable). */
    r[TIMEFRAME_TF_TICKS] = cell_dff(tf_ticks, ticks_next, one);
    r[TIMEFRAME_TF_BAR_SEQ] = cell_dff(tf_bar_seq, seq_next, one);
    r[TIMEFRAME_TF_BAR_CLOSED] = cell_dff(tf_bar_closed, closed_next, one);
    r[TIMEFRAME_TF_BAR_START] = cell_dff(tf_bar_start, start_next, one);
    r[TIMEFRAME_ELAPSED] = elapsed;
    r[TIMEFRAME_LT] = lt;
    r[TIMEFRAME_GE] = ge;
    r[TIMEFRAME_ROLLOVER] = rollover;
    r[TIMEFRAME_SEQ_NEXT] = seq_next;
    r[TIMEFRAME_CLOSED_NEXT] = closed_next;
    r[TIMEFRAME_START_NEXT] = start_next;
    r[TIMEFRAME_STEP] = step;
    r[TIMEFRAME_TICKS_NEXT] = ticks_next;
    r[TIMEFRAME_TF_BAR_SEQ_OUT] = tf_bar_seq;
    r[TIMEFRAME_TF_BAR_CLOSED_OUT] = tf_bar_closed;
    r[TIMEFRAME_TF_BAR_START_OUT] = tf_bar_start;

}

/* timeframe_run: canonical free-running clock. Power on once; the clock
 * self-oscillates while the power bit is set. Nothing external steps it. */
static inline void timeframe_run(word_t *r) {
    while (r[TIMEFRAME_TF_POWER] & 1ULL) { timeframe_tick(r); }
}

#endif /* TIMEFRAME_GEN_H */
