/* GENERATED by gennet.py from fpga_blank.net.json — DO NOT EDIT BY HAND.
 * THE identical FPGA blank (Xilinx Virtex UltraScale+ VU9P (XILINX_VU9P_SPEC_EXTRACTION.md)).
 * Pure device reference: fabric geometry + full-part I/O/resource tables.
 * A BLANK ASSIGNS NOTHING: no clock tables, no module names, no
 * placements, no addresses. Clocks arrive with the oscillator modules at
 * install (phase 4); boards are identical instances named at addressing. */
#ifndef FPGA_BLANK_GEN_H
#define FPGA_BLANK_GEN_H
#include <stdint.h>

typedef uint64_t fpga_blank_word_t;

/* ---- fabric geometry (the interconnect) ---- */
#define FPGA_BLANK_FABRIC_REGS 262144u
#define FPGA_BLANK_WORD_BITS 64u

/* ---- address-space GEOMETRY (sizes only; addressing is phase 3) ---- */
#define FPGA_BLANK_ADDR_SPACE_SIZE 0x10000000u
#define FPGA_BLANK_SLOT_ALIGNMENT 0x1000u
#define FPGA_BLANK_CDC_REGION_SIZE 0x100000u

/* ---- full-part I/O + resource budget (real-part facts, undivided) ---- */
#define FPGA_BLANK_IO_GTY_LANES 32u
#define FPGA_BLANK_IO_IO_BANKS 44u
#define FPGA_BLANK_RES_CLB_CAPACITY 182400u
#define FPGA_BLANK_RES_BRAM_CAPACITY 2160u
#define FPGA_BLANK_RES_DSP_CAPACITY 6840u

/* fpga_blank_init: zero the fabric (power-off reset). A blank runs no clock
 * and owns no logic; this is the only state operation it defines. */
static inline void fpga_blank_init(fpga_blank_word_t *f) {
    fpga_blank_word_t i = 0ULL;
    for (i = 0ULL; i < FPGA_BLANK_FABRIC_REGS; i = i + 1ULL) { f[i] = 0ULL; }
}

#endif /* FPGA_BLANK_GEN_H */
