#!/usr/bin/env python3
"""gennet.py — FPGA-BLANK generator: fpga_blank.net.json -> fpga_blank_gen.h.

EMITTED BY gen_fpga_blank.py — DO NOT EDIT BY HAND (regenerate via the tool).
A blank is pure device reference: emits ONLY the fabric geometry (the
interconnect), address-space geometry constants (sizes, NOT addresses), the
clock-domain table, I/O + resource budget, and a zero-init. NO logic, NO tick.
"""
import json
import sys


def main():
    net_path = sys.argv[1] if len(sys.argv) > 1 else "fpga_blank.net.json"
    net = json.load(open(net_path))
    if net.get("kind") != "fpga_blank":
        sys.stderr.write("gennet: not an fpga_blank netlist\n")
        sys.exit(2)
    dev = net["device"]
    DEV = dev.upper()
    fab = net["fabric"]
    geo = net["address_space_geometry"]

    out = []
    out.append(f"/* GENERATED by gennet.py from {net_path} — DO NOT EDIT BY HAND.")
    out.append(f" * THE identical FPGA blank ({net.get('part_ref', '')}).")
    out.append(" * Pure device reference: fabric geometry + clock/I-O/resource tables.")
    out.append(" * NO module allocation, NO logic, NO addresses — boards are identical")
    out.append(" * instances named at addressing (phase 3); install is phase 4. */")
    out.append(f"#ifndef {DEV}_GEN_H")
    out.append(f"#define {DEV}_GEN_H")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f"typedef uint64_t {dev}_word_t;")
    out.append("")
    out.append("/* ---- fabric geometry (the interconnect) ---- */")
    out.append(f"#define {DEV}_FABRIC_REGS {fab['registers']}u")
    out.append(f"#define {DEV}_WORD_BITS {fab['word_bits']}u")
    out.append("")
    out.append("/* ---- address-space GEOMETRY (sizes only; addressing is phase 3) ---- */")
    out.append(f"#define {DEV}_ADDR_SPACE_SIZE {hex(geo['size'])}u")
    out.append(f"#define {DEV}_SLOT_ALIGNMENT {hex(geo['slot_alignment'])}u")
    out.append(f"#define {DEV}_CDC_REGION_SIZE {hex(geo['cdc_region_size'])}u")
    out.append("")
    out.append("/* ---- clock-domain table (descriptive; oscillator modules own the clocks) ---- */")
    for cn, c in net.get("clock_domain_table", {}).items():
        out.append(f"#define {DEV}_CLK_{cn.upper()}_HZ {c['frequency_hz']}u")
    out.append("")
    out.append("/* ---- full-part I/O + resource budget (real-part facts, undivided) ---- */")
    for k, v in net.get("io_geometry", {}).items():
        out.append(f"#define {DEV}_IO_{k.upper()} {v}u")
    for rn, r in net.get("resource_budget", {}).items():
        out.append(f"#define {DEV}_RES_{rn.upper()}_CAPACITY {r['capacity']}u")
    out.append("")
    out.append(f"/* {dev}_init: zero the fabric (power-off reset). A blank runs no clock")
    out.append(" * and owns no logic; this is the only state operation it defines. */")
    out.append(f"static inline void {dev}_init({dev}_word_t *f) {{")
    out.append(f"    {dev}_word_t i = 0ULL;")
    out.append(f"    for (i = 0ULL; i < {DEV}_FABRIC_REGS; i = i + 1ULL) {{ f[i] = 0ULL; }}")
    out.append("}")
    out.append("")
    out.append(f"#endif /* {DEV}_GEN_H */")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
