#!/usr/bin/env python3
"""gennet.py — FPGA-BLANK generator: fpga_blank.net.json -> fpga_blank_gen.h.

EMITTED BY gen_fpga_blank.py — DO NOT EDIT BY HAND (regenerate via the tool).
A blank is pure device reference, and A BLANK ASSIGNS NOTHING: this generator
is STRUCTURALLY INCAPABLE of emitting clock tables, module names, placements,
or addresses — it emits ONLY the fabric geometry (the interconnect),
address-space geometry constants (sizes, NOT addresses), full-part I/O +
resource budget, and a zero-init. It REFUSES a netlist carrying assignment.
"""
import json
import sys

# Assignment keys: their presence in the netlist means a poisoned spec upstream.
POISON = ("clock_domain_table", "clock_domains", "clock", "dff_nodes",
          "comb_nodes", "config_nodes", "window_base", "role",
          "intended_modules_doc", "intended_modules", "placement", "residents",
          "modules", "slots")


def main():
    net_path = sys.argv[1] if len(sys.argv) > 1 else "fpga_blank.net.json"
    net = json.load(open(net_path))
    if net.get("kind") != "fpga_blank":
        sys.stderr.write("gennet: not an fpga_blank netlist\n")
        sys.exit(2)
    for k in POISON:
        if net.get(k):
            sys.stderr.write(f"gennet: REFUSED — netlist carries '{k}' (a blank "
                             f"assigns nothing; fix the spec upstream)\n")
            sys.exit(3)

    dev = net["device"]
    DEV = dev.upper()
    fab = net["fabric"]
    geo = net["address_space_geometry"]

    out = []
    out.append(f"/* GENERATED by gennet.py from {net_path} — DO NOT EDIT BY HAND.")
    out.append(f" * THE identical FPGA blank ({net.get('part_ref', '')}).")
    out.append(" * Pure device reference: fabric geometry + full-part I/O/resource tables.")
    out.append(" * A BLANK ASSIGNS NOTHING: no clock tables, no module names, no")
    out.append(" * placements, no addresses. Clocks arrive with the oscillator modules at")
    out.append(" * install (phase 4); boards are identical instances named at addressing. */")
    out.append(f"#ifndef {DEV}_GEN_H")
    out.append(f"#define {DEV}_GEN_H")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f"typedef uint64_t {dev}_word_t;")
    out.append("")
    out.append("/* ---- fabric geometry (the interconnect) ---- */")
    out.append(f"#define {DEV}_FABRIC_REGS {fab['registers']}u")
    out.append(f"#define {DEV}_WORD_BITS {fab['word_bits']}u")
    out.append("")
    out.append("/* ---- address-space GEOMETRY (sizes only; addressing is phase 3) ---- */")
    out.append(f"#define {DEV}_ADDR_SPACE_SIZE {hex(geo['size'])}u")
    out.append(f"#define {DEV}_SLOT_ALIGNMENT {hex(geo['slot_alignment'])}u")
    out.append(f"#define {DEV}_CDC_REGION_SIZE {hex(geo['cdc_region_size'])}u")
    out.append("")
    out.append("/* ---- full-part I/O + resource budget (real-part facts, undivided) ---- */")
    for k, v in net.get("io_geometry", {}).items():
        out.append(f"#define {DEV}_IO_{k.upper()} {v}u")
    for rn, r in net.get("resource_budget", {}).items():
        out.append(f"#define {DEV}_RES_{rn.upper()}_CAPACITY {r['capacity']}u")
    out.append("")
    out.append(f"/* {dev}_init: zero the fabric (power-off reset). A blank runs no clock")
    out.append(" * and owns no logic; this is the only state operation it defines. */")
    out.append(f"static inline void {dev}_init({dev}_word_t *f) {{")
    out.append(f"    {dev}_word_t i = 0ULL;")
    out.append(f"    for (i = 0ULL; i < {DEV}_FABRIC_REGS; i = i + 1ULL) {{ f[i] = 0ULL; }}")
    out.append("}")
    out.append("")
    out.append(f"#endif /* {DEV}_GEN_H */")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
